import type { AgenteCopy } from './pt';

export const agenteCopyEn: AgenteCopy = {
  title: 'Certified Agent',
  subtitle:
    'Represent Kuteka on the ground: set your coverage, explore active inventory and activate follow-ups.',
  explore: 'Explore inventory',
  preferencesTitle: 'Coverage preferences',
  preferencesHint: 'Indicate the area and purpose you would like to operate in.',
  savePreferences: 'Save preferences',
  saving: 'Saving…',
  saved: 'Preferences saved.',
  needAgent:
    'Real operations require the Certified Agent role (assigned by Administration). Below is a Beta preview of the pipeline.',
  demoTitle: 'Pipeline Beta preview',
  demoHint: 'Illustrative data with the Beta inventory — try the journey without agent permission.',
  demoVisits: 'Visits',
  demoAgenda: 'Agenda',
  demoPipeline: 'Pipeline',
  requestAgent: 'Request activation (contact)',
  requestAgentHint:
    'The Certified Agent role is assigned by Administration. Contact Kuteka or continue exploring the Beta preview.',
  loadError: 'We are having trouble showing the Agent area. Please try again.',
  saveError: 'We could not save. Please try again.',
  forbidden: 'You do not have Certified Agent permission.',
  exploreTitle: 'Active inventory',
  exploreSubtitle: 'Properties available for responsible follow-up in the field.',
  emptyExploreTitle: 'No property in this coverage',
  emptyExplore:
    'There are no active properties matching the current filters. Adjust the coverage or explore again later.',
  emptyAssignmentsTitle: 'No active follow-ups',
  emptyAssignments: 'Once you activate a follow-up, it is recorded here to track your field work.',
  emptyAssignmentsCta: 'Explore inventory',
  assignmentsTitle: 'Active follow-ups',
  activate: 'Activate follow-up',
  activating: 'Activating…',
  activated: 'Follow-up activated.',
  alreadyAssigned: 'You already have an active follow-up for this property.',
  backToHub: 'Back to Agent area',
  backToExplore: 'Back to inventory',
  detailTitle: 'Property for follow-up',
  openDetail: 'Open listing',
  mvpNote:
    'Focus on coverage and follow-ups. Visits, proposals and the Academy will be introduced in later phases.',
  viewHousingInventory: 'View inventory',
  activateAgentAdmin: 'Activate agent (Admin)',
  nextSteps: {
    title: 'Continue the Kuteka flow',
    viewActiveProperties: 'View active properties',
    verifyAccount: 'Verify account',
    administration: 'Administration',
    contactKuteka: 'Contact Kuteka',
  },
  fields: {
    purpose: 'Purpose',
    province: 'Province',
    city: 'City',
    type: 'Type',
    address: 'Address',
    code: 'Code',
    notes: 'Field notes (optional)',
    any: 'Any',
    status: 'Status',
  },
  types: {
    apartment: 'Apartment',
    house: 'House',
    land: 'Land',
    commercial: 'Commercial',
  },
  purposes: {
    rent: 'Rent',
    sale: 'Sale',
    both: 'Sale and rent',
  },
  statuses: {
    active: 'Active',
    released: 'Released',
  },
};
