import type { PatrimoniosCopy } from './pt';

export const patrimoniosCopyEn: PatrimoniosCopy = {
  title: 'Patrimonies',
  subtitle:
    'Activate a property with commercial purpose, Kuteka services, asset management and a full listing — aligned with the Operations Manual.',
  emptyTitle: 'No property activated',
  empty:
    'Activate your first property with photos, requested services and management level. The Beta inventory is already available under Housing.',
  emptyCta: 'Activate your first property',
  activate: 'Activate Property',
  activating: 'Activating…',
  activated: 'Property activated.',
  submittedForReview:
    'Property submitted. It is Under review by Administration and will only be published after approval.',
  backToList: 'Back to properties',
  needPartner: 'To activate a property you need the Property Partner role on your account.',
  activateRole: 'Activate Partner role',
  loadError: 'We are having trouble showing the properties. Please try again.',
  saveError: 'We could not publish the property. Check the fields and try again.',
  mediaUploadError: 'Photos or videos were not uploaded. Try again with lighter files.',
  forbidden: 'Your current role does not allow managing properties. Activate Property Partner.',
  detailTitle: 'Property detail',
  seeInHousing: 'View as Client',
  wizard: {
    stepOf: 'Step {current} of {total}',
    continue: 'Continue',
    back: 'Back',
    saveDraft: 'Save draft',
    draftSaved: 'Draft saved.',
    draftRestored: 'Draft restored',
    reviewHint:
      'Review the details before publishing. You can return to previous steps to fix them.',
    titleRequired: 'Enter a title with at least 3 characters.',
    steps: {
      media: 'Photos & videos',
      essentials: 'Essentials',
      commercial: 'Commercial',
      services: 'Services and management',
      location: 'Location',
      characteristics: 'Characteristics',
      review: 'Notes and review',
    },
  },
  sections: {
    commercial: 'Commercial purpose',
    commercialHint: 'Defines whether the property enters the market for sale, rent, or both.',
    services: 'Requested Kuteka services',
    servicesHint:
      'Kuteka is a property management company — choose one or several services beyond publishing.',
    management: 'Asset management level',
    managementHint: 'Indicate how far Kuteka should get involved with this property.',
    unfinished: 'Unfinished property / under construction',
    unfinishedHint: 'For partial constructions, indicate what you would like from Kuteka.',
    renovation: 'Renovation and enhancement',
    renovationHint: 'Improvement requests associated with this property (optional).',
    location: 'Location',
    characteristics: 'Characteristics',
    infrastructure: 'Infrastructure and nearby amenities',
    media: 'Photos & videos',
    essentials: 'Essential details',
    essentialsHint: 'Title, property type and commercial purpose.',
    commercialPrice: 'Commercial terms',
    commercialPriceHint: 'Indicate the price or rent in AOA (optional at this stage).',
    review: 'Notes and review',
  },
  fields: {
    title: 'Title / property name',
    titlePlaceholder: 'e.g. T4 house in Talatona',
    type: 'Type',
    purpose: 'Commercial purpose',
    province: 'Province',
    municipality: 'Municipality',
    commune: 'Commune',
    city: 'City',
    neighborhood: 'Neighbourhood',
    address: 'Street',
    streetNumber: 'Number',
    latitude: 'GPS latitude',
    longitude: 'GPS longitude',
    notes: 'Notes (optional)',
    status: 'Status',
    code: 'Code',
    price: 'Price (AOA)',
    pricePlaceholder: 'e.g. 185000000',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    areaTotal: 'Total area (m²)',
    areaUseful: 'Usable area (m²)',
    yearBuilt: 'Approximate year built',
    conservation: 'Conservation condition',
    construction: 'Construction status',
    unfinishedIntent: 'Intent for unfinished construction',
    management: 'Management level',
    suites: 'Suites',
    parkingSpaces: 'Parking spaces',
    furnished: 'Furnished',
    landArea: 'Land area (m²)',
    builtArea: 'Built area (m²)',
    commissionSettlement: 'Commission settlement',
  },
  commissionSettlements: {
    immediate: 'Immediate',
    after_first_rent: 'After first rent',
    automatic_retention: 'Automatic retention',
  },
  amenities: {
    garage: 'Garage',
    yard: 'Yard',
    pool: 'Pool',
    garden: 'Garden',
    annex: 'Annex',
    equippedKitchen: 'Equipped kitchen',
    balcony: 'Balcony',
    terrace: 'Terrace',
  },
  infra: {
    water: 'Piped water',
    electricity: 'Mains electricity',
    generator: 'Generator',
    internet: 'Internet',
    security: 'Security',
    paved: 'Paved street',
    schools: 'Nearby schools',
    hospitals: 'Nearby hospitals',
    markets: 'Nearby markets',
    transport: 'Nearby transport',
  },
  media: {
    title: 'Listing photos & videos',
    hint: 'Drag photos or videos (MP4, WebM, MOV), set the featured item, reorder and preview before saving. Images are compressed automatically.',
    drop: 'Drop photos or videos here',
    pick: 'Choose files',
    primary: 'Featured',
    setPrimary: 'Set as featured',
    remove: 'Remove',
    preview: 'Listing preview',
    badgePhoto: 'Photo',
    badgeVideo: 'Video',
    videoTooLarge: 'Each video can be up to 80 MB. Choose a lighter file.',
    unsupported: 'Use photos (JPG, PNG, WebP) or videos (MP4, WebM, MOV).',
  },
  types: {
    apartment: 'Apartment',
    house: 'House',
    land: 'Land',
    commercial: 'Commercial',
  },
  purposes: {
    rent: 'Rent',
    sale: 'Sale',
    both: 'Sale and rent',
  },
  statuses: {
    draft: 'Under review / draft',
    active: 'Active (published)',
    archived: 'Archived',
  },
  listHeading: 'Your properties',
  listHint:
    'Listings and properties under management — the Client finds published ones under Housing.',
  mvpNote:
    'After the commercial purpose, indicate the Kuteka services and the management level. Management/evaluation services require a technical assessment before full publication.',
  detailNote:
    'Once active, this listing becomes available under Housing for the Client — with the same premium sheet, map and reputation.',
  nextSteps: {
    detailErrorHint: 'This property may have been removed or is not accessible.',
    seeProperties: 'View properties',
    startOverTitle: 'Start over',
    startOverHint: 'Activate a property or complete account verification.',
    trustCenter: 'Trust Center',
    suggestedTitle: 'Suggested next step',
    suggestedHint:
      'Share the listing under Housing to generate visits, or move to a contract once you have interested parties.',
    createContract: 'Create contract',
    continueFlowTitle: 'Continue the flow',
    goDashboard: 'Go to dashboard',
    verifyAccount: 'Verify account',
    seeAgentArea: 'View Agent area',
  },
};
