import type { PatrimoniosCopy } from './pt';

export const patrimoniosCopyEs: PatrimoniosCopy = {
  title: 'Patrimonios',
  subtitle:
    'Active un patrimonio con finalidad comercial, servicios Kuteka, gestión patrimonial y ficha completa — conforme al Manual Operativo.',
  emptyTitle: 'Ningún patrimonio activado',
  empty:
    'Active su primer patrimonio con fotografías, servicios deseados y nivel de gestión. El inventario de demostración ya está disponible en Vivienda.',
  emptyCta: 'Activar el primer patrimonio',
  activate: 'Activar patrimonio',
  activating: 'Activando…',
  activated: 'Patrimonio activado.',
  backToList: 'Volver a los patrimonios',
  needPartner: 'Para activar un patrimonio necesita el rol de Socio Patrimonial en su cuenta.',
  activateRole: 'Activar rol de Socio',
  loadError: 'Estamos teniendo dificultades para mostrar los patrimonios. Inténtelo de nuevo.',
  saveError: 'No pudimos publicar el patrimonio. Verifique los campos e inténtelo de nuevo.',
  mediaUploadError: 'Las fotografías no se enviaron. Inténtelo de nuevo con imágenes más ligeras.',
  forbidden: 'Su rol actual no permite gestionar patrimonios. Active Socio Patrimonial.',
  detailTitle: 'Detalle del patrimonio',
  seeInHousing: 'Ver como Cliente',
  wizard: {
    stepOf: 'Paso {current} de {total}',
    continue: 'Continuar',
    back: 'Anterior',
    saveDraft: 'Guardar borrador',
    draftSaved: 'Borrador guardado.',
    draftRestored: 'Borrador restaurado',
    reviewHint:
      'Revise los datos antes de publicar. Puede volver a los pasos anteriores para corregirlos.',
    titleRequired: 'Indique un título con al menos 3 caracteres.',
    steps: {
      media: 'Fotografías',
      essentials: 'Datos esenciales',
      commercial: 'Comercial',
      services: 'Servicios y gestión',
      location: 'Ubicación',
      characteristics: 'Características',
      review: 'Notas y revisión',
    },
  },
  sections: {
    commercial: 'Finalidad comercial',
    commercialHint: 'Define si el inmueble entra al mercado para venta, alquiler o ambos.',
    services: 'Servicios de Kuteka solicitados',
    servicesHint:
      'Kuteka es una empresa de gestión patrimonial — elija uno o varios servicios además de la publicación.',
    management: 'Nivel de gestión patrimonial',
    managementHint: 'Indique hasta dónde debe intervenir Kuteka en este patrimonio.',
    unfinished: 'Inmueble inacabado / en obra',
    unfinishedHint: 'Para construcciones parciales, indique qué desea de Kuteka.',
    renovation: 'Renovación y revalorización',
    renovationHint: 'Solicitudes de mejora asociadas a este inmueble (opcional).',
    location: 'Ubicación',
    characteristics: 'Características',
    infrastructure: 'Infraestructuras y proximidades',
    media: 'Fotografías',
    essentials: 'Datos esenciales',
    essentialsHint: 'Título, tipo de inmueble y finalidad comercial.',
    commercialPrice: 'Condiciones comerciales',
    commercialPriceHint: 'Indique el precio o el alquiler en AOA (opcional en esta fase).',
    review: 'Notas y revisión',
  },
  fields: {
    title: 'Título / nombre del inmueble',
    titlePlaceholder: 'Ej.: Chalet de 4 habitaciones en Talatona',
    type: 'Tipo',
    purpose: 'Finalidad comercial',
    province: 'Provincia',
    municipality: 'Municipio',
    commune: 'Comuna',
    city: 'Ciudad',
    neighborhood: 'Barrio',
    address: 'Calle',
    streetNumber: 'Número',
    latitude: 'Latitud GPS',
    longitude: 'Longitud GPS',
    notes: 'Notas (opcional)',
    status: 'Estado',
    code: 'Código',
    price: 'Precio (AOA)',
    pricePlaceholder: 'Ej.: 185000000',
    bedrooms: 'Habitaciones',
    bathrooms: 'Baños',
    areaTotal: 'Área total (m²)',
    areaUseful: 'Área útil (m²)',
    yearBuilt: 'Año aproximado de construcción',
    conservation: 'Estado de conservación',
    construction: 'Estado de la construcción',
    unfinishedIntent: 'Intención para la obra inacabada',
    management: 'Nivel de gestión',
  },
  infra: {
    water: 'Agua corriente',
    electricity: 'Energía eléctrica',
    generator: 'Generador',
    internet: 'Internet',
    security: 'Seguridad',
    paved: 'Pavimentación de la calle',
    schools: 'Proximidad de colegios',
    hospitals: 'Proximidad de hospitales',
    markets: 'Proximidad de mercados',
    transport: 'Proximidad de transporte',
  },
  media: {
    title: 'Fotografías del anuncio',
    hint: 'Arrastre varias imágenes, defina la principal, reordénelas y previsualícelas antes de guardar. Compresión automática activada.',
    drop: 'Suelte las fotografías aquí',
    pick: 'Elegir imágenes',
    primary: 'Principal',
    setPrimary: 'Definir como principal',
    remove: 'Eliminar',
    preview: 'Vista previa del anuncio',
  },
  types: {
    apartment: 'Apartamento',
    house: 'Casa',
    land: 'Terreno',
    commercial: 'Comercial',
  },
  purposes: {
    rent: 'Alquiler',
    sale: 'Venta',
    both: 'Venta y alquiler',
  },
  statuses: {
    draft: 'En evaluación / borrador',
    active: 'Activo (publicado)',
    archived: 'Archivado',
  },
  listHeading: 'Sus patrimonios',
  listHint:
    'Anuncios y patrimonios bajo gestión — el Cliente encuentra los publicados en Vivienda.',
  mvpNote:
    'Después de la finalidad comercial, indique los servicios de Kuteka y el nivel de gestión. Los servicios de gestión/evaluación requieren una evaluación técnica antes de la publicación completa.',
  detailNote:
    'Una vez activo, este anuncio queda disponible en Vivienda para el Cliente — con la misma ficha premium, mapa y reputación.',
  nextSteps: {
    detailErrorHint: 'Este patrimonio puede haber sido eliminado o no estar accesible.',
    seeProperties: 'Ver patrimonios',
    startOverTitle: 'Empezar de nuevo',
    startOverHint: 'Active un patrimonio o complete la verificación de la cuenta.',
    trustCenter: 'Centro de Confianza',
    suggestedTitle: 'Próximo paso sugerido',
    suggestedHint:
      'Comparta el anuncio en Vivienda para generar visitas, o avance a contrato cuando tenga interesados.',
    createContract: 'Crear contrato',
    continueFlowTitle: 'Continuar el flujo',
    goDashboard: 'Ir al panel',
    verifyAccount: 'Verificar cuenta',
    seeAgentArea: 'Ver área del Agente',
  },
};
