import type { PatrimoniosCopy } from './pt';

export const patrimoniosCopyFr: PatrimoniosCopy = {
  title: 'Patrimoines',
  subtitle:
    'Activez un patrimoine à vocation commerciale, avec services Kuteka, gestion patrimoniale et fiche complète — conformément au Manuel Opérationnel.',
  emptyTitle: 'Aucun patrimoine activé',
  empty:
    'Activez votre premier patrimoine avec des photos, les services souhaités et le niveau de gestion. L’inventaire de démonstration est déjà disponible dans Habitat.',
  emptyCta: 'Activer le premier patrimoine',
  activate: 'Activer un patrimoine',
  activating: 'Activation…',
  activated: 'Patrimoine activé.',
  backToList: 'Retour aux patrimoines',
  needPartner:
    'Pour activer un patrimoine, vous devez avoir le rôle Partenaire Patrimonial sur votre compte.',
  activateRole: 'Activer le rôle Partenaire',
  loadError: 'Nous avons du mal à afficher les patrimoines. Veuillez réessayer.',
  saveError: 'Nous n’avons pas pu publier le patrimoine. Vérifiez les champs et réessayez.',
  mediaUploadError:
    'Les photos ou vidéos n’ont pas été envoyées. Réessayez avec des fichiers plus légers.',
  forbidden:
    'Votre rôle actuel ne permet pas de gérer des patrimoines. Activez Partenaire Patrimonial.',
  detailTitle: 'Détail du patrimoine',
  seeInHousing: 'Voir en tant que Client',
  wizard: {
    stepOf: 'Étape {current} sur {total}',
    continue: 'Continuer',
    back: 'Précédent',
    saveDraft: 'Enregistrer le brouillon',
    draftSaved: 'Brouillon enregistré.',
    draftRestored: 'Brouillon restauré',
    reviewHint:
      'Vérifiez les informations avant de publier. Vous pouvez revenir aux étapes précédentes pour les corriger.',
    titleRequired: 'Indiquez un titre d’au moins 3 caractères.',
    steps: {
      media: 'Photos et vidéos',
      essentials: 'Essentiels',
      commercial: 'Commercial',
      services: 'Services et gestion',
      location: 'Localisation',
      characteristics: 'Caractéristiques',
      review: 'Notes et révision',
    },
  },
  sections: {
    commercial: 'Vocation commerciale',
    commercialHint:
      'Définit si le bien entre sur le marché pour la vente, la location, ou les deux.',
    services: 'Services Kuteka souhaités',
    servicesHint:
      'Kuteka est une société de gestion patrimoniale — choisissez un ou plusieurs services au-delà de la publication.',
    management: 'Niveau de gestion patrimoniale',
    managementHint: 'Indiquez jusqu’où Kuteka doit intervenir sur ce patrimoine.',
    unfinished: 'Bien inachevé / en construction',
    unfinishedHint: 'Pour les constructions partielles, indiquez ce que vous attendez de Kuteka.',
    renovation: 'Rénovation et valorisation',
    renovationHint: 'Demandes d’amélioration associées à ce bien (facultatif).',
    location: 'Localisation',
    characteristics: 'Caractéristiques',
    infrastructure: 'Infrastructures et proximités',
    media: 'Photos et vidéos',
    essentials: 'Informations essentielles',
    essentialsHint: 'Titre, type de bien et vocation commerciale.',
    commercialPrice: 'Conditions commerciales',
    commercialPriceHint: 'Indiquez le prix ou le loyer en AOA (facultatif à ce stade).',
    review: 'Notes et révision',
  },
  fields: {
    title: 'Titre / nom du bien',
    titlePlaceholder: 'Ex. : Villa T4 à Talatona',
    type: 'Type',
    purpose: 'Vocation commerciale',
    province: 'Province',
    municipality: 'Municipalité',
    commune: 'Commune',
    city: 'Ville',
    neighborhood: 'Quartier',
    address: 'Rue',
    streetNumber: 'Numéro',
    latitude: 'Latitude GPS',
    longitude: 'Longitude GPS',
    notes: 'Notes (facultatif)',
    status: 'État',
    code: 'Code',
    price: 'Prix (AOA)',
    pricePlaceholder: 'Ex. : 185 000 000',
    bedrooms: 'Chambres',
    bathrooms: 'Salles de bains',
    areaTotal: 'Surface totale (m²)',
    areaUseful: 'Surface utile (m²)',
    yearBuilt: 'Année de construction approximative',
    conservation: 'État de conservation',
    construction: 'État de la construction',
    unfinishedIntent: 'Intention pour la construction inachevée',
    management: 'Niveau de gestion',
  },
  infra: {
    water: 'Eau courante',
    electricity: 'Électricité',
    generator: 'Générateur',
    internet: 'Internet',
    security: 'Sécurité',
    paved: 'Rue pavée',
    schools: 'Proximité des écoles',
    hospitals: 'Proximité des hôpitaux',
    markets: 'Proximité des marchés',
    transport: 'Proximité des transports',
  },
  media: {
    title: 'Photos et vidéos de l’annonce',
    hint: 'Glissez des photos ou vidéos (MP4, WebM, MOV), définissez l’élément principal, réorganisez et prévisualisez avant d’enregistrer. Compression automatique des images.',
    drop: 'Déposez photos ou vidéos ici',
    pick: 'Choisir des fichiers',
    primary: 'Principale',
    setPrimary: 'Définir comme principale',
    remove: 'Supprimer',
    preview: 'Aperçu de l’annonce',
    badgePhoto: 'Photo',
    badgeVideo: 'Vidéo',
    videoTooLarge: 'Chaque vidéo peut faire jusqu’à 80 Mo. Choisissez un fichier plus léger.',
    unsupported: 'Utilisez des photos (JPG, PNG, WebP) ou des vidéos (MP4, WebM, MOV).',
  },
  types: {
    apartment: 'Appartement',
    house: 'Villa',
    land: 'Terrain',
    commercial: 'Commercial',
  },
  purposes: {
    rent: 'Location',
    sale: 'Vente',
    both: 'Vente et location',
  },
  statuses: {
    draft: 'En évaluation / brouillon',
    active: 'Actif (publié)',
    archived: 'Archivé',
  },
  listHeading: 'Vos patrimoines',
  listHint:
    'Annonces et patrimoines sous gestion — le Client trouve les biens publiés dans Habitat.',
  mvpNote:
    'Après la vocation commerciale, indiquez les services Kuteka et le niveau de gestion. Les services de gestion/évaluation nécessitent une évaluation technique avant la publication complète.',
  detailNote:
    'Une fois actif, cette annonce devient disponible dans Habitat pour le Client — avec la même fiche premium, la carte et la réputation.',
  nextSteps: {
    detailErrorHint: 'Ce patrimoine a peut-être été supprimé ou n’est pas accessible.',
    seeProperties: 'Voir les patrimoines',
    startOverTitle: 'Recommencer',
    startOverHint: 'Activez un patrimoine ou complétez la vérification du compte.',
    trustCenter: 'Centre de Confiance',
    suggestedTitle: 'Prochaine étape suggérée',
    suggestedHint:
      'Partagez l’annonce dans Habitat pour générer des visites, ou passez au contrat lorsque vous avez des intéressés.',
    createContract: 'Créer un contrat',
    continueFlowTitle: 'Continuer le parcours',
    goDashboard: 'Aller au tableau de bord',
    verifyAccount: 'Vérifier le compte',
    seeAgentArea: 'Voir l’espace Agent',
  },
};
