export const patrimoniosCopyPt = {
  title: 'Patrimónios',
  subtitle:
    'Active património com finalidade comercial, serviços Kuteka, gestão patrimonial e ficha completa — alinhado ao Manual Operacional.',
  emptyTitle: 'Nenhum património activado',
  empty:
    'Active o primeiro património com fotografias, serviços pretendidos e nível de gestão. O inventário de demonstração já está disponível em Habitação.',
  emptyCta: 'Ativar o primeiro património',
  activate: 'Ativar Património',
  activating: 'A activar…',
  activated: 'Património activado.',
  backToList: 'Voltar aos patrimónios',
  needPartner: 'Para activar património precisa do papel Parceiro Patrimonial na sua conta.',
  activateRole: 'Activar papel Parceiro',
  loadError: 'Estamos a ter dificuldade em mostrar os patrimónios. Tente novamente.',
  saveError: 'Não conseguimos publicar o património. Verifique os campos e tente novamente.',
  mediaUploadError: 'As fotografias não foram enviadas. Tente novamente com imagens mais leves.',
  forbidden: 'O seu papel actual não permite gerir patrimónios. Active Parceiro Patrimonial.',
  detailTitle: 'Detalhe do património',
  seeInHousing: 'Ver como Cliente',
  wizard: {
    stepOf: 'Passo {current} de {total}',
    continue: 'Continuar',
    back: 'Anterior',
    saveDraft: 'Guardar rascunho',
    draftSaved: 'Rascunho guardado.',
    draftRestored: 'Rascunho restaurado',
    reviewHint:
      'Revise os dados antes de publicar. Pode voltar aos passos anteriores para corrigir.',
    titleRequired: 'Indique um título com pelo menos 3 caracteres.',
    steps: {
      media: 'Fotografias',
      essentials: 'Essenciais',
      commercial: 'Comercial',
      services: 'Serviços e gestão',
      location: 'Localização',
      characteristics: 'Características',
      review: 'Notas e revisão',
    },
  },
  sections: {
    commercial: 'Finalidade comercial',
    commercialHint: 'Define se o imóvel entra no mercado para venda, arrendamento ou ambos.',
    services: 'Serviços pretendidos da Kuteka',
    servicesHint:
      'A Kuteka é uma empresa de gestão patrimonial — escolha um ou vários serviços além da publicação.',
    management: 'Nível de gestão patrimonial',
    managementHint: 'Indique até onde a Kuteka deve intervir neste património.',
    unfinished: 'Imóvel inacabado / obra',
    unfinishedHint: 'Para construções parciais, indique o que pretende da Kuteka.',
    renovation: 'Remodelação e valorização',
    renovationHint: 'Pedidos de melhoria associados a este imóvel (opcional).',
    location: 'Localização',
    characteristics: 'Características',
    infrastructure: 'Infraestruturas e proximidades',
    media: 'Fotografias',
    essentials: 'Dados essenciais',
    essentialsHint: 'Título, tipo de imóvel e finalidade comercial.',
    commercialPrice: 'Condições comerciais',
    commercialPriceHint: 'Indique o preço ou renda em AOA (opcional nesta fase).',
    review: 'Notas e revisão',
  },
  fields: {
    title: 'Título / nome do imóvel',
    titlePlaceholder: 'Ex.: Moradia T4 Talatona',
    type: 'Tipo',
    purpose: 'Finalidade comercial',
    province: 'Província',
    municipality: 'Município',
    commune: 'Comuna',
    city: 'Cidade',
    neighborhood: 'Bairro',
    address: 'Rua',
    streetNumber: 'Número',
    latitude: 'Latitude GPS',
    longitude: 'Longitude GPS',
    notes: 'Notas (opcional)',
    status: 'Estado',
    code: 'Código',
    price: 'Preço (AOA)',
    pricePlaceholder: 'Ex.: 185000000',
    bedrooms: 'Quartos',
    bathrooms: 'Casas de banho',
    areaTotal: 'Área total (m²)',
    areaUseful: 'Área útil (m²)',
    yearBuilt: 'Ano aproximado de construção',
    conservation: 'Estado de conservação',
    construction: 'Estado da construção',
    unfinishedIntent: 'Intenção para obra inacabada',
    management: 'Nível de gestão',
  },
  infra: {
    water: 'Água canalizada',
    electricity: 'Energia eléctrica',
    generator: 'Gerador',
    internet: 'Internet',
    security: 'Segurança',
    paved: 'Pavimentação da rua',
    schools: 'Proximidade de escolas',
    hospitals: 'Proximidade de hospitais',
    markets: 'Proximidade de mercados',
    transport: 'Proximidade de transportes',
  },
  media: {
    title: 'Fotografias do anúncio',
    hint: 'Arraste várias imagens, defina a principal, reordene e pré-visualize antes de guardar. Compressão automática activa.',
    drop: 'Largue as fotografias aqui',
    pick: 'Escolher imagens',
    primary: 'Principal',
    setPrimary: 'Definir principal',
    remove: 'Remover',
    preview: 'Pré-visualização do anúncio',
  },
  types: {
    apartment: 'Apartamento',
    house: 'Moradia',
    land: 'Terreno',
    commercial: 'Comercial',
  },
  purposes: {
    rent: 'Arrendamento',
    sale: 'Venda',
    both: 'Venda e arrendamento',
  },
  statuses: {
    draft: 'Em avaliação / rascunho',
    active: 'Activo (publicado)',
    archived: 'Arquivado',
  },
  listHeading: 'Os seus patrimónios',
  listHint: 'Anúncios e patrimónios sob gestão — o Cliente encontra os publicados em Habitação.',
  mvpNote:
    'Após a finalidade comercial, indique os serviços Kuteka e o nível de gestão. Serviços de gestão/avaliação exigem avaliação técnica antes da publicação plena.',
} as const;

export function getPatrimoniosCopy() {
  return patrimoniosCopyPt;
}
