export const patrimoniosCopyPt = {
  title: 'Patrimónios',
  subtitle: 'Publique anúncios com fotografia, preço e galeria — prontos para o Cliente explorar.',
  emptyTitle: 'Nenhum património activado',
  empty:
    'Active o primeiro património com fotografias e preço. O inventário de demonstração já está disponível em Habitação.',
  emptyCta: 'Ativar o primeiro património',
  activate: 'Ativar Património',
  activating: 'A activar…',
  activated: 'Património activado.',
  backToList: 'Voltar aos patrimónios',
  needPartner: 'Para activar património precisa do papel Parceiro Patrimonial na sua conta.',
  activateRole: 'Activar papel Parceiro',
  loadError: 'Não foi possível carregar os patrimónios. Tente novamente.',
  saveError: 'Não foi possível activar o património. Verifique os dados e tente novamente.',
  mediaUploadError: 'Não foi possível carregar as fotografias. Tente novamente.',
  forbidden: 'Não tem permissão para gerir patrimónios.',
  detailTitle: 'Detalhe do património',
  seeInHousing: 'Ver como Cliente',
  fields: {
    title: 'Título',
    titlePlaceholder: 'Ex.: Moradia T4 Talatona',
    type: 'Tipo',
    purpose: 'Finalidade',
    province: 'Província',
    city: 'Cidade',
    address: 'Morada (opcional)',
    notes: 'Notas (opcional)',
    status: 'Estado',
    code: 'Código',
    price: 'Preço (AOA)',
    pricePlaceholder: 'Ex.: 185000000',
    bedrooms: 'Quartos',
  },
  media: {
    title: 'Fotografias do anúncio',
    hint: 'Arraste várias imagens, defina a principal, reordene e pré-visualize antes de guardar. Compressão automática activa.',
    drop: 'Largue as fotografias aqui',
    pick: 'Escolher imagens',
    primary: 'Principal',
    setPrimary: 'Definir principal',
    remove: 'Remover',
    preview: 'Pré-visualização do anúncio',
  },
  types: {
    apartment: 'Apartamento',
    house: 'Moradia',
    land: 'Terreno',
    commercial: 'Comercial',
  },
  purposes: {
    rent: 'Arrendamento',
    sale: 'Venda',
    both: 'Venda e arrendamento',
  },
  statuses: {
    draft: 'Rascunho',
    active: 'Activo',
    archived: 'Arquivado',
  },
  listHeading: 'Os seus patrimónios',
  listHint: 'Anúncios publicados — o Cliente encontra-os em Explorar Habitação.',
  mvpNote: 'Inclua preço e fotografias para o anúncio aparecer completo no fluxo do Cliente.',
} as const;

export function getPatrimoniosCopy() {
  return patrimoniosCopyPt;
}
