services:
  - type: web
    name: kutekalink
    runtime: static
    repo: https://github.com/EduardoZ121/Site_Angola
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_GOOGLE_CLIENT_ID
        value: 17788689781-3laohdt607lr8jnh30fatvqtji6htt3l.apps.googleusercontent.com
    domains:
      - kutekalink.com
      - www.kutekalink.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
