import type { IdentidadeCopy } from './pt';

export const identidadeCopyEn: IdentidadeCopy = {
  title: 'Kuteka Identity',
  subtitle: 'Your verified data — used automatically in contracts, payments and documents.',
  eyebrow: 'Identity Center',
  loadError: 'We are having trouble showing your data. Please try again shortly.',
  saveError: "We couldn't save right now. Check your connection and try again.",
  saveOk: 'Saved successfully.',
  saveAndContinue: 'Save and continue',
  continue: 'Continue',
  forbidden: 'Sign in to continue.',
  exportOk: 'Your data is ready to download.',
  exportError: "We couldn't prepare the export. Please try again later.",
  uploadError: 'The file was not uploaded. Choose another image or try again.',
  kycGateTitle: 'Verification required',
  kycGateBody:
    'For contracts, payments, reservations and visits, you need verified identity. Complete the Trust Center.',
  kycGateHint: 'Complete identity verification (KIS · KYC level 2+) in Profile before continuing.',
  kycCta: 'Open Trust Center',
  progress: 'Your profile is {n}% complete.',
  nextStep: 'Move to the next step',
  nextStepHint: 'Continue verification to unlock contracts and payments.',
  loading: 'Loading…',
  stepsNavLabel: 'KIS steps',
  documentUploadRequired: 'Upload the front and back of the document.',
  sections: {
    overview: 'Overview',
    trust: 'Verification status',
    personal: 'Personal identity',
    document: 'Identification document',
    photo: 'Official photo',
    contacts: 'Contacts',
    address: 'Address',
    banking: 'Banking details (optional)',
    privacy: 'Privacy and data',
  },
  steps: {
    overview: 'Overview',
    contacts: 'Contacts',
    personal: 'Identity',
    document: 'Document',
    photo: 'Photo',
    address: 'Address',
    banking: 'Bank',
    privacy: 'Privacy',
  },
  trustIndex: 'Trust index (UTS)',
  kycLevel: 'Verification level',
  completeness: 'Profile progress',
  personal: {
    legalFullName: 'Full legal name (as per ID)',
    preferredName: 'Preferred name',
    sex: 'Sex',
    birthDate: 'Date of birth',
    nationality: 'Nationality',
    placeOfBirth: 'Place of birth',
    maritalStatus: 'Marital status',
    save: 'Save identity',
  },
  sex: {
    female: 'Female',
    male: 'Male',
    other: 'Other',
    undisclosed: 'Prefer not to say',
  },
  marital: {
    single: 'Single',
    married: 'Married',
    de_facto: 'Domestic partnership',
    divorced: 'Divorced',
    widowed: 'Widowed',
    undisclosed: 'Prefer not to say',
  },
  document: {
    kind: 'Document type',
    number: 'Document number',
    issuedOn: 'Issue date',
    expiresOn: 'Expiry date',
    issuedAt: 'Place of issue',
    country: 'Issuing country',
    front: 'Front of document',
    back: 'Back of document',
    submit: 'Submit for verification',
    verified: 'Document verified',
    pending: 'Verification pending',
    rejected: 'Document rejected',
    rejectionReason: 'Reason',
    ocrNote:
      'Automatic document reading is in preparation — for now verification is handled by the Kuteka team.',
    kinds: {
      bi: 'National ID',
      passport: 'Passport',
      residence_card: 'Residence Card',
      other: 'Other',
    },
  },
  photo: {
    avatar: 'Profile photo',
    selfie: 'Selfie (optional, for future validation)',
    uploadAvatar: 'Upload photo',
    uploadSelfie: 'Upload selfie',
    required: 'A profile photo is required to move progress forward.',
    livenessNote:
      'Advanced facial validation is coming soon. Your profile photo already counts toward progress.',
  },
  contacts: {
    emailPrimary: 'Primary email',
    emailSecondary: 'Secondary email',
    phonePrimary: 'Primary phone',
    phoneSecondary: 'Alternate phone',
    emailConfirmed: 'Email confirmed',
    emailPending: 'Email unconfirmed',
    phoneConfirmed: 'Phone confirmed',
    phonePending: 'Phone unconfirmed',
    markPhone: 'Confirm this phone number is correct',
    save: 'Save contacts',
  },
  address: {
    country: 'Country',
    province: 'Province',
    municipality: 'Municipality',
    commune: 'Commune',
    neighborhood: 'Neighborhood',
    street: 'Street',
    number: 'Number',
    postalCode: 'Postal code',
    gps: 'GPS (optional)',
    gpsLat: 'Latitude',
    gpsLng: 'Longitude',
    save: 'Save address',
    submit: 'Submit address for verification',
  },
  banking: {
    bank: 'Bank',
    iban: 'IBAN',
    account: 'Account number',
    holder: 'Account holder name',
    wallets: 'Digital wallets (comma-separated)',
    save: 'Save banking details',
    submit: 'Submit for verification',
    hint: 'Optional — useful for refunds and a Premium account.',
  },
  privacy: {
    body: 'Your documents are protected. You can download a copy of your data at any time.',
    export: 'Download my data',
    confianca: 'Open Trust checklist',
    history: 'Change history',
    historyEmpty: 'No changes recorded yet.',
    access: 'Who accessed your data',
    accessLogs: 'Recent accesses',
    accessLogsEmpty: 'No accesses recorded yet.',
    emptyHistory: 'No changes recorded yet.',
    emptyAccess: 'No accesses recorded yet.',
  },
  party: {
    fromKis: 'Data comes automatically from your Kuteka identity.',
    empty: 'Complete your identity to fill in this block automatically.',
    bi: 'Document',
    address: 'Address',
    phone: 'Phone',
    email: 'Email',
  },
  pillars: {
    identity: 'Identity',
    email: 'Email',
    phone: 'Phone',
    document: 'Document',
    address: 'Address',
    banking: 'Bank account',
    photo: 'Photo',
  },
  trustCenter: {
    kicker: 'Kuteka Identity System',
    title: 'Kuteka Trust Center',
    subtitle:
      "See what you've already verified, what's missing and why some services are still locked.",
    accountStatusLabel: 'Account status',
    accountActive: 'Active account',
    accountPending: 'Account under verification',
    accountRestricted: 'Restricted account',
    utsLabel: 'UTS',
    utsOutOf: '/100',
    profileLabel: 'KIS profile',
    pillarsTitle: 'Trust pillars',
    pillarMissingLabel: 'Not added yet',
    nextStepSectionTitle: 'Next step',
    continueKis: 'Continue in KIS',
    openIdentity: 'Open identity',
    trustChecklist: 'Trust checklist',
    whyTitle: 'Why this matters',
    whyBody:
      'The Trust Center is the human-readable view of the KIS. Contracts, Kuteka Pay, reservations and services use these states — without asking again for what you already verified. KAI uses the same signal to suggest the next unlock.',
    refresh: 'Refresh status',
    statusLabels: {
      verified: 'Verified',
      pending: 'Under review',
      rejected: 'Rejected',
      missing: 'Not added',
    },
    utsBandLabels: {
      excellent: 'Excellent',
      good: 'Good',
      fair: 'Improving',
      low: 'Starting',
    },
    kycLevelLabels: {
      0: 'Level 0 — Account created',
      1: 'Level 1 — Contacts confirmed',
      2: 'Level 2 — Document validated',
      3: 'Level 3 — Kuteka Identity',
      4: 'Level 4 — Verified Premium Account',
    },
    unlockHints: {
      level2: 'Level 2 unlocks contracts, reservations, visits and Kuteka Pay.',
      level3: 'Level 3 fully validates your Kuteka identity for advanced operations.',
      level4: 'Level 4 (Premium) completes verified address and banking data.',
    },
    nextSteps: {
      contacts: {
        title: 'Verify your phone to progress',
        bodyLow: 'Confirm your phone and complete your identity to unlock Kuteka Pay.',
        bodyHigh: 'Verify your phone to strengthen your UTS and reach the next level.',
      },
      personal: {
        title: 'Complete your personal identity',
        body: 'Legal name, date of birth and nationality automatically feed contracts.',
      },
      document: {
        title: 'Submit your identification document',
        body: 'National ID or passport (front and back) — required for KYC level 2 and payments.',
      },
      photo: {
        title: 'Add your official photo',
        body: 'A profile photo strengthens trust on the platform and in the Digital Passport.',
      },
      address: {
        title: 'Validate your address',
        body: 'Your address appears on invoices, receipts and contracts — submit it for verification.',
      },
      banking: {
        title: 'Add your banking details',
        body: 'Optional for now; required for refunds and the Premium level (KYC 4).',
      },
      overview: {
        title: 'KIS profile in good shape',
        body: 'Keep your documents up to date. Explore the services you have unlocked.',
      },
    },
    kai: {
      payGateTitle: 'Verify your identity to use Kuteka Pay',
      nextBodyTemplate: 'Complete the Trust Center ({pct}%) and unlock reservations and services.',
      strongTitleTemplate: 'UTS {uts} — {band}',
      strongBody: 'Solid identity. You can operate contracts and payments with full confidence.',
      completeTitle: 'Complete your profile and unlock reservations',
    },
  },
};
