import type { IdentidadeCopy } from './pt';

export const identidadeCopyEs: IdentidadeCopy = {
  title: 'Identidad Kuteka',
  subtitle: 'Sus datos verificados — utilizados automáticamente en contratos, pagos y documentos.',
  eyebrow: 'Centro de identidad',
  loadError:
    'Estamos teniendo dificultades para mostrar sus datos. Inténtelo de nuevo en unos momentos.',
  saveError: 'No pudimos guardar en este momento. Verifique la conexión e inténtelo de nuevo.',
  saveOk: 'Guardado con éxito.',
  saveAndContinue: 'Guardar y continuar',
  continue: 'Continuar',
  forbidden: 'Inicie sesión para continuar.',
  exportOk: 'Sus datos están listos para descargar.',
  exportError: 'No pudimos preparar la exportación. Inténtelo más tarde.',
  uploadError: 'El archivo no se envió. Elija otra imagen o inténtelo de nuevo.',
  kycGateTitle: 'Verificación necesaria',
  kycGateBody:
    'Para contratos, pagos, reservas y visitas, necesita identidad verificada. Complete el Centro de Confianza.',
  kycGateHint:
    'Complete la verificación de identidad (KIS · KYC nivel 2+) en Perfil antes de continuar.',
  kycCta: 'Abrir Centro de Confianza',
  progress: 'Su perfil está completo al {n}%.',
  nextStep: 'Ir al siguiente paso',
  nextStepHint: 'Continúe la verificación para desbloquear contratos y pagos.',
  loading: 'Cargando…',
  stepsNavLabel: 'Pasos del KIS',
  documentUploadRequired: 'Cargue el frente y el reverso del documento.',
  sections: {
    overview: 'Resumen',
    trust: 'Estado de verificación',
    personal: 'Identidad personal',
    document: 'Documento de identificación',
    photo: 'Fotografía oficial',
    contacts: 'Contactos',
    address: 'Dirección',
    banking: 'Datos bancarios (opcional)',
    privacy: 'Privacidad y datos',
  },
  steps: {
    overview: 'Resumen',
    contacts: 'Contactos',
    personal: 'Identidad',
    document: 'Documento',
    photo: 'Fotografía',
    address: 'Dirección',
    banking: 'Banco',
    privacy: 'Privacidad',
  },
  trustIndex: 'Índice de confianza (UTS)',
  kycLevel: 'Nivel de verificación',
  completeness: 'Progreso del perfil',
  personal: {
    legalFullName: 'Nombre completo legal (según documento de identidad)',
    preferredName: 'Nombre preferido',
    sex: 'Sexo',
    birthDate: 'Fecha de nacimiento',
    nationality: 'Nacionalidad',
    placeOfBirth: 'Lugar de nacimiento',
    maritalStatus: 'Estado civil',
    save: 'Guardar identidad',
  },
  sex: {
    female: 'Femenino',
    male: 'Masculino',
    other: 'Otro',
    undisclosed: 'Prefiero no decirlo',
  },
  marital: {
    single: 'Soltero(a)',
    married: 'Casado(a)',
    de_facto: 'Unión de hecho',
    divorced: 'Divorciado(a)',
    widowed: 'Viudo(a)',
    undisclosed: 'Prefiero no decirlo',
  },
  document: {
    kind: 'Tipo de documento',
    number: 'Número de documento',
    issuedOn: 'Fecha de emisión',
    expiresOn: 'Fecha de caducidad',
    issuedAt: 'Lugar de emisión',
    country: 'País emisor',
    front: 'Anverso del documento',
    back: 'Reverso del documento',
    submit: 'Enviar para verificación',
    verified: 'Documento verificado',
    pending: 'Verificación pendiente',
    rejected: 'Documento rechazado',
    rejectionReason: 'Motivo',
    ocrNote:
      'La lectura automática del documento está en preparación — por ahora la verificación la realiza el equipo Kuteka.',
    kinds: {
      bi: 'Documento de identidad',
      passport: 'Pasaporte',
      residence_card: 'Tarjeta de residencia',
      other: 'Otro',
    },
  },
  photo: {
    avatar: 'Foto de perfil',
    selfie: 'Selfie (opcional, para validación futura)',
    uploadAvatar: 'Subir foto',
    uploadSelfie: 'Subir selfie',
    required: 'La foto de perfil es obligatoria para avanzar en el progreso.',
    livenessNote:
      'La validación facial avanzada llegará pronto. Su foto de perfil ya cuenta para el progreso.',
  },
  contacts: {
    emailPrimary: 'Correo principal',
    emailSecondary: 'Correo secundario',
    phonePrimary: 'Teléfono principal',
    phoneSecondary: 'Teléfono alternativo',
    emailConfirmed: 'Correo confirmado',
    emailPending: 'Correo por confirmar',
    phoneConfirmed: 'Teléfono confirmado',
    phonePending: 'Teléfono por confirmar',
    markPhone: 'Confirmar que este teléfono es correcto',
    save: 'Guardar contactos',
  },
  address: {
    country: 'País',
    province: 'Provincia',
    municipality: 'Municipio',
    commune: 'Comuna',
    neighborhood: 'Barrio',
    street: 'Calle',
    number: 'Número',
    postalCode: 'Código postal',
    gps: 'GPS (opcional)',
    gpsLat: 'Latitud',
    gpsLng: 'Longitud',
    save: 'Guardar dirección',
    submit: 'Enviar dirección para verificación',
  },
  banking: {
    bank: 'Banco',
    iban: 'IBAN',
    account: 'Número de cuenta',
    holder: 'Nombre del titular',
    wallets: 'Billeteras digitales (separadas por comas)',
    save: 'Guardar datos bancarios',
    submit: 'Enviar para verificación',
    hint: 'Opcional — útil para reembolsos y cuenta Premium.',
  },
  privacy: {
    body: 'Sus documentos están protegidos. Puede descargar una copia de sus datos en cualquier momento.',
    export: 'Descargar mis datos',
    confianca: 'Abrir lista de verificación de Confianza',
    history: 'Historial de cambios',
    historyEmpty: 'Aún no hay cambios registrados.',
    access: 'Quién consultó sus datos',
    accessLogs: 'Consultas recientes',
    accessLogsEmpty: 'Aún no hay consultas registradas.',
    emptyHistory: 'Aún no hay cambios registrados.',
    emptyAccess: 'Aún no hay consultas registradas.',
  },
  party: {
    fromKis: 'Datos provenientes automáticamente de su identidad Kuteka.',
    empty: 'Complete su identidad para rellenar este bloque automáticamente.',
    bi: 'Documento',
    address: 'Dirección',
    phone: 'Teléfono',
    email: 'Correo',
  },
  pillars: {
    identity: 'Identidad',
    email: 'Correo',
    phone: 'Teléfono',
    document: 'Documento',
    address: 'Dirección',
    banking: 'Cuenta bancaria',
    photo: 'Fotografía',
  },
  trustCenter: {
    kicker: 'Kuteka Identity System',
    title: 'Centro de Confianza Kuteka',
    subtitle:
      'Vea lo que ya ha validado, lo que falta y por qué algunos servicios siguen bloqueados.',
    accountStatusLabel: 'Estado de la cuenta',
    accountActive: 'Cuenta activa',
    accountPending: 'Cuenta en verificación',
    accountRestricted: 'Cuenta limitada',
    utsLabel: 'UTS',
    utsOutOf: '/100',
    profileLabel: 'Perfil KIS',
    pillarsTitle: 'Pilares de confianza',
    pillarMissingLabel: 'Aún no añadido',
    nextStepSectionTitle: 'Siguiente paso',
    continueKis: 'Continuar en el KIS',
    openIdentity: 'Abrir identidad',
    trustChecklist: 'Checklist de Confianza',
    whyTitle: 'Por qué esto importa',
    whyBody:
      'El Centro de Confianza es la lectura humana del KIS. Contratos, Kuteka Pay, reservas y servicios usan estos estados — sin volver a pedir lo que ya validó. El KAI usa la misma señal para sugerir el siguiente desbloqueo.',
    refresh: 'Actualizar estado',
    statusLabels: {
      verified: 'Verificado',
      pending: 'En análisis',
      rejected: 'Rechazado',
      missing: 'No añadido',
    },
    utsBandLabels: {
      excellent: 'Excelente',
      good: 'Bueno',
      fair: 'En evolución',
      low: 'Inicial',
    },
    kycLevelLabels: {
      0: 'Nivel 0 — Cuenta creada',
      1: 'Nivel 1 — Contactos confirmados',
      2: 'Nivel 2 — Documento validado',
      3: 'Nivel 3 — Identidad Kuteka',
      4: 'Nivel 4 — Cuenta Premium Verificada',
    },
    unlockHints: {
      level2: 'Con el nivel 2 desbloquea contratos, reservas, visitas y Kuteka Pay.',
      level3: 'Con el nivel 3 la identidad Kuteka queda validada para operaciones avanzadas.',
      level4: 'Con el nivel 4 (Premium) completa dirección verificada y datos bancarios.',
    },
    nextSteps: {
      contacts: {
        title: 'Verifique el teléfono para progresar',
        bodyLow: 'Confirme el teléfono y avance su identidad para desbloquear Kuteka Pay.',
        bodyHigh: 'Verifique el teléfono para reforzar el UTS y alcanzar el siguiente nivel.',
      },
      personal: {
        title: 'Complete su identidad personal',
        body: 'Nombre según documento, fecha de nacimiento y nacionalidad alimentan contratos automáticamente.',
      },
      document: {
        title: 'Envíe el documento de identificación',
        body: 'Documento de identidad o pasaporte (anverso y reverso) — necesario para KYC nivel 2 y pagos.',
      },
      photo: {
        title: 'Añada su fotografía oficial',
        body: 'La foto de perfil fortalece la confianza en la plataforma y en el Pasaporte Digital.',
      },
      address: {
        title: 'Valide su dirección',
        body: 'La dirección aparece en facturas, recibos y contratos — envíela para verificación.',
      },
      banking: {
        title: 'Añada datos bancarios',
        body: 'Opcional por ahora; necesario para reembolsos y el nivel Premium (KYC 4).',
      },
      overview: {
        title: 'Perfil KIS en buen estado',
        body: 'Siga manteniendo documentos válidos. Explore los servicios desbloqueados.',
      },
    },
    kai: {
      payGateTitle: 'Verifique su identidad para usar Kuteka Pay',
      nextBodyTemplate:
        'Complete el Centro de Confianza ({pct}%) y desbloquee reservas y servicios.',
      strongTitleTemplate: 'UTS {uts} — {band}',
      strongBody: 'Identidad sólida. Puede operar contratos y pagos con plena confianza.',
      completeTitle: 'Complete su perfil y desbloquee reservas',
    },
  },
};
