import type { IdentidadeCopy } from './pt';

export const identidadeCopyFr: IdentidadeCopy = {
  title: 'Identité Kuteka',
  subtitle:
    'Vos données vérifiées — utilisées automatiquement dans les contrats, paiements et documents.',
  eyebrow: "Centre d'identité",
  loadError: 'Nous avons du mal à afficher vos données. Réessayez dans un instant.',
  saveError: "Impossible d'enregistrer pour le moment. Vérifiez la connexion et réessayez.",
  saveOk: 'Enregistré avec succès.',
  saveAndContinue: 'Enregistrer et continuer',
  continue: 'Continuer',
  forbidden: 'Connectez-vous pour continuer.',
  exportOk: 'Vos données sont prêtes à être téléchargées.',
  exportError: "Impossible de préparer l'export. Réessayez plus tard.",
  uploadError: "Le fichier n'a pas été envoyé. Choisissez une autre image ou réessayez.",
  kycGateTitle: 'Vérification requise',
  kycGateBody:
    'Pour les contrats, paiements, réservations et visites, une identité vérifiée est nécessaire. Complétez le Centre de Confiance.',
  kycGateHint:
    'Complétez la vérification d’identité (KIS · KYC niveau 2+) dans Profil avant de continuer.',
  kycCta: 'Ouvrir le Centre de Confiance',
  progress: 'Votre profil est complété à {n} %.',
  nextStep: "Passer à l'étape suivante",
  nextStepHint: 'Continuez la vérification pour débloquer contrats et paiements.',
  loading: 'Chargement…',
  stepsNavLabel: 'Étapes du KIS',
  documentUploadRequired: 'Téléversez le recto et le verso du document.',
  sections: {
    overview: 'Résumé',
    trust: 'État de vérification',
    personal: 'Identité personnelle',
    document: "Document d'identification",
    photo: 'Photo officielle',
    contacts: 'Contacts',
    address: 'Adresse',
    banking: 'Coordonnées bancaires (facultatif)',
    privacy: 'Confidentialité et données',
  },
  steps: {
    overview: 'Résumé',
    contacts: 'Contacts',
    personal: 'Identité',
    document: 'Document',
    photo: 'Photo',
    address: 'Adresse',
    banking: 'Banque',
    privacy: 'Confidentialité',
  },
  trustIndex: 'Indice de confiance (UTS)',
  kycLevel: 'Niveau de vérification',
  completeness: 'Progression du profil',
  personal: {
    legalFullName: "Nom complet légal (selon la pièce d'identité)",
    preferredName: 'Nom préféré',
    sex: 'Sexe',
    birthDate: 'Date de naissance',
    nationality: 'Nationalité',
    placeOfBirth: 'Lieu de naissance',
    maritalStatus: 'État civil',
    save: "Enregistrer l'identité",
  },
  sex: {
    female: 'Féminin',
    male: 'Masculin',
    other: 'Autre',
    undisclosed: 'Préfère ne pas préciser',
  },
  marital: {
    single: 'Célibataire',
    married: 'Marié(e)',
    de_facto: 'Union de fait',
    divorced: 'Divorcé(e)',
    widowed: 'Veuf/veuve',
    undisclosed: 'Préfère ne pas préciser',
  },
  document: {
    kind: 'Type de document',
    number: 'Numéro du document',
    issuedOn: "Date d'émission",
    expiresOn: "Date d'expiration",
    issuedAt: "Lieu d'émission",
    country: 'Pays émetteur',
    front: 'Recto du document',
    back: 'Verso du document',
    submit: 'Soumettre pour vérification',
    verified: 'Document vérifié',
    pending: 'Vérification en attente',
    rejected: 'Document rejeté',
    rejectionReason: 'Motif',
    ocrNote:
      "La lecture automatique du document est en préparation — pour l'instant la vérification est effectuée par l'équipe Kuteka.",
    kinds: {
      bi: "Carte d'identité",
      passport: 'Passeport',
      residence_card: 'Carte de résidence',
      other: 'Autre',
    },
  },
  photo: {
    avatar: 'Photo de profil',
    selfie: 'Selfie (facultatif, pour validation future)',
    uploadAvatar: 'Télécharger la photo',
    uploadSelfie: 'Télécharger le selfie',
    required: 'La photo de profil est obligatoire pour faire progresser votre dossier.',
    livenessNote:
      'La validation faciale avancée arrive bientôt. Votre photo de profil compte déjà dans la progression.',
  },
  contacts: {
    emailPrimary: 'Email principal',
    emailSecondary: 'Email secondaire',
    phonePrimary: 'Téléphone principal',
    phoneSecondary: 'Téléphone alternatif',
    emailConfirmed: 'Email confirmé',
    emailPending: 'Email non confirmé',
    phoneConfirmed: 'Téléphone confirmé',
    phonePending: 'Téléphone non confirmé',
    markPhone: 'Confirmer que ce numéro est correct',
    save: 'Enregistrer les contacts',
  },
  address: {
    country: 'Pays',
    province: 'Province',
    municipality: 'Municipalité',
    commune: 'Commune',
    neighborhood: 'Quartier',
    street: 'Rue',
    number: 'Numéro',
    postalCode: 'Code postal',
    gps: 'GPS (facultatif)',
    gpsLat: 'Latitude',
    gpsLng: 'Longitude',
    save: "Enregistrer l'adresse",
    submit: "Soumettre l'adresse pour vérification",
  },
  banking: {
    bank: 'Banque',
    iban: 'IBAN',
    account: 'Numéro de compte',
    holder: 'Nom du titulaire',
    wallets: 'Portefeuilles numériques (séparés par des virgules)',
    save: 'Enregistrer les données bancaires',
    submit: 'Soumettre pour vérification',
    hint: 'Facultatif — utile pour les remboursements et le compte Premium.',
  },
  privacy: {
    body: 'Vos documents sont protégés. Vous pouvez télécharger une copie de vos données à tout moment.',
    export: 'Télécharger mes données',
    confianca: 'Ouvrir la checklist Confiance',
    history: 'Historique des modifications',
    historyEmpty: 'Aucune modification enregistrée pour le moment.',
    access: 'Qui a consulté vos données',
    accessLogs: 'Consultations récentes',
    accessLogsEmpty: 'Aucune consultation enregistrée pour le moment.',
    emptyHistory: 'Aucune modification enregistrée pour le moment.',
    emptyAccess: 'Aucune consultation enregistrée pour le moment.',
  },
  party: {
    fromKis: 'Données provenant automatiquement de votre identité Kuteka.',
    empty: 'Complétez votre identité pour remplir ce bloc automatiquement.',
    bi: 'Document',
    address: 'Adresse',
    phone: 'Téléphone',
    email: 'Email',
  },
  pillars: {
    identity: 'Identité',
    email: 'Email',
    phone: 'Téléphone',
    document: 'Document',
    address: 'Adresse',
    banking: 'Compte bancaire',
    photo: 'Photo',
  },
  trustCenter: {
    kicker: 'Kuteka Identity System',
    title: 'Centre de Confiance Kuteka',
    subtitle:
      'Découvrez ce que vous avez déjà validé, ce qui manque et pourquoi certains services restent verrouillés.',
    accountStatusLabel: 'État du compte',
    accountActive: 'Compte actif',
    accountPending: 'Compte en vérification',
    accountRestricted: 'Compte limité',
    utsLabel: 'UTS',
    utsOutOf: '/100',
    profileLabel: 'Profil KIS',
    pillarsTitle: 'Piliers de confiance',
    pillarMissingLabel: 'Pas encore ajouté',
    nextStepSectionTitle: 'Prochaine étape',
    continueKis: 'Continuer dans le KIS',
    openIdentity: "Ouvrir l'identité",
    trustChecklist: 'Checklist Confiance',
    whyTitle: 'Pourquoi c’est important',
    whyBody:
      'Le Centre de Confiance est la lecture humaine du KIS. Contrats, Kuteka Pay, réservations et services utilisent ces états — sans redemander ce que vous avez déjà validé. KAI utilise le même signal pour suggérer le prochain déblocage.',
    refresh: 'Actualiser l’état',
    statusLabels: {
      verified: 'Vérifié',
      pending: 'En analyse',
      rejected: 'Rejeté',
      missing: 'Non ajouté',
    },
    utsBandLabels: {
      excellent: 'Excellent',
      good: 'Bon',
      fair: 'En progression',
      low: 'Initial',
    },
    kycLevelLabels: {
      0: 'Niveau 0 — Compte créé',
      1: 'Niveau 1 — Contacts confirmés',
      2: 'Niveau 2 — Document validé',
      3: 'Niveau 3 — Identité Kuteka',
      4: 'Niveau 4 — Compte Premium vérifié',
    },
    unlockHints: {
      level2: 'Le niveau 2 débloque contrats, réservations, visites et Kuteka Pay.',
      level3: 'Le niveau 3 valide totalement votre identité Kuteka pour les opérations avancées.',
      level4: 'Le niveau 4 (Premium) complète l’adresse vérifiée et les données bancaires.',
    },
    nextSteps: {
      contacts: {
        title: 'Vérifiez votre téléphone pour progresser',
        bodyLow: 'Confirmez votre téléphone et complétez votre identité pour débloquer Kuteka Pay.',
        bodyHigh:
          'Vérifiez votre téléphone pour renforcer votre UTS et atteindre le niveau suivant.',
      },
      personal: {
        title: 'Complétez votre identité personnelle',
        body: 'Nom légal, date de naissance et nationalité alimentent automatiquement les contrats.',
      },
      document: {
        title: "Soumettez votre document d'identification",
        body: "Carte d'identité ou passeport (recto et verso) — requis pour le KYC niveau 2 et les paiements.",
      },
      photo: {
        title: 'Ajoutez votre photo officielle',
        body: 'Une photo de profil renforce la confiance sur la plateforme et dans le Passeport Numérique.',
      },
      address: {
        title: 'Validez votre adresse',
        body: 'Votre adresse apparaît sur les factures, reçus et contrats — soumettez-la pour vérification.',
      },
      banking: {
        title: 'Ajoutez vos coordonnées bancaires',
        body: 'Facultatif pour l’instant ; requis pour les remboursements et le niveau Premium (KYC 4).',
      },
      overview: {
        title: 'Profil KIS en bon état',
        body: 'Continuez à maintenir des documents valides. Explorez les services débloqués.',
      },
    },
    kai: {
      payGateTitle: 'Vérifiez votre identité pour utiliser Kuteka Pay',
      nextBodyTemplate:
        'Complétez le Centre de Confiance ({pct}%) et débloquez réservations et services.',
      strongTitleTemplate: 'UTS {uts} — {band}',
      strongBody: 'Identité solide. Vous pouvez opérer contrats et paiements en toute confiance.',
      completeTitle: 'Complétez votre profil et débloquez des réservations',
    },
  },
};
