export function getIdentidadeCopy() {
  return {
    title: 'Identidade Kuteka',
    subtitle:
      'Os seus dados verificados — usados automaticamente em contratos, pagamentos e documentos.',
    eyebrow: 'Centro de identidade',
    loadError:
      'Estamos a ter dificuldade em mostrar os seus dados. Tente novamente dentro de momentos.',
    saveError: 'Não conseguimos guardar agora. Verifique a ligação e tente outra vez.',
    saveOk: 'Guardado com sucesso.',
    saveAndContinue: 'Guardar e continuar',
    continue: 'Continuar',
    forbidden: 'Inicie sessão para continuar.',
    exportOk: 'Os seus dados estão prontos a descarregar.',
    exportError: 'Não conseguimos preparar a exportação. Tente mais tarde.',
    uploadError: 'O ficheiro não foi enviado. Escolha outra imagem ou tente novamente.',
    kycGateTitle: 'Verificação necessária',
    kycGateBody:
      'Para contratos, pagamentos, reservas e visitas, precisa de identidade verificada. Complete o Centro de Confiança.',
    kycCta: 'Abrir Centro de Confiança',
    progress: 'O seu perfil está {n}% completo.',
    nextStep: 'Seguir para o próximo passo',
    nextStepHint: 'Continue a verificação para desbloquear contratos e pagamentos.',
    sections: {
      overview: 'Resumo',
      trust: 'Estado de verificação',
      personal: 'Identidade pessoal',
      document: 'Documento de identificação',
      photo: 'Fotografia oficial',
      contacts: 'Contactos',
      address: 'Endereço',
      banking: 'Dados bancários (opcional)',
      privacy: 'Privacidade e dados',
    },
    steps: {
      overview: 'Resumo',
      contacts: 'Contactos',
      personal: 'Identidade',
      document: 'Documento',
      photo: 'Fotografia',
      address: 'Morada',
      banking: 'Banco',
      privacy: 'Privacidade',
    },
    trustIndex: 'Índice de confiança (UTS)',
    kycLevel: 'Nível de verificação',
    completeness: 'Progresso do perfil',
    personal: {
      legalFullName: 'Nome completo (conforme BI)',
      preferredName: 'Nome preferido',
      sex: 'Sexo',
      birthDate: 'Data de nascimento',
      nationality: 'Nacionalidade',
      placeOfBirth: 'Naturalidade',
      maritalStatus: 'Estado civil',
      save: 'Guardar identidade',
    },
    sex: {
      female: 'Feminino',
      male: 'Masculino',
      other: 'Outro',
      undisclosed: 'Prefiro não indicar',
    },
    marital: {
      single: 'Solteiro(a)',
      married: 'Casado(a)',
      de_facto: 'União de facto',
      divorced: 'Divorciado(a)',
      widowed: 'Viúvo(a)',
      undisclosed: 'Prefiro não indicar',
    },
    document: {
      kind: 'Tipo de documento',
      number: 'Número do documento',
      issuedOn: 'Data de emissão',
      expiresOn: 'Data de validade',
      issuedAt: 'Local de emissão',
      country: 'País emissor',
      front: 'Frente do documento',
      back: 'Verso do documento',
      submit: 'Submeter para verificação',
      verified: 'Documento verificado',
      pending: 'Aguardando verificação',
      rejected: 'Documento rejeitado',
      rejectionReason: 'Motivo',
      ocrNote:
        'Leitura automática do documento em preparação — por agora a verificação é feita pela equipa Kuteka.',
      kinds: {
        bi: 'BI',
        passport: 'Passaporte',
        residence_card: 'Cartão de Residência',
        other: 'Outro',
      },
    },
    photo: {
      avatar: 'Fotografia de perfil',
      selfie: 'Selfie (opcional, para validação futura)',
      uploadAvatar: 'Carregar fotografia',
      uploadSelfie: 'Carregar selfie',
      required: 'A fotografia de perfil é obrigatória para avançar no progresso.',
      livenessNote:
        'Validação facial avançada chegará em breve. A fotografia de perfil já conta para o progresso.',
    },
    contacts: {
      emailPrimary: 'Email principal',
      emailSecondary: 'Email secundário',
      phonePrimary: 'Telefone principal',
      phoneSecondary: 'Telefone alternativo',
      emailConfirmed: 'Email confirmado',
      emailPending: 'Email por confirmar',
      phoneConfirmed: 'Telefone confirmado',
      phonePending: 'Telefone por confirmar',
      markPhone: 'Confirmar que este telefone está correcto',
      save: 'Guardar contactos',
    },
    address: {
      country: 'País',
      province: 'Província',
      municipality: 'Município',
      commune: 'Comuna',
      neighborhood: 'Bairro',
      street: 'Rua',
      number: 'Número',
      postalCode: 'Código postal',
      gps: 'GPS (opcional)',
      gpsLat: 'Latitude',
      gpsLng: 'Longitude',
      save: 'Guardar endereço',
      submit: 'Submeter endereço para verificação',
    },
    banking: {
      bank: 'Banco',
      iban: 'IBAN',
      account: 'Número da conta',
      holder: 'Nome do titular',
      wallets: 'Carteiras digitais (separadas por vírgula)',
      save: 'Guardar dados bancários',
      submit: 'Submeter para verificação',
      hint: 'Opcional — útil para reembolsos e conta Premium.',
    },
    privacy: {
      body: 'Os seus documentos estão protegidos. Pode descarregar uma cópia dos seus dados a qualquer momento.',
      export: 'Descarregar os meus dados',
      confianca: 'Abrir checklist Confiança',
      history: 'Histórico de alterações',
      historyEmpty: 'Ainda sem alterações registadas.',
      access: 'Quem consultou os seus dados',
      accessLogs: 'Consultas recentes',
      accessLogsEmpty: 'Ainda sem consultas registadas.',
      emptyHistory: 'Ainda sem alterações registadas.',
      emptyAccess: 'Ainda sem consultas registadas.',
    },
    party: {
      fromKis: 'Dados vindos automaticamente da sua identidade Kuteka.',
      empty: 'Complete a identidade para preencher este bloco automaticamente.',
      bi: 'Documento',
      address: 'Morada',
      phone: 'Telefone',
      email: 'Email',
    },
    pillars: {
      identity: 'Identidade',
      email: 'Email',
      phone: 'Telefone',
      document: 'Documento',
      address: 'Endereço',
      banking: 'Conta bancária',
      photo: 'Fotografia',
    },
  } as const;
}

export type IdentidadeCopy = ReturnType<typeof getIdentidadeCopy>;
