export function getIdentidadeCopy() {
  return {
    title: 'Perfil e Identidade Real',
    subtitle:
      'A Kuteka opera com identidade verificada — estes dados alimentam contratos, facturas e confiança.',
    eyebrow: 'Identidade Kuteka',
    loadError: 'Não foi possível carregar o perfil.',
    saveError: 'Não foi possível guardar. Tente novamente.',
    saveOk: 'Dados guardados.',
    forbidden: 'Sessão necessária.',
    exportOk: 'Exportação pronta.',
    exportError: 'Não foi possível exportar os seus dados.',
    uploadError: 'Falha no envio do ficheiro.',
    kycGateTitle: 'Verificação necessária',
    kycGateBody:
      'Acções de contrato, pagamento, reserva, visita, compra, venda ou arrendamento exigem identidade verificada (nível 2+).',
    kycCta: 'Completar verificação',
    sections: {
      trust: 'Estado de Verificação Kuteka',
      personal: 'Identidade Pessoal',
      document: 'Documento de Identificação',
      photo: 'Fotografia Oficial',
      contacts: 'Contactos Verificados',
      address: 'Endereço',
      banking: 'Dados Bancários (opcional)',
      privacy: 'Protecção de Dados',
    },
    trustIndex: 'Índice de Confiança',
    kycLevel: 'Nível KYC',
    personal: {
      legalFullName: 'Nome completo (conforme BI)',
      preferredName: 'Nome preferido',
      sex: 'Sexo',
      birthDate: 'Data de nascimento',
      nationality: 'Nacionalidade',
      placeOfBirth: 'Naturalidade',
      maritalStatus: 'Estado civil',
      save: 'Guardar identidade',
    },
    sex: {
      female: 'Feminino',
      male: 'Masculino',
      other: 'Outro',
      undisclosed: 'Prefiro não indicar',
    },
    marital: {
      single: 'Solteiro(a)',
      married: 'Casado(a)',
      de_facto: 'União de facto',
      divorced: 'Divorciado(a)',
      widowed: 'Viúvo(a)',
      undisclosed: 'Prefiro não indicar',
    },
    document: {
      kind: 'Tipo de documento',
      number: 'Número do documento',
      issuedOn: 'Data de emissão',
      expiresOn: 'Data de validade',
      issuedAt: 'Local de emissão',
      country: 'País emissor',
      front: 'Frente do documento',
      back: 'Verso do documento',
      submit: 'Submeter para verificação',
      verified: 'Documento verificado',
      pending: 'Aguardando verificação',
      rejected: 'Documento rejeitado',
      kinds: {
        bi: 'BI',
        passport: 'Passaporte',
        residence_card: 'Cartão de Residência',
        other: 'Outro',
      },
    },
    photo: {
      avatar: 'Fotografia de perfil',
      selfie: 'Selfie para validação facial (opcional)',
      uploadAvatar: 'Carregar fotografia',
      uploadSelfie: 'Carregar selfie',
    },
    contacts: {
      emailPrimary: 'Email principal',
      emailSecondary: 'Email secundário',
      phonePrimary: 'Telefone principal',
      phoneSecondary: 'Telefone alternativo',
      emailConfirmed: 'Email confirmado',
      emailPending: 'Email por confirmar',
      phoneConfirmed: 'Telefone confirmado',
      phonePending: 'Telefone por confirmar',
      markPhone: 'Marcar telefone como confirmado (MVP)',
      save: 'Guardar contactos',
    },
    address: {
      country: 'País',
      province: 'Província',
      municipality: 'Município',
      commune: 'Comuna',
      neighborhood: 'Bairro',
      street: 'Rua',
      number: 'Número',
      postalCode: 'Código postal',
      gps: 'GPS (opcional)',
      save: 'Guardar endereço',
      submit: 'Submeter endereço para verificação',
    },
    banking: {
      bank: 'Banco',
      iban: 'IBAN',
      account: 'Número da conta',
      holder: 'Nome do titular',
      wallets: 'Carteiras digitais (separadas por vírgula)',
      save: 'Guardar dados bancários',
      hint: 'Opcional — necessário para alguns pagamentos e reembolsos.',
    },
    privacy: {
      body: 'Documentos ficam em armazenamento privado, com auditoria de acessos e histórico de alterações. Pode exportar os seus dados a qualquer momento.',
      export: 'Descarregar os meus dados',
      confianca: 'Abrir checklist Confiança',
    },
    pillars: {
      identity: 'Identidade',
      email: 'Email',
      phone: 'Telefone',
      document: 'Documento',
      address: 'Endereço',
      banking: 'Conta bancária',
    },
  } as const;
}

export type IdentidadeCopy = ReturnType<typeof getIdentidadeCopy>;
