import type { SegurancaCopy } from './pt';

/** Security Center copy — en. */
export const segurancaCopyEn: SegurancaCopy = {
  eyebrow: 'Identity & Security',
  title: 'Security Center',
  subtitle: 'Confirmations, sessions, devices and your Kuteka account security level.',
  verifiedBadge: 'Verified',
  pendingBadge: 'Pending',
  kyc: {
    complete: 'KYC complete',
    level: 'KYC level {n}',
    initial: 'KYC started',
    notStarted: 'KYC not started',
  },
  securityLevel: 'Security level',
  emailLabel: 'Email',
  phoneLabel: 'Phone',
  kycStatus: 'KYC status',
  openTrustCenter: 'Open Trust Center',
  lastLogin: 'Last login',
  noRecordYet: 'No record yet',
  mfaLabel: '2FA',
  mfaActive: 'Active',
  mfaPreparing: 'Ready — future activation',
  infraReady: 'Infra ready',
  phoneVerifySection: {
    title: 'Verify phone (SMS OTP)',
    hint: 'Sandbox flow ready for Twilio, MessageBird or Infobip (Angola).',
    numberLabel: 'Number',
    sendCode: 'Send code',
    otpLabel: '6-digit code',
    confirmPhone: 'Confirm phone',
  },
  devices: {
    title: 'Active devices',
    empty: 'Inventory ready. Devices will appear once the flag is active.',
    fallbackName: 'Device',
    seenAt: 'Seen {date}',
  },
  sessions: {
    title: 'Open sessions',
    emptyPrefix: 'Remote session management ready (flag',
    emptySuffix: ').',
    unknownIp: 'Unknown IP',
    terminate: 'End',
  },
  history: {
    title: 'Authentication and change history',
    empty:
      'No events yet. Logins, recoveries and sensitive changes will appear here — with notification when flagged.',
    notifySuffix: ' · notify',
  },
  emailChange: {
    title: 'Change email',
    hint: 'Dual confirmation (code on current and new email). In beta, codes may appear here (beta_inline).',
    inactiveHint:
      'Prepared, not activated (D5). Account email cannot be changed in this test. Identity stays the user id, not the address.',
    newEmailLabel: 'New email',
    request: 'Request change',
    oldCodeLabel: 'Code from current email',
    newCodeLabel: 'Code from new email',
    confirm: 'Confirm change',
    betaCodesHint: 'Beta codes — current: {old} · new: {new}',
    requested: 'Request created. Enter both codes below.',
    completed: 'Email updated successfully.',
  },
  actions: {
    sandboxHint: 'Sandbox: use code {code}',
    codeSent: 'Code sent. Enter the 6 digits below.',
    phoneVerified: 'Phone verified successfully.',
    sessionRevoked: 'Session marked as ended.',
  },
  scoreLabels: {
    excellent: 'Excellent',
    high: 'Good',
    medium: 'Moderate',
    low: 'Needs improvement',
  },
  events: {
    otp_issued: 'OTP code issued',
    otp_verified: 'OTP code verified',
    session_revoked: 'Session ended remotely',
    login_new: 'New login',
    device_new: 'New device',
    password_changed: 'Password changed',
    email_changed: 'Email changed',
    phone_changed: 'Phone changed',
    document_updated: 'Document updated',
    banking_added: 'Bank account added',
    recovery_started: 'Account recovery started',
    permissions_changed: 'Permissions changed',
  },
  client: {
    authUnavailable: 'Authentication is not available in this environment.',
    loadError: 'Could not load the Security Center.',
    networkErrorLoad: 'Network error loading security data.',
    invalidPhone: 'Enter a valid phone number (e.g. +2449XXXXXXXX).',
    otpSendError: 'Could not send the code.',
    otpIssueError: 'Could not issue the OTP code.',
    networkErrorOtpIssue: 'Network error issuing OTP.',
    otpLengthError: 'Enter the 6-digit code.',
    otpInvalidGeneric: 'Invalid code.',
    otpErrors: {
      invalid_code: 'Incorrect code. Try again.',
      expired: 'The code expired. Request a new one.',
      already_used: 'This code was already used.',
      too_many_attempts: 'Too many attempts. Request a new code.',
      challenge_not_found: 'Challenge not found. Request a new code.',
      forbidden: 'You do not have permission to validate this code.',
    },
    otpValidateFallback: 'Could not validate the code.',
    networkErrorOtpValidate: 'Network error validating OTP.',
    revokeError: 'Could not end the session.',
    revokeNotFound: 'Session not found or already ended.',
    networkErrorGeneric: 'Network error.',
  },
};
