import type { SegurancaCopy } from './pt';

/** Centro de Seguridad — copy es. */
export const segurancaCopyEs: SegurancaCopy = {
  eyebrow: 'Identity & Security',
  title: 'Centro de Seguridad',
  subtitle: 'Confirmaciones, sesiones, dispositivos y nivel de seguridad de su cuenta Kuteka.',
  verifiedBadge: 'Verificado',
  pendingBadge: 'Pendiente',
  kyc: {
    complete: 'KYC completo',
    level: 'KYC nivel {n}',
    initial: 'KYC iniciado',
    notStarted: 'KYC por iniciar',
  },
  securityLevel: 'Nivel de seguridad',
  emailLabel: 'Email',
  phoneLabel: 'Teléfono',
  kycStatus: 'Estado KYC',
  openTrustCenter: 'Abrir Centro de Confianza',
  lastLogin: 'Último acceso',
  noRecordYet: 'Aún sin registro',
  mfaLabel: '2FA',
  mfaActive: 'Activo',
  mfaPreparing: 'Preparado — activación futura',
  infraReady: 'Infraestructura lista',
  phoneVerifySection: {
    title: 'Verificar teléfono (OTP SMS)',
    hint: 'Flujo sandbox listo para Twilio, MessageBird o Infobip (Angola).',
    numberLabel: 'Número',
    sendCode: 'Enviar código',
    otpLabel: 'Código de 6 dígitos',
    confirmPhone: 'Confirmar teléfono',
  },
  devices: {
    title: 'Dispositivos activos',
    empty: 'Inventario listo. Los dispositivos aparecerán cuando el flag esté activo.',
    fallbackName: 'Dispositivo',
    seenAt: 'Visto {date}',
  },
  sessions: {
    title: 'Sesiones abiertas',
    emptyPrefix: 'Gestión remota de sesiones lista (flag',
    emptySuffix: ').',
    unknownIp: 'IP desconocida',
    terminate: 'Terminar',
  },
  history: {
    title: 'Historial de autenticaciones y cambios',
    empty:
      'Aún sin eventos. Inicios de sesión, recuperaciones y cambios sensibles aparecerán aquí — con notificación cuando esté marcado.',
    notifySuffix: ' · notificar',
  },
  emailChange: {
    title: 'Cambiar email',
    hint: 'Confirmación doble (código en el email actual y el nuevo). En beta los códigos pueden aparecer aquí (beta_inline).',
    inactiveHint:
      'Preparado, no activado (D5). El email de la cuenta no se cambia en esta prueba. La identidad sigue siendo el usuario, no la dirección.',
    newEmailLabel: 'Nuevo email',
    request: 'Solicitar cambio',
    oldCodeLabel: 'Código del email actual',
    newCodeLabel: 'Código del nuevo email',
    confirm: 'Confirmar cambio',
    betaCodesHint: 'Códigos beta — actual: {old} · nuevo: {new}',
    requested: 'Solicitud creada. Introduzca los dos códigos abajo.',
    completed: 'Email actualizado con éxito.',
  },
  actions: {
    sandboxHint: 'Sandbox: use el código {code}',
    codeSent: 'Código enviado. Introduzca los 6 dígitos abajo.',
    phoneVerified: 'Teléfono verificado con éxito.',
    sessionRevoked: 'Sesión marcada como terminada.',
  },
  scoreLabels: {
    excellent: 'Excelente',
    high: 'Bueno',
    medium: 'Moderado',
    low: 'A reforzar',
  },
  events: {
    otp_issued: 'Código OTP emitido',
    otp_verified: 'Código OTP validado',
    session_revoked: 'Sesión terminada remotamente',
    login_new: 'Nuevo inicio de sesión',
    device_new: 'Nuevo dispositivo',
    password_changed: 'Contraseña cambiada',
    email_changed: 'Email cambiado',
    phone_changed: 'Teléfono cambiado',
    document_updated: 'Documento actualizado',
    banking_added: 'Cuenta bancaria añadida',
    recovery_started: 'Recuperación de cuenta iniciada',
    permissions_changed: 'Permisos modificados',
  },
  client: {
    authUnavailable: 'La autenticación no está disponible en este entorno.',
    loadError: 'No fue posible cargar el Centro de Seguridad.',
    networkErrorLoad: 'Error de red al cargar la seguridad.',
    invalidPhone: 'Indique un número de teléfono válido (ej.: +2449XXXXXXXX).',
    otpSendError: 'No fue posible enviar el código.',
    otpIssueError: 'No fue posible emitir el código OTP.',
    networkErrorOtpIssue: 'Error de red al emitir el OTP.',
    otpLengthError: 'Introduzca el código de 6 dígitos.',
    otpInvalidGeneric: 'Código inválido.',
    otpErrors: {
      invalid_code: 'Código incorrecto. Inténtelo de nuevo.',
      expired: 'El código expiró. Solicite uno nuevo.',
      already_used: 'Este código ya fue utilizado.',
      too_many_attempts: 'Demasiados intentos. Solicite un nuevo código.',
      challenge_not_found: 'Desafío no encontrado. Solicite un nuevo código.',
      forbidden: 'No tiene permiso para validar este código.',
    },
    otpValidateFallback: 'No fue posible validar el código.',
    networkErrorOtpValidate: 'Error de red al validar el OTP.',
    revokeError: 'No fue posible terminar la sesión.',
    revokeNotFound: 'Sesión no encontrada o ya terminada.',
    networkErrorGeneric: 'Error de red.',
  },
};
