import type { SegurancaCopy } from './pt';

/** Centre de Sécurité — copy fr. */
export const segurancaCopyFr: SegurancaCopy = {
  eyebrow: 'Identity & Security',
  title: 'Centre de Sécurité',
  subtitle: 'Confirmations, sessions, appareils et niveau de sécurité de votre compte Kuteka.',
  verifiedBadge: 'Vérifié',
  pendingBadge: 'En attente',
  kyc: {
    complete: 'KYC complet',
    level: 'KYC niveau {n}',
    initial: 'KYC démarré',
    notStarted: 'KYC à démarrer',
  },
  securityLevel: 'Niveau de sécurité',
  emailLabel: 'E-mail',
  phoneLabel: 'Téléphone',
  kycStatus: 'État KYC',
  openTrustCenter: 'Ouvrir le Centre de Confiance',
  lastLogin: 'Dernière connexion',
  noRecordYet: 'Pas encore d’historique',
  mfaLabel: '2FA',
  mfaActive: 'Actif',
  mfaPreparing: 'Prêt — activation à venir',
  infraReady: 'Infra prête',
  phoneVerifySection: {
    title: 'Vérifier le téléphone (OTP SMS)',
    hint: 'Flux sandbox prêt pour Twilio, MessageBird ou Infobip (Angola).',
    numberLabel: 'Numéro',
    sendCode: 'Envoyer le code',
    otpLabel: 'Code à 6 chiffres',
    confirmPhone: 'Confirmer le téléphone',
  },
  devices: {
    title: 'Appareils actifs',
    empty: 'Inventaire prêt. Les appareils apparaîtront une fois le flag activé.',
    fallbackName: 'Appareil',
    seenAt: 'Vu {date}',
  },
  sessions: {
    title: 'Sessions ouvertes',
    emptyPrefix: 'Gestion des sessions à distance prête (flag',
    emptySuffix: ').',
    unknownIp: 'IP inconnue',
    terminate: 'Terminer',
  },
  history: {
    title: 'Historique des connexions et modifications',
    empty:
      'Pas encore d’événements. Connexions, récupérations et modifications sensibles apparaîtront ici — avec notification si marquées.',
    notifySuffix: ' · notifier',
  },
  emailChange: {
    title: 'Changer l’e-mail',
    hint: 'Confirmation double (code sur l’e-mail actuel et le nouveau). En bêta, les codes peuvent apparaître ici (beta_inline).',
    newEmailLabel: 'Nouvel e-mail',
    request: 'Demander le changement',
    oldCodeLabel: 'Code de l’e-mail actuel',
    newCodeLabel: 'Code du nouvel e-mail',
    confirm: 'Confirmer le changement',
    betaCodesHint: 'Codes bêta — actuel : {old} · nouveau : {new}',
    requested: 'Demande créée. Saisissez les deux codes ci-dessous.',
    completed: 'E-mail mis à jour avec succès.',
  },
  actions: {
    sandboxHint: 'Sandbox : utilisez le code {code}',
    codeSent: 'Code envoyé. Saisissez les 6 chiffres ci-dessous.',
    phoneVerified: 'Téléphone vérifié avec succès.',
    sessionRevoked: 'Session marquée comme terminée.',
  },
  scoreLabels: {
    excellent: 'Excellent',
    high: 'Bon',
    medium: 'Modéré',
    low: 'À renforcer',
  },
  events: {
    otp_issued: 'Code OTP émis',
    otp_verified: 'Code OTP validé',
    session_revoked: 'Session terminée à distance',
    login_new: 'Nouvelle connexion',
    device_new: 'Nouvel appareil',
    password_changed: 'Mot de passe modifié',
    email_changed: 'E-mail modifié',
    phone_changed: 'Téléphone modifié',
    document_updated: 'Document mis à jour',
    banking_added: 'Compte bancaire ajouté',
    recovery_started: 'Récupération de compte démarrée',
    permissions_changed: 'Permissions modifiées',
  },
  client: {
    authUnavailable: 'L’authentification n’est pas disponible dans cet environnement.',
    loadError: 'Impossible de charger le Centre de Sécurité.',
    networkErrorLoad: 'Erreur réseau lors du chargement de la sécurité.',
    invalidPhone: 'Indiquez un numéro de téléphone valide (ex. : +2449XXXXXXXX).',
    otpSendError: 'Impossible d’envoyer le code.',
    otpIssueError: 'Impossible d’émettre le code OTP.',
    networkErrorOtpIssue: 'Erreur réseau lors de l’émission de l’OTP.',
    otpLengthError: 'Saisissez le code à 6 chiffres.',
    otpInvalidGeneric: 'Code invalide.',
    otpErrors: {
      invalid_code: 'Code incorrect. Réessayez.',
      expired: 'Le code a expiré. Demandez-en un nouveau.',
      already_used: 'Ce code a déjà été utilisé.',
      too_many_attempts: 'Trop de tentatives. Demandez un nouveau code.',
      challenge_not_found: 'Défi introuvable. Demandez un nouveau code.',
      forbidden: 'Vous n’avez pas la permission de valider ce code.',
    },
    otpValidateFallback: 'Impossible de valider le code.',
    networkErrorOtpValidate: 'Erreur réseau lors de la validation de l’OTP.',
    revokeError: 'Impossible de terminer la session.',
    revokeNotFound: 'Session introuvable ou déjà terminée.',
    networkErrorGeneric: 'Erreur réseau.',
  },
};
