import type { HabitacaoCopy } from './pt';

export const habitacaoCopyEn: HabitacaoCopy = {
  title: 'Housing',
  subtitle:
    'Explore active inventory with photos, price and location — and register your interest.',
  explore: 'Explore Housing',
  preferencesTitle: 'Your preferences',
  preferencesHint: 'We use these filters as a starting point when exploring.',
  savePreferences: 'Save preferences',
  saving: 'Saving…',
  saved: 'Preferences saved.',
  needClient: 'To use Housing you need the Client role on your account.',
  activateRole: 'Activate Client role',
  loadError: 'We are having trouble showing Housing. Please try again.',
  saveError: 'We could not save the preferences. Please try again.',
  forbidden: 'You do not have permission to explore housing.',
  exploreTitle: 'Explore housing',
  exploreSubtitle: 'Active properties — including Kuteka Beta inventory.',
  emptyTitle: 'No results for this search',
  empty:
    'Adjust filters or search terms. The Kuteka Beta inventory should appear with no filters applied.',
  emptyCta: 'Clear filters',
  backToHub: 'Back to Housing',
  backToExplore: 'Back to exploration',
  detailTitle: 'Housing detail',
  openDetail: 'View details',
  interest: 'Register interest',
  interestBusy: 'Registering…',
  interestDone: 'Interest registered. An Agent may follow up on the request.',
  interestError: 'We could not register the interest. Please try again.',
  goTrust: 'Verify account (Trust)',
  goAgent: 'Agent area',
  search: 'Search',
  searchPlaceholder: 'Title, city, code…',
  applyFilters: 'Apply filters',
  clearFilters: 'Clear',
  pagePrev: 'Previous',
  pageNext: 'Next',
  pageOf: 'Page',
  results: 'results',
  loadingMore: 'Loading more…',
  endOfResults: 'End of results',
  photoAriaTemplate: 'Photo: {title}',
  detail: {
    inactiveHint: 'This listing may no longer be active.',
    prepareContract: 'Prepare contract',
    nextTitle: 'Continue the journey',
    stepAgent: 'Agent follows up',
    stepContract: 'Prepare contract',
    stepTrust: 'Trust verifies',
    stepMore: 'More properties',
    stepExplore: 'Explore inventory',
  },
  mvpNote: 'From interest it moves to Agent and Trust — a continuous flow across the platform.',
  fields: {
    purpose: 'Purpose',
    province: 'Province',
    city: 'City',
    type: 'Type',
    address: 'Address',
    code: 'Code',
    any: 'Any',
    price: 'Price',
    bedrooms: 'Bedrooms',
  },
  types: {
    apartment: 'Apartment',
    house: 'House',
    land: 'Land',
    commercial: 'Commercial',
  },
  purposes: {
    rent: 'Rent',
    sale: 'Sale',
    both: 'Sale and rent',
  },
  hub: {
    eyebrow: 'Client Experience',
    subtitle: 'Preferences, interests, visits and shortcuts for your journey.',
    navLabel: 'Client sections',
    tabs: {
      residencia: 'Residence',
      preferencias: 'Preferences',
      interesses: 'Favorites / Interests',
      visitas: 'Visits',
    },
    visits: {
      title: 'Visits & follow-up',
      description: 'Interest requests and follow-up statuses (visit / proposal).',
    },
    favorites: {
      title: 'Favorites / Interests',
      description: 'Properties you have expressed interest in at Kuteka.',
    },
    loading: 'Loading…',
    emptyInterests:
      'No interests registered yet. Explore the inventory and register interest in properties.',
    exploreNow: 'Explore now',
    propertyFallback: 'Property',
    viewDetail: 'View listing',
  },
};
