import type { HabitacaoCopy } from './pt';

export const habitacaoCopyEs: HabitacaoCopy = {
  title: 'Vivienda',
  subtitle:
    'Explore el inventario activo con fotografías, precio y ubicación — y muestre su interés.',
  explore: 'Explorar Vivienda',
  preferencesTitle: 'Sus preferencias',
  preferencesHint: 'Usamos estos filtros como punto de partida en la exploración.',
  savePreferences: 'Guardar preferencias',
  saving: 'Guardando…',
  saved: 'Preferencias guardadas.',
  needClient: 'Para usar Vivienda necesita el rol de Cliente en su cuenta.',
  activateRole: 'Activar rol de Cliente',
  loadError: 'Estamos teniendo dificultades para mostrar Vivienda. Inténtelo de nuevo.',
  saveError: 'No pudimos guardar las preferencias. Inténtelo de nuevo.',
  forbidden: 'No tiene permiso para explorar vivienda.',
  exploreTitle: 'Explorar vivienda',
  exploreSubtitle: 'Patrimonios activos — incluido el inventario Beta Kuteka.',
  emptyTitle: 'Sin resultados para esta búsqueda',
  empty:
    'Ajuste los filtros o la búsqueda. El inventario Beta Kuteka debería aparecer sin filtros.',
  emptyCta: 'Borrar filtros',
  backToHub: 'Volver a Vivienda',
  backToExplore: 'Volver a la exploración',
  detailTitle: 'Detalle de la vivienda',
  openDetail: 'Ver detalles',
  interest: 'Mostrar interés',
  interestBusy: 'Registrando…',
  interestDone: 'Interés registrado. Un Agente puede dar seguimiento a la solicitud.',
  interestError: 'No pudimos registrar el interés. Inténtelo de nuevo.',
  goTrust: 'Verificar cuenta (Confianza)',
  goAgent: 'Área del Agente',
  search: 'Buscar',
  searchPlaceholder: 'Título, ciudad, código…',
  applyFilters: 'Aplicar filtros',
  clearFilters: 'Borrar',
  pagePrev: 'Anterior',
  pageNext: 'Siguiente',
  pageOf: 'Página',
  results: 'resultados',
  loadingMore: 'Cargando más…',
  endOfResults: 'Fin de los resultados',
  photoAriaTemplate: 'Fotografía: {title}',
  detail: {
    inactiveHint: 'Este anuncio puede que ya no esté activo.',
    prepareContract: 'Preparar contrato',
    nextTitle: 'Continuar el recorrido',
    stepAgent: 'El Agente acompaña',
    stepContract: 'Preparar contrato',
    stepTrust: 'Confianza verifica',
    stepMore: 'Más patrimonios',
    stepExplore: 'Explorar inventario',
  },
  mvpNote: 'Del interés se pasa a Agente y Confianza — un flujo continuo en la plataforma.',
  fields: {
    purpose: 'Finalidad',
    province: 'Provincia',
    city: 'Ciudad',
    type: 'Tipo',
    address: 'Dirección',
    code: 'Código',
    any: 'Cualquiera',
    price: 'Precio',
    bedrooms: 'Habitaciones',
  },
  types: {
    apartment: 'Apartamento',
    house: 'Casa',
    land: 'Terreno',
    commercial: 'Comercial',
  },
  purposes: {
    rent: 'Alquiler',
    sale: 'Venta',
    both: 'Venta y alquiler',
  },
  hub: {
    eyebrow: 'Experiencia Cliente',
    subtitle: 'Preferencias, intereses, visitas y atajos de su recorrido.',
    navLabel: 'Secciones cliente',
    tabs: {
      residencia: 'Residencia',
      preferencias: 'Preferencias',
      interesses: 'Favoritos / Intereses',
      visitas: 'Visitas',
    },
    visits: {
      title: 'Visitas y seguimiento',
      description: 'Solicitudes de interés y estados de seguimiento (visita / propuesta).',
    },
    favorites: {
      title: 'Favoritos / Intereses',
      description: 'Inmuebles en los que ha mostrado interés en Kuteka.',
    },
    loading: 'Cargando…',
    emptyInterests:
      'Aún no hay intereses registrados. Explore el inventario y muestre interés en los inmuebles.',
    exploreNow: 'Explorar ahora',
    propertyFallback: 'Patrimonio',
    viewDetail: 'Ver ficha',
  },
};
