import type { HabitacaoCopy } from './pt';

export const habitacaoCopyFr: HabitacaoCopy = {
  title: 'Habitat',
  subtitle:
    'Explorez l’inventaire actif avec photos, prix et localisation — et manifestez votre intérêt.',
  explore: 'Explorer l’habitat',
  preferencesTitle: 'Vos préférences',
  preferencesHint: 'Nous utilisons ces filtres comme point de départ pour l’exploration.',
  savePreferences: 'Enregistrer les préférences',
  saving: 'Enregistrement…',
  saved: 'Préférences enregistrées.',
  needClient: 'Pour utiliser Habitat, vous devez avoir le rôle Client sur votre compte.',
  activateRole: 'Activer le rôle Client',
  loadError: 'Nous avons du mal à afficher Habitat. Veuillez réessayer.',
  saveError: 'Nous n’avons pas pu enregistrer les préférences. Veuillez réessayer.',
  forbidden: 'Vous n’avez pas la permission d’explorer l’habitat.',
  exploreTitle: 'Explorer l’habitat',
  exploreSubtitle: 'Patrimoines actifs — y compris l’inventaire de démonstration Kuteka.',
  emptyTitle: 'Aucun résultat pour cette recherche',
  empty:
    'Ajustez les filtres ou la recherche. L’inventaire de démonstration devrait apparaître sans filtre.',
  emptyCta: 'Effacer les filtres',
  backToHub: 'Retour à Habitat',
  backToExplore: 'Retour à l’exploration',
  detailTitle: 'Détail du logement',
  openDetail: 'Voir les détails',
  interest: 'Manifester un intérêt',
  interestBusy: 'Enregistrement…',
  interestDone: 'Intérêt enregistré. Un Agent peut suivre la demande.',
  interestError: 'Nous n’avons pas pu enregistrer l’intérêt. Veuillez réessayer.',
  goTrust: 'Vérifier le compte (Confiance)',
  goAgent: 'Espace Agent',
  search: 'Rechercher',
  searchPlaceholder: 'Titre, ville, code…',
  applyFilters: 'Appliquer les filtres',
  clearFilters: 'Effacer',
  pagePrev: 'Précédent',
  pageNext: 'Suivant',
  pageOf: 'Page',
  results: 'résultats',
  mvpNote: 'De l’intérêt, on passe à Agent puis à Confiance — un flux continu sur la plateforme.',
  fields: {
    purpose: 'Finalité',
    province: 'Province',
    city: 'Ville',
    type: 'Type',
    address: 'Adresse',
    code: 'Code',
    any: 'Indifférent',
    price: 'Prix',
    bedrooms: 'Chambres',
  },
  types: {
    apartment: 'Appartement',
    house: 'Villa',
    land: 'Terrain',
    commercial: 'Commercial',
  },
  purposes: {
    rent: 'Location',
    sale: 'Vente',
    both: 'Vente et location',
  },
  hub: {
    eyebrow: 'Expérience Client',
    subtitle: 'Préférences, intérêts, visites et raccourcis de votre parcours.',
    navLabel: 'Sections client',
    tabs: {
      residencia: 'Résidence',
      preferencias: 'Préférences',
      interesses: 'Favoris / Intérêts',
      visitas: 'Visites',
    },
    visits: {
      title: 'Visites & suivi',
      description: 'Demandes d’intérêt et statuts de suivi (visite / proposition).',
    },
    favorites: {
      title: 'Favoris / Intérêts',
      description: 'Biens pour lesquels vous avez manifesté un intérêt chez Kuteka.',
    },
    loading: 'Chargement…',
    emptyInterests:
      'Aucun intérêt enregistré pour le moment. Explorez l’inventaire et manifestez votre intérêt pour des biens.',
    exploreNow: 'Explorer maintenant',
    propertyFallback: 'Patrimoine',
    viewDetail: 'Voir la fiche',
  },
};
