export const habitacaoCopyPt = {
  title: 'Habitação',
  subtitle:
    'Explore inventário activo com fotografia, preço e localização — e demonstre interesse.',
  explore: 'Explorar Habitação',
  preferencesTitle: 'As suas preferências',
  preferencesHint: 'Usamos estes filtros como ponto de partida na exploração.',
  savePreferences: 'Guardar preferências',
  saving: 'A guardar…',
  saved: 'Preferências guardadas.',
  needClient: 'Para usar Habitação precisa do papel Cliente na sua conta.',
  activateRole: 'Activar papel Cliente',
  loadError: 'Estamos a ter dificuldade em mostrar a Habitação. Tente novamente.',
  saveError: 'Não conseguimos guardar as preferências. Tente novamente.',
  forbidden: 'Não tem permissão para explorar habitação.',
  exploreTitle: 'Explorar habitação',
  exploreSubtitle: 'Patrimónios activos — incluindo inventário de demonstração Kuteka.',
  emptyTitle: 'Sem resultados nesta exploração',
  empty: 'Ajuste filtros ou pesquisa. O inventário de demonstração deve aparecer sem filtros.',
  emptyCta: 'Limpar filtros',
  backToHub: 'Voltar à Habitação',
  backToExplore: 'Voltar à exploração',
  detailTitle: 'Detalhe da habitação',
  openDetail: 'Ver detalhes',
  interest: 'Demonstrar interesse',
  interestBusy: 'A registar…',
  interestDone: 'Interesse registado. Um Agente pode acompanhar o pedido.',
  interestError: 'Não conseguimos registar o interesse. Tente novamente.',
  goTrust: 'Verificar conta (Confiança)',
  goAgent: 'Área do Agente',
  search: 'Pesquisar',
  searchPlaceholder: 'Título, cidade, código…',
  applyFilters: 'Aplicar filtros',
  clearFilters: 'Limpar',
  pagePrev: 'Anterior',
  pageNext: 'Seguinte',
  pageOf: 'Página',
  results: 'resultados',
  mvpNote: 'Do interesse segue para Agente e Confiança — fluxo contínuo da plataforma.',
  fields: {
    purpose: 'Finalidade',
    province: 'Província',
    city: 'Cidade',
    type: 'Tipo',
    address: 'Morada',
    code: 'Código',
    any: 'Qualquer',
    price: 'Preço',
    bedrooms: 'Quartos',
  },
  types: {
    apartment: 'Apartamento',
    house: 'Moradia',
    land: 'Terreno',
    commercial: 'Comercial',
  },
  purposes: {
    rent: 'Arrendamento',
    sale: 'Venda',
    both: 'Venda e arrendamento',
  },
  hub: {
    eyebrow: 'Experiência Cliente',
    subtitle: 'Preferências, interesses, visitas e atalhos da sua jornada.',
    navLabel: 'Secções cliente',
    tabs: {
      residencia: 'Residência',
      preferencias: 'Preferências',
      interesses: 'Favoritos / Interesses',
      visitas: 'Visitas',
    },
    visits: {
      title: 'Visitas & acompanhamento',
      description: 'Pedidos de interesse e estados de acompanhamento (visita / proposta).',
    },
    favorites: {
      title: 'Favoritos / Interesses',
      description: 'Imóveis em que demonstrou interesse na Kuteka.',
    },
    loading: 'A carregar…',
    emptyInterests:
      'Ainda não há interesses registados. Explore o inventário e demonstre interesse nos imóveis.',
    exploreNow: 'Explorar agora',
    propertyFallback: 'Património',
    viewDetail: 'Ver ficha',
  },
} as const;

type DeepStringify<T> = {
  [K in keyof T]: T[K] extends string ? string : DeepStringify<T[K]>;
};

export type HabitacaoCopy = DeepStringify<typeof habitacaoCopyPt>;
