import type { ShellCopy } from './pt';

export const shellCopyEn: ShellCopy = {
  areaTitle: 'Kuteka Platform',
  navAria: 'Platform navigation',
  openMenu: 'Open menu',
  closeMenu: 'Close menu',
  soon: 'Soon',
  notificationsTitle: 'Notifications',
  notificationsEmpty: 'No new notifications right now.',
  notificationsMarkRead: 'Mark as read',
  notificationsViewAll: 'View all',
  language: 'Language',
  languageHint: 'Changes the whole interface',
  userMenuAria: 'Account menu',
  switchRole: 'Switch role',
  switchRoleHint: 'Updates menus, dashboard and workflows immediately',
  activeExperience: 'Active experience',
  accountLabel: 'Account',
  changePhoto: 'Change photo',
  groups: {
    geral: 'General',
    cliente: 'Client',
    parceiro: 'Property Partner',
    agente: 'Agent',
    admin: 'Administration',
  },
  userMenu: {
    profile: 'Profile',
    profileHint: 'My personal details',
    roles: 'My roles',
    rolesHint: 'Activate or manage account roles',
    patrimonios: 'My properties',
    patrimoniosHint: 'Listings and property management',
    contracts: 'Contracts',
    contractsHint: 'Drafts and formalisations',
    documents: 'Documents',
    documentsHint: 'Trust and verification',
    notifications: 'Notifications',
    notificationsHint: 'Alerts for your active role',
    messages: 'Messages',
    messagesHint: 'Conversations with Kuteka',
    language: 'Language',
    languageHint: 'Português, English, Français, Español',
    settings: 'Settings',
    settingsHint: 'Language, currency, theme and privacy',
    privacy: 'Privacy',
    privacyHint: 'Data and consents',
    help: 'Help Centre',
    helpHint: 'Manual, FAQ and tutorials',
    contact: 'Contact Kuteka',
    contactHint: 'WhatsApp, phone, email and chat',
    logout: 'Sign out',
  },
  settingsPage: {
    title: 'Settings',
    subtitle: 'Account preferences and Kuteka experience.',
    language: 'Language',
    currency: 'Currency',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    notifications: 'Notifications',
    notificationsHint: 'Receive alerts for the active role',
    privacy: 'Privacy',
    privacyHint: 'Review the privacy policy',
    security: 'Security',
    password: 'Password',
    passwordHint: 'Change or recover your password',
    sessions: 'Active sessions',
    sessionsHint: 'Sign out of this device whenever you want',
    saveLocale: 'Language saved to your account preferences',
  },
  helpPage: {
    title: 'Help Centre',
    subtitle: 'Guides to publish, buy, rent and operate on Kuteka.',
    manual: 'User manual',
    faq: 'FAQ',
    videos: 'Videos',
    tutorials: 'Tutorials',
    howPublish: 'How to publish',
    howBuy: 'How to buy',
    howRent: 'How to rent',
    contactCta: 'Still need help? Contact us',
  },
  contactPage: {
    title: 'Contact Kuteka',
    subtitle: 'Choose the most convenient channel for your team.',
    whatsapp: 'WhatsApp',
    phone: 'Phone',
    email: 'Email',
    chat: 'Chat',
    helpCenter: 'Help Centre',
    hours: 'Support on weekdays, 09:00–18:00 (WAT)',
  },
  items: {
    home: 'Home',
    explorar: 'Explore Housing',
    residencia: 'Residence',
    favoritos: 'Favourites / Interests',
    visitas: 'Visits',
    futuro: 'Future availability',
    propostas: 'Proposals',
    patrimonios: 'Properties',
    ativar: 'Activate Property',
    habitacao: 'Housing',
    agente: 'Agent',
    confianca: 'Trust',
    contratos: 'Contracts',
    relatorios: 'Reports',
    conta: 'Account',
    admin: 'Administration',
    super: 'Super Admin',
    financeiro: 'Finance',
    mudanca: 'Smart Move',
    encontrar: 'Find a Home',
    servicos: 'Providers',
    planos: 'Partner Plans',
  },
  routeBlocked: {
    title: 'Area unavailable in this role',
    body: 'The active experience does not include this flow. Switch role in the account menu or choose an authorised shortcut.',
    switch: 'Switch role',
    home: 'Go to home',
  },
};
