import type { ShellCopy } from './pt';

export const shellCopyEn: ShellCopy = {
  areaTitle: 'Kuteka Platform',
  navAria: 'Platform navigation',
  openMenu: 'Open menu',
  closeMenu: 'Close menu',
  soon: 'Soon',
  notificationsTitle: 'Notifications',
  notificationsEmpty: 'No new notifications right now.',
  notificationsMarkRead: 'Mark as read',
  notificationsViewAll: 'View all',
  language: 'Language',
  languageHint: 'Changes the whole interface',
  userMenuAria: 'Account menu',
  switchRole: 'Switch role',
  switchRoleHint: 'Updates menus, dashboard and workflows immediately',
  activeExperience: 'Active experience',
  accountLabel: 'Account',
  changePhoto: 'Change photo',
  groups: {
    geral: 'General',
    cliente: 'Client',
    parceiro: 'Property Partner',
    agente: 'Agent',
    admin: 'Administration',
  },
  userMenu: {
    profile: 'Profile',
    profileHint: 'My personal details',
    centroConfiancaHint: 'Account status, UTS and next steps',
    centroSegurancaHint: 'Email, phone, sessions and security level',
    roleCountSingular: 'role',
    roleCountPlural: 'roles',
    roles: 'My roles',
    rolesHint: 'Activate or manage account roles',
    patrimonios: 'My properties',
    patrimoniosHint: 'Listings and property management',
    contracts: 'Contracts',
    contractsHint: 'Drafts and formalisations',
    documents: 'Documents',
    documentsHint: 'Trust and verification',
    notifications: 'Notifications',
    notificationsHint: 'Alerts for your active role',
    messages: 'Messages',
    messagesHint: 'Conversations with Kuteka',
    language: 'Language',
    languageHint: 'Português, English, Français, Español',
    settings: 'Settings',
    settingsHint: 'Language, currency, theme and privacy',
    privacy: 'Privacy',
    privacyHint: 'Data and consents',
    help: 'Help Centre',
    helpHint: 'Manual, FAQ and tutorials',
    contact: 'Contact Kuteka',
    contactHint: 'WhatsApp, phone, email and chat',
    logout: 'Sign out',
  },
  settingsPage: {
    title: 'Settings',
    subtitle: 'Account preferences and Kuteka experience.',
    language: 'Language',
    currency: 'Currency',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    notifications: 'Notifications',
    notificationsHint: 'Receive alerts for the active role',
    privacy: 'Privacy',
    privacyHint: 'Review the privacy policy',
    security: 'Security',
    password: 'Password',
    passwordHint: 'Change or recover your password',
    sessions: 'Active sessions',
    sessionsHint: 'Sign out of this device whenever you want',
    saveLocale: 'Language saved to your account preferences',
  },
  helpPage: {
    title: 'Help Centre',
    subtitle: 'Guides to publish, buy, rent and operate on Kuteka.',
    manual: 'User manual',
    faq: 'FAQ',
    videos: 'Videos',
    tutorials: 'Tutorials',
    howPublish: 'How to publish',
    howBuy: 'How to buy',
    howRent: 'How to rent',
    contactCta: 'Still need help? Contact us',
  },
  contactPage: {
    title: 'Contact Kuteka',
    subtitle: 'Choose the most convenient channel for your team.',
    whatsapp: 'WhatsApp',
    phone: 'Phone',
    email: 'Email',
    chat: 'Chat',
    helpCenter: 'Help Centre',
    hours: 'Support on weekdays, 09:00–18:00 (WAT)',
  },
  items: {
    home: 'Home',
    explorar: 'Explore Housing',
    residencia: 'Residence',
    favoritos: 'Favourites / Interests',
    visitas: 'Visits',
    futuro: 'Future availability',
    propostas: 'Proposals',
    patrimonios: 'Properties',
    ativar: 'Activate Property',
    habitacao: 'Housing',
    agente: 'Agent',
    confianca: 'Trust',
    centroConfianca: 'Trust Center',
    centroSeguranca: 'Security Center',
    contratos: 'Contracts',
    relatorios: 'Reports',
    conta: 'Account',
    admin: 'Administration',
    super: 'Super Admin',
    financeiro: 'Finance',
    mudanca: 'Smart Move',
    encontrar: 'Find a Home',
    concierge: 'Concierge',
    garantia: 'Kuteka Guarantee',
    assistencia: '24h Assistance',
    servicos: 'Providers',
    planos: 'Partner Plans',
  },
  routeBlocked: {
    title: 'Area unavailable in this role',
    body: 'The active experience does not include this flow. Switch role in the account menu or choose an authorised shortcut.',
    switch: 'Switch role',
    home: 'Go to home',
  },
  forbidden: {
    activateRole: 'Activate role',
    goDashboard: 'Go to dashboard',
    verifyAccount: 'Verify account',
    continueElsewhere: 'Continue another way',
  },
  helpExtra: {
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    securityCenter: 'Security Center',
    downloadManualPdf: 'Download Manual (PDF)',
    downloadManualWord: 'Download Manual (Word)',
    videosPending:
      'Video tutorials will be published progressively. Until then, use the written tutorials in this manual and the shortcuts above.',
  },
  brandTagline: 'Property management',
  loadingMore: 'Loading more…',
  loadingContent: 'Loading content…',
  securityCenterHint: 'Email, phone, sessions, devices and account security level.',
  feedEndTitle: 'You reached the end of the current inventory',
  feedEndBody: 'New properties appear here as soon as they are published.',
  feed: {
    activateRoleTitle: 'Activate the Client role to see the feed',
    activateRoleBody:
      'The continuous feed shows properties, highlights and recommendations as soon as you have access to Housing.',
    activateRoleCta: 'Activate role',
    warmingTitle: 'Feed warming up',
    warmingBody: 'No active listings yet. Publish your first property or explore Housing.',
    exploreWithFilters: 'Explore with filters',
    markers: {
      new: { title: 'New properties', hint: 'Just joined the platform.' },
      featured: {
        title: 'Featured',
        hint: 'Selection with premium presence.',
        badge: 'Featured',
      },
      nearby: { title: 'Near you', hint: 'Relevant inventory to explore now.' },
      recommend: {
        title: 'Recommendations',
        hint: 'Suggestions based on active inventory.',
      },
      trends: { title: 'Trends', hint: 'What the community is viewing.' },
      premium: {
        title: 'Premium properties',
        hint: 'High-end properties.',
        badge: 'Premium',
      },
      contracts: {
        title: 'Contract activity',
        hint: 'Formalization progressing on the platform.',
        badge: 'Contracts',
      },
      news: { title: 'News', hint: 'Recent marketplace updates.' },
      smart: {
        title: 'Smart recommendations',
        hint: 'Getting ready for the KAI engine.',
        badge: 'KAI prep',
      },
      more: { title: 'More properties', hint: 'Keep exploring — the feed doesn’t end here.' },
      sponsored: {
        title: 'Sponsored listings',
        hint: 'Campaigns and promoted inventory.',
        badge: 'Sponsored',
      },
    },
    linkCard: {
      title: 'Explore housing with filters',
      hint: 'Fine-tune location, purpose and typology without leaving the platform.',
      cta: 'Open explore',
    },
  },
  institutional: {
    badge: 'Kuteka · v1.0 Beta',
    backToLanding: 'Back to Landing',
    contactKuteka: 'Contact Kuteka',
  },
  errors: {
    routeErrorTitle: 'Error',
    routeErrorBody: 'We are having trouble showing this page. Please try again.',
    retry: 'Try again',
    globalErrorTitle: 'Something went wrong',
    globalErrorBody: 'An unexpected error occurred. You can try again.',
    notFoundTitle: 'Page not found',
    notFoundBody: 'The requested resource does not exist.',
    goHome: 'Go to the foundation',
  },
};
