import type { ShellCopy } from './pt';

export const shellCopyEs: ShellCopy = {
  areaTitle: 'Plataforma Kuteka',
  navAria: 'Navegación de la plataforma',
  openMenu: 'Abrir menú',
  closeMenu: 'Cerrar menú',
  soon: 'Pronto',
  notificationsTitle: 'Notificaciones',
  notificationsEmpty: 'No hay notificaciones nuevas por ahora.',
  notificationsMarkRead: 'Marcar como leídas',
  notificationsViewAll: 'Ver todas',
  language: 'Idioma',
  languageHint: 'Cambia toda la interfaz',
  userMenuAria: 'Menú de la cuenta',
  switchRole: 'Cambiar de rol',
  switchRoleHint: 'Actualiza menús, panel y flujos de inmediato',
  activeExperience: 'Experiencia activa',
  accountLabel: 'Cuenta',
  changePhoto: 'Cambiar fotografía',
  groups: {
    geral: 'General',
    cliente: 'Cliente',
    parceiro: 'Socio Patrimonial',
    agente: 'Agente',
    admin: 'Administración',
  },
  userMenu: {
    profile: 'Perfil',
    profileHint: 'Mis datos personales',
    roles: 'Mis roles',
    rolesHint: 'Activar o gestionar roles de la cuenta',
    patrimonios: 'Mis patrimonios',
    patrimoniosHint: 'Anuncios y gestión patrimonial',
    contracts: 'Contratos',
    contractsHint: 'Minutas y formalizaciones',
    documents: 'Documentos',
    documentsHint: 'Confianza y verificación',
    notifications: 'Notificaciones',
    notificationsHint: 'Alertas de su rol activo',
    messages: 'Mensajes',
    messagesHint: 'Conversaciones con Kuteka',
    language: 'Idioma',
    languageHint: 'Português, English, Français, Español',
    settings: 'Ajustes',
    settingsHint: 'Idioma, moneda, tema y privacidad',
    privacy: 'Privacidad',
    privacyHint: 'Datos y consentimientos',
    help: 'Centro de Ayuda',
    helpHint: 'Manual, FAQ y tutoriales',
    contact: 'Contactar a Kuteka',
    contactHint: 'WhatsApp, teléfono, email y chat',
    logout: 'Cerrar sesión',
  },
  settingsPage: {
    title: 'Ajustes',
    subtitle: 'Preferencias de la cuenta y de la experiencia Kuteka.',
    language: 'Idioma',
    currency: 'Moneda',
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Oscuro',
    themeSystem: 'Sistema',
    notifications: 'Notificaciones',
    notificationsHint: 'Recibir alertas del rol activo',
    privacy: 'Privacidad',
    privacyHint: 'Consulte la política de privacidad',
    security: 'Seguridad',
    password: 'Contraseña',
    passwordHint: 'Cambiar o recuperar la contraseña',
    sessions: 'Sesiones activas',
    sessionsHint: 'Cierre sesión en este dispositivo cuando quiera',
    saveLocale: 'Idioma guardado en las preferencias de la cuenta',
  },
  helpPage: {
    title: 'Centro de Ayuda',
    subtitle: 'Guías para publicar, comprar, arrendar y operar en Kuteka.',
    manual: 'Manual del usuario',
    faq: 'Preguntas frecuentes',
    videos: 'Vídeos',
    tutorials: 'Tutoriales',
    howPublish: 'Cómo publicar',
    howBuy: 'Cómo comprar',
    howRent: 'Cómo arrendar',
    contactCta: '¿Aún necesita ayuda? Contáctenos',
  },
  contactPage: {
    title: 'Contactar a Kuteka',
    subtitle: 'Elija el canal más conveniente para su equipo.',
    whatsapp: 'WhatsApp',
    phone: 'Teléfono',
    email: 'Email',
    chat: 'Chat',
    helpCenter: 'Centro de Ayuda',
    hours: 'Atención en días laborables, 09:00–18:00 (WAT)',
  },
  items: {
    home: 'Inicio',
    explorar: 'Explorar Vivienda',
    residencia: 'Residencia',
    favoritos: 'Favoritos / Intereses',
    visitas: 'Visitas',
    futuro: 'Disponibilidad futura',
    propostas: 'Propuestas',
    patrimonios: 'Patrimonios',
    ativar: 'Activar Patrimonio',
    habitacao: 'Vivienda',
    agente: 'Agente',
    confianca: 'Confianza',
    contratos: 'Contratos',
    relatorios: 'Informes',
    conta: 'Cuenta',
    admin: 'Administración',
  },
  routeBlocked: {
    title: 'Área no disponible en este rol',
    body: 'La experiencia activa no incluye este flujo. Cambie de rol en el menú de la cuenta o elija un acceso autorizado.',
    switch: 'Cambiar de rol',
    home: 'Ir al inicio',
  },
};
