import type { ShellCopy } from './pt';

export const shellCopyEs: ShellCopy = {
  areaTitle: 'Plataforma Kuteka',
  navAria: 'Navegación de la plataforma',
  openMenu: 'Abrir menú',
  closeMenu: 'Cerrar menú',
  soon: 'Pronto',
  notificationsTitle: 'Notificaciones',
  notificationsEmpty: 'No hay notificaciones nuevas por ahora.',
  notificationsMarkRead: 'Marcar como leídas',
  notificationsViewAll: 'Ver todas',
  language: 'Idioma',
  languageHint: 'Cambia toda la interfaz',
  userMenuAria: 'Menú de la cuenta',
  switchRole: 'Cambiar de rol',
  switchRoleHint: 'Actualiza menús, panel y flujos de inmediato',
  activeExperience: 'Experiencia activa',
  accountLabel: 'Cuenta',
  changePhoto: 'Cambiar fotografía',
  groups: {
    geral: 'General',
    cliente: 'Cliente',
    parceiro: 'Socio Patrimonial',
    agente: 'Agente',
    admin: 'Administración',
  },
  userMenu: {
    profile: 'Perfil',
    profileHint: 'Mis datos personales',
    centroConfiancaHint: 'Estado de la cuenta, UTS y próximos pasos',
    centroSegurancaHint: 'Email, teléfono, sesiones y nivel de seguridad',
    roleCountSingular: 'rol',
    roleCountPlural: 'roles',
    roles: 'Mis roles',
    rolesHint: 'Activar o gestionar roles de la cuenta',
    patrimonios: 'Mis patrimonios',
    patrimoniosHint: 'Anuncios y gestión patrimonial',
    contracts: 'Contratos',
    contractsHint: 'Minutas y formalizaciones',
    documents: 'Documentos',
    documentsHint: 'Confianza y verificación',
    notifications: 'Notificaciones',
    notificationsHint: 'Alertas de su rol activo',
    messages: 'Mensajes',
    messagesHint: 'Conversaciones con Kuteka',
    language: 'Idioma',
    languageHint: 'Português, English, Français, Español',
    settings: 'Ajustes',
    settingsHint: 'Idioma, moneda, tema y privacidad',
    privacy: 'Privacidad',
    privacyHint: 'Datos y consentimientos',
    help: 'Centro de Ayuda',
    helpHint: 'Manual, FAQ y tutoriales',
    contact: 'Contactar a Kuteka',
    contactHint: 'WhatsApp, teléfono, email y chat',
    logout: 'Cerrar sesión',
  },
  settingsPage: {
    title: 'Ajustes',
    subtitle: 'Preferencias de la cuenta y de la experiencia Kuteka.',
    language: 'Idioma',
    currency: 'Moneda',
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Oscuro',
    themeSystem: 'Sistema',
    notifications: 'Notificaciones',
    notificationsHint: 'Recibir alertas del rol activo',
    privacy: 'Privacidad',
    privacyHint: 'Consulte la política de privacidad',
    security: 'Seguridad',
    password: 'Contraseña',
    passwordHint: 'Cambiar o recuperar la contraseña',
    sessions: 'Sesiones activas',
    sessionsHint: 'Cierre sesión en este dispositivo cuando quiera',
    saveLocale: 'Idioma guardado en las preferencias de la cuenta',
  },
  helpPage: {
    title: 'Centro de Ayuda',
    subtitle: 'Guías para publicar, comprar, arrendar y operar en Kuteka.',
    manual: 'Manual del usuario',
    faq: 'Preguntas frecuentes',
    videos: 'Vídeos',
    tutorials: 'Tutoriales',
    howPublish: 'Cómo publicar',
    howBuy: 'Cómo comprar',
    howRent: 'Cómo arrendar',
    contactCta: '¿Aún necesita ayuda? Contáctenos',
  },
  contactPage: {
    title: 'Contactar a Kuteka',
    subtitle: 'Elija el canal más conveniente para su equipo.',
    whatsapp: 'WhatsApp',
    phone: 'Teléfono',
    email: 'Email',
    chat: 'Chat',
    helpCenter: 'Centro de Ayuda',
    hours: 'Atención en días laborables, 09:00–18:00 (WAT)',
  },
  items: {
    home: 'Inicio',
    explorar: 'Explorar Vivienda',
    residencia: 'Residencia',
    favoritos: 'Favoritos / Intereses',
    visitas: 'Visitas',
    futuro: 'Disponibilidad futura',
    propostas: 'Propuestas',
    patrimonios: 'Patrimonios',
    ativar: 'Activar Patrimonio',
    habitacao: 'Vivienda',
    agente: 'Agente',
    confianca: 'Confianza',
    centroConfianca: 'Centro de Confianza',
    centroSeguranca: 'Centro de Seguridad',
    contratos: 'Contratos',
    relatorios: 'Informes',
    conta: 'Cuenta',
    admin: 'Administración',
    super: 'Super Admin',
    financeiro: 'Finanzas',
    mudanca: 'Mudanza Inteligente',
    encontrar: 'Encontrar Casa',
    concierge: 'Conserjería',
    garantia: 'Garantía Kuteka',
    assistencia: 'Asistencia 24h',
    servicos: 'Prestadores',
    planos: 'Planes Socio',
  },
  routeBlocked: {
    title: 'Área no disponible en este rol',
    body: 'La experiencia activa no incluye este flujo. Cambie de rol en el menú de la cuenta o elija un acceso autorizado.',
    switch: 'Cambiar de rol',
    home: 'Ir al inicio',
  },
  forbidden: {
    activateRole: 'Activar rol',
    goDashboard: 'Ir al panel',
    verifyAccount: 'Verificar cuenta',
    continueElsewhere: 'Continuar por otro camino',
  },
  helpExtra: {
    terms: 'Términos de Uso',
    privacy: 'Política de Privacidad',
    securityCenter: 'Centro de Seguridad',
    downloadManualPdf: 'Descargar Manual (PDF)',
    downloadManualWord: 'Descargar Manual (Word)',
    videosPending:
      'Los tutoriales en vídeo se publicarán de forma progresiva. Mientras tanto, use los tutoriales escritos de este manual y los atajos de arriba.',
  },
  brandTagline: 'Gestión patrimonial',
  loadingMore: 'Cargando más…',
  loadingContent: 'Cargando contenido…',
  securityCenterHint: 'Email, teléfono, sesiones, dispositivos y nivel de seguridad de la cuenta.',
  feedEndTitle: 'Llegó al final del inventario actual',
  feedEndBody: 'Los nuevos patrimonios aparecen aquí en cuanto se publiquen.',
  feed: {
    activateRoleTitle: 'Active el papel Cliente para ver el feed',
    activateRoleBody:
      'El feed continuo muestra patrimonios, destacados y recomendaciones en cuanto tenga acceso a Vivienda.',
    activateRoleCta: 'Activar papel',
    warmingTitle: 'Feed calentando',
    warmingBody: 'Aún no hay anuncios activos. Publique su primer patrimonio o explore Vivienda.',
    exploreWithFilters: 'Explorar con filtros',
    markers: {
      new: { title: 'Patrimonios nuevos', hint: 'Acaban de entrar en la plataforma.' },
      featured: {
        title: 'Destacados',
        hint: 'Selección con presencia premium.',
        badge: 'Destacado',
      },
      nearby: { title: 'Cerca de usted', hint: 'Inventario relevante para explorar ahora.' },
      recommend: {
        title: 'Recomendaciones',
        hint: 'Sugerencias basadas en el inventario activo.',
      },
      trends: { title: 'Tendencias', hint: 'Lo que la comunidad está viendo.' },
      premium: {
        title: 'Inmuebles premium',
        hint: 'Patrimonio de gama alta.',
        badge: 'Premium',
      },
      contracts: {
        title: 'Actividad de contratos',
        hint: 'Formalización avanzando en la plataforma.',
        badge: 'Contratos',
      },
      news: { title: 'Novedades', hint: 'Actualizaciones recientes del marketplace.' },
      smart: {
        title: 'Recomendaciones inteligentes',
        hint: 'Preparación para el motor KAI.',
        badge: 'KAI prep',
      },
      more: { title: 'Más patrimonios', hint: 'Siga explorando — el feed no termina aquí.' },
      sponsored: {
        title: 'Anuncios patrocinados',
        hint: 'Campañas e inventario en promoción.',
        badge: 'Patrocinado',
      },
    },
    linkCard: {
      title: 'Explorar vivienda con filtros',
      hint: 'Ajuste ubicación, finalidad y tipología sin salir de la plataforma.',
      cta: 'Abrir explorar',
    },
  },
  institutional: {
    badge: 'Kuteka · v1.0 Beta',
    backToLanding: 'Volver a la Landing',
    contactKuteka: 'Contactar a Kuteka',
  },
  errors: {
    routeErrorTitle: 'Error',
    routeErrorBody: 'Estamos teniendo dificultades para mostrar esta página. Inténtelo de nuevo.',
    retry: 'Intentar de nuevo',
    globalErrorTitle: 'Algo salió mal',
    globalErrorBody: 'Ocurrió un error inesperado. Puede intentarlo de nuevo.',
    notFoundTitle: 'Página no encontrada',
    notFoundBody: 'El recurso solicitado no existe.',
    goHome: 'Ir a la fundación',
  },
};
