import type { ShellCopy } from './pt';

export const shellCopyFr: ShellCopy = {
  areaTitle: 'Plateforme Kuteka',
  navAria: 'Navigation de la plateforme',
  openMenu: 'Ouvrir le menu',
  closeMenu: 'Fermer le menu',
  soon: 'Bientôt',
  notificationsTitle: 'Notifications',
  notificationsEmpty: 'Aucune nouvelle notification pour le moment.',
  notificationsMarkRead: 'Marquer comme lues',
  notificationsViewAll: 'Voir tout',
  language: 'Langue',
  languageHint: 'Modifie toute l’interface',
  userMenuAria: 'Menu du compte',
  switchRole: 'Changer de rôle',
  switchRoleHint: 'Met à jour menus, tableau de bord et flux immédiatement',
  activeExperience: 'Expérience active',
  accountLabel: 'Compte',
  changePhoto: 'Changer la photo',
  groups: {
    geral: 'Général',
    cliente: 'Client',
    parceiro: 'Partenaire Patrimonial',
    agente: 'Agent',
    admin: 'Administration',
  },
  userMenu: {
    profile: 'Profil',
    profileHint: 'Mes informations personnelles',
    roles: 'Mes rôles',
    rolesHint: 'Activer ou gérer les rôles du compte',
    patrimonios: 'Mes patrimoines',
    patrimoniosHint: 'Annonces et gestion patrimoniale',
    contracts: 'Contrats',
    contractsHint: 'Projets et formalisations',
    documents: 'Documents',
    documentsHint: 'Confiance et vérification',
    notifications: 'Notifications',
    notificationsHint: 'Alertes de votre rôle actif',
    messages: 'Messages',
    messagesHint: 'Conversations avec Kuteka',
    language: 'Langue',
    languageHint: 'Português, English, Français, Español',
    settings: 'Paramètres',
    settingsHint: 'Langue, devise, thème et confidentialité',
    privacy: 'Confidentialité',
    privacyHint: 'Données et consentements',
    help: 'Centre d’aide',
    helpHint: 'Manuel, FAQ et tutoriels',
    contact: 'Contacter Kuteka',
    contactHint: 'WhatsApp, téléphone, e-mail et chat',
    logout: 'Se déconnecter',
  },
  settingsPage: {
    title: 'Paramètres',
    subtitle: 'Préférences du compte et de l’expérience Kuteka.',
    language: 'Langue',
    currency: 'Devise',
    theme: 'Thème',
    themeLight: 'Clair',
    themeDark: 'Sombre',
    themeSystem: 'Système',
    notifications: 'Notifications',
    notificationsHint: 'Recevoir les alertes du rôle actif',
    privacy: 'Confidentialité',
    privacyHint: 'Consulter la politique de confidentialité',
    security: 'Sécurité',
    password: 'Mot de passe',
    passwordHint: 'Modifier ou récupérer le mot de passe',
    sessions: 'Sessions actives',
    sessionsHint: 'Déconnectez-vous de cet appareil quand vous voulez',
    saveLocale: 'Langue enregistrée dans les préférences du compte',
  },
  helpPage: {
    title: 'Centre d’aide',
    subtitle: 'Guides pour publier, acheter, louer et opérer sur Kuteka.',
    manual: 'Manuel utilisateur',
    faq: 'FAQ',
    videos: 'Vidéos',
    tutorials: 'Tutoriels',
    howPublish: 'Comment publier',
    howBuy: 'Comment acheter',
    howRent: 'Comment louer',
    contactCta: 'Besoin d’aide ? Contactez-nous',
  },
  contactPage: {
    title: 'Contacter Kuteka',
    subtitle: 'Choisissez le canal le plus pratique pour votre équipe.',
    whatsapp: 'WhatsApp',
    phone: 'Téléphone',
    email: 'E-mail',
    chat: 'Chat',
    helpCenter: 'Centre d’aide',
    hours: 'Assistance en jours ouvrables, 09:00–18:00 (WAT)',
  },
  items: {
    home: 'Accueil',
    explorar: 'Explorer l’habitat',
    residencia: 'Résidence',
    favoritos: 'Favoris / Intérêts',
    visitas: 'Visites',
    futuro: 'Disponibilité future',
    propostas: 'Propositions',
    patrimonios: 'Patrimoines',
    ativar: 'Activer un patrimoine',
    habitacao: 'Habitat',
    agente: 'Agent',
    confianca: 'Confiance',
    contratos: 'Contrats',
    relatorios: 'Rapports',
    conta: 'Compte',
    admin: 'Administration',
  },
  routeBlocked: {
    title: 'Zone indisponible pour ce rôle',
    body: 'L’expérience active n’inclut pas ce flux. Changez de rôle dans le menu du compte ou choisissez un raccourci autorisé.',
    switch: 'Changer de rôle',
    home: 'Aller à l’accueil',
  },
};
