import type { ShellCopy } from './pt';

export const shellCopyFr: ShellCopy = {
  areaTitle: 'Plateforme Kuteka',
  navAria: 'Navigation de la plateforme',
  openMenu: 'Ouvrir le menu',
  closeMenu: 'Fermer le menu',
  soon: 'Bientôt',
  notificationsTitle: 'Notifications',
  notificationsEmpty: 'Aucune nouvelle notification pour le moment.',
  notificationsMarkRead: 'Marquer comme lues',
  notificationsViewAll: 'Voir tout',
  language: 'Langue',
  languageHint: 'Modifie toute l’interface',
  userMenuAria: 'Menu du compte',
  switchRole: 'Changer de rôle',
  switchRoleHint: 'Met à jour menus, tableau de bord et flux immédiatement',
  activeExperience: 'Expérience active',
  accountLabel: 'Compte',
  changePhoto: 'Changer la photo',
  groups: {
    geral: 'Général',
    cliente: 'Client',
    parceiro: 'Partenaire Patrimonial',
    agente: 'Agent',
    prestador: 'Prestataire',
    admin: 'Administration',
  },
  userMenu: {
    profile: 'Profil',
    profileHint: 'Mes informations personnelles',
    centroConfiancaHint: 'État du compte, UTS et prochaines étapes',
    centroSegurancaHint: 'E-mail, téléphone, sessions et niveau de sécurité',
    roleCountSingular: 'rôle',
    roleCountPlural: 'rôles',
    roles: 'Mes rôles',
    rolesHint: 'Activer ou gérer les rôles du compte',
    patrimonios: 'Mes patrimoines',
    patrimoniosHint: 'Annonces et gestion patrimoniale',
    contracts: 'Contrats',
    contractsHint: 'Projets et formalisations',
    documents: 'Documents',
    documentsHint: 'Confiance et vérification',
    notifications: 'Notifications',
    notificationsHint: 'Alertes de votre rôle actif',
    messages: 'Messages',
    messagesHint: 'Conversations avec Clients, Partenaires, Agents et Prestataires',
    language: 'Langue',
    languageHint: 'Português, English, Français, Español',
    settings: 'Paramètres',
    settingsHint: 'Langue, devise, thème et confidentialité',
    privacy: 'Confidentialité',
    privacyHint: 'Données et consentements',
    help: 'Centre d’aide',
    helpHint: 'Manuel, FAQ et tutoriels',
    contact: 'Contacter Kuteka',
    contactHint: 'E-mail et documentation publique',
    logout: 'Se déconnecter',
  },
  settingsPage: {
    title: 'Paramètres',
    subtitle: 'Préférences du compte et de l’expérience Kuteka.',
    language: 'Langue',
    currency: 'Devise',
    theme: 'Thème',
    themeLight: 'Clair',
    themeDark: 'Sombre',
    themeSystem: 'Système',
    notifications: 'Notifications',
    notificationsHint: 'Recevoir les alertes du rôle actif',
    privacy: 'Confidentialité',
    privacyHint: 'Consulter la politique de confidentialité',
    security: 'Sécurité',
    password: 'Mot de passe',
    passwordHint: 'Modifier ou récupérer le mot de passe',
    sessions: 'Sessions actives',
    sessionsHint: 'Déconnectez-vous de cet appareil quand vous voulez',
    saveLocale: 'Langue enregistrée dans les préférences du compte',
  },
  helpPage: {
    title: 'Centre de Documentation Kuteka',
    subtitle: 'Manuel, FAQ, glossaire, nouveautés et état des services — tout au même endroit.',
    manual: 'Manuel utilisateur',
    faq: 'FAQ',
    glossario: 'Glossaire',
    novidades: 'Nouveautés',
    estado: 'État des Services',
    roadmap: 'Feuille de route publique',
    videos: 'Vidéos',
    tutorials: 'Tutoriels',
    howPublish: 'Comment publier',
    howBuy: 'Comment acheter',
    howRent: 'Comment louer',
    contactCta: 'Besoin d’aide ? Contactez-nous',
    publicNotice:
      'Vous consultez le Centre de Documentation public. Connectez-vous pour une expérience complète et personnalisée.',
  },
  contactPage: {
    title: 'Contacter Kuteka',
    subtitle: 'Écrivez-nous par e-mail ou consultez la documentation publique.',
    whatsapp: 'WhatsApp',
    phone: 'Téléphone',
    email: 'E-mail',
    chat: 'Chat',
    helpCenter: 'Documentation',
    hours: 'Assistance en jours ouvrables, 09:00–18:00 (WAT)',
  },
  items: {
    home: 'Accueil',
    explorar: 'Explorer l’habitat',
    residencia: 'Résidence',
    favoritos: 'Favoris / Intérêts',
    visitas: 'Visites',
    futuro: 'Disponibilité future',
    propostas: 'Propositions',
    patrimonios: 'Patrimoines',
    ativar: 'Activer un patrimoine',
    habitacao: 'Habitat',
    agente: 'Agent',
    mensagens: 'Messages',
    confianca: 'Confiance',
    centroConfianca: 'Centre de Confiance',
    centroSeguranca: 'Centre de Sécurité',
    contratos: 'Contrats',
    relatorios: 'Rapports',
    conta: 'Compte',
    admin: 'Administration',
    super: 'Super Admin',
    financeiro: 'Finance',
    mudanca: 'Déménagement intelligent',
    encontrar: 'Trouver un logement',
    concierge: 'Conciergerie',
    garantia: 'Garantie Kuteka',
    assistencia: 'Assistance 24h',
    servicos: 'Prestataires',
    planos: 'Plans Partenaire',
    fundador: 'Founder Center',
    escalacoes: 'Escalades',
  },
  routeBlocked: {
    title: 'Zone indisponible pour ce rôle',
    body: 'L’expérience active n’inclut pas ce flux. Changez de rôle dans le menu du compte ou choisissez un raccourci autorisé.',
    switch: 'Changer de rôle',
    home: 'Aller à l’accueil',
  },
  forbidden: {
    activateRole: 'Activer un rôle',
    goDashboard: 'Aller au tableau de bord',
    verifyAccount: 'Vérifier le compte',
    continueElsewhere: 'Continuer autrement',
  },
  helpExtra: {
    terms: 'Conditions d’utilisation',
    privacy: 'Politique de confidentialité',
    cookies: 'Politique de Cookies',
    securityCenter: 'Centre de Sécurité',
    contactSupport: 'Contacter le support',
    downloadManualPdf: 'Télécharger le Manuel (PDF)',
    downloadManualWord: 'Télécharger le Manuel (Word)',
    videosPending:
      'Les tutoriels vidéo seront publiés progressivement. En attendant, utilisez les tutoriels écrits de ce manuel et les raccourcis ci-dessus.',
  },
  brandTagline: 'Gestion patrimoniale',
  loadingMore: 'Chargement…',
  loadingContent: 'Chargement du contenu…',
  securityCenterHint: 'E-mail, téléphone, sessions, appareils et niveau de sécurité du compte.',
  feedEndTitle: 'Vous avez atteint la fin de l’inventaire actuel',
  feedEndBody: 'Les nouveaux patrimoines apparaissent ici dès qu’ils sont publiés.',
  feed: {
    activateRoleTitle: 'Activez le rôle Client pour voir le fil',
    activateRoleBody:
      'Le fil continu affiche les patrimoines, les mises en avant et les recommandations dès que vous avez accès à Logement.',
    activateRoleCta: 'Activer le rôle',
    warmingTitle: 'Le fil se prépare',
    warmingBody:
      'Pas encore d’annonces actives. Publiez votre premier patrimoine ou explorez Logement.',
    exploreWithFilters: 'Explorer avec des filtres',
    markers: {
      new: { title: 'Nouveaux patrimoines', hint: 'Viennent de rejoindre la plateforme.' },
      featured: {
        title: 'En vedette',
        hint: 'Sélection avec présence premium.',
        badge: 'En vedette',
      },
      nearby: { title: 'Près de vous', hint: 'Inventaire pertinent à explorer maintenant.' },
      recommend: {
        title: 'Recommandations',
        hint: 'Suggestions basées sur l’inventaire actif.',
      },
      trends: { title: 'Tendances', hint: 'Ce que la communauté regarde.' },
      premium: {
        title: 'Biens premium',
        hint: 'Patrimoine haut de gamme.',
        badge: 'Premium',
      },
      contracts: {
        title: 'Activité des contrats',
        hint: 'Formalisation en cours sur la plateforme.',
        badge: 'Contrats',
      },
      news: { title: 'Actualités', hint: 'Mises à jour récentes du marketplace.' },
      smart: {
        title: 'Recommandations intelligentes',
        hint: 'Préparation pour le moteur KAI.',
        badge: 'KAI prep',
      },
      more: {
        title: 'Plus de patrimoines',
        hint: 'Continuez à explorer — le fil ne s’arrête pas là.',
      },
      sponsored: {
        title: 'Annonces sponsorisées',
        hint: 'Campagnes et inventaire en promotion.',
        badge: 'Sponsorisé',
      },
    },
    linkCard: {
      title: 'Explorer le logement avec des filtres',
      hint: 'Affinez la localisation, l’objectif et la typologie sans quitter la plateforme.',
      cta: 'Ouvrir explorer',
    },
  },
  institutional: {
    badge: 'Kuteka · v1.0 Beta',
    backToLanding: 'Retour à la Landing',
    contactKuteka: 'Contacter Kuteka',
  },
  errors: {
    routeErrorTitle: 'Erreur',
    routeErrorBody: 'Nous avons des difficultés à afficher cette page. Veuillez réessayer.',
    retry: 'Réessayer',
    globalErrorTitle: 'Une erreur est survenue',
    globalErrorBody: 'Une erreur inattendue s’est produite. Vous pouvez réessayer.',
    notFoundTitle: 'Page introuvable',
    notFoundBody: 'La ressource demandée n’existe pas.',
    goHome: 'Aller à la fondation',
  },
  hero: {
    dashboard: {
      alt: 'Maison contemporaine au crépuscule',
      eyebrow: 'Kuteka · Angola',
      title: 'Plateforme immobilière vivante',
      subtitle: 'Patrimoine, logement et confiance — la suite naturelle de la Landing.',
    },
    patrimonios: {
      alt: 'Maison contemporaine à l’architecture premium',
      eyebrow: 'Partenaire patrimonial',
      title: 'Publiez le patrimoine avec présence',
      subtitle: 'Photos, prix et galerie — l’annonce commence ici.',
    },
    habitacao: {
      alt: 'Intérieur résidentiel élégant',
      eyebrow: 'Client',
      title: 'Trouvez un logement en toute transparence',
      subtitle: 'Explorez, filtrez et manifestez votre intérêt pour l’inventaire actif.',
    },
    agente: {
      alt: 'Médiation et travail de terrain',
      eyebrow: 'Agent certifié',
      title: 'Suivez sur le terrain',
      subtitle: 'Couverture, visites, intérêts et pipeline en un seul endroit.',
    },
    confianca: {
      alt: 'Documentation et vérification sécurisées',
      eyebrow: 'Vérification',
      title: 'Relations sûres avec des preuves',
      subtitle: 'Checklist claire — En analyse, Approuvé ou Rejeté.',
    },
    contratos: {
      alt: 'Table exécutive avec contrat et signature',
      eyebrow: 'Contrat',
      title: 'Formalisez avec clarté',
      subtitle: 'Parties, valeur, termes et acceptation avant les Paiements.',
    },
    admin: {
      alt: 'Environnement exécutif d’opération',
      eyebrow: 'Opération',
      title: 'Commande de la plateforme',
      subtitle: 'Comptes, patrimoines, vérifications et demandes en attente.',
    },
  },
  flowNextSteps: {
    defaultTitle: 'Continuer le parcours',
    kaiEyebrow: 'KAI · Prochaine étape',
  },
  betaFeedback: {
    eyebrow: 'Accès anticipé',
    title: 'Partager un retour Beta',
    subtitle:
      'Aidez à améliorer Kuteka avant le lancement commercial. Le Super Admin le voit dans le Panneau Beta.',
    kindFeedback: 'Suggestion / retour',
    kindBug: 'Signaler un bug',
    bodyLabel: 'Description',
    placeholder: 'Ce qui a bien fonctionné, ce qui a échoué, ou ce que vous aimeriez voir…',
    submit: 'Envoyer',
    sending: 'Envoi…',
    success: 'Merci — votre contribution a été enregistrée.',
    error: 'Envoi impossible. Réessayez.',
  },
  firstActions: {
    title: 'Votre première action utile',
    kaiHint: 'KAI indique la prochaine étape adaptée à votre rôle actif.',
    clientExplore: 'Explorer le logement',
    clientTrust: 'Compléter l’identité (KIS)',
    partnerActivate: 'Activer un patrimoine',
    partnerInventory: 'Voir l’inventaire Logement',
    agentPipeline: 'Ouvrir le pipeline Agent',
    adminPanel: 'Ouvrir Administration',
    dualClient: 'Explorer en Client',
    dualPartner: 'Publier en Partenaire',
  },
};
