/** Shell chrome copy — pt-AO. */
export const shellCopyPt = {
  areaTitle: 'Plataforma Kuteka',
  navAria: 'Navegação da plataforma',
  openMenu: 'Abrir menu',
  closeMenu: 'Fechar menu',
  soon: 'Em breve',
  notificationsTitle: 'Notificações',
  notificationsEmpty: 'Sem notificações novas neste momento.',
  notificationsMarkRead: 'Marcar como lidas',
  notificationsViewAll: 'Ver todas',
  language: 'Idioma',
  languageHint: 'Altera toda a interface',
  userMenuAria: 'Menu da conta',
  switchRole: 'Mudar de papel',
  switchRoleHint: 'Altera menus, dashboard e fluxos imediatamente',
  activeExperience: 'Experiência activa',
  accountLabel: 'Conta',
  changePhoto: 'Alterar fotografia',
  groups: {
    geral: 'Geral',
    cliente: 'Cliente',
    parceiro: 'Parceiro Patrimonial',
    agente: 'Agente',
    admin: 'Administração',
  },
  userMenu: {
    profile: 'Perfil',
    profileHint: 'Os meus dados pessoais',
    centroConfiancaHint: 'Estado da conta, UTS e próximos passos',
    centroSegurancaHint: 'Email, telefone, sessões e nível de segurança',
    roleCountSingular: 'papel',
    roleCountPlural: 'papéis',
    roles: 'Os meus papéis',
    rolesHint: 'Activar ou gerir papéis da conta',
    patrimonios: 'Os meus patrimónios',
    patrimoniosHint: 'Anúncios e gestão patrimonial',
    contracts: 'Contratos',
    contractsHint: 'Minutas e formalizações',
    documents: 'Documentos',
    documentsHint: 'Confiança e verificação',
    notifications: 'Notificações',
    notificationsHint: 'Alertas do seu papel activo',
    messages: 'Mensagens',
    messagesHint: 'Conversas com Clientes, Parceiros, Agentes e Prestadores',
    language: 'Idioma',
    languageHint: 'Português, English, Français, Español',
    settings: 'Definições',
    settingsHint: 'Idioma, moeda, tema e privacidade',
    privacy: 'Privacidade',
    privacyHint: 'Dados e consentimentos',
    help: 'Centro de Ajuda',
    helpHint: 'Manual, FAQ e tutoriais',
    contact: 'Contactar a Kuteka',
    contactHint: 'WhatsApp, telefone, email e chat',
    logout: 'Terminar sessão',
  },
  settingsPage: {
    title: 'Definições',
    subtitle: 'Preferências da conta e da experiência Kuteka.',
    language: 'Idioma',
    currency: 'Moeda',
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Escuro',
    themeSystem: 'Sistema',
    notifications: 'Notificações',
    notificationsHint: 'Receber alertas do papel activo',
    privacy: 'Privacidade',
    privacyHint: 'Consulte a política de privacidade',
    security: 'Segurança',
    password: 'Palavra-passe',
    passwordHint: 'Alterar ou recuperar palavra-passe',
    sessions: 'Sessões activas',
    sessionsHint: 'Termine a sessão neste dispositivo quando quiser',
    saveLocale: 'Idioma guardado nas preferências da conta',
  },
  helpPage: {
    title: 'Centro de Documentação Kuteka',
    subtitle: 'Manual, FAQ, glossário, novidades e estado dos serviços — tudo num só lugar.',
    manual: 'Manual do utilizador',
    faq: 'Perguntas frequentes',
    glossario: 'Glossário',
    novidades: 'Novidades',
    estado: 'Estado dos Serviços',
    roadmap: 'Roteiro público',
    videos: 'Vídeos',
    tutorials: 'Tutoriais',
    howPublish: 'Como publicar',
    howBuy: 'Como comprar',
    howRent: 'Como arrendar',
    contactCta: 'Ainda precisa de ajuda? Contacte-nos',
    publicNotice:
      'Está a ver o Centro de Documentação público. Inicie sessão para uma experiência completa e personalizada.',
  },
  contactPage: {
    title: 'Contactar a Kuteka',
    subtitle: 'Escolha o canal mais conveniente para a sua equipa.',
    whatsapp: 'WhatsApp',
    phone: 'Telefone',
    email: 'Email',
    chat: 'Chat',
    helpCenter: 'Centro de Ajuda',
    hours: 'Atendimento em dias úteis, 09:00–18:00 (WAT)',
  },
  items: {
    home: 'Início',
    explorar: 'Explorar Habitação',
    residencia: 'Residência',
    favoritos: 'Favoritos / Interesses',
    visitas: 'Visitas',
    futuro: 'Disponibilidade futura',
    propostas: 'Propostas',
    patrimonios: 'Patrimónios',
    ativar: 'Ativar Património',
    habitacao: 'Habitação',
    agente: 'Agente',
    mensagens: 'Mensagens',
    confianca: 'Confiança',
    centroConfianca: 'Centro de Confiança',
    centroSeguranca: 'Centro de Segurança',
    contratos: 'Contratos',
    relatorios: 'Relatórios',
    conta: 'Conta',
    admin: 'Administração',
    super: 'Super Admin',
    financeiro: 'Financeiro',
    mudanca: 'Mudança Inteligente',
    encontrar: 'Encontrar Casa',
    concierge: 'Concierge',
    garantia: 'Garantia Kuteka',
    assistencia: 'Assistência 24h',
    servicos: 'Prestadores',
    planos: 'Planos Parceiro',
  },
  routeBlocked: {
    title: 'Área indisponível neste papel',
    body: 'A experiência activa não inclui este fluxo. Mude de papel no menu da conta ou escolha um atalho autorizado.',
    switch: 'Mudar de papel',
    home: 'Ir ao início',
  },
  forbidden: {
    activateRole: 'Activar papel',
    goDashboard: 'Ir ao painel',
    verifyAccount: 'Verificar conta',
    continueElsewhere: 'Continuar noutro caminho',
  },
  helpExtra: {
    terms: 'Termos de Utilização',
    privacy: 'Política de Privacidade',
    cookies: 'Política de Cookies',
    securityCenter: 'Centro de Segurança',
    contactSupport: 'Contactar suporte',
    downloadManualPdf: 'Descarregar Manual (PDF)',
    downloadManualWord: 'Descarregar Manual (Word)',
    videosPending:
      'Os tutoriais em vídeo serão publicados progressivamente. Até lá, use os tutoriais escritos deste manual e os atalhos acima.',
  },
  brandTagline: 'Gestão patrimonial',
  loadingMore: 'A carregar mais…',
  loadingContent: 'A carregar conteúdo…',
  securityCenterHint: 'Email, telefone, sessões, dispositivos e nível de segurança da conta.',
  feedEndTitle: 'Chegou ao fim do inventário actual',
  feedEndBody: 'Novos patrimónios aparecem aqui assim que forem publicados.',
  feed: {
    activateRoleTitle: 'Active o papel Cliente para ver o feed',
    activateRoleBody:
      'O feed contínuo mostra patrimónios, destaques e recomendações assim que tiver acesso a Habitação.',
    activateRoleCta: 'Activar papel',
    warmingTitle: 'Feed a aquecer',
    warmingBody:
      'Ainda não há anúncios activos. Publique o primeiro património ou explore Habitação.',
    exploreWithFilters: 'Explorar com filtros',
    markers: {
      new: { title: 'Patrimónios novos', hint: 'Acabaram de entrar na plataforma.' },
      featured: {
        title: 'Em destaque',
        hint: 'Selecção com presença premium.',
        badge: 'Destaque',
      },
      nearby: { title: 'Próximos de si', hint: 'Inventário relevante para explorar agora.' },
      recommend: {
        title: 'Recomendações',
        hint: 'Sugestões com base no inventário activo.',
      },
      trends: { title: 'Tendências', hint: 'O que a comunidade está a ver.' },
      premium: {
        title: 'Imóveis premium',
        hint: 'Património de gama alta.',
        badge: 'Premium',
      },
      contracts: {
        title: 'Actividade de contratos',
        hint: 'Formalização a avançar na plataforma.',
        badge: 'Contratos',
      },
      news: { title: 'Novidades', hint: 'Actualizações recentes do marketplace.' },
      smart: {
        title: 'Recomendações inteligentes',
        hint: 'Preparação para o motor KAI.',
        badge: 'KAI prep',
      },
      more: { title: 'Mais patrimónios', hint: 'Continue a explorar — o feed não acaba aqui.' },
      sponsored: {
        title: 'Anúncios patrocinados',
        hint: 'Campanhas e inventário em promoção.',
        badge: 'Patrocinado',
      },
    },
    linkCard: {
      title: 'Explorar habitação com filtros',
      hint: 'Afine localização, finalidade e tipologia sem sair da plataforma.',
      cta: 'Abrir explorar',
    },
  },
  institutional: {
    badge: 'Kuteka · v1.0 Beta',
    backToLanding: 'Voltar à Landing',
    contactKuteka: 'Contactar a Kuteka',
  },
  errors: {
    routeErrorTitle: 'Erro',
    routeErrorBody: 'Estamos a ter dificuldade em mostrar esta página. Tente novamente.',
    retry: 'Tentar novamente',
    globalErrorTitle: 'Algo correu mal',
    globalErrorBody: 'Ocorreu um erro inesperado. Pode tentar novamente.',
    notFoundTitle: 'Página não encontrada',
    notFoundBody: 'O recurso pedido não existe.',
    goHome: 'Ir para a fundação',
  },
} as const;

type DeepStringify<T> = {
  [K in keyof T]: T[K] extends string ? string : DeepStringify<T[K]>;
};

export type ShellCopy = DeepStringify<typeof shellCopyPt>;
