import type { ConfiancaCopy } from './pt';

export const confiancaCopyEn: ConfiancaCopy = {
  title: 'Trust',
  subtitle:
    'Verify your account with structured evidence. Secure relationships start with a clear checklist.',
  permissionBadge: 'trust.manage',
  submit: 'Submit verification',
  submitTitle: 'Submit verification item',
  submitHint: 'Indicate the type and supporting notes. File upload arrives in later phases.',
  submitting: 'Submitting…',
  submitted: 'Item submitted for verification.',
  backToHub: 'Back to Trust',
  checklistTitle: 'Account checklist',
  checklistHint: 'Latest status for each verification type.',
  historyTitle: 'Recent submissions',
  historyHint: 'History of your submissions and reviews.',
  emptyChecklistTitle: 'No submissions yet',
  emptyChecklist:
    'Start by submitting your identity verification. Each item joins the review queue.',
  emptyChecklistCta: 'Submit verification',
  emptyHistoryTitle: 'No history',
  emptyHistory: 'Submissions will appear here after the first one is sent.',
  review: 'Admin review',
  reviewTitle: 'Trust review',
  reviewHint: 'Queue of submitted or under-review items. Accept, reject or mark as in review.',
  emptyReviewTitle: 'Empty queue',
  emptyReview: 'There are no items pending review at the moment.',
  accept: 'Accept',
  reject: 'Reject',
  markReview: 'Under review',
  reviewing: 'Updating…',
  reviewed: 'Review recorded.',
  rejectionReasonLabel: 'Rejection reason',
  rejectionReasonPlaceholder: 'Explain what is missing or incorrect.',
  rejectionReasonRequired: 'Rejection reason is required.',
  loadError: 'We are having trouble showing Trust. Please try again.',
  saveError: 'We could not submit right now. Please try again.',
  forbidden: 'You do not have permission to manage Trust (trust.manage).',
  reviewForbidden: 'You do not have permission to review submissions (admin.panel).',
  mvpNote: 'MVP: checklist and statuses. Digital Passport, Score and file upload will follow.',
  fields: {
    docType: 'Verification type',
    notes: 'Notes (optional)',
    status: 'Status',
    property: 'Property (optional)',
    none: '—',
    createdAt: 'Submitted',
    reviewedAt: 'Reviewed',
  },
  docTypes: {
    identity: 'Identity',
    proof_of_address: 'Proof of address',
    property_title: 'Property title',
    agent_credential: 'Agent credential',
  },
  statuses: {
    submitted: 'Under review',
    under_review: 'Under review',
    accepted: 'Approved',
    rejected: 'Rejected',
    pending: 'Not submitted',
  },
  historyLabel: 'Verification history',
};
