import type { ConfiancaCopy } from './pt';

export const confiancaCopyEs: ConfiancaCopy = {
  title: 'Confianza',
  subtitle:
    'Verifique su cuenta con evidencias estructuradas. Las relaciones seguras comienzan con una lista de verificación clara.',
  permissionBadge: 'trust.manage',
  submit: 'Enviar verificación',
  submitTitle: 'Enviar elemento de verificación',
  submitHint:
    'Indique el tipo y notas de apoyo. La carga de archivos llegará en fases posteriores.',
  submitting: 'Enviando…',
  submitted: 'Elemento enviado para verificación.',
  backToHub: 'Volver a Confianza',
  checklistTitle: 'Lista de verificación de la cuenta',
  checklistHint: 'Estado más reciente de cada tipo de verificación.',
  historyTitle: 'Envíos recientes',
  historyHint: 'Historial de sus envíos y revisiones.',
  emptyChecklistTitle: 'Aún sin envíos',
  emptyChecklist:
    'Comience enviando la verificación de identidad. Cada elemento entra en la cola de revisión.',
  emptyChecklistCta: 'Enviar verificación',
  emptyHistoryTitle: 'Sin historial',
  emptyHistory: 'Los envíos aparecerán aquí después del primer envío.',
  review: 'Revisión de administrador',
  reviewTitle: 'Revisión de Confianza',
  reviewHint: 'Cola de elementos enviados o en revisión. Acepte, rechace o marque en análisis.',
  emptyReviewTitle: 'Cola vacía',
  emptyReview: 'No hay elementos pendientes de revisión en este momento.',
  accept: 'Aceptar',
  reject: 'Rechazar',
  markReview: 'En revisión',
  reviewing: 'Actualizando…',
  reviewed: 'Revisión registrada.',
  rejectionReasonLabel: 'Motivo del rechazo',
  rejectionReasonPlaceholder: 'Explique qué falta o es incorrecto.',
  rejectionReasonRequired: 'El motivo del rechazo es obligatorio.',
  loadError: 'Estamos teniendo dificultades para mostrar Confianza. Inténtelo de nuevo.',
  saveError: 'No pudimos enviarlo en este momento. Inténtelo de nuevo.',
  forbidden: 'No tiene permiso para gestionar Confianza (trust.manage).',
  reviewForbidden: 'No tiene permiso para revisar envíos (admin.panel).',
  mvpNote:
    'MVP: lista de verificación y estados. El Pasaporte Digital, la Puntuación y la carga de archivos llegarán después.',
  fields: {
    docType: 'Tipo de verificación',
    notes: 'Notas (opcional)',
    status: 'Estado',
    property: 'Patrimonio (opcional)',
    none: '—',
    createdAt: 'Enviado',
    reviewedAt: 'Revisado',
  },
  docTypes: {
    identity: 'Identidad',
    proof_of_address: 'Comprobante de domicilio',
    property_title: 'Título de propiedad',
    agent_credential: 'Credencial de agente',
  },
  statuses: {
    submitted: 'En análisis',
    under_review: 'En análisis',
    accepted: 'Aprobado',
    rejected: 'Rechazado',
    pending: 'Por enviar',
  },
  historyLabel: 'Historial de verificaciones',
};
