import type { ConfiancaCopy } from './pt';

export const confiancaCopyFr: ConfiancaCopy = {
  title: 'Confiance',
  subtitle:
    'Vérifiez votre compte avec des preuves structurées. Des relations sûres commencent par une liste de contrôle claire.',
  permissionBadge: 'trust.manage',
  submit: 'Soumettre une vérification',
  submitTitle: 'Soumettre un élément de vérification',
  submitHint:
    'Indiquez le type et des notes à l’appui. Le téléversement de fichiers arrivera dans une phase ultérieure.',
  submitting: 'Envoi…',
  submitted: 'Élément soumis pour vérification.',
  backToHub: 'Retour à Confiance',
  checklistTitle: 'Liste de contrôle du compte',
  checklistHint: 'Dernier état de chaque type de vérification.',
  historyTitle: 'Soumissions récentes',
  historyHint: 'Historique de vos soumissions et révisions.',
  emptyChecklistTitle: 'Aucune soumission pour le moment',
  emptyChecklist:
    'Commencez par soumettre la vérification d’identité. Chaque élément rejoint la file de révision.',
  emptyChecklistCta: 'Soumettre une vérification',
  emptyHistoryTitle: 'Aucun historique',
  emptyHistory: 'Les soumissions apparaîtront ici après le premier envoi.',
  review: 'Révision admin',
  reviewTitle: 'Révision de Confiance',
  reviewHint: 'File des éléments soumis ou en révision. Acceptez, rejetez ou marquez en analyse.',
  emptyReviewTitle: 'File vide',
  emptyReview: 'Aucun élément en attente de révision pour le moment.',
  accept: 'Accepter',
  reject: 'Rejeter',
  markReview: 'En révision',
  reviewing: 'Mise à jour…',
  reviewed: 'Révision enregistrée.',
  rejectionReasonLabel: 'Motif du rejet',
  rejectionReasonPlaceholder: 'Expliquez ce qui manque ou est incorrect.',
  rejectionReasonRequired: 'Le motif du rejet est obligatoire.',
  loadError: 'Nous avons du mal à afficher Confiance. Veuillez réessayer.',
  saveError: 'Nous n’avons pas pu soumettre pour le moment. Veuillez réessayer.',
  forbidden: 'Vous n’avez pas la permission de gérer Confiance (trust.manage).',
  reviewForbidden: 'Vous n’avez pas la permission de réviser les soumissions (admin.panel).',
  mvpNote:
    'MVP : liste de contrôle et statuts. Passeport numérique, score et téléversement de fichiers viendront ensuite.',
  fields: {
    docType: 'Type de vérification',
    notes: 'Notes (facultatif)',
    status: 'État',
    property: 'Patrimoine (facultatif)',
    none: '—',
    createdAt: 'Soumis',
    reviewedAt: 'Révisé',
  },
  docTypes: {
    identity: 'Identité',
    proof_of_address: 'Justificatif de domicile',
    property_title: 'Titre de propriété',
    agent_credential: 'Accréditation d’agent',
  },
  statuses: {
    submitted: 'En analyse',
    under_review: 'En analyse',
    accepted: 'Approuvé',
    rejected: 'Rejeté',
    pending: 'À soumettre',
  },
  historyLabel: 'Historique des vérifications',
};
