export const confiancaCopyPt = {
  title: 'Confiança',
  subtitle:
    'Verifique a sua conta com evidências estruturadas. Relações seguras começam por uma checklist clara.',
  permissionBadge: 'trust.manage',
  submit: 'Submeter verificação',
  submitTitle: 'Submeter item de verificação',
  submitHint: 'Indique o tipo e notas de apoio. O upload de ficheiros chega em fases seguintes.',
  submitting: 'A submeter…',
  submitted: 'Item submetido para verificação.',
  backToHub: 'Voltar à Confiança',
  checklistTitle: 'Checklist da conta',
  checklistHint: 'Estado mais recente de cada tipo de verificação.',
  historyTitle: 'Submissões recentes',
  historyHint: 'Histórico das suas submissões e revisões.',
  emptyChecklistTitle: 'Ainda sem submissões',
  emptyChecklist:
    'Comece por submeter a verificação de identidade. Cada item entra em fila de revisão.',
  emptyChecklistCta: 'Submeter verificação',
  emptyHistoryTitle: 'Sem histórico',
  emptyHistory: 'As submissões aparecerão aqui após o primeiro envio.',
  review: 'Revisão admin',
  reviewTitle: 'Revisão de Confiança',
  reviewHint: 'Fila de itens submetidos ou em revisão. Aceite, rejeite ou marque em análise.',
  emptyReviewTitle: 'Fila vazia',
  emptyReview: 'Não há itens pendentes de revisão neste momento.',
  accept: 'Aceitar',
  reject: 'Rejeitar',
  markReview: 'Em revisão',
  reviewing: 'A actualizar…',
  reviewed: 'Revisão registada.',
  rejectionReasonLabel: 'Motivo da rejeição',
  rejectionReasonPlaceholder: 'Explique o que falta ou está incorrecto.',
  rejectionReasonRequired: 'Motivo da rejeição é obrigatório.',
  loadError: 'Estamos a ter dificuldade em mostrar a Confiança. Tente novamente.',
  saveError: 'Não conseguimos submeter agora. Tente novamente.',
  forbidden: 'Não tem permissão para gerir a Confiança (trust.manage).',
  reviewForbidden: 'Não tem permissão para rever submissões (admin.panel).',
  mvpNote:
    'MVP: checklist e estados. Passaporte Digital, Score e upload de ficheiros virão depois.',
  fields: {
    docType: 'Tipo de verificação',
    notes: 'Notas (opcional)',
    status: 'Estado',
    property: 'Património (opcional)',
    none: '—',
    createdAt: 'Submetido',
    reviewedAt: 'Revisado',
  },
  docTypes: {
    identity: 'Identidade',
    proof_of_address: 'Comprovativo de morada',
    property_title: 'Título de propriedade',
    agent_credential: 'Credencial de agente',
  },
  statuses: {
    submitted: 'Em análise',
    under_review: 'Em análise',
    accepted: 'Aprovado',
    rejected: 'Rejeitado',
    pending: 'Por submeter',
  },
  historyLabel: 'Histórico de verificações',
  trustCard: {
    title: 'Confiança',
    ickLabel: 'Índice Kuteka (ICK)',
    ratingLabel: 'Avaliação',
    ratingTemplate: '{avg} ({count})',
    noRating: 'Sem avaliações ainda',
    contractsLabel: 'Contratos concluídos',
    avgResponseLabel: 'Tempo médio de resposta',
    avgResponseTemplate: '{n} min',
    avgResponseUnknown: 'Sem dados',
    kisLevelLabel: 'Nível KIS',
    kisLevelTemplate: 'Nível {n}',
    memberSinceLabel: 'Membro desde',
    lastActivityLabel: 'Última atividade',
    notAvailable: '—',
    kaiTitle: 'KAI',
  },
  reputationKai: {
    excellentRecent: 'Este imóvel possui excelente reputação nos últimos 12 meses.',
    goodRecent: 'Boa reputação recente — avaliações consistentes nos últimos meses.',
    avgRatingTemplate: 'Classificação média de {avg}/5 com {count} avaliação(ões).',
    contractsTemplate: '{n} contrato(s) concluído(s) com sucesso.',
    trustedProfile: 'Perfil com boa reputação e histórico consistente na Kuteka.',
    highIck: 'Índice Kuteka elevado — confiança acima da média da plataforma.',
    newProfile: 'Perfil ainda a construir histórico de reputação.',
    verifiedIdentity: 'Identidade verificada ao nível KIS {n}.',
  },
} as const;

type DeepStringify<T> = {
  [K in keyof T]: T[K] extends string ? string : DeepStringify<T[K]>;
};

export type ConfiancaCopy = DeepStringify<typeof confiancaCopyPt>;
