import type { MensagensCopy } from './pt';

export const mensagensCopyEn: MensagensCopy = {
  title: 'Messages',
  subtitle: 'Chat with Clients, Partners, Agents and Providers without leaving Kuteka.',
  inboxTitle: 'Inbox',
  searchPlaceholder: 'Search by person or conversation…',
  emptyTitle: 'No conversations yet',
  empty:
    'Once you start a conversation with a Client, Partner, Agent or Provider, it shows up here.',
  emptyFiltered: 'No conversation matches your search or the selected filter.',
  loadError: 'We are having trouble showing your messages. Please try again.',
  threadLoadError: 'We could not open this conversation. Please try again.',
  sendError: 'We could not send the message. Please try again.',
  startError: 'We could not start this conversation.',
  statusChangeError: 'We could not update the conversation status.',
  selectConversation: 'Select a conversation to see the messages.',
  composerPlaceholder: 'Write a message…',
  send: 'Send',
  sending: 'Sending…',
  backToList: 'Back to conversations',
  statuses: {
    active: 'Active',
    archived: 'Archived',
    completed: 'Completed',
  },
  statusFilters: {
    all: 'All',
    active: 'Active',
    archived: 'Archived',
    completed: 'Completed',
  },
  markRead: 'Mark as read',
  archive: 'Archive',
  reopen: 'Reopen',
  complete: 'Mark completed',
  unreadBadgeAria: 'unread messages',
  topbar: {
    title: 'Messages',
    empty: 'No new messages right now.',
    loading: 'Loading conversations…',
    viewAll: 'View all',
    loadError: 'We could not load recent conversations.',
  },
  contactPolicy: {
    title: 'Why can’t I see phone or email?',
    body: 'For everyone’s safety, phone and email are only shared once there is an active/completed contract, a scheduled visit, or an explicit Kuteka authorization. Until then, arrange everything through Kuteka Chat.',
    shareLocked: 'Contacts have not been released for this conversation yet.',
    shareUnlocked: 'Contract formalised — contacts can now be shared in this conversation.',
  },
  contextLabels: {
    property: 'Property',
    contract: 'Contract',
    service: 'Service',
    general: 'General',
    admin: 'Administration',
    interest: 'Interest',
  },
  roleLabels: {
    client: 'Client',
    partner: 'Partner',
    agent: 'Agent',
    provider: 'Provider',
    admin: 'Administration',
    superadmin: 'Super Admin',
    other: 'Kuteka user',
  },
  cta: {
    messageOwner: 'Message',
    messageBusy: 'Opening conversation…',
    messageSent: 'Conversation started — open Messages to continue.',
    messageSelf: 'This is your own listing — you cannot message yourself.',
    notAllowed: 'This conversation cannot start from your current account role.',
    openInbox: 'Open Messages',
  },
  forbidden: 'Sign in to access Messages.',
};
