import type { MensagensCopy } from './pt';

export const mensagensCopyEs: MensagensCopy = {
  title: 'Mensajes',
  subtitle: 'Converse con Clientes, Socios, Agentes y Prestadores sin salir de Kuteka.',
  inboxTitle: 'Bandeja de entrada',
  searchPlaceholder: 'Buscar por persona o conversación…',
  emptyTitle: 'Aún sin conversaciones',
  empty:
    'Cuando inicie una conversación con un Cliente, Socio, Agente o Prestador, aparecerá aquí.',
  emptyFiltered: 'Ninguna conversación coincide con la búsqueda o el filtro seleccionado.',
  loadError: 'Estamos teniendo dificultades para mostrar sus mensajes. Inténtelo de nuevo.',
  threadLoadError: 'No se pudo abrir esta conversación. Inténtelo de nuevo.',
  sendError: 'No se pudo enviar el mensaje. Inténtelo de nuevo.',
  startError: 'No se pudo iniciar esta conversación.',
  statusChangeError: 'No se pudo actualizar el estado de la conversación.',
  selectConversation: 'Seleccione una conversación para ver los mensajes.',
  composerPlaceholder: 'Escriba un mensaje…',
  send: 'Enviar',
  sending: 'Enviando…',
  backToList: 'Volver a las conversaciones',
  statuses: {
    active: 'Activa',
    archived: 'Archivada',
    completed: 'Concluida',
  },
  statusFilters: {
    all: 'Todas',
    active: 'Activas',
    archived: 'Archivadas',
    completed: 'Concluidas',
  },
  markRead: 'Marcar como leída',
  archive: 'Archivar',
  reopen: 'Reactivar',
  complete: 'Marcar concluida',
  unreadBadgeAria: 'mensajes sin leer',
  topbar: {
    title: 'Mensajes',
    empty: 'Sin mensajes nuevos por ahora.',
    loading: 'Cargando conversaciones…',
    viewAll: 'Ver todas',
    loadError: 'No se pudieron cargar las conversaciones recientes.',
  },
  contactPolicy: {
    title: '¿Por qué no veo el teléfono o el email?',
    body: 'Por seguridad de ambas partes, el teléfono y el email solo se comparten cuando existe un contrato activo/concluido, una visita programada, o una autorización explícita de Kuteka. Hasta entonces, coordine todo por el Chat Kuteka.',
    shareLocked: 'Los contactos aún no se han liberado para esta conversación.',
    shareUnlocked:
      'Contrato formalizado — los contactos ya pueden compartirse en esta conversación.',
  },
  contextLabels: {
    property: 'Patrimonio',
    contract: 'Contrato',
    service: 'Servicio',
    general: 'General',
    admin: 'Administración',
    interest: 'Interés',
  },
  roleLabels: {
    client: 'Cliente',
    partner: 'Socio',
    agent: 'Agente',
    provider: 'Prestador',
    admin: 'Administración',
    superadmin: 'Super Admin',
    other: 'Usuario Kuteka',
  },
  cta: {
    messageOwner: 'Mensaje',
    messageBusy: 'Abriendo conversación…',
    messageSent: 'Conversación iniciada — abra Mensajes para continuar.',
    messageSelf: 'Este inmueble es suyo — no puede enviarse un mensaje a sí mismo.',
    notAllowed: 'No es posible iniciar esta conversación desde su papel de cuenta actual.',
    openInbox: 'Abrir Mensajes',
  },
  forbidden: 'Inicie sesión para acceder a Mensajes.',
};
