import type { MensagensCopy } from './pt';

export const mensagensCopyFr: MensagensCopy = {
  title: 'Messages',
  subtitle: 'Discutez avec Clients, Partenaires, Agents et Prestataires sans quitter Kuteka.',
  inboxTitle: 'Boîte de réception',
  searchPlaceholder: 'Rechercher une personne ou une conversation…',
  emptyTitle: 'Aucune conversation pour le moment',
  empty:
    'Dès que vous démarrez une conversation avec un Client, Partenaire, Agent ou Prestataire, elle apparaît ici.',
  emptyFiltered: 'Aucune conversation ne correspond à la recherche ou au filtre sélectionné.',
  loadError: 'Nous avons du mal à afficher vos messages. Veuillez réessayer.',
  threadLoadError: 'Impossible d’ouvrir cette conversation. Veuillez réessayer.',
  sendError: 'Impossible d’envoyer le message. Veuillez réessayer.',
  startError: 'Impossible de démarrer cette conversation.',
  statusChangeError: 'Impossible de mettre à jour le statut de la conversation.',
  selectConversation: 'Sélectionnez une conversation pour voir les messages.',
  composerPlaceholder: 'Écrire un message…',
  send: 'Envoyer',
  sending: 'Envoi…',
  backToList: 'Retour aux conversations',
  statuses: {
    active: 'Active',
    archived: 'Archivée',
    completed: 'Terminée',
  },
  statusFilters: {
    all: 'Toutes',
    active: 'Actives',
    archived: 'Archivées',
    completed: 'Terminées',
  },
  markRead: 'Marquer comme lu',
  archive: 'Archiver',
  reopen: 'Réactiver',
  complete: 'Marquer terminée',
  unreadBadgeAria: 'messages non lus',
  topbar: {
    title: 'Messages',
    empty: 'Aucun nouveau message pour le moment.',
    loading: 'Chargement des conversations…',
    viewAll: 'Voir tout',
    loadError: 'Impossible de charger les conversations récentes.',
  },
  contactPolicy: {
    title: 'Pourquoi ne vois-je pas le téléphone ou l’email ?',
    body: 'Pour la sécurité de tous, le téléphone et l’email ne sont partagés qu’après un contrat actif/terminé, une visite programmée, ou une autorisation explicite de Kuteka. En attendant, tout se organise via Kuteka Chat.',
    shareLocked: 'Les contacts ne sont pas encore libérés pour cette conversation.',
    shareUnlocked:
      'Contrat formalisé — les contacts peuvent désormais être partagés dans cette conversation.',
  },
  contextLabels: {
    property: 'Patrimoine',
    contract: 'Contrat',
    service: 'Service',
    general: 'Général',
    admin: 'Administration',
    interest: 'Intérêt',
  },
  roleLabels: {
    client: 'Client',
    partner: 'Partenaire',
    agent: 'Agent',
    provider: 'Prestataire',
    admin: 'Administration',
    superadmin: 'Super Admin',
    other: 'Utilisateur Kuteka',
  },
  cta: {
    messageOwner: 'Message',
    messageBusy: 'Ouverture de la conversation…',
    messageSent: 'Conversation démarrée — ouvrez Messages pour continuer.',
    messageSelf: 'Ce bien vous appartient — vous ne pouvez pas vous envoyer un message.',
    notAllowed: 'Cette conversation ne peut pas démarrer avec votre rôle de compte actuel.',
    openInbox: 'Ouvrir Messages',
  },
  forbidden: 'Connectez-vous pour accéder aux Messages.',
};
