import type { MonetizationCopy } from './pt';

/** Monetization suite copy — en. */
export const monetizationCopyEn: MonetizationCopy = {
  common: {
    actionError: 'We could not complete this action. Try again.',
    loadError: 'We are having trouble showing this data. Try again.',
    cancel: 'Cancel',
    viewTimeline: 'View timeline',
    hideTimeline: 'Hide timeline',
    noEvents: 'No events.',
    financeiro: 'Finance',
    slaBreached: 'SLA exceeded',
    slaAtLimit: 'SLA at the limit',
    slaInHours: 'SLA in {hours}h',
    slaInDays: 'SLA in {days}d',
    reason: 'Reason: {value}',
    kycRequiredHint:
      'Complete identity verification (KIS · KYC level 2+) in Profile before continuing.',
  },
  smartMove: {
    eyebrow: 'Smart Move',
    title: 'Urgency-assisted search',
    subtitle:
      'Tell us your move-out date, pay the opening fee (sandbox) and Kuteka activates a partner, agents and KAI. The success fee is only charged when you accept a solution. Exploring homes stays free.',
    providersLink: 'Provider network',
    newRequestTitle: 'New request',
    urgencyLabel: 'Urgency',
    contractLabel: 'Contract (optional)',
    noContractOption: 'No link',
    notesLabel: 'Preferences / notes',
    notesPlaceholder: 'Area, typology, budget…',
    submit: 'Activate Smart Move (sandbox)',
    requestsTitle: 'Requests',
    operatorBadge: 'Operator (agent / finance)',
    openingAmount: 'Opening {amount}',
    openingPending: 'Opening pending',
    paidSuffix: ' · paid',
    successAmountSuffix: ' · success {amount}',
    chargedSuffix: ' (charged)',
    solutionPrefix: 'Solution: {value}',
    partnerNotifiedSuffix: ' · partner notified',
    agentTaskSuffix: ' · agent task',
    acceptAndPay: 'Accept and pay success fee',
    reject: 'Reject',
    matchInputAria: 'Matched property ID (optional)',
    matchInputPlaceholder: 'Property ID (optional)',
    registerMatch: 'Register match',
    failSla: 'Fail (SLA)',
    emptyList: 'No move requests yet.',
    failReasonDefault: 'SLA not met.',
    messages: {
      activated: 'Smart Move active. Opening fee captured (sandbox). Pipeline in progress.',
      accepted: 'Solution accepted. Success fee charged via Kuteka Pay.',
      rejected: 'Solution rejected. Search resumed.',
      cancelled: 'Request cancelled. Opening fee refunded as credits.',
      matched: 'Match registered. Client notified.',
      failed: 'Request marked as failed. Urgency-based refund applied.',
    },
    loadError: 'We are having trouble showing your move requests. Try again.',
  },
  findHome: {
    eyebrow: 'Find a Home',
    title: 'Priority-assisted search',
    subtitle:
      'Share what you are looking for and Kuteka coordinates KAI and operators. There is a single priority fee via Kuteka Pay; exploring homes stays free.',
    exploreLink: 'Explore for free',
    newRequestTitle: 'New request',
    provinceLabel: 'Province',
    municipalityLabel: 'Municipality',
    provincePlaceholder: 'Luanda',
    municipalityPlaceholder: 'Belas',
    typologyLabel: 'Typology',
    budgetLabel: 'Maximum budget (Kz)',
    notesLabel: 'Preferences / notes',
    notesPlaceholder: 'Area, access, essential conditions…',
    submit: 'Activate priority search (sandbox)',
    requestsTitle: 'Requests',
    operatorBadge: 'Operator',
    budgetUpTo: 'Up to {amount}',
    budgetOpen: 'Open budget',
    priorityAmountSuffix: ' · priority {amount}',
    paidSuffix: ' · paid',
    matchPrefix: 'Match: {value}',
    acceptHome: 'Accept home',
    reject: 'Reject',
    matchInputAria: 'Matched property ID',
    matchInputPlaceholder: 'Property ID (optional)',
    registerMatch: 'Register match',
    failSla: 'Fail (SLA)',
    emptyList: 'No search requests yet.',
    failReasonDefault: 'SLA not met.',
    messages: {
      created: 'Priority search active. Fee charged via Kuteka Pay (sandbox).',
      accepted: 'Home accepted. Request completed with no extra fee.',
      rejected: 'Home rejected. Search resumed.',
      cancelled: 'Request cancelled. Full refund applied.',
      matched: 'Match registered. Client notified.',
      failed: 'Request failed. Full refund applied.',
    },
    loadError: 'We are having trouble showing your search requests. Try again.',
  },
  concierge: {
    eyebrow: 'Kuteka Concierge',
    title: 'Specialised help, whenever you need it',
    subtitle:
      'Explain your request and the Kuteka team follows through to completion. The single fee uses Kuteka Pay; cancelling before service starts refunds the full amount as credits.',
    providersLink: 'Providers',
    newRequestTitle: 'New request',
    categoryLabel: 'Category',
    notesLabel: 'How can we help?',
    notesPlaceholder: 'Describe the outcome you want, context and relevant deadlines…',
    propertyLabel: 'Property ID (optional)',
    propertyPlaceholder: 'Property UUID',
    contractLabel: 'Contract ID (optional)',
    contractPlaceholder: 'Contract UUID',
    submit: 'Request Concierge (sandbox)',
    requestsTitle: 'Requests',
    operatorBadge: 'Operator',
    feeAmount: 'Fee {amount}',
    feePending: 'Fee pending',
    paidSuffix: ' · Kuteka Pay',
    propertySuffix: ' · property {id}',
    contractSuffix: ' · contract {id}',
    operationPrefix: 'Operation: {value}',
    operatorNoteAria: 'Operator note',
    operatorNotePlaceholder: 'Operational note (optional)',
    start: 'Start',
    complete: 'Complete',
    markFail: 'Mark as failed',
    emptyList: 'No Concierge requests yet.',
    failReasonDefault: 'Service not completed.',
    messages: {
      created: 'Request active. Service fee charged via Kuteka Pay (sandbox).',
      cancelled: 'Request cancelled. Full refund applied as credits.',
      started: 'Service started.',
      completed: 'Service completed.',
      failed: 'Request failed. Full refund applied as credits.',
    },
    loadError: 'We are having trouble showing your Concierge requests. Try again.',
  },
  assistencia: {
    eyebrow: '24h Assistance',
    title: 'Urgent help for your property',
    subtitle:
      'Log the occurrence and the Kuteka team coordinates the assistance. The call costs around 5,000 Kz via Kuteka Pay; cancelling before it starts refunds 100% as credits.',
    providersLink: 'Providers',
    newRequestTitle: 'New urgent request',
    categoryLabel: 'Category',
    urgencyLabel: 'Urgency',
    notesLabel: 'What happened?',
    notesPlaceholder: 'Describe the problem, risks and directions to reach the location…',
    propertyLabel: 'Property ID (optional)',
    propertyPlaceholder: 'Property UUID',
    submit: 'Create request',
    requestsTitle: 'Assistance requests',
    operatorBadge: 'Operator',
    feeAmount: 'Fee {amount}',
    feeEstimate: 'Estimated fee 5,000 Kz',
    paidSuffix: ' · Kuteka Pay',
    propertySuffix: ' · property {id}',
    operationPrefix: 'Operation: {value}',
    payAndActivate: 'Pay and activate',
    operatorNoteAria: 'Operator note',
    operatorNotePlaceholder: 'Operational note (optional)',
    start: 'Start',
    complete: 'Complete',
    markFail: 'Mark as failed',
    emptyList: 'No assistance requests yet.',
    failReasonDefault: 'Assistance not completed.',
    messages: {
      created: 'Draft created. Confirm payment to activate the assistance.',
      activated: 'Request active. Fee charged via Kuteka Pay (sandbox).',
      cancelled: 'Request cancelled. Full refund applied once charged.',
      started: 'Assistance started.',
      completed: 'Assistance completed.',
      failed: 'Request marked as failed. Full refund applied.',
    },
    loadError: 'We are having trouble showing 24h Assistance. Try again.',
  },
  garantia: {
    eyebrow: 'Kuteka Guarantee',
    title: 'Optional monthly protection',
    subtitle:
      'Coverage for around 3,500 Kz/month, paid through the shared Kuteka Pay stack. Cancelling ends coverage; if cancelled the same day as activation, the monthly fee is fully refunded as credits.',
    newSubTitle: 'New subscription',
    newSubBody: 'Create the draft and optionally link a property or contract you have access to.',
    propertyLabel: 'Property ID (optional)',
    propertyPlaceholder: 'Property UUID',
    contractLabel: 'Contract ID (optional)',
    contractPlaceholder: 'Contract UUID',
    submit: 'Create draft',
    subscriptionsTitle: 'Subscriptions',
    operatorBadge: 'Finance',
    monthlyLabel: 'Monthly Guarantee',
    defaultAmount: '3,500 Kz/month',
    paidSuffix: ' · Kuteka Pay',
    propertySuffix: ' · property {id}',
    contractSuffix: ' · contract {id}',
    coveragePrefix: 'Coverage: ',
    activateAndPay: 'Activate and pay',
    reasonAria: 'Status reason',
    reasonPlaceholder: 'Reason (optional)',
    markPastDue: 'Past due',
    markFail: 'Mark as failed',
    emptyList: 'No Guarantee subscriptions yet.',
    messages: {
      created: 'Draft created. Activate when ready to pay.',
      activated: 'Guarantee active. Monthly fee charged via Kuteka Pay (sandbox).',
      cancelled: 'Guarantee cancelled. Refund applied when eligible.',
      pastDue: 'Subscription marked with payment past due.',
      failed: 'Subscription marked as failed.',
    },
    loadError: 'We are having trouble showing Guarantee subscriptions. Try again.',
  },
  marketplace: {
    eyebrow: 'Operational marketplace',
    title: 'Kuteka service network',
    subtitle:
      'Provider → quote → acceptance → execution → payment (Kuteka Pay) → rating. The commission stays in the Ledger (B2B take-rate — no escrow).',
    smartMoveLink: 'Smart Move',
    tabs: {
      providers: 'Providers',
      myOrders: 'My requests',
      inbox: 'Received requests',
    },
    providersPanel: {
      title: 'Active providers',
      hint: 'Filter by category and request a service.',
      categoryLabel: 'Category',
      slaLabel: 'SLA (hours)',
      titleLabel: 'Request title',
      titleDefault: 'Service request',
      serviceOfProvider: 'Service {name}',
      requestService: 'Request service',
      empty: 'No providers in this category.',
    },
    myOrdersPanel: {
      title: 'My requests',
      notePrefix: 'Note: {value}',
      acceptQuote: 'Accept quote',
      payWithKutekaPay: 'Pay with Kuteka Pay',
      ratingAria: 'Rating',
      rate: 'Rate',
      ratedLabel: 'Rated ★ {score}',
      empty: 'No requests yet.',
    },
    inboxPanel: {
      title: 'Received requests',
      hint: 'Send quotes, start and complete services. Demos can be operated by finance.manage.',
      amountAria: 'Quote amount (AOA)',
      amountPlaceholder: 'Amount AOA',
      sendQuote: 'Send quote',
      requote: 'Requote',
      startExecution: 'Start execution',
      completeService: 'Complete service',
      empty: 'No requests received.',
    },
    orderMeta: {
      noQuote: 'No quote',
      commissionSuffix: ' · commission {amount}',
      paidSuffix: ' · paid',
      ratingSuffix: ' · ★ {score}',
    },
    messages: {
      requestCreated: 'Request created. Awaiting provider quote.',
      quoteAccepted: 'Quote accepted.',
      paid: 'Payment processed via Kuteka Pay. Commission recorded in the Ledger.',
      rated: 'Rating recorded. Thank you!',
      cancelled: 'Request cancelled.',
      quoteSent: 'Quote sent to client.',
      started: 'Execution started.',
      completed: 'Service completed.',
    },
    loadError: 'We are having trouble showing the marketplace. Try again.',
  },
  partnerPlans: {
    eyebrow: 'Partner',
    title: 'Kuteka Partner Plans',
    subtitle:
      'Bronze, Silver and Gold — recurring B2B revenue. Sandbox payment until Multicaixa/EMIS.',
    patrimoniosLink: 'Properties',
    forbidden: 'Partner Plans require a Property Partner role or Super Admin.',
    chooseTitle: 'Choose a plan',
    active: 'Active',
    activateSandbox: 'Activate (sandbox)',
    subscriptionsTitle: 'Subscriptions',
    since: 'since {date}',
    renewsSuffix: ' · renews {date}',
    empty: 'No active plan yet.',
    messages: {
      activated: 'Plan activated (sandbox). Subscription {id}',
    },
  },
  catalog: {
    urgency: {
      planned_90: 'Planned (61–90 days)',
      priority_60: 'Priority (31–60 days)',
      urgent_30: 'Urgent (15–30 days)',
      emergency_14: 'Emergency (1–14 days)',
    },
    providerCategories: {
      all: 'All',
      cleaning: 'Cleaning',
      moving: 'Moving',
      painting: 'Painting',
      plumbing: 'Plumbing',
      electricity: 'Electricity',
      gardening: 'Gardening',
      security: 'Security',
      renovation: 'Renovation',
      internet: 'Internet',
      insurance: 'Insurance',
      other: 'Other',
    },
    orderStatus: {
      requested: 'Requested',
      quoted: 'Quoted',
      accepted: 'Accepted',
      in_progress: 'In progress',
      completed: 'Completed',
      cancelled: 'Cancelled',
      disputed: 'Disputed',
    },
    smartMoveStatus: {
      draft: 'Draft',
      awaiting_payment: 'Awaiting payment',
      active: 'Active',
      matched: 'Solution found',
      completed: 'Completed',
      cancelled: 'Cancelled',
      failed: 'Failed',
    },
    findHomeTypology: {
      t0: 'T0 / Studio',
      t1: 'T1',
      t2: 'T2',
      t3: 'T3',
      t4: 'T4',
      t5_plus: 'T5 or more',
      moradia: 'House',
      terreno: 'Land',
      comercial: 'Commercial',
      outro: 'Other',
    },
    findHomeTypologyNone: 'No typology',
    findHomeStatus: {
      draft: 'Draft',
      awaiting_payment: 'Awaiting payment',
      active: 'Active search',
      matched: 'Home found',
      completed: 'Completed',
      cancelled: 'Cancelled',
      failed: 'No solution',
    },
    conciergeCategory: {
      housing_guidance: 'Housing guidance',
      contract_support: 'Contract support',
      document_support: 'Document support',
      move_coordination: 'Move coordination',
      property_support: 'Property support',
      other: 'Other request',
    },
    conciergeStatus: {
      draft: 'Draft',
      awaiting_payment: 'Awaiting payment',
      active: 'Awaiting operator',
      in_progress: 'In service',
      completed: 'Completed',
      cancelled: 'Cancelled',
      failed: 'Failed',
    },
    garantiaStatus: {
      draft: 'Draft',
      awaiting_payment: 'Awaiting payment',
      active: 'Coverage active',
      cancelled: 'Cancelled',
      past_due: 'Payment past due',
      failed: 'Failed',
    },
    assistenciaCategory: {
      plumbing: 'Plumbing',
      electricity: 'Electricity',
      locksmith: 'Locks and keys',
      security: 'Security',
      water_damage: 'Water damage or flooding',
      gas: 'Gas',
      other: 'Other emergency',
    },
    assistenciaUrgency: {
      urgent: 'Urgent — within the next 24 hours',
      emergency: 'Emergency — immediate risk',
    },
    assistenciaStatus: {
      draft: 'Draft',
      awaiting_payment: 'Awaiting payment',
      active: 'Awaiting operator',
      in_progress: 'Assistance in progress',
      completed: 'Completed',
      cancelled: 'Cancelled',
      failed: 'Failed',
    },
    partnerPlanNames: {
      'partner.bronze.monthly': 'Bronze',
      'partner.silver.monthly': 'Silver',
      'partner.gold.monthly': 'Gold',
    },
    partnerPlanBlurbs: {
      'partner.bronze.monthly': 'Base visibility + priority leads.',
      'partner.silver.monthly': 'Explore highlight + advanced reports.',
      'partner.gold.monthly': 'Maximum exposure + commercial KAI + priority support.',
    },
  },
};
