import type { MonetizationCopy } from './pt';

/** Monetization suite copy — es. */
export const monetizationCopyEs: MonetizationCopy = {
  common: {
    actionError: 'No pudimos completar esta acción. Inténtelo de nuevo.',
    loadError: 'Estamos teniendo dificultades para mostrar estos datos. Inténtelo de nuevo.',
    cancel: 'Cancelar',
    viewTimeline: 'Ver cronología',
    hideTimeline: 'Ocultar cronología',
    noEvents: 'Sin eventos.',
    financeiro: 'Finanzas',
    slaBreached: 'SLA superado',
    slaAtLimit: 'SLA al límite',
    slaInHours: 'SLA en {hours}h',
    slaInDays: 'SLA en {days}d',
    reason: 'Motivo: {value}',
    kycRequiredHint:
      'Complete la verificación de identidad (KIS · KYC nivel 2+) en Perfil antes de continuar.',
  },
  smartMove: {
    eyebrow: 'Mudanza Inteligente',
    title: 'Búsqueda asistida por urgencia',
    subtitle:
      'Indique su fecha de salida, pague la tarifa de apertura (sandbox) y Kuteka activa un socio, agentes y KAI. La tarifa de éxito solo se cobra cuando acepta una solución. Explorar viviendas sigue siendo gratis.',
    providersLink: 'Red de prestadores',
    newRequestTitle: 'Nueva solicitud',
    urgencyLabel: 'Urgencia',
    contractLabel: 'Contrato (opcional)',
    noContractOption: 'Sin vínculo',
    notesLabel: 'Preferencias / notas',
    notesPlaceholder: 'Zona, tipología, presupuesto…',
    submit: 'Activar Mudanza Inteligente (sandbox)',
    requestsTitle: 'Solicitudes',
    operatorBadge: 'Operador (agente / finanzas)',
    openingAmount: 'Apertura {amount}',
    openingPending: 'Apertura pendiente',
    paidSuffix: ' · pagada',
    successAmountSuffix: ' · éxito {amount}',
    chargedSuffix: ' (cobrada)',
    solutionPrefix: 'Solución: {value}',
    partnerNotifiedSuffix: ' · socio notificado',
    agentTaskSuffix: ' · tarea de agente',
    acceptAndPay: 'Aceptar y pagar el éxito',
    reject: 'Rechazar',
    matchInputAria: 'ID del inmueble encontrado (opcional)',
    matchInputPlaceholder: 'ID del inmueble (opcional)',
    registerMatch: 'Registrar match',
    failSla: 'Fallar (SLA)',
    emptyList: 'Aún sin solicitudes de mudanza.',
    failReasonDefault: 'SLA no cumplido.',
    messages: {
      activated:
        'Mudanza Inteligente activa. Tarifa de apertura capturada (sandbox). Proceso en curso.',
      accepted: 'Solución aceptada. Tarifa de éxito cobrada vía Kuteka Pay.',
      rejected: 'Solución rechazada. Búsqueda reanudada.',
      cancelled: 'Solicitud cancelada. Apertura devuelta en créditos.',
      matched: 'Match registrado. Cliente notificado.',
      failed: 'Solicitud marcada como fallida. Reembolso por urgencia aplicado.',
    },
    loadError:
      'Estamos teniendo dificultades para mostrar las solicitudes de mudanza. Inténtelo de nuevo.',
  },
  findHome: {
    eyebrow: 'Encontrar Casa',
    title: 'Búsqueda prioritaria asistida',
    subtitle:
      'Comparta lo que busca y Kuteka coordina KAI y operadores. Hay una única tarifa de prioridad vía Kuteka Pay; explorar viviendas sigue siendo gratis.',
    exploreLink: 'Explorar gratis',
    newRequestTitle: 'Nueva solicitud',
    provinceLabel: 'Provincia',
    municipalityLabel: 'Municipio',
    provincePlaceholder: 'Luanda',
    municipalityPlaceholder: 'Belas',
    typologyLabel: 'Tipología',
    budgetLabel: 'Presupuesto máximo (Kz)',
    notesLabel: 'Preferencias / notas',
    notesPlaceholder: 'Zona, accesos, condiciones esenciales…',
    submit: 'Activar búsqueda prioritaria (sandbox)',
    requestsTitle: 'Solicitudes',
    operatorBadge: 'Operador',
    budgetUpTo: 'Hasta {amount}',
    budgetOpen: 'Presupuesto abierto',
    priorityAmountSuffix: ' · prioridad {amount}',
    paidSuffix: ' · pagada',
    matchPrefix: 'Match: {value}',
    acceptHome: 'Aceptar vivienda',
    reject: 'Rechazar',
    matchInputAria: 'ID del inmueble encontrado',
    matchInputPlaceholder: 'ID del inmueble (opcional)',
    registerMatch: 'Registrar match',
    failSla: 'Fallar (SLA)',
    emptyList: 'Aún sin solicitudes de búsqueda.',
    failReasonDefault: 'SLA no cumplido.',
    messages: {
      created: 'Búsqueda prioritaria activa. Tarifa cobrada vía Kuteka Pay (sandbox).',
      accepted: 'Vivienda aceptada. Solicitud completada sin tarifa adicional.',
      rejected: 'Vivienda rechazada. Búsqueda reanudada.',
      cancelled: 'Solicitud cancelada. Reembolso íntegro aplicado.',
      matched: 'Match registrado. Cliente notificado.',
      failed: 'Solicitud fallida. Reembolso íntegro aplicado.',
    },
    loadError:
      'Estamos teniendo dificultades para mostrar las solicitudes de búsqueda. Inténtelo de nuevo.',
  },
  concierge: {
    eyebrow: 'Concierge Kuteka',
    title: 'Ayuda especializada, cuando la necesita',
    subtitle:
      'Explique su solicitud y el equipo de Kuteka la acompaña hasta el final. La tarifa única usa Kuteka Pay; cancelar antes de la atención devuelve el importe íntegro en créditos.',
    providersLink: 'Prestadores',
    newRequestTitle: 'Nueva solicitud',
    categoryLabel: 'Categoría',
    notesLabel: '¿Cómo podemos ayudar?',
    notesPlaceholder: 'Describa el resultado que desea, el contexto y los plazos relevantes…',
    propertyLabel: 'ID del inmueble (opcional)',
    propertyPlaceholder: 'UUID del inmueble',
    contractLabel: 'ID del contrato (opcional)',
    contractPlaceholder: 'UUID del contrato',
    submit: 'Solicitar Concierge (sandbox)',
    requestsTitle: 'Solicitudes',
    operatorBadge: 'Operador',
    feeAmount: 'Tarifa {amount}',
    feePending: 'Tarifa pendiente',
    paidSuffix: ' · Kuteka Pay',
    propertySuffix: ' · inmueble {id}',
    contractSuffix: ' · contrato {id}',
    operationPrefix: 'Operación: {value}',
    operatorNoteAria: 'Nota del operador',
    operatorNotePlaceholder: 'Nota operativa (opcional)',
    start: 'Iniciar',
    complete: 'Concluir',
    markFail: 'Marcar como fallida',
    emptyList: 'Aún sin solicitudes Concierge.',
    failReasonDefault: 'Servicio no concluido.',
    messages: {
      created: 'Solicitud activa. Tarifa de servicio cobrada vía Kuteka Pay (sandbox).',
      cancelled: 'Solicitud cancelada. Reembolso íntegro aplicado en créditos.',
      started: 'Atención iniciada.',
      completed: 'Atención concluida.',
      failed: 'Solicitud fallida. Reembolso íntegro aplicado en créditos.',
    },
    loadError:
      'Estamos teniendo dificultades para mostrar las solicitudes Concierge. Inténtelo de nuevo.',
  },
  assistencia: {
    eyebrow: 'Asistencia 24h',
    title: 'Ayuda urgente para su inmueble',
    subtitle:
      'Registre la incidencia y el equipo de Kuteka coordina la asistencia. La llamada cuesta unos 5.000 Kz vía Kuteka Pay; la cancelación antes del inicio devuelve el 100% en créditos.',
    providersLink: 'Prestadores',
    newRequestTitle: 'Nueva solicitud urgente',
    categoryLabel: 'Categoría',
    urgencyLabel: 'Urgencia',
    notesLabel: '¿Qué ocurrió?',
    notesPlaceholder: 'Describa el problema, los riesgos e indicaciones para llegar al lugar…',
    propertyLabel: 'ID del inmueble (opcional)',
    propertyPlaceholder: 'UUID del inmueble',
    submit: 'Crear solicitud',
    requestsTitle: 'Solicitudes de asistencia',
    operatorBadge: 'Operador',
    feeAmount: 'Tarifa {amount}',
    feeEstimate: 'Tarifa estimada 5.000 Kz',
    paidSuffix: ' · Kuteka Pay',
    propertySuffix: ' · inmueble {id}',
    operationPrefix: 'Operación: {value}',
    payAndActivate: 'Pagar y activar',
    operatorNoteAria: 'Nota del operador',
    operatorNotePlaceholder: 'Nota operativa (opcional)',
    start: 'Iniciar',
    complete: 'Concluir',
    markFail: 'Marcar como fallida',
    emptyList: 'Aún sin solicitudes de asistencia.',
    failReasonDefault: 'Asistencia no concluida.',
    messages: {
      created: 'Borrador creado. Confirme el pago para activar la asistencia.',
      activated: 'Solicitud activa. Tarifa cobrada vía Kuteka Pay (sandbox).',
      cancelled: 'Solicitud cancelada. Reembolso íntegro aplicado una vez cobrado.',
      started: 'Asistencia iniciada.',
      completed: 'Asistencia concluida.',
      failed: 'Solicitud marcada como fallida. Reembolso íntegro aplicado.',
    },
    loadError: 'Estamos teniendo dificultades para mostrar la Asistencia 24h. Inténtelo de nuevo.',
  },
  garantia: {
    eyebrow: 'Garantía Kuteka',
    title: 'Protección mensual opcional',
    subtitle:
      'Cobertura de unos 3.500 Kz/mes, pagada a través de la pila compartida Kuteka Pay. La cancelación termina la cobertura; si se cancela el mismo día de la activación, la mensualidad se devuelve íntegramente en créditos.',
    newSubTitle: 'Nueva suscripción',
    newSubBody:
      'Cree el borrador y asocie, si lo desea, un inmueble o contrato al que tenga acceso.',
    propertyLabel: 'ID del inmueble (opcional)',
    propertyPlaceholder: 'UUID del inmueble',
    contractLabel: 'ID del contrato (opcional)',
    contractPlaceholder: 'UUID del contrato',
    submit: 'Crear borrador',
    subscriptionsTitle: 'Suscripciones',
    operatorBadge: 'Finanzas',
    monthlyLabel: 'Garantía mensual',
    defaultAmount: '3.500 Kz/mes',
    paidSuffix: ' · Kuteka Pay',
    propertySuffix: ' · inmueble {id}',
    contractSuffix: ' · contrato {id}',
    coveragePrefix: 'Cobertura: ',
    activateAndPay: 'Activar y pagar',
    reasonAria: 'Motivo del estado',
    reasonPlaceholder: 'Motivo (opcional)',
    markPastDue: 'En mora',
    markFail: 'Marcar como fallida',
    emptyList: 'Aún sin suscripciones Garantía.',
    messages: {
      created: 'Borrador creado. Actívelo cuando esté listo para pagar.',
      activated: 'Garantía activa. Mensualidad cobrada vía Kuteka Pay (sandbox).',
      cancelled: 'Garantía cancelada. El reembolso se aplica cuando sea elegible.',
      pastDue: 'Suscripción marcada con pago en mora.',
      failed: 'Suscripción marcada como fallida.',
    },
    loadError:
      'Estamos teniendo dificultades para mostrar las suscripciones Garantía. Inténtelo de nuevo.',
  },
  marketplace: {
    eyebrow: 'Marketplace operativo',
    title: 'Red de servicios Kuteka',
    subtitle:
      'Prestador → presupuesto → aceptación → ejecución → pago (Kuteka Pay) → evaluación. La comisión queda en el Ledger (take-rate B2B — sin depósito en garantía).',
    smartMoveLink: 'Mudanza Inteligente',
    tabs: {
      providers: 'Prestadores',
      myOrders: 'Mis solicitudes',
      inbox: 'Solicitudes recibidas',
    },
    providersPanel: {
      title: 'Prestadores activos',
      hint: 'Filtre por categoría y solicite un servicio.',
      categoryLabel: 'Categoría',
      slaLabel: 'SLA (horas)',
      titleLabel: 'Título de la solicitud',
      titleDefault: 'Solicitud de servicio',
      serviceOfProvider: 'Servicio {name}',
      requestService: 'Solicitar servicio',
      empty: 'Sin prestadores en esta categoría.',
    },
    myOrdersPanel: {
      title: 'Mis solicitudes',
      notePrefix: 'Nota: {value}',
      acceptQuote: 'Aceptar presupuesto',
      payWithKutekaPay: 'Pagar con Kuteka Pay',
      ratingAria: 'Valoración',
      rate: 'Valorar',
      ratedLabel: 'Valorado ★ {score}',
      empty: 'Aún sin solicitudes.',
    },
    inboxPanel: {
      title: 'Solicitudes recibidas',
      hint: 'Envíe presupuestos, inicie y concluya servicios. Las demos pueden ser operadas por finance.manage.',
      amountAria: 'Importe del presupuesto (AOA)',
      amountPlaceholder: 'Importe AOA',
      sendQuote: 'Enviar presupuesto',
      requote: 'Represupuestar',
      startExecution: 'Iniciar ejecución',
      completeService: 'Concluir servicio',
      empty: 'Sin solicitudes recibidas.',
    },
    orderMeta: {
      noQuote: 'Sin presupuesto',
      commissionSuffix: ' · comisión {amount}',
      paidSuffix: ' · pagado',
      ratingSuffix: ' · ★ {score}',
    },
    messages: {
      requestCreated: 'Solicitud creada. Esperando presupuesto del prestador.',
      quoteAccepted: 'Presupuesto aceptado.',
      paid: 'Pago procesado vía Kuteka Pay. Comisión registrada en el Ledger.',
      rated: '¡Valoración registrada. Gracias!',
      cancelled: 'Solicitud cancelada.',
      quoteSent: 'Presupuesto enviado al cliente.',
      started: 'Ejecución iniciada.',
      completed: 'Servicio concluido.',
    },
    loadError: 'Estamos teniendo dificultades para mostrar el marketplace. Inténtelo de nuevo.',
  },
  partnerPlans: {
    eyebrow: 'Socio',
    title: 'Planes Socio Kuteka',
    subtitle:
      'Bronze, Silver y Gold — ingresos B2B recurrentes. Pago sandbox hasta Multicaixa/EMIS.',
    patrimoniosLink: 'Patrimonios',
    forbidden: 'Los Planes Socio requieren un rol de Socio Patrimonial o Super Admin.',
    chooseTitle: 'Elegir plan',
    active: 'Activo',
    activateSandbox: 'Activar (sandbox)',
    subscriptionsTitle: 'Suscripciones',
    since: 'desde {date}',
    renewsSuffix: ' · renueva {date}',
    empty: 'Aún sin plan activo.',
    messages: {
      activated: 'Plan activado (sandbox). Suscripción {id}',
    },
  },
  catalog: {
    urgency: {
      planned_90: 'Planificada (61–90 días)',
      priority_60: 'Prioritaria (31–60 días)',
      urgent_30: 'Urgente (15–30 días)',
      emergency_14: 'Emergencia (1–14 días)',
    },
    providerCategories: {
      all: 'Todas',
      cleaning: 'Limpieza',
      moving: 'Mudanzas',
      painting: 'Pintura',
      plumbing: 'Fontanería',
      electricity: 'Electricidad',
      gardening: 'Jardinería',
      security: 'Seguridad',
      renovation: 'Remodelación',
      internet: 'Internet',
      insurance: 'Seguros',
      other: 'Otros',
    },
    orderStatus: {
      requested: 'Solicitado',
      quoted: 'Presupuestado',
      accepted: 'Aceptado',
      in_progress: 'En ejecución',
      completed: 'Concluido',
      cancelled: 'Cancelado',
      disputed: 'En disputa',
    },
    smartMoveStatus: {
      draft: 'Borrador',
      awaiting_payment: 'Esperando pago',
      active: 'Activo',
      matched: 'Solución encontrada',
      completed: 'Concluido',
      cancelled: 'Cancelado',
      failed: 'Fallido',
    },
    findHomeTypology: {
      t0: 'T0 / Estudio',
      t1: 'T1',
      t2: 'T2',
      t3: 'T3',
      t4: 'T4',
      t5_plus: 'T5 o más',
      moradia: 'Casa',
      terreno: 'Terreno',
      comercial: 'Comercial',
      outro: 'Otro',
    },
    findHomeTypologyNone: 'Sin tipología',
    findHomeStatus: {
      draft: 'Borrador',
      awaiting_payment: 'Esperando pago',
      active: 'Búsqueda activa',
      matched: 'Vivienda encontrada',
      completed: 'Concluido',
      cancelled: 'Cancelado',
      failed: 'Sin solución',
    },
    conciergeCategory: {
      housing_guidance: 'Orientación habitacional',
      contract_support: 'Apoyo con contrato',
      document_support: 'Apoyo documental',
      move_coordination: 'Coordinación de mudanza',
      property_support: 'Apoyo con el inmueble',
      other: 'Otra solicitud',
    },
    conciergeStatus: {
      draft: 'Borrador',
      awaiting_payment: 'Esperando pago',
      active: 'Esperando operador',
      in_progress: 'En atención',
      completed: 'Concluido',
      cancelled: 'Cancelado',
      failed: 'Fallido',
    },
    garantiaStatus: {
      draft: 'Borrador',
      awaiting_payment: 'Esperando pago',
      active: 'Cobertura activa',
      cancelled: 'Cancelada',
      past_due: 'Pago en mora',
      failed: 'Fallida',
    },
    assistenciaCategory: {
      plumbing: 'Fontanería',
      electricity: 'Electricidad',
      locksmith: 'Cerraduras y llaves',
      security: 'Seguridad',
      water_damage: 'Filtración o inundación',
      gas: 'Gas',
      other: 'Otra emergencia',
    },
    assistenciaUrgency: {
      urgent: 'Urgente — en las próximas 24 horas',
      emergency: 'Emergencia — riesgo inmediato',
    },
    assistenciaStatus: {
      draft: 'Borrador',
      awaiting_payment: 'Esperando pago',
      active: 'Esperando operador',
      in_progress: 'Asistencia en curso',
      completed: 'Concluida',
      cancelled: 'Cancelada',
      failed: 'Fallida',
    },
    partnerPlanNames: {
      'partner.bronze.monthly': 'Bronze',
      'partner.silver.monthly': 'Silver',
      'partner.gold.monthly': 'Gold',
    },
    partnerPlanBlurbs: {
      'partner.bronze.monthly': 'Visibilidad base + leads prioritarios.',
      'partner.silver.monthly': 'Destaque en explorar + informes avanzados.',
      'partner.gold.monthly': 'Máxima exposición + KAI comercial + soporte prioritario.',
    },
  },
};
