import type { MonetizationCopy } from './pt';

/** Monetization suite copy — fr. */
export const monetizationCopyFr: MonetizationCopy = {
  common: {
    actionError: 'Nous n’avons pas pu terminer cette action. Réessayez.',
    loadError: 'Nous avons du mal à afficher ces données. Réessayez.',
    cancel: 'Annuler',
    viewTimeline: 'Voir la chronologie',
    hideTimeline: 'Masquer la chronologie',
    noEvents: 'Aucun événement.',
    financeiro: 'Finance',
    slaBreached: 'SLA dépassé',
    slaAtLimit: 'SLA à la limite',
    slaInHours: 'SLA dans {hours}h',
    slaInDays: 'SLA dans {days}j',
    reason: 'Motif : {value}',
    kycRequiredHint:
      'Complétez la vérification d’identité (KIS · KYC niveau 2+) dans Profil avant de continuer.',
  },
  smartMove: {
    eyebrow: 'Déménagement intelligent',
    title: 'Recherche assistée par urgence',
    subtitle:
      'Indiquez votre date de sortie, payez les frais d’ouverture (sandbox) et Kuteka active un partenaire, des agents et KAI. Les frais de succès ne sont facturés que lorsque vous acceptez une solution. Explorer les logements reste gratuit.',
    providersLink: 'Réseau de prestataires',
    newRequestTitle: 'Nouvelle demande',
    urgencyLabel: 'Urgence',
    contractLabel: 'Contrat (facultatif)',
    noContractOption: 'Sans lien',
    notesLabel: 'Préférences / notes',
    notesPlaceholder: 'Zone, typologie, budget…',
    submit: 'Activer le Déménagement intelligent (sandbox)',
    requestsTitle: 'Demandes',
    operatorBadge: 'Opérateur (agent / finance)',
    openingAmount: 'Ouverture {amount}',
    openingPending: 'Ouverture en attente',
    paidSuffix: ' · payée',
    successAmountSuffix: ' · succès {amount}',
    chargedSuffix: ' (facturée)',
    solutionPrefix: 'Solution : {value}',
    partnerNotifiedSuffix: ' · partenaire notifié',
    agentTaskSuffix: ' · tâche agent',
    acceptAndPay: 'Accepter et payer le succès',
    reject: 'Refuser',
    matchInputAria: 'ID du bien trouvé (facultatif)',
    matchInputPlaceholder: 'ID du bien (facultatif)',
    registerMatch: 'Enregistrer le match',
    failSla: 'Échouer (SLA)',
    emptyList: 'Pas encore de demandes de déménagement.',
    failReasonDefault: 'SLA non respecté.',
    messages: {
      activated:
        'Déménagement intelligent actif. Frais d’ouverture capturés (sandbox). Pipeline en cours.',
      accepted: 'Solution acceptée. Frais de succès facturés via Kuteka Pay.',
      rejected: 'Solution refusée. Recherche reprise.',
      cancelled: 'Demande annulée. Ouverture remboursée en crédits.',
      matched: 'Match enregistré. Client notifié.',
      failed: 'Demande marquée comme échouée. Remboursement selon l’urgence appliqué.',
    },
    loadError: 'Nous avons du mal à afficher les demandes de déménagement. Réessayez.',
  },
  findHome: {
    eyebrow: 'Trouver un logement',
    title: 'Recherche prioritaire assistée',
    subtitle:
      'Indiquez ce que vous recherchez et Kuteka coordonne KAI et les opérateurs. Il y a des frais de priorité uniques via Kuteka Pay ; explorer les logements reste gratuit.',
    exploreLink: 'Explorer gratuitement',
    newRequestTitle: 'Nouvelle demande',
    provinceLabel: 'Province',
    municipalityLabel: 'Municipalité',
    provincePlaceholder: 'Luanda',
    municipalityPlaceholder: 'Belas',
    typologyLabel: 'Typologie',
    budgetLabel: 'Budget maximum (Kz)',
    notesLabel: 'Préférences / notes',
    notesPlaceholder: 'Zone, accès, conditions essentielles…',
    submit: 'Activer la recherche prioritaire (sandbox)',
    requestsTitle: 'Demandes',
    operatorBadge: 'Opérateur',
    budgetUpTo: 'Jusqu’à {amount}',
    budgetOpen: 'Budget ouvert',
    priorityAmountSuffix: ' · priorité {amount}',
    paidSuffix: ' · payée',
    matchPrefix: 'Match : {value}',
    acceptHome: 'Accepter le logement',
    reject: 'Refuser',
    matchInputAria: 'ID du bien trouvé',
    matchInputPlaceholder: 'ID du bien (facultatif)',
    registerMatch: 'Enregistrer le match',
    failSla: 'Échouer (SLA)',
    emptyList: 'Pas encore de demandes de recherche.',
    failReasonDefault: 'SLA non respecté.',
    messages: {
      created: 'Recherche prioritaire active. Frais facturés via Kuteka Pay (sandbox).',
      accepted: 'Logement accepté. Demande terminée sans frais supplémentaires.',
      rejected: 'Logement refusé. Recherche reprise.',
      cancelled: 'Demande annulée. Remboursement intégral appliqué.',
      matched: 'Match enregistré. Client notifié.',
      failed: 'Demande échouée. Remboursement intégral appliqué.',
    },
    loadError: 'Nous avons du mal à afficher les demandes de recherche. Réessayez.',
  },
  concierge: {
    eyebrow: 'Concierge Kuteka',
    title: 'Une aide spécialisée, quand vous en avez besoin',
    subtitle:
      'Expliquez votre demande et l’équipe Kuteka vous accompagne jusqu’à la fin. Les frais uniques passent par Kuteka Pay ; annuler avant le service rembourse la totalité en crédits.',
    providersLink: 'Prestataires',
    newRequestTitle: 'Nouvelle demande',
    categoryLabel: 'Catégorie',
    notesLabel: 'Comment pouvons-nous aider ?',
    notesPlaceholder: 'Décrivez le résultat souhaité, le contexte et les délais pertinents…',
    propertyLabel: 'ID du bien (facultatif)',
    propertyPlaceholder: 'UUID du bien',
    contractLabel: 'ID du contrat (facultatif)',
    contractPlaceholder: 'UUID du contrat',
    submit: 'Demander Concierge (sandbox)',
    requestsTitle: 'Demandes',
    operatorBadge: 'Opérateur',
    feeAmount: 'Frais {amount}',
    feePending: 'Frais en attente',
    paidSuffix: ' · Kuteka Pay',
    propertySuffix: ' · bien {id}',
    contractSuffix: ' · contrat {id}',
    operationPrefix: 'Opération : {value}',
    operatorNoteAria: 'Note de l’opérateur',
    operatorNotePlaceholder: 'Note opérationnelle (facultatif)',
    start: 'Démarrer',
    complete: 'Terminer',
    markFail: 'Marquer comme échoué',
    emptyList: 'Pas encore de demandes Concierge.',
    failReasonDefault: 'Service non terminé.',
    messages: {
      created: 'Demande active. Frais de service facturés via Kuteka Pay (sandbox).',
      cancelled: 'Demande annulée. Remboursement intégral appliqué en crédits.',
      started: 'Service démarré.',
      completed: 'Service terminé.',
      failed: 'Demande échouée. Remboursement intégral appliqué en crédits.',
    },
    loadError: 'Nous avons du mal à afficher les demandes Concierge. Réessayez.',
  },
  assistencia: {
    eyebrow: 'Assistance 24h',
    title: 'Aide urgente pour votre bien',
    subtitle:
      'Signalez l’incident et l’équipe Kuteka coordonne l’assistance. L’appel coûte environ 5 000 Kz via Kuteka Pay ; l’annulation avant le début rembourse 100 % en crédits.',
    providersLink: 'Prestataires',
    newRequestTitle: 'Nouvelle demande urgente',
    categoryLabel: 'Catégorie',
    urgencyLabel: 'Urgence',
    notesLabel: 'Que s’est-il passé ?',
    notesPlaceholder: 'Décrivez le problème, les risques et l’itinéraire pour accéder au lieu…',
    propertyLabel: 'ID du bien (facultatif)',
    propertyPlaceholder: 'UUID du bien',
    submit: 'Créer la demande',
    requestsTitle: 'Demandes d’assistance',
    operatorBadge: 'Opérateur',
    feeAmount: 'Frais {amount}',
    feeEstimate: 'Frais estimés 5 000 Kz',
    paidSuffix: ' · Kuteka Pay',
    propertySuffix: ' · bien {id}',
    operationPrefix: 'Opération : {value}',
    payAndActivate: 'Payer et activer',
    operatorNoteAria: 'Note de l’opérateur',
    operatorNotePlaceholder: 'Note opérationnelle (facultatif)',
    start: 'Démarrer',
    complete: 'Terminer',
    markFail: 'Marquer comme échoué',
    emptyList: 'Pas encore de demandes d’assistance.',
    failReasonDefault: 'Assistance non terminée.',
    messages: {
      created: 'Brouillon créé. Confirmez le paiement pour activer l’assistance.',
      activated: 'Demande active. Frais facturés via Kuteka Pay (sandbox).',
      cancelled: 'Demande annulée. Remboursement intégral appliqué une fois facturé.',
      started: 'Assistance démarrée.',
      completed: 'Assistance terminée.',
      failed: 'Demande marquée comme échouée. Remboursement intégral appliqué.',
    },
    loadError: 'Nous avons du mal à afficher l’Assistance 24h. Réessayez.',
  },
  garantia: {
    eyebrow: 'Garantie Kuteka',
    title: 'Protection mensuelle facultative',
    subtitle:
      'Couverture d’environ 3 500 Kz/mois, payée via la stack Kuteka Pay partagée. L’annulation met fin à la couverture ; si annulée le jour même de l’activation, la mensualité est intégralement remboursée en crédits.',
    newSubTitle: 'Nouvel abonnement',
    newSubBody:
      'Créez le brouillon et associez, si vous le souhaitez, un bien ou un contrat auquel vous avez accès.',
    propertyLabel: 'ID du bien (facultatif)',
    propertyPlaceholder: 'UUID du bien',
    contractLabel: 'ID du contrat (facultatif)',
    contractPlaceholder: 'UUID du contrat',
    submit: 'Créer le brouillon',
    subscriptionsTitle: 'Abonnements',
    operatorBadge: 'Finance',
    monthlyLabel: 'Garantie mensuelle',
    defaultAmount: '3 500 Kz/mois',
    paidSuffix: ' · Kuteka Pay',
    propertySuffix: ' · bien {id}',
    contractSuffix: ' · contrat {id}',
    coveragePrefix: 'Couverture : ',
    activateAndPay: 'Activer et payer',
    reasonAria: 'Motif du statut',
    reasonPlaceholder: 'Motif (facultatif)',
    markPastDue: 'En retard',
    markFail: 'Marquer comme échoué',
    emptyList: 'Pas encore d’abonnements Garantie.',
    messages: {
      created: 'Brouillon créé. Activez quand vous êtes prêt à payer.',
      activated: 'Garantie active. Mensualité facturée via Kuteka Pay (sandbox).',
      cancelled: 'Garantie annulée. Le remboursement est appliqué si éligible.',
      pastDue: 'Abonnement marqué avec paiement en retard.',
      failed: 'Abonnement marqué comme échoué.',
    },
    loadError: 'Nous avons du mal à afficher les abonnements Garantie. Réessayez.',
  },
  marketplace: {
    eyebrow: 'Marketplace opérationnel',
    title: 'Réseau de services Kuteka',
    subtitle:
      'Prestataire → devis → acceptation → exécution → paiement (Kuteka Pay) → évaluation. La commission reste dans le Ledger (take-rate B2B — sans séquestre).',
    smartMoveLink: 'Déménagement intelligent',
    tabs: {
      providers: 'Prestataires',
      myOrders: 'Mes demandes',
      inbox: 'Demandes reçues',
    },
    providersPanel: {
      title: 'Prestataires actifs',
      hint: 'Filtrez par catégorie et demandez un service.',
      categoryLabel: 'Catégorie',
      slaLabel: 'SLA (heures)',
      titleLabel: 'Titre de la demande',
      titleDefault: 'Demande de service',
      serviceOfProvider: 'Service {name}',
      requestService: 'Demander un service',
      empty: 'Aucun prestataire dans cette catégorie.',
    },
    myOrdersPanel: {
      title: 'Mes demandes',
      notePrefix: 'Note : {value}',
      acceptQuote: 'Accepter le devis',
      payWithKutekaPay: 'Payer avec Kuteka Pay',
      ratingAria: 'Évaluation',
      rate: 'Évaluer',
      ratedLabel: 'Évalué ★ {score}',
      empty: 'Pas encore de demandes.',
    },
    inboxPanel: {
      title: 'Demandes reçues',
      hint: 'Envoyez des devis, démarrez et terminez des services. Les démos peuvent être gérées par finance.manage.',
      amountAria: 'Montant du devis (AOA)',
      amountPlaceholder: 'Montant AOA',
      sendQuote: 'Envoyer le devis',
      requote: 'Refaire le devis',
      startExecution: 'Démarrer l’exécution',
      completeService: 'Terminer le service',
      empty: 'Aucune demande reçue.',
    },
    orderMeta: {
      noQuote: 'Sans devis',
      commissionSuffix: ' · commission {amount}',
      paidSuffix: ' · payé',
      ratingSuffix: ' · ★ {score}',
    },
    messages: {
      requestCreated: 'Demande créée. En attente du devis du prestataire.',
      quoteAccepted: 'Devis accepté.',
      paid: 'Paiement traité via Kuteka Pay. Commission enregistrée dans le Ledger.',
      rated: 'Évaluation enregistrée. Merci !',
      cancelled: 'Demande annulée.',
      quoteSent: 'Devis envoyé au client.',
      started: 'Exécution démarrée.',
      completed: 'Service terminé.',
    },
    loadError: 'Nous avons du mal à afficher le marketplace. Réessayez.',
  },
  partnerPlans: {
    eyebrow: 'Partenaire',
    title: 'Plans Partenaire Kuteka',
    subtitle:
      'Bronze, Silver et Gold — revenu B2B récurrent. Paiement sandbox jusqu’à Multicaixa/EMIS.',
    patrimoniosLink: 'Patrimoines',
    forbidden: 'Les Plans Partenaire nécessitent un rôle de Partenaire Patrimonial ou Super Admin.',
    chooseTitle: 'Choisir un plan',
    active: 'Actif',
    activateSandbox: 'Activer (sandbox)',
    subscriptionsTitle: 'Abonnements',
    since: 'depuis {date}',
    renewsSuffix: ' · renouvelle {date}',
    empty: 'Aucun plan actif pour le moment.',
    messages: {
      activated: 'Plan activé (sandbox). Abonnement {id}',
    },
  },
  catalog: {
    urgency: {
      planned_90: 'Planifiée (61–90 jours)',
      priority_60: 'Prioritaire (31–60 jours)',
      urgent_30: 'Urgente (15–30 jours)',
      emergency_14: 'Urgence (1–14 jours)',
    },
    providerCategories: {
      all: 'Toutes',
      cleaning: 'Nettoyage',
      moving: 'Déménagements',
      painting: 'Peinture',
      plumbing: 'Plomberie',
      electricity: 'Électricité',
      gardening: 'Jardinage',
      security: 'Sécurité',
      renovation: 'Rénovation',
      internet: 'Internet',
      insurance: 'Assurances',
      other: 'Autres',
    },
    orderStatus: {
      requested: 'Demandé',
      quoted: 'Devis reçu',
      accepted: 'Accepté',
      in_progress: 'En cours',
      completed: 'Terminé',
      cancelled: 'Annulé',
      disputed: 'En litige',
    },
    smartMoveStatus: {
      draft: 'Brouillon',
      awaiting_payment: 'En attente de paiement',
      active: 'Actif',
      matched: 'Solution trouvée',
      completed: 'Terminé',
      cancelled: 'Annulé',
      failed: 'Échoué',
    },
    findHomeTypology: {
      t0: 'T0 / Studio',
      t1: 'T1',
      t2: 'T2',
      t3: 'T3',
      t4: 'T4',
      t5_plus: 'T5 ou plus',
      moradia: 'Maison',
      terreno: 'Terrain',
      comercial: 'Commercial',
      outro: 'Autre',
    },
    findHomeTypologyNone: 'Sans typologie',
    findHomeStatus: {
      draft: 'Brouillon',
      awaiting_payment: 'En attente de paiement',
      active: 'Recherche active',
      matched: 'Logement trouvé',
      completed: 'Terminé',
      cancelled: 'Annulé',
      failed: 'Sans solution',
    },
    conciergeCategory: {
      housing_guidance: 'Orientation logement',
      contract_support: 'Aide contrat',
      document_support: 'Aide documentaire',
      move_coordination: 'Coordination de déménagement',
      property_support: 'Aide bien immobilier',
      other: 'Autre demande',
    },
    conciergeStatus: {
      draft: 'Brouillon',
      awaiting_payment: 'En attente de paiement',
      active: 'En attente d’opérateur',
      in_progress: 'En cours de traitement',
      completed: 'Terminé',
      cancelled: 'Annulé',
      failed: 'Échoué',
    },
    garantiaStatus: {
      draft: 'Brouillon',
      awaiting_payment: 'En attente de paiement',
      active: 'Couverture active',
      cancelled: 'Annulée',
      past_due: 'Paiement en retard',
      failed: 'Échouée',
    },
    assistenciaCategory: {
      plumbing: 'Plomberie',
      electricity: 'Électricité',
      locksmith: 'Serrures et clés',
      security: 'Sécurité',
      water_damage: 'Infiltration ou inondation',
      gas: 'Gaz',
      other: 'Autre urgence',
    },
    assistenciaUrgency: {
      urgent: 'Urgent — dans les prochaines 24 heures',
      emergency: 'Urgence — risque immédiat',
    },
    assistenciaStatus: {
      draft: 'Brouillon',
      awaiting_payment: 'En attente de paiement',
      active: 'En attente d’opérateur',
      in_progress: 'Assistance en cours',
      completed: 'Terminée',
      cancelled: 'Annulée',
      failed: 'Échouée',
    },
    partnerPlanNames: {
      'partner.bronze.monthly': 'Bronze',
      'partner.silver.monthly': 'Silver',
      'partner.gold.monthly': 'Gold',
    },
    partnerPlanBlurbs: {
      'partner.bronze.monthly': 'Visibilité de base + leads prioritaires.',
      'partner.silver.monthly': 'Mise en avant dans explorer + rapports avancés.',
      'partner.gold.monthly': 'Exposition maximale + KAI commercial + support prioritaire.',
    },
  },
};
