/** Monetization suite copy — pt-AO. Covers Smart Move, Find Home, Concierge, */
/** Assistência 24h, Garantia, Marketplace and Partner Plans. */
export const monetizationCopyPt = {
  common: {
    actionError: 'Não conseguimos concluir esta acção. Tente novamente.',
    loadError: 'Estamos a ter dificuldade em mostrar estes dados. Tente novamente.',
    cancel: 'Cancelar',
    viewTimeline: 'Ver cronologia',
    hideTimeline: 'Ocultar cronologia',
    noEvents: 'Sem eventos.',
    financeiro: 'Financeiro',
    slaBreached: 'SLA ultrapassado',
    slaAtLimit: 'SLA no limite',
    slaInHours: 'SLA em {hours}h',
    slaInDays: 'SLA em {days}d',
    reason: 'Motivo: {value}',
    kycRequiredHint:
      'Complete a verificação de identidade (KIS · KYC nível 2+) em Perfil antes de continuar.',
  },
  smartMove: {
    eyebrow: 'Mudança Inteligente',
    title: 'Procura assistida por urgência',
    subtitle:
      'Informe a saída, pague a taxa de abertura (sandbox) e a Kuteka activa parceiro, agentes e KAI. A taxa de sucesso só é cobrada quando aceita uma solução. Explorar casas continua gratuito.',
    providersLink: 'Rede de prestadores',
    newRequestTitle: 'Novo pedido',
    urgencyLabel: 'Urgência',
    contractLabel: 'Contrato (opcional)',
    noContractOption: 'Sem vínculo',
    notesLabel: 'Preferências / notas',
    notesPlaceholder: 'Zona, tipologia, orçamento…',
    submit: 'Activar Mudança Inteligente (sandbox)',
    requestsTitle: 'Pedidos',
    operatorBadge: 'Operador (agente / finance)',
    openingAmount: 'Abertura {amount}',
    openingPending: 'Abertura pendente',
    paidSuffix: ' · paga',
    successAmountSuffix: ' · sucesso {amount}',
    chargedSuffix: ' (cobrada)',
    solutionPrefix: 'Solução: {value}',
    partnerNotifiedSuffix: ' · parceiro notificado',
    agentTaskSuffix: ' · tarefa agente',
    acceptAndPay: 'Aceitar e pagar sucesso',
    reject: 'Recusar',
    matchInputAria: 'ID do imóvel encontrado (opcional)',
    matchInputPlaceholder: 'ID do imóvel (opcional)',
    registerMatch: 'Registar match',
    failSla: 'Falhar (SLA)',
    emptyList: 'Ainda sem pedidos de mudança.',
    failReasonDefault: 'SLA não cumprido.',
    messages: {
      activated:
        'Mudança Inteligente activa. Taxa de abertura capturada (sandbox). Pipeline em curso.',
      accepted: 'Solução aceite. Taxa de sucesso cobrada via Kuteka Pay.',
      rejected: 'Solução recusada. Procura retomada.',
      cancelled: 'Pedido cancelado. Abertura devolvida em créditos.',
      matched: 'Match registado. Cliente notificado.',
      failed: 'Pedido marcado como falhado. Reembolso por urgência aplicado.',
    },
    loadError: 'Estamos a ter dificuldade em mostrar os pedidos de mudança. Tente novamente.',
  },
  findHome: {
    eyebrow: 'Encontrar Casa',
    title: 'Procura prioritária assistida',
    subtitle:
      'Partilhe o que procura e a Kuteka coordena KAI e operadores. Há uma única taxa de prioridade via Kuteka Pay; explorar casas continua gratuito.',
    exploreLink: 'Explorar gratuitamente',
    newRequestTitle: 'Novo pedido',
    provinceLabel: 'Província',
    municipalityLabel: 'Município',
    provincePlaceholder: 'Luanda',
    municipalityPlaceholder: 'Belas',
    typologyLabel: 'Tipologia',
    budgetLabel: 'Orçamento máximo (Kz)',
    notesLabel: 'Preferências / notas',
    notesPlaceholder: 'Zona, acessos, condições essenciais…',
    submit: 'Activar procura prioritária (sandbox)',
    requestsTitle: 'Pedidos',
    operatorBadge: 'Operador',
    budgetUpTo: 'Até {amount}',
    budgetOpen: 'Orçamento aberto',
    priorityAmountSuffix: ' · prioridade {amount}',
    paidSuffix: ' · paga',
    matchPrefix: 'Match: {value}',
    acceptHome: 'Aceitar casa',
    reject: 'Recusar',
    matchInputAria: 'ID do imóvel encontrado',
    matchInputPlaceholder: 'ID do imóvel (opcional)',
    registerMatch: 'Registar match',
    failSla: 'Falhar (SLA)',
    emptyList: 'Ainda sem pedidos de procura.',
    failReasonDefault: 'SLA não cumprido.',
    messages: {
      created: 'Procura prioritária activa. Taxa cobrada via Kuteka Pay (sandbox).',
      accepted: 'Casa aceite. Pedido concluído sem taxa adicional.',
      rejected: 'Casa recusada. Procura retomada.',
      cancelled: 'Pedido cancelado. Reembolso integral aplicado.',
      matched: 'Match registado. Cliente notificado.',
      failed: 'Pedido falhado. Reembolso integral aplicado.',
    },
    loadError: 'Estamos a ter dificuldade em mostrar os pedidos de procura. Tente novamente.',
  },
  concierge: {
    eyebrow: 'Concierge Kuteka',
    title: 'Ajuda especializada, quando precisa',
    subtitle:
      'Explique o pedido e a equipa Kuteka acompanha-o até à conclusão. A taxa única usa Kuteka Pay; cancelar antes do atendimento devolve o valor integral em créditos.',
    providersLink: 'Prestadores',
    newRequestTitle: 'Novo pedido',
    categoryLabel: 'Categoria',
    notesLabel: 'Como podemos ajudar?',
    notesPlaceholder: 'Descreva o resultado que pretende, contexto e prazos relevantes…',
    propertyLabel: 'ID do imóvel (opcional)',
    propertyPlaceholder: 'UUID do imóvel',
    contractLabel: 'ID do contrato (opcional)',
    contractPlaceholder: 'UUID do contrato',
    submit: 'Pedir Concierge (sandbox)',
    requestsTitle: 'Pedidos',
    operatorBadge: 'Operador',
    feeAmount: 'Taxa {amount}',
    feePending: 'Taxa pendente',
    paidSuffix: ' · Kuteka Pay',
    propertySuffix: ' · imóvel {id}',
    contractSuffix: ' · contrato {id}',
    operationPrefix: 'Operação: {value}',
    operatorNoteAria: 'Nota do operador',
    operatorNotePlaceholder: 'Nota operacional (opcional)',
    start: 'Iniciar',
    complete: 'Concluir',
    markFail: 'Marcar falha',
    emptyList: 'Ainda sem pedidos Concierge.',
    failReasonDefault: 'Serviço não concluído.',
    messages: {
      created: 'Pedido activo. Taxa de serviço cobrada via Kuteka Pay (sandbox).',
      cancelled: 'Pedido cancelado. Reembolso integral aplicado em créditos.',
      started: 'Atendimento iniciado.',
      completed: 'Atendimento concluído.',
      failed: 'Pedido falhado. Reembolso integral aplicado em créditos.',
    },
    loadError: 'Estamos a ter dificuldade em mostrar os pedidos Concierge. Tente novamente.',
  },
  assistencia: {
    eyebrow: 'Assistência 24h',
    title: 'Ajuda urgente para o seu imóvel',
    subtitle:
      'Registe a ocorrência e a equipa Kuteka coordena a assistência. A chamada custa cerca de 5 000 Kz via Kuteka Pay; o cancelamento antes do início devolve 100% em créditos.',
    providersLink: 'Prestadores',
    newRequestTitle: 'Novo pedido urgente',
    categoryLabel: 'Categoria',
    urgencyLabel: 'Urgência',
    notesLabel: 'O que aconteceu?',
    notesPlaceholder: 'Descreva o problema, riscos e indicações para chegar ao local…',
    propertyLabel: 'ID do imóvel (opcional)',
    propertyPlaceholder: 'UUID do imóvel',
    submit: 'Criar pedido',
    requestsTitle: 'Pedidos de assistência',
    operatorBadge: 'Operador',
    feeAmount: 'Taxa {amount}',
    feeEstimate: 'Taxa estimada 5 000 Kz',
    paidSuffix: ' · Kuteka Pay',
    propertySuffix: ' · imóvel {id}',
    operationPrefix: 'Operação: {value}',
    payAndActivate: 'Pagar e activar',
    operatorNoteAria: 'Nota do operador',
    operatorNotePlaceholder: 'Nota operacional (opcional)',
    start: 'Iniciar',
    complete: 'Concluir',
    markFail: 'Marcar falha',
    emptyList: 'Ainda sem pedidos de assistência.',
    failReasonDefault: 'Assistência não concluída.',
    messages: {
      created: 'Rascunho criado. Confirme o pagamento para activar a assistência.',
      activated: 'Pedido activo. Taxa cobrada via Kuteka Pay (sandbox).',
      cancelled: 'Pedido cancelado. Reembolso integral aplicado quando cobrado.',
      started: 'Assistência iniciada.',
      completed: 'Assistência concluída.',
      failed: 'Pedido marcado como falhado. Reembolso integral aplicado.',
    },
    loadError: 'Estamos a ter dificuldade em mostrar a Assistência 24h. Tente novamente.',
  },
  garantia: {
    eyebrow: 'Garantia Kuteka',
    title: 'Protecção mensal opcional',
    subtitle:
      'Cobertura por cerca de 3 500 Kz/mês, paga pela stack partilhada Kuteka Pay. O cancelamento termina a cobertura; no mesmo dia da activação, a mensalidade é devolvida integralmente em créditos.',
    newSubTitle: 'Nova subscrição',
    newSubBody: 'Crie o rascunho e associe, se quiser, um imóvel ou contrato a que tem acesso.',
    propertyLabel: 'ID do imóvel (opcional)',
    propertyPlaceholder: 'UUID do imóvel',
    contractLabel: 'ID do contrato (opcional)',
    contractPlaceholder: 'UUID do contrato',
    submit: 'Criar rascunho',
    subscriptionsTitle: 'Subscrições',
    operatorBadge: 'Finanças',
    monthlyLabel: 'Garantia mensal',
    defaultAmount: '3 500 Kz/mês',
    paidSuffix: ' · Kuteka Pay',
    propertySuffix: ' · imóvel {id}',
    contractSuffix: ' · contrato {id}',
    coveragePrefix: 'Cobertura: ',
    activateAndPay: 'Activar e pagar',
    reasonAria: 'Motivo do estado',
    reasonPlaceholder: 'Motivo (opcional)',
    markPastDue: 'Em atraso',
    markFail: 'Marcar falha',
    emptyList: 'Ainda sem subscrições Garantia.',
    messages: {
      created: 'Rascunho criado. Active quando estiver pronto para pagar.',
      activated: 'Garantia activa. Mensalidade cobrada via Kuteka Pay (sandbox).',
      cancelled: 'Garantia cancelada. O reembolso é aplicado quando elegível.',
      pastDue: 'Subscrição marcada com pagamento em atraso.',
      failed: 'Subscrição marcada como falhada.',
    },
    loadError: 'Estamos a ter dificuldade em mostrar as subscrições Garantia. Tente novamente.',
  },
  marketplace: {
    eyebrow: 'Marketplace operacional',
    title: 'Rede de serviços Kuteka',
    subtitle:
      'Prestador → orçamento → aceitação → execução → pagamento (Kuteka Pay) → avaliação. A comissão fica no Ledger (take-rate B2B — sem escrow).',
    smartMoveLink: 'Mudança Inteligente',
    tabs: {
      providers: 'Prestadores',
      myOrders: 'Os meus pedidos',
      inbox: 'Pedidos recebidos',
    },
    providersPanel: {
      title: 'Prestadores activos',
      hint: 'Filtre por categoria e peça um serviço.',
      categoryLabel: 'Categoria',
      slaLabel: 'SLA (horas)',
      titleLabel: 'Título do pedido',
      titleDefault: 'Pedido de serviço',
      serviceOfProvider: 'Serviço {name}',
      requestService: 'Pedir serviço',
      empty: 'Sem prestadores nesta categoria.',
    },
    myOrdersPanel: {
      title: 'Os meus pedidos',
      notePrefix: 'Nota: {value}',
      acceptQuote: 'Aceitar orçamento',
      payWithKutekaPay: 'Pagar com Kuteka Pay',
      ratingAria: 'Avaliação',
      rate: 'Avaliar',
      ratedLabel: 'Avaliado ★ {score}',
      empty: 'Ainda sem pedidos.',
    },
    inboxPanel: {
      title: 'Pedidos recebidos',
      hint: 'Envie orçamentos, inicie e conclua serviços. Demos podem ser operados por finance.manage.',
      amountAria: 'Valor do orçamento (AOA)',
      amountPlaceholder: 'Valor AOA',
      sendQuote: 'Enviar orçamento',
      requote: 'Reorçamentar',
      startExecution: 'Iniciar execução',
      completeService: 'Concluir serviço',
      empty: 'Sem pedidos recebidos.',
    },
    orderMeta: {
      noQuote: 'Sem orçamento',
      commissionSuffix: ' · comissão {amount}',
      paidSuffix: ' · pago',
      ratingSuffix: ' · ★ {score}',
    },
    messages: {
      requestCreated: 'Pedido criado. Aguarda orçamento do prestador.',
      quoteAccepted: 'Orçamento aceite.',
      paid: 'Pagamento processado via Kuteka Pay. Comissão registada no Ledger.',
      rated: 'Avaliação registada. Obrigado!',
      cancelled: 'Pedido cancelado.',
      quoteSent: 'Orçamento enviado ao cliente.',
      started: 'Execução iniciada.',
      completed: 'Serviço concluído.',
    },
    loadError: 'Estamos a ter dificuldade em mostrar o marketplace. Tente novamente.',
  },
  partnerPlans: {
    eyebrow: 'Parceiro',
    title: 'Planos Parceiro Kuteka',
    subtitle:
      'Bronze, Silver e Gold — receita B2B recorrente. Pagamento sandbox até Multicaixa/EMIS.',
    patrimoniosLink: 'Patrimónios',
    forbidden: 'Planos Parceiro exigem papel de parceiro patrimonial ou Super Admin.',
    chooseTitle: 'Escolher plano',
    active: 'Activo',
    activateSandbox: 'Activar (sandbox)',
    subscriptionsTitle: 'Subscrições',
    since: 'desde {date}',
    renewsSuffix: ' · renova {date}',
    empty: 'Nenhum plano activo ainda.',
    messages: {
      activated: 'Plano activado (sandbox). Subscrição {id}',
    },
  },
  catalog: {
    urgency: {
      planned_90: 'Planeada (61–90 dias)',
      priority_60: 'Prioritária (31–60 dias)',
      urgent_30: 'Urgente (15–30 dias)',
      emergency_14: 'Emergência (1–14 dias)',
    },
    providerCategories: {
      all: 'Todas',
      cleaning: 'Limpeza',
      moving: 'Mudanças',
      painting: 'Pintura',
      plumbing: 'Canalização',
      electricity: 'Electricidade',
      gardening: 'Jardinagem',
      security: 'Segurança',
      renovation: 'Remodelação',
      internet: 'Internet',
      insurance: 'Seguros',
      other: 'Outros',
    },
    orderStatus: {
      requested: 'Pedido',
      quoted: 'Orçamentado',
      accepted: 'Aceite',
      in_progress: 'Em execução',
      completed: 'Concluído',
      cancelled: 'Cancelado',
      disputed: 'Em disputa',
    },
    smartMoveStatus: {
      draft: 'Rascunho',
      awaiting_payment: 'A aguardar pagamento',
      active: 'Activo',
      matched: 'Solução encontrada',
      completed: 'Concluído',
      cancelled: 'Cancelado',
      failed: 'Falhado',
    },
    findHomeTypology: {
      t0: 'T0 / Estúdio',
      t1: 'T1',
      t2: 'T2',
      t3: 'T3',
      t4: 'T4',
      t5_plus: 'T5 ou mais',
      moradia: 'Moradia',
      terreno: 'Terreno',
      comercial: 'Comercial',
      outro: 'Outro',
    },
    findHomeTypologyNone: 'Sem tipologia',
    findHomeStatus: {
      draft: 'Rascunho',
      awaiting_payment: 'A aguardar pagamento',
      active: 'Procura activa',
      matched: 'Casa encontrada',
      completed: 'Concluído',
      cancelled: 'Cancelado',
      failed: 'Sem solução',
    },
    conciergeCategory: {
      housing_guidance: 'Orientação habitacional',
      contract_support: 'Apoio com contrato',
      document_support: 'Apoio documental',
      move_coordination: 'Coordenação de mudança',
      property_support: 'Apoio com imóvel',
      other: 'Outro pedido',
    },
    conciergeStatus: {
      draft: 'Rascunho',
      awaiting_payment: 'A aguardar pagamento',
      active: 'A aguardar operador',
      in_progress: 'Em atendimento',
      completed: 'Concluído',
      cancelled: 'Cancelado',
      failed: 'Falhado',
    },
    garantiaStatus: {
      draft: 'Rascunho',
      awaiting_payment: 'A aguardar pagamento',
      active: 'Cobertura activa',
      cancelled: 'Cancelada',
      past_due: 'Pagamento em atraso',
      failed: 'Falhada',
    },
    assistenciaCategory: {
      plumbing: 'Canalização',
      electricity: 'Electricidade',
      locksmith: 'Fechaduras e chaves',
      security: 'Segurança',
      water_damage: 'Infiltração ou inundação',
      gas: 'Gás',
      other: 'Outra emergência',
    },
    assistenciaUrgency: {
      urgent: 'Urgente — nas próximas 24 horas',
      emergency: 'Emergência — risco imediato',
    },
    assistenciaStatus: {
      draft: 'Rascunho',
      awaiting_payment: 'A aguardar pagamento',
      active: 'A aguardar operador',
      in_progress: 'Assistência em curso',
      completed: 'Concluída',
      cancelled: 'Cancelada',
      failed: 'Falhada',
    },
    partnerPlanNames: {
      'partner.bronze.monthly': 'Bronze',
      'partner.silver.monthly': 'Silver',
      'partner.gold.monthly': 'Gold',
    },
    partnerPlanBlurbs: {
      'partner.bronze.monthly': 'Visibilidade base + leads prioritários.',
      'partner.silver.monthly': 'Destaque no explore + relatórios avançados.',
      'partner.gold.monthly': 'Máxima exposição + KAI comercial + suporte prioritário.',
    },
  },
} as const;

type DeepStringify<T> = {
  [K in keyof T]: T[K] extends string ? string : DeepStringify<T[K]>;
};

export type MonetizationCopy = DeepStringify<typeof monetizationCopyPt>;
