import type { FinanceCopy, FinanceHubCopy } from './pt';

export const financeCopyEn: FinanceCopy = {
  superTitle: 'Super Admin — Command Center',
  superSubtitle:
    'Kuteka financial engine: revenue, catalog, pricing, credits, refunds, disputes, reconciliation, fraud, KAI, CRM and exports. Cross-cutting infrastructure, no fund custody.',
  eyebrow: 'Revenue Command Center',
  forbidden: 'Only Super Administrator (finance.manage) can access this panel.',
  loadError: 'We are having trouble showing the finance center. Please try again.',
  sections: {
    revenue: 'Revenue',
    products: 'Catalog',
    prices: 'Pricing',
    ledger: 'Ledger',
    commissions: 'Commissions',
    gateways: 'Kuteka Pay / Gateways',
    invoices: 'Invoicing',
    sandbox: 'Sandbox Pay',
    credits: 'Kuteka Credits',
    health: 'Service Health',
    refunds: 'Refunds',
    disputes: 'Disputes',
    recon: 'Reconciliation',
    fraud: 'Fraud',
    kai: 'KAI Rules',
    crm: 'CRM',
    exports: 'Exports',
    campaigns: 'Campaigns',
    payEngine: 'Kuteka Pay — Adapters',
    payEngineDefault: 'Default gateway',
    payEngineIntent: 'Create payment intent',
    payEngineWebhook: 'Simulate webhook (sandbox)',
    payEngineIntents: 'Recent payment intents',
  },
  tabs: {
    revenue: 'Revenue',
    catalog: 'Catalog',
    pricing: 'Pricing',
    credits: 'Credits',
    refunds: 'Refunds',
    disputes: 'Disputes',
    recon: 'Reconciliation',
    fraud: 'Fraud',
    kai: 'KAI',
    crm: 'CRM',
    exports: 'Exports',
    invoices: 'Invoicing',
    payengine: 'Kuteka Pay',
    gateways: 'Gateways',
    flags: 'Service Health',
    campaigns: 'Campaigns',
    kocc: 'Operating Control',
    institutional: 'Institutional Management',
  },
  metrics: {
    captured: 'Captured charges',
    pending: 'Pending',
    commissions: 'Commissions',
    credits: 'Credits granted',
    intents: 'Payment intents',
    invoices: 'Invoices',
    products: 'Active products',
    gateways: 'Sandbox gateways',
    refunds: 'Refunds',
    disputes: 'Open disputes',
    fraud: 'Fraud signals',
    crm: 'CRM accounts',
    kai: 'KAI rules',
  },
  custodyNote: 'Custody mode: none (no escrow). Money never sits with Kuteka.',
  sandboxHint: 'Test environment — no real money until Multicaixa/EMIS/Stripe are activated.',
  payEngineHint:
    'Unified payment engine in SANDBOX. No real money, no custody, no live gateway in this test.',
  payEngineDefaultHint:
    'Beta: the default adapter is locked to sandbox. Other gateway names stay in the table with no live charge.',
  payEngineIntentHint:
    'Creates a test payment intent linked to a module. In sandbox it returns auto_capture_ready.',
  payEngineWebhookHint:
    'Simulates gateway events (succeeded/failed/cancelled/expired) on a sandbox intent.',
  createIntent: 'Create intent',
  simulateWebhook: 'Simulate webhook',
  setDefaultGateway: 'Set as default',
  quote: 'Quote',
  pay: 'Create sandbox payment',
  capture: 'Simulate capture',
  savePrice: 'Update price',
  grantCredits: 'Grant credits',
  createRefund: 'Create refund',
  openDispute: 'Open dispute',
  runRecon: 'Run reconciliation',
  createExport: 'Generate export',
  upsertProduct: 'Save product',
  setCommission: 'Save commission',
  upsertKai: 'Save KAI rule',
  upsertCrm: 'Save CRM account',
  flagFraud: 'Flag',
  generatePdf: 'Generate invoice',
  markEmailed: 'Mark as sent',
  errors: {
    loadError: 'We are having trouble showing the financial data. Please try again.',
    saveError: "We couldn't save right now. Please try again.",
    forbidden: 'No financial permission.',
    quoteError: "We couldn't get the quote. Please try again.",
    payError: "We couldn't start the payment. Please try again.",
  },
  payEngineErrors: {
    loadError: 'We are having trouble showing Kuteka Pay. Please try again.',
    createError: "We couldn't start the payment. Please try again.",
    captureError: "We couldn't confirm the payment. Please try again.",
    failError: "We couldn't update the payment status. Please try again.",
    cancelError: "We couldn't cancel the payment. Please try again.",
    statusError: "We couldn't get the payment status. Please try again.",
    webhookError: "We couldn't simulate the payment event. Please try again.",
    saveError: "We couldn't save right now. Please try again.",
  },
};

export const financeHubCopyEn: FinanceHubCopy = {
  creditBalance: 'Credit balance',
  redeem: 'Use credits',
  redeemHint: 'Apply your Kuteka Credits to a service.',
  myRefunds: 'My refunds',
  downloadInvoice: 'Download invoice',
  noRefunds: 'No refunds.',
  redeemDone: 'Credits used successfully.',
};
