import type { FinanceCopy, FinanceHubCopy } from './pt';

export const financeCopyEs: FinanceCopy = {
  superTitle: 'Super Admin — Centro de Comando',
  superSubtitle:
    'Motor financiero Kuteka: ingresos, catálogo, precios, créditos, reembolsos, disputas, reconciliación, fraude, KAI, CRM y exportaciones. Infraestructura transversal, sin custodia de fondos.',
  eyebrow: 'Revenue Command Center',
  forbidden: 'Solo el Super Administrador (finance.manage) puede acceder a este panel.',
  loadError: 'Estamos teniendo dificultades para mostrar el centro financiero. Inténtelo de nuevo.',
  sections: {
    revenue: 'Ingresos',
    products: 'Catálogo',
    prices: 'Precios',
    ledger: 'Libro mayor',
    commissions: 'Comisiones',
    gateways: 'Kuteka Pay / Pasarelas',
    invoices: 'Facturación',
    sandbox: 'Sandbox Pay',
    credits: 'Kuteka Credits',
    health: 'Service Health',
    refunds: 'Reembolsos',
    disputes: 'Disputas',
    recon: 'Reconciliación',
    fraud: 'Fraude',
    kai: 'Reglas KAI',
    crm: 'CRM',
    exports: 'Exportaciones',
    campaigns: 'Campañas',
    payEngine: 'Kuteka Pay — Adaptadores',
    payEngineDefault: 'Pasarela predeterminada',
    payEngineIntent: 'Crear payment intent',
    payEngineWebhook: 'Simular webhook (sandbox)',
    payEngineIntents: 'Payment intents recientes',
  },
  tabs: {
    revenue: 'Ingresos',
    catalog: 'Catálogo',
    pricing: 'Precios',
    credits: 'Créditos',
    refunds: 'Reembolsos',
    disputes: 'Disputas',
    recon: 'Reconciliación',
    fraud: 'Fraude',
    kai: 'KAI',
    crm: 'CRM',
    exports: 'Exportaciones',
    invoices: 'Facturación',
    payengine: 'Kuteka Pay',
    gateways: 'Pasarelas',
    flags: 'Service Health',
    campaigns: 'Campañas',
    kocc: 'Control Operativo',
  },
  metrics: {
    captured: 'Cargos capturados',
    pending: 'Pendientes',
    commissions: 'Comisiones',
    credits: 'Créditos otorgados',
    intents: 'Payment intents',
    invoices: 'Facturas',
    products: 'Productos activos',
    gateways: 'Pasarelas sandbox',
    refunds: 'Reembolsos',
    disputes: 'Disputas abiertas',
    fraud: 'Señales de fraude',
    crm: 'Cuentas CRM',
    kai: 'Reglas KAI',
  },
  custodyNote:
    'Modo de custodia: none (sin depósito en garantía). El dinero nunca queda en Kuteka.',
  sandboxHint: 'Entorno de prueba — sin dinero real hasta activar Multicaixa/EMIS/Stripe.',
  payEngineHint:
    'Motor de pago unificado: todos los módulos usan kuteka_pay_*. Estado de los adaptadores (sandbox|multicaixa|emis|stripe|wise|bank_transfer).',
  payEngineDefaultHint:
    'Define el adaptador base usado cuando un módulo no indica pasarela. Fase B: sandbox por defecto.',
  payEngineIntentHint:
    'Crea un payment intent de prueba vinculado a un módulo. En sandbox devuelve auto_capture_ready.',
  payEngineWebhookHint:
    'Simula eventos de pasarela (succeeded/failed/cancelled/expired) sobre un intent sandbox.',
  createIntent: 'Crear intent',
  simulateWebhook: 'Simular webhook',
  setDefaultGateway: 'Definir como predeterminada',
  quote: 'Cotizar',
  pay: 'Crear pago sandbox',
  capture: 'Simular captura',
  savePrice: 'Actualizar precio',
  grantCredits: 'Otorgar créditos',
  createRefund: 'Crear reembolso',
  openDispute: 'Abrir disputa',
  runRecon: 'Ejecutar reconciliación',
  createExport: 'Generar exportación',
  upsertProduct: 'Guardar producto',
  setCommission: 'Guardar comisión',
  upsertKai: 'Guardar regla KAI',
  upsertCrm: 'Guardar cuenta CRM',
  flagFraud: 'Señalar',
  generatePdf: 'Generar factura',
  markEmailed: 'Marcar como enviada',
  errors: {
    loadError:
      'Estamos teniendo dificultades para mostrar los datos financieros. Inténtelo de nuevo.',
    saveError: 'No pudimos guardar en este momento. Inténtelo de nuevo.',
    forbidden: 'Sin permiso financiero.',
    quoteError: 'No pudimos obtener la cotización. Inténtelo de nuevo.',
    payError: 'No pudimos iniciar el pago. Inténtelo de nuevo.',
  },
  payEngineErrors: {
    loadError: 'Estamos teniendo dificultades para mostrar Kuteka Pay. Inténtelo de nuevo.',
    createError: 'No pudimos iniciar el pago. Inténtelo de nuevo.',
    captureError: 'No pudimos confirmar el pago. Inténtelo de nuevo.',
    failError: 'No pudimos actualizar el estado del pago. Inténtelo de nuevo.',
    cancelError: 'No pudimos cancelar el pago. Inténtelo de nuevo.',
    statusError: 'No pudimos obtener el estado del pago. Inténtelo de nuevo.',
    webhookError: 'No pudimos simular el evento de pago. Inténtelo de nuevo.',
    saveError: 'No pudimos guardar en este momento. Inténtelo de nuevo.',
  },
};

export const financeHubCopyEs: FinanceHubCopy = {
  creditBalance: 'Saldo de créditos',
  redeem: 'Usar créditos',
  redeemHint: 'Aplique sus Kuteka Credits a un servicio.',
  myRefunds: 'Mis reembolsos',
  downloadInvoice: 'Descargar factura',
  noRefunds: 'Sin reembolsos.',
  redeemDone: 'Créditos usados con éxito.',
};
