import type { FinanceCopy, FinanceHubCopy } from './pt';

export const financeCopyFr: FinanceCopy = {
  superTitle: 'Super Admin — Centre de Commande',
  superSubtitle:
    'Moteur financier Kuteka : revenus, catalogue, tarifs, crédits, remboursements, litiges, réconciliation, fraude, KAI, CRM et exports. Infrastructure transversale, sans conservation de fonds.',
  eyebrow: 'Revenue Command Center',
  forbidden: 'Seul le Super Administrateur (finance.manage) peut accéder à ce panneau.',
  loadError: 'Nous avons du mal à afficher le centre financier. Réessayez.',
  sections: {
    revenue: 'Revenus',
    products: 'Catalogue',
    prices: 'Tarifs',
    ledger: 'Grand livre',
    commissions: 'Commissions',
    gateways: 'Kuteka Pay / Passerelles',
    invoices: 'Facturation',
    sandbox: 'Sandbox Pay',
    credits: 'Kuteka Credits',
    health: 'Service Health',
    refunds: 'Remboursements',
    disputes: 'Litiges',
    recon: 'Réconciliation',
    fraud: 'Fraude',
    kai: 'Règles KAI',
    crm: 'CRM',
    exports: 'Exports',
    campaigns: 'Campagnes',
    payEngine: 'Kuteka Pay — Adaptateurs',
    payEngineDefault: 'Passerelle par défaut',
    payEngineIntent: 'Créer un payment intent',
    payEngineWebhook: 'Simuler un webhook (sandbox)',
    payEngineIntents: 'Payment intents récents',
  },
  tabs: {
    revenue: 'Revenus',
    catalog: 'Catalogue',
    pricing: 'Tarifs',
    credits: 'Crédits',
    refunds: 'Remboursements',
    disputes: 'Litiges',
    recon: 'Réconciliation',
    fraud: 'Fraude',
    kai: 'KAI',
    crm: 'CRM',
    exports: 'Exports',
    invoices: 'Facturation',
    payengine: 'Kuteka Pay',
    gateways: 'Passerelles',
    flags: 'Service Health',
    campaigns: 'Campagnes',
    kocc: 'Contrôle opérationnel',
    institutional: 'Gestion institutionnelle',
  },
  metrics: {
    captured: 'Charges capturées',
    pending: 'En attente',
    commissions: 'Commissions',
    credits: 'Crédits accordés',
    intents: 'Payment intents',
    invoices: 'Factures',
    products: 'Produits actifs',
    gateways: 'Passerelles sandbox',
    refunds: 'Remboursements',
    disputes: 'Litiges ouverts',
    fraud: 'Signaux de fraude',
    crm: 'Comptes CRM',
    kai: 'Règles KAI',
  },
  custodyNote: 'Mode de conservation : none (sans séquestre). Kuteka ne détient jamais les fonds.',
  sandboxHint:
    "Environnement de test — pas d'argent réel avant l'activation de Multicaixa/EMIS/Stripe.",
  payEngineHint:
    'Moteur de paiement unifié : tous les modules utilisent kuteka_pay_*. État des adaptateurs (sandbox|multicaixa|emis|stripe|wise|bank_transfer).',
  payEngineDefaultHint:
    "Définit l'adaptateur de base utilisé quand un module n'indique pas de passerelle. Phase B : sandbox par défaut.",
  payEngineIntentHint:
    'Crée un payment intent de test lié à un module. En sandbox, renvoie auto_capture_ready.',
  payEngineWebhookHint:
    'Simule des événements de passerelle (succeeded/failed/cancelled/expired) sur un intent sandbox.',
  createIntent: "Créer l'intent",
  simulateWebhook: 'Simuler le webhook',
  setDefaultGateway: 'Définir par défaut',
  quote: 'Devis',
  pay: 'Créer un paiement sandbox',
  capture: 'Simuler la capture',
  savePrice: 'Mettre à jour le prix',
  grantCredits: 'Accorder des crédits',
  createRefund: 'Créer un remboursement',
  openDispute: 'Ouvrir un litige',
  runRecon: 'Lancer la réconciliation',
  createExport: "Générer l'export",
  upsertProduct: 'Enregistrer le produit',
  setCommission: 'Enregistrer la commission',
  upsertKai: 'Enregistrer la règle KAI',
  upsertCrm: 'Enregistrer le compte CRM',
  flagFraud: 'Signaler',
  generatePdf: 'Générer la facture',
  markEmailed: 'Marquer comme envoyée',
  errors: {
    loadError: 'Nous avons du mal à afficher les données financières. Réessayez.',
    saveError: "Impossible d'enregistrer pour le moment. Réessayez.",
    forbidden: 'Aucune permission financière.',
    quoteError: "Impossible d'obtenir le devis. Réessayez.",
    payError: 'Impossible de démarrer le paiement. Réessayez.',
  },
  payEngineErrors: {
    loadError: 'Nous avons du mal à afficher Kuteka Pay. Réessayez.',
    createError: 'Impossible de démarrer le paiement. Réessayez.',
    captureError: 'Impossible de confirmer le paiement. Réessayez.',
    failError: "Impossible de mettre à jour l'état du paiement. Réessayez.",
    cancelError: "Impossible d'annuler le paiement. Réessayez.",
    statusError: "Impossible d'obtenir l'état du paiement. Réessayez.",
    webhookError: "Impossible de simuler l'événement de paiement. Réessayez.",
    saveError: "Impossible d'enregistrer pour le moment. Réessayez.",
  },
};

export const financeHubCopyFr: FinanceHubCopy = {
  creditBalance: 'Solde de crédits',
  redeem: 'Utiliser les crédits',
  redeemHint: 'Appliquez vos Kuteka Credits à un service.',
  myRefunds: 'Mes remboursements',
  downloadInvoice: 'Télécharger la facture',
  noRefunds: 'Aucun remboursement.',
  redeemDone: 'Crédits utilisés avec succès.',
};
