export const financeCopyPt = {
  superTitle: 'Super Admin — Centro de Comando',
  superSubtitle:
    'Motor financeiro Kuteka: receita, catálogo, preços, créditos, reembolsos, disputas, reconciliação, fraude, KAI, CRM e exportações. Infraestrutura transversal, sem custódia de fundos.',
  eyebrow: 'Revenue Command Center',
  forbidden: 'Apenas Super Administrador (finance.manage) acede a este painel.',
  loadError: 'Estamos a ter dificuldade em mostrar o centro financeiro. Tente novamente.',
  sections: {
    revenue: 'Receita',
    products: 'Catálogo',
    prices: 'Preços',
    ledger: 'Ledger',
    commissions: 'Comissões',
    gateways: 'Kuteka Pay / Gateways',
    invoices: 'Faturação',
    sandbox: 'Sandbox Pay',
    credits: 'Kuteka Credits',
    health: 'Service Health',
    refunds: 'Reembolsos',
    disputes: 'Disputas',
    recon: 'Reconciliação',
    fraud: 'Fraude',
    kai: 'Regras KAI',
    crm: 'CRM',
    exports: 'Exportações',
    campaigns: 'Campanhas',
    payEngine: 'Kuteka Pay — Adaptadores',
    payEngineDefault: 'Gateway por omissão',
    payEngineIntent: 'Criar payment intent',
    payEngineWebhook: 'Simular webhook (sandbox)',
    payEngineIntents: 'Payment intents recentes',
  },
  tabs: {
    revenue: 'Receita',
    catalog: 'Catálogo',
    pricing: 'Preços',
    credits: 'Créditos',
    refunds: 'Reembolsos',
    disputes: 'Disputas',
    recon: 'Reconciliação',
    fraud: 'Fraude',
    kai: 'KAI',
    crm: 'CRM',
    exports: 'Exportações',
    invoices: 'Faturação',
    payengine: 'Kuteka Pay',
    gateways: 'Gateways',
    flags: 'Service Health',
    campaigns: 'Campanhas',
  },
  metrics: {
    captured: 'Cobranças capturadas',
    pending: 'Pendentes',
    commissions: 'Comissões',
    credits: 'Créditos concedidos',
    intents: 'Payment intents',
    invoices: 'Faturas',
    products: 'Produtos activos',
    gateways: 'Gateways sandbox',
    refunds: 'Reembolsos',
    disputes: 'Disputas abertas',
    fraud: 'Sinais de fraude',
    crm: 'Contas CRM',
    kai: 'Regras KAI',
  },
  custodyNote: 'Modo de custódia: none (sem escrow). O dinheiro não fica na Kuteka.',
  sandboxHint: 'Ambiente de teste — sem dinheiro real até activar Multicaixa/EMIS/Stripe.',
  payEngineHint:
    'Motor de pagamento unificado: todos os módulos usam kuteka_pay_*. Saúde dos adaptadores (sandbox|multicaixa|emis|stripe|wise|bank_transfer).',
  payEngineDefaultHint:
    'Define o adaptador base usado quando um módulo não indica gateway. Fase B: sandbox por omissão.',
  payEngineIntentHint:
    'Cria um payment intent de teste ligado a um módulo. Em sandbox devolve auto_capture_ready.',
  payEngineWebhookHint:
    'Simula eventos de gateway (succeeded/failed/cancelled/expired) sobre um intent sandbox.',
  createIntent: 'Criar intent',
  simulateWebhook: 'Simular webhook',
  setDefaultGateway: 'Definir por omissão',
  quote: 'Cotar',
  pay: 'Criar pagamento sandbox',
  capture: 'Simular captura',
  savePrice: 'Actualizar preço',
  grantCredits: 'Conceder créditos',
  createRefund: 'Criar reembolso',
  openDispute: 'Abrir disputa',
  runRecon: 'Correr reconciliação',
  createExport: 'Gerar exportação',
  upsertProduct: 'Guardar produto',
  setCommission: 'Guardar comissão',
  upsertKai: 'Guardar regra KAI',
  upsertCrm: 'Guardar conta CRM',
  flagFraud: 'Sinalizar',
  generatePdf: 'Gerar fatura',
  markEmailed: 'Marcar enviada',
  errors: {
    loadError: 'Estamos a ter dificuldade em mostrar os dados financeiros. Tente novamente.',
    saveError: 'Não conseguimos guardar agora. Tente novamente.',
    forbidden: 'Sem permissão financeira.',
    quoteError: 'Não conseguimos obter a cotação. Tente novamente.',
    payError: 'Não conseguimos iniciar o pagamento. Tente novamente.',
  },
  payEngineErrors: {
    loadError: 'Estamos a ter dificuldade em mostrar o Kuteka Pay. Tente novamente.',
    createError: 'Não conseguimos iniciar o pagamento. Tente novamente.',
    captureError: 'Não conseguimos confirmar o pagamento. Tente novamente.',
    failError: 'Não conseguimos actualizar o estado do pagamento. Tente novamente.',
    cancelError: 'Não conseguimos cancelar o pagamento. Tente novamente.',
    statusError: 'Não conseguimos obter o estado do pagamento. Tente novamente.',
    webhookError: 'Não conseguimos simular o evento de pagamento. Tente novamente.',
    saveError: 'Não conseguimos guardar agora. Tente novamente.',
  },
} as const;

export const financeHubCopyPt = {
  creditBalance: 'Saldo de créditos',
  redeem: 'Usar créditos',
  redeemHint: 'Aplica os teus Kuteka Credits a um serviço.',
  myRefunds: 'Os meus reembolsos',
  downloadInvoice: 'Descarregar fatura',
  noRefunds: 'Sem reembolsos.',
  redeemDone: 'Créditos usados com sucesso.',
} as const;

type DeepStringify<T> = {
  [K in keyof T]: T[K] extends string ? string : DeepStringify<T[K]>;
};

export type FinanceCopy = DeepStringify<typeof financeCopyPt>;
export type FinanceHubCopy = DeepStringify<typeof financeHubCopyPt>;
