export function getFinanceCopy() {
  return {
    superTitle: 'Super Admin — Centro de Comando',
    superSubtitle:
      'Motor financeiro Kuteka: receita, catálogo, preços, créditos, reembolsos, disputas, reconciliação, fraude, KAI, CRM e exportações. Infraestrutura transversal, sem custódia de fundos.',
    eyebrow: 'Revenue Command Center',
    forbidden: 'Apenas Super Administrador (finance.manage) acede a este painel.',
    loadError: 'Não foi possível carregar o centro financeiro.',
    sections: {
      revenue: 'Receita',
      products: 'Catálogo',
      prices: 'Preços',
      ledger: 'Ledger',
      commissions: 'Comissões',
      gateways: 'Kuteka Pay / Gateways',
      invoices: 'Faturação',
      sandbox: 'Sandbox Pay',
      credits: 'Kuteka Credits',
      health: 'Service Health',
      refunds: 'Reembolsos',
      disputes: 'Disputas',
      recon: 'Reconciliação',
      fraud: 'Fraude',
      kai: 'Regras KAI',
      crm: 'CRM',
      exports: 'Exportações',
      campaigns: 'Campanhas',
    },
    tabs: {
      revenue: 'Receita',
      catalog: 'Catálogo',
      pricing: 'Preços',
      credits: 'Créditos',
      refunds: 'Reembolsos',
      disputes: 'Disputas',
      recon: 'Reconciliação',
      fraud: 'Fraude',
      kai: 'KAI',
      crm: 'CRM',
      exports: 'Exportações',
      invoices: 'Faturação',
      gateways: 'Gateways',
      flags: 'Service Health',
      campaigns: 'Campanhas',
    },
    metrics: {
      captured: 'Cobranças capturadas',
      pending: 'Pendentes',
      commissions: 'Comissões',
      credits: 'Créditos concedidos',
      intents: 'Payment intents',
      invoices: 'Faturas',
      products: 'Produtos activos',
      gateways: 'Gateways sandbox',
      refunds: 'Reembolsos',
      disputes: 'Disputas abertas',
      fraud: 'Sinais de fraude',
      crm: 'Contas CRM',
      kai: 'Regras KAI',
    },
    custodyNote: 'Modo de custódia: none (sem escrow). O dinheiro não fica na Kuteka.',
    sandboxHint: 'Ambiente de teste — sem dinheiro real até activar Multicaixa/EMIS/Stripe.',
    quote: 'Cotar',
    pay: 'Criar pagamento sandbox',
    capture: 'Simular captura',
    savePrice: 'Actualizar preço',
    grantCredits: 'Conceder créditos',
    createRefund: 'Criar reembolso',
    openDispute: 'Abrir disputa',
    runRecon: 'Correr reconciliação',
    createExport: 'Gerar exportação',
    upsertProduct: 'Guardar produto',
    setCommission: 'Guardar comissão',
    upsertKai: 'Guardar regra KAI',
    upsertCrm: 'Guardar conta CRM',
    flagFraud: 'Sinalizar',
    generatePdf: 'Gerar fatura',
    markEmailed: 'Marcar enviada',
  } as const;
}

export function getFinanceHubCopy() {
  return {
    creditBalance: 'Saldo de créditos',
    redeem: 'Usar créditos',
    redeemHint: 'Aplica os teus Kuteka Credits a um serviço.',
    myRefunds: 'Os meus reembolsos',
    downloadInvoice: 'Descarregar fatura',
    noRefunds: 'Sem reembolsos.',
    redeemDone: 'Créditos usados com sucesso.',
  } as const;
}
