import type { AdministracaoCopy } from './pt';

export const administracaoCopyEn: AdministracaoCopy = {
  title: 'Administration',
  subtitle: 'Operational dashboard — accounts, properties, agents, verifications and requests.',
  permissionBadge: 'admin.panel',
  users: 'Users',
  usersTitle: 'Users and roles',
  usersHint: 'Read access to accounts and assignment of the Certified Agent role.',
  trustReview: 'Verifications',
  housingExplore: 'Properties (Client view)',
  contracts: 'Contracts',
  backToHub: 'Back to Administration',
  assignAgent: 'Assign Certified Agent',
  assigning: 'Assigning…',
  assigned: 'Certified Agent role assigned.',
  alreadyAgent: 'This user is already a Certified Agent.',
  emptyUsersTitle: 'No users',
  emptyUsers: 'There are no profiles to show yet.',
  statsTitle: 'Platform summary',
  statsHint: 'Operational indicators connected across the active modules.',
  pendingTitle: 'Pending requests',
  pendingHint: 'Client interests awaiting follow-up.',
  emptyPending: 'No pending requests at the moment.',
  openProperty: 'Open property',
  stats: {
    profiles: 'Users',
    properties: 'Active properties',
    assignments: 'Active follow-ups',
    agents: 'Certified Agents',
    trust: 'Pending verifications',
    interests: 'Pending interests',
    demo: 'Beta inventory',
    contractsActive: 'Active contracts',
    contractsPending: 'Pending contracts',
  },
  loadError: 'We are having trouble showing Administration. Please try again.',
  forbidden: 'You do not have permission to access Administration (admin.panel).',
  mvpNote: 'Live dashboard: navigate to users, Trust review and the Client inventory.',
  roleLabels: {
    client: 'Client',
    patrimonial_partner: 'Property Partner',
    certified_agent: 'Certified Agent',
    administrator: 'Administrator',
  },
};
