import type { AdministracaoCopy } from './pt';

export const administracaoCopyEn: AdministracaoCopy = {
  title: 'Administration · Work Center',
  subtitle:
    'Operational queue by role — publications, SLA, contact PP, audit and moderation. Not just a dashboard.',
  permissionBadge: 'admin.panel',
  users: 'Users',
  usersTitle: 'Users and roles',
  usersHint: 'Read access to accounts and assignment of the Certified Agent role.',
  trustReview: 'Verifications',
  housingExplore: 'Properties (Client view)',
  contracts: 'Contracts',
  backToHub: 'Back to Administration',
  assignAgent: 'Assign Certified Agent',
  assigning: 'Assigning…',
  assigned: 'Certified Agent role assigned.',
  alreadyAgent: 'This user is already a Certified Agent.',
  emptyUsersTitle: 'No users',
  emptyUsers: 'There are no profiles to show yet.',
  statsTitle: 'Platform summary',
  statsHint: 'Operational indicators connected across the active modules.',
  pendingTitle: 'Pending requests',
  pendingHint: 'Client interests awaiting follow-up.',
  emptyPending: 'No pending requests at the moment.',
  openProperty: 'Open property',
  publicationQueueTitle: 'Work Center — Publications',
  publicationQueueHint:
    'Operational queue: In review, Pending, SLA soon/overdue, Waiting PP/Agent. Decide with reason, notify and audit.',
  emptyQueue: 'No properties awaiting a publication decision.',
  workBucketAll: 'All',
  workBucketInReview: 'In review',
  workBucketPending: 'Pending',
  workBucketSlaSoon: 'SLA soon',
  workBucketSlaOverdue: 'SLA overdue',
  workBucketWaitingPp: 'Waiting PP',
  workBucketWaitingAgent: 'Waiting Agent',
  waitingLabel: 'Waiting',
  partnerLabel: 'Partner (PP)',
  assigneeLabel: 'Assignee',
  nextActionLabel: 'Next action',
  assignToMe: 'Assign to me',
  assignBusy: 'Assigning…',
  assignOk: 'Case assigned.',
  contactPartner: 'Contact Partner',
  rolePowerTitle: 'What can I do in this role?',
  rolePowerSupervisor:
    'Supervisor: review, pend, request documents/visit, contact PP, assign, SLA and moderation. Cannot approve or reject.',
  rolePowerAdmin:
    'Admin: everything Supervisor can do + approve/reject listings and manage ops/agents per permissions.',
  rolePowerSuper:
    'Super Admin: everything Admin can do + manage Admins/Supervisors, permissions, KOCC and critical settings.',
  rolePowerFounder:
    'Founder/Owner: maximum institutional control (Institutional Management + Super).',
  inSheetReviewTitle: 'Publication decision',
  inSheetReviewHint:
    'Operational actions on this sheet — reason required when pending/rejecting; the PP is notified with the next step.',
  inSheetNotInQueue: 'This property may not be in the active queue — actions can still apply.',
  notesRequired: 'Note / message to PP',
  supervisorCannotApprove: 'Supervisors cannot approve or reject — ask an Admin.',
  supervisorScopeHint: 'As Supervisor you can pend, request documents/visit and contact the PP.',
  approve: 'Approve',
  pending: 'Pending',
  reject: 'Reject',
  requestCorrections: 'Request corrections',
  requestVisit: 'Request technical visit',
  requestDocs: 'Request documents',
  notes: 'Notes (optional)',
  reasons: 'Reasons',
  decideBusy: 'Deciding…',
  decideOk: 'Decision recorded.',
  decideError: 'Could not record the decision. Check the reasons and try again.',
  kaiScore: 'KAI score / risk',
  slaDeadline: 'SLA deadline',
  kosAnalyticsTitle: 'KOS Analytics',
  kosAnalyticsHint: 'Operational indicators for decisions — publication, SLA and conversion.',
  kosInReview: 'In review',
  kosOverdueSla: 'Overdue SLA',
  kosApproved7d: 'Approved (7d)',
  kosRejected7d: 'Rejected (7d)',
  kosAvgApprovalHours: 'Avg. approval (h)',
  kosRejectionRate: 'Rejection rate (7d)',
  kosInterestToContract: 'Interest → contract',
  kosOpenReports: 'Open reports',
  auditTitle: 'Audit centre',
  auditHint: 'Recent events with actor, roles, reason and before/after state.',
  emptyAudit: 'No audit events to show.',
  auditAction: 'Action',
  auditActor: 'Actor',
  auditRoles: 'Roles',
  auditReason: 'Reason',
  auditEntity: 'Entity',
  auditWhen: 'When',
  auditBefore: 'Before',
  auditAfter: 'After',
  moderationTitle: 'Moderation centre',
  moderationHint: 'Open or reviewing reports — resolve, dismiss or mark as reviewing.',
  emptyModeration: 'No open reports at the moment.',
  moderationResolve: 'Resolve',
  moderationDismiss: 'Dismiss',
  moderationReviewing: 'Reviewing',
  moderationNotes: 'Resolution notes (optional)',
  moderationBusy: 'Updating…',
  moderationOk: 'Report updated.',
  moderationResolveError: 'Could not update the report. Please try again.',
  moderationTarget: 'Target',
  moderationReason: 'Reason',
  moderationStatus: 'Status',
  stats: {
    profiles: 'Users',
    properties: 'Active properties',
    assignments: 'Active follow-ups',
    agents: 'Certified Agents',
    trust: 'Pending verifications',
    interests: 'Pending interests',
    demo: 'Beta inventory',
    contractsActive: 'Active contracts',
    contractsPending: 'Pending contracts',
  },
  loadError: 'We are having trouble showing Administration. Please try again.',
  forbidden:
    'You do not have permission to access Administration (admin.panel or properties.review).',
  mvpNote: 'Live dashboard: navigate to users, Trust review and the Client inventory.',
  roleLabels: {
    client: 'Client',
    patrimonial_partner: 'Property Partner',
    certified_agent: 'Certified Agent',
    administrator: 'Administrator',
  },
};
