import type { AdministracaoCopy } from './pt';

export const administracaoCopyEn: AdministracaoCopy = {
  title: 'Administration',
  subtitle: 'Operational dashboard — accounts, properties, agents, verifications and requests.',
  permissionBadge: 'admin.panel',
  users: 'Users',
  usersTitle: 'Users and roles',
  usersHint: 'Read access to accounts and assignment of the Certified Agent role.',
  trustReview: 'Verifications',
  housingExplore: 'Properties (Client view)',
  contracts: 'Contracts',
  backToHub: 'Back to Administration',
  assignAgent: 'Assign Certified Agent',
  assigning: 'Assigning…',
  assigned: 'Certified Agent role assigned.',
  alreadyAgent: 'This user is already a Certified Agent.',
  emptyUsersTitle: 'No users',
  emptyUsers: 'There are no profiles to show yet.',
  statsTitle: 'Platform summary',
  statsHint: 'Operational indicators connected across the active modules.',
  pendingTitle: 'Pending requests',
  pendingHint: 'Client interests awaiting follow-up.',
  emptyPending: 'No pending requests at the moment.',
  openProperty: 'Open property',
  publicationQueueTitle: 'Publication queue',
  publicationQueueHint:
    'Properties under review — approve, mark pending, reject, or request corrections, a technical visit, or documents.',
  emptyQueue: 'No properties awaiting a publication decision.',
  approve: 'Approve',
  pending: 'Pending',
  reject: 'Reject',
  requestCorrections: 'Request corrections',
  requestVisit: 'Request technical visit',
  requestDocs: 'Request documents',
  notes: 'Notes (optional)',
  reasons: 'Reasons',
  decideBusy: 'Deciding…',
  decideOk: 'Decision recorded.',
  decideError: 'Could not record the decision. Check the reasons and try again.',
  kaiScore: 'KAI score',
  slaDeadline: 'SLA deadline',
  kosAnalyticsTitle: 'KOS Analytics',
  kosAnalyticsHint: 'Operational indicators for decisions — publication, SLA and conversion.',
  kosInReview: 'In review',
  kosOverdueSla: 'Overdue SLA',
  kosApproved7d: 'Approved (7d)',
  kosRejected7d: 'Rejected (7d)',
  kosAvgApprovalHours: 'Avg. approval (h)',
  kosRejectionRate: 'Rejection rate (7d)',
  kosInterestToContract: 'Interest → contract',
  kosOpenReports: 'Open reports',
  auditTitle: 'Audit centre',
  auditHint: 'Recent events with actor, roles, reason and before/after state.',
  emptyAudit: 'No audit events to show.',
  auditAction: 'Action',
  auditActor: 'Actor',
  auditRoles: 'Roles',
  auditReason: 'Reason',
  auditEntity: 'Entity',
  auditWhen: 'When',
  auditBefore: 'Before',
  auditAfter: 'After',
  moderationTitle: 'Moderation centre',
  moderationHint: 'Open or reviewing reports — resolve, dismiss or mark as reviewing.',
  emptyModeration: 'No open reports at the moment.',
  moderationResolve: 'Resolve',
  moderationDismiss: 'Dismiss',
  moderationReviewing: 'Reviewing',
  moderationNotes: 'Resolution notes (optional)',
  moderationBusy: 'Updating…',
  moderationOk: 'Report updated.',
  moderationResolveError: 'Could not update the report. Please try again.',
  moderationTarget: 'Target',
  moderationReason: 'Reason',
  moderationStatus: 'Status',
  stats: {
    profiles: 'Users',
    properties: 'Active properties',
    assignments: 'Active follow-ups',
    agents: 'Certified Agents',
    trust: 'Pending verifications',
    interests: 'Pending interests',
    demo: 'Beta inventory',
    contractsActive: 'Active contracts',
    contractsPending: 'Pending contracts',
  },
  loadError: 'We are having trouble showing Administration. Please try again.',
  forbidden:
    'You do not have permission to access Administration (admin.panel or properties.review).',
  mvpNote: 'Live dashboard: navigate to users, Trust review and the Client inventory.',
  roleLabels: {
    client: 'Client',
    patrimonial_partner: 'Property Partner',
    certified_agent: 'Certified Agent',
    administrator: 'Administrator',
  },
};
