import type { AdministracaoCopy } from './pt';

export const administracaoCopyEs: AdministracaoCopy = {
  title: 'Administración',
  subtitle: 'Panel operativo — cuentas, patrimonios, agentes, verificaciones y solicitudes.',
  permissionBadge: 'admin.panel',
  users: 'Usuarios',
  usersTitle: 'Usuarios y roles',
  usersHint: 'Lectura de las cuentas y asignación del rol de Agente Certificado.',
  trustReview: 'Verificaciones',
  housingExplore: 'Patrimonios (vista de Cliente)',
  contracts: 'Contratos',
  backToHub: 'Volver a Administración',
  assignAgent: 'Asignar Agente Certificado',
  assigning: 'Asignando…',
  assigned: 'Rol de Agente Certificado asignado.',
  alreadyAgent: 'Este usuario ya es Agente Certificado.',
  emptyUsersTitle: 'Sin usuarios',
  emptyUsers: 'Aún no hay perfiles para mostrar.',
  statsTitle: 'Resumen de la plataforma',
  statsHint: 'Indicadores operativos interconectados de los módulos activos.',
  pendingTitle: 'Solicitudes pendientes',
  pendingHint: 'Intereses de Cliente a la espera de seguimiento.',
  emptyPending: 'Sin solicitudes pendientes en este momento.',
  openProperty: 'Abrir patrimonio',
  publicationQueueTitle: 'Centro de Trabajo — Publicaciones',
  publicationQueueHint:
    'Cola operativa: En análisis, Pendientes, SLA próximo/vencido, Esperando PP/Agente. Decida con motivo, notificación y auditoría.',
  emptyQueue: 'Sin patrimonios a la espera de una decisión de publicación.',
  workBucketAll: 'Todos',
  workBucketInReview: 'En análisis',
  workBucketPending: 'Pendientes',
  workBucketSlaSoon: 'SLA próximo',
  workBucketSlaOverdue: 'SLA vencido',
  workBucketWaitingPp: 'Esperando PP',
  workBucketWaitingAgent: 'Esperando Agente',
  waitingLabel: 'En espera',
  partnerLabel: 'Socio (PP)',
  assigneeLabel: 'Responsable',
  nextActionLabel: 'Próxima acción',
  assignToMe: 'Asignarme',
  assignBusy: 'Asignando…',
  assignOk: 'Proceso asignado.',
  contactPartner: 'Contactar Socio',
  rolePowerTitle: '¿Qué puedo hacer en este rol?',
  rolePowerSupervisor:
    'Supervisor: analizar, poner en pendiente, pedir documentos/visita, contactar PP, asignar, SLA y moderación. No aprueba ni rechaza.',
  rolePowerAdmin:
    'Admin: todo del Supervisor + aprobar/rechazar publicaciones y gestionar operaciones/agentes según permisos.',
  rolePowerSuper:
    'Super Admin: todo del Admin + gestionar Admins/Supervisores, permisos, KOCC y configuraciones críticas.',
  rolePowerFounder: 'Founder/Owner: control institucional máximo (Gestión Institucional + Super).',
  inSheetReviewTitle: 'Decisión de publicación',
  inSheetReviewHint:
    'Acciones operativas en esta ficha — motivo obligatorio al pendenciar/rechazar; el PP recibe el siguiente paso.',
  inSheetNotInQueue:
    'Este patrimonio puede no estar en la cola activa — las acciones aún pueden aplicarse.',
  notesRequired: 'Observación / mensaje al PP',
  supervisorCannotApprove: 'El Supervisor no puede aprobar ni rechazar — pida a un Admin.',
  supervisorScopeHint:
    'Como Supervisor puede pendenciar, pedir documentos/visita y contactar al PP.',
  approve: 'Aprobar',
  pending: 'Pendiente',
  reject: 'Rechazar',
  requestCorrections: 'Pedir correcciones',
  requestVisit: 'Pedir visita técnica',
  requestDocs: 'Pedir documentos',
  notes: 'Notas (opcional)',
  reasons: 'Motivos',
  decideBusy: 'Decidiendo…',
  decideOk: 'Decisión registrada.',
  decideError: 'No se pudo registrar la decisión. Revise los motivos e inténtelo de nuevo.',
  kaiScore: 'Índice KAI / riesgo',
  slaDeadline: 'Plazo SLA',
  kosAnalyticsTitle: 'KOS Analytics',
  kosAnalyticsHint: 'Indicadores operativos para decidir — publicación, SLA y conversión.',
  kosInReview: 'En análisis',
  kosOverdueSla: 'SLA vencido',
  kosApproved7d: 'Aprobados (7d)',
  kosRejected7d: 'Rechazados (7d)',
  kosAvgApprovalHours: 'Media de aprobación (h)',
  kosRejectionRate: 'Tasa de rechazo (7d)',
  kosInterestToContract: 'Interés → contrato',
  kosOpenReports: 'Denuncias abiertas',
  auditTitle: 'Centro de auditoría',
  auditHint: 'Eventos recientes con actor, roles, motivo y estado antes/después.',
  emptyAudit: 'Sin eventos de auditoría para mostrar.',
  auditAction: 'Acción',
  auditActor: 'Actor',
  auditRoles: 'Roles',
  auditReason: 'Motivo',
  auditEntity: 'Entidad',
  auditWhen: 'Cuándo',
  auditBefore: 'Antes',
  auditAfter: 'Después',
  moderationTitle: 'Centro de moderación',
  moderationHint: 'Denuncias abiertas o en análisis — resuelva, descarte o marque en análisis.',
  emptyModeration: 'Sin denuncias abiertas en este momento.',
  moderationResolve: 'Resolver',
  moderationDismiss: 'Descartar',
  moderationReviewing: 'En análisis',
  moderationNotes: 'Notas de resolución (opcional)',
  moderationBusy: 'Actualizando…',
  moderationOk: 'Denuncia actualizada.',
  moderationResolveError: 'No se pudo actualizar la denuncia. Inténtelo de nuevo.',
  moderationTarget: 'Objetivo',
  moderationReason: 'Motivo',
  moderationStatus: 'Estado',
  stats: {
    profiles: 'Usuarios',
    properties: 'Patrimonios activos',
    assignments: 'Seguimientos activos',
    agents: 'Agentes Certificados',
    trust: 'Verificaciones pendientes',
    interests: 'Intereses pendientes',
    demo: 'Inventario Beta',
    contractsActive: 'Contratos activos',
    contractsPending: 'Contratos pendientes',
  },
  loadError: 'Estamos teniendo dificultades para mostrar Administración. Inténtelo de nuevo.',
  forbidden: 'No tiene permiso para acceder a Administración (admin.panel o properties.review).',
  mvpNote: 'Panel en vivo: navegue a usuarios, revisión de Confianza e inventario del Cliente.',
  roleLabels: {
    client: 'Cliente',
    patrimonial_partner: 'Socio Patrimonial',
    certified_agent: 'Agente Certificado',
    administrator: 'Administrador',
  },
};
