import type { AdministracaoCopy } from './pt';

export const administracaoCopyEs: AdministracaoCopy = {
  title: 'Administración',
  subtitle: 'Panel operativo — cuentas, patrimonios, agentes, verificaciones y solicitudes.',
  permissionBadge: 'admin.panel',
  users: 'Usuarios',
  usersTitle: 'Usuarios y roles',
  usersHint: 'Lectura de las cuentas y asignación del rol de Agente Certificado.',
  trustReview: 'Verificaciones',
  housingExplore: 'Patrimonios (vista de Cliente)',
  contracts: 'Contratos',
  backToHub: 'Volver a Administración',
  assignAgent: 'Asignar Agente Certificado',
  assigning: 'Asignando…',
  assigned: 'Rol de Agente Certificado asignado.',
  alreadyAgent: 'Este usuario ya es Agente Certificado.',
  emptyUsersTitle: 'Sin usuarios',
  emptyUsers: 'Aún no hay perfiles para mostrar.',
  statsTitle: 'Resumen de la plataforma',
  statsHint: 'Indicadores operativos interconectados de los módulos activos.',
  pendingTitle: 'Solicitudes pendientes',
  pendingHint: 'Intereses de Cliente a la espera de seguimiento.',
  emptyPending: 'Sin solicitudes pendientes en este momento.',
  openProperty: 'Abrir patrimonio',
  publicationQueueTitle: 'Cola de publicación',
  publicationQueueHint:
    'Patrimonios en análisis — apruebe, ponga en pendiente, rechace o pida correcciones, visita técnica o documentos.',
  emptyQueue: 'Sin patrimonios a la espera de una decisión de publicación.',
  approve: 'Aprobar',
  pending: 'Pendiente',
  reject: 'Rechazar',
  requestCorrections: 'Pedir correcciones',
  requestVisit: 'Pedir visita técnica',
  requestDocs: 'Pedir documentos',
  notes: 'Notas (opcional)',
  reasons: 'Motivos',
  decideBusy: 'Decidiendo…',
  decideOk: 'Decisión registrada.',
  decideError: 'No se pudo registrar la decisión. Revise los motivos e inténtelo de nuevo.',
  kaiScore: 'Índice KAI',
  slaDeadline: 'Plazo SLA',
  stats: {
    profiles: 'Usuarios',
    properties: 'Patrimonios activos',
    assignments: 'Seguimientos activos',
    agents: 'Agentes Certificados',
    trust: 'Verificaciones pendientes',
    interests: 'Intereses pendientes',
    demo: 'Inventario Beta',
    contractsActive: 'Contratos activos',
    contractsPending: 'Contratos pendientes',
  },
  loadError: 'Estamos teniendo dificultades para mostrar Administración. Inténtelo de nuevo.',
  forbidden: 'No tiene permiso para acceder a Administración (admin.panel o properties.review).',
  mvpNote: 'Panel en vivo: navegue a usuarios, revisión de Confianza e inventario del Cliente.',
  roleLabels: {
    client: 'Cliente',
    patrimonial_partner: 'Socio Patrimonial',
    certified_agent: 'Agente Certificado',
    administrator: 'Administrador',
  },
};
