import type { AdministracaoCopy } from './pt';

export const administracaoCopyFr: AdministracaoCopy = {
  title: 'Administration',
  subtitle:
    'Tableau de bord opérationnel — comptes, patrimoines, agents, vérifications et demandes.',
  permissionBadge: 'admin.panel',
  users: 'Utilisateurs',
  usersTitle: 'Utilisateurs et rôles',
  usersHint: 'Lecture des comptes et attribution du rôle Agent Certifié.',
  trustReview: 'Vérifications',
  housingExplore: 'Patrimoines (vue Client)',
  contracts: 'Contrats',
  backToHub: 'Retour à l’Administration',
  assignAgent: 'Attribuer Agent Certifié',
  assigning: 'Attribution…',
  assigned: 'Rôle Agent Certifié attribué.',
  alreadyAgent: 'Cet utilisateur est déjà Agent Certifié.',
  emptyUsersTitle: 'Aucun utilisateur',
  emptyUsers: 'Il n’y a encore aucun profil à afficher.',
  statsTitle: 'Résumé de la plateforme',
  statsHint: 'Indicateurs opérationnels interconnectés des modules actifs.',
  pendingTitle: 'Demandes en attente',
  pendingHint: 'Intérêts de Client en attente de suivi.',
  emptyPending: 'Aucune demande en attente pour le moment.',
  openProperty: 'Ouvrir le patrimoine',
  publicationQueueTitle: 'Centre de travail — Publications',
  publicationQueueHint:
    'File opérationnelle : En analyse, En attente, SLA proche/dépassé, En attente PP/Agent. Décidez avec motif, notification et audit.',
  emptyQueue: 'Aucun patrimoine en attente d’une décision de publication.',
  workBucketAll: 'Tous',
  workBucketInReview: 'En analyse',
  workBucketPending: 'En attente',
  workBucketSlaSoon: 'SLA proche',
  workBucketSlaOverdue: 'SLA dépassé',
  workBucketWaitingPp: 'En attente PP',
  workBucketWaitingAgent: 'En attente Agent',
  waitingLabel: 'En attente',
  partnerLabel: 'Partenaire (PP)',
  assigneeLabel: 'Responsable',
  nextActionLabel: 'Prochaine action',
  assignToMe: 'M’assigner',
  assignBusy: 'Assignation…',
  assignOk: 'Dossier assigné.',
  contactPartner: 'Contacter le partenaire',
  rolePowerTitle: 'Que puis-je faire dans ce rôle ?',
  rolePowerSupervisor:
    'Superviseur : analyser, mettre en attente, demander documents/visite, contacter le PP, assigner, SLA et modération. Ne peut ni approuver ni rejeter.',
  rolePowerAdmin:
    'Admin : tout du Superviseur + approuver/rejeter les publications et gérer opérations/agents selon permissions.',
  rolePowerSuper:
    'Super Admin : tout de l’Admin + gérer Admins/Superviseurs, permissions, KOCC et réglages critiques.',
  rolePowerFounder:
    'Founder/Owner : contrôle institutionnel maximal (Gestion institutionnelle + Super).',
  inSheetReviewTitle: 'Décision de publication',
  inSheetReviewHint:
    'Actions opérationnelles sur cette fiche — motif obligatoire pour attente/rejet ; le PP est notifié avec la suite.',
  inSheetNotInQueue:
    'Ce patrimoine peut ne pas être dans la file active — les actions peuvent quand même s’appliquer.',
  notesRequired: 'Observation / message au PP',
  supervisorCannotApprove: 'Le Superviseur ne peut ni approuver ni rejeter — demandez à un Admin.',
  supervisorScopeHint:
    'En tant que Superviseur vous pouvez mettre en attente, demander documents/visite et contacter le PP.',
  approve: 'Approuver',
  pending: 'En attente',
  reject: 'Rejeter',
  requestCorrections: 'Demander des corrections',
  requestVisit: 'Demander une visite technique',
  requestDocs: 'Demander des documents',
  notes: 'Notes (facultatif)',
  reasons: 'Motifs',
  decideBusy: 'Décision en cours…',
  decideOk: 'Décision enregistrée.',
  decideError: 'Impossible d’enregistrer la décision. Vérifiez les motifs et réessayez.',
  kaiScore: 'Indice KAI / risque',
  slaDeadline: 'Échéance SLA',
  kosAnalyticsTitle: 'KOS Analytics',
  kosAnalyticsHint: 'Indicateurs opérationnels pour décider — publication, SLA et conversion.',
  kosInReview: 'En analyse',
  kosOverdueSla: 'SLA en retard',
  kosApproved7d: 'Approuvés (7j)',
  kosRejected7d: 'Rejetés (7j)',
  kosAvgApprovalHours: 'Moy. d’approbation (h)',
  kosRejectionRate: 'Taux de rejet (7j)',
  kosInterestToContract: 'Intérêt → contrat',
  kosOpenReports: 'Signalements ouverts',
  auditTitle: 'Centre d’audit',
  auditHint: 'Événements récents avec acteur, rôles, motif et état avant/après.',
  emptyAudit: 'Aucun événement d’audit à afficher.',
  auditAction: 'Action',
  auditActor: 'Acteur',
  auditRoles: 'Rôles',
  auditReason: 'Motif',
  auditEntity: 'Entité',
  auditWhen: 'Quand',
  auditBefore: 'Avant',
  auditAfter: 'Après',
  moderationTitle: 'Centre de modération',
  moderationHint: 'Signalements ouverts ou en analyse — résolvez, ignorez ou mettez en analyse.',
  emptyModeration: 'Aucun signalement ouvert pour le moment.',
  moderationResolve: 'Résoudre',
  moderationDismiss: 'Ignorer',
  moderationReviewing: 'En analyse',
  moderationNotes: 'Notes de résolution (facultatif)',
  moderationBusy: 'Mise à jour…',
  moderationOk: 'Signalement mis à jour.',
  moderationResolveError: 'Impossible de mettre à jour le signalement. Réessayez.',
  moderationTarget: 'Cible',
  moderationReason: 'Motif',
  moderationStatus: 'Statut',
  stats: {
    profiles: 'Utilisateurs',
    properties: 'Patrimoines actifs',
    assignments: 'Suivis actifs',
    agents: 'Agents Certifiés',
    trust: 'Vérifications en attente',
    interests: 'Intérêts en attente',
    demo: 'Inventaire Bêta',
    contractsActive: 'Contrats actifs',
    contractsPending: 'Contrats en attente',
  },
  loadError: 'Nous avons du mal à afficher l’Administration. Veuillez réessayer.',
  forbidden:
    'Vous n’avez pas la permission d’accéder à l’Administration (admin.panel ou properties.review).',
  mvpNote:
    'Tableau de bord en direct : accédez aux utilisateurs, à la révision de Confiance et à l’inventaire du Client.',
  roleLabels: {
    client: 'Client',
    patrimonial_partner: 'Partenaire Patrimonial',
    certified_agent: 'Agent Certifié',
    administrator: 'Administrateur',
  },
};
