import type { AuthCopy } from './pt';

/** Auth UI copy — en. */
export const authCopyEn: AuthCopy = {
  brand: {
    name: 'Kuteka',
  },
  common: {
    loading: 'Loading…',
    networkError: 'We could not complete the request. Check your connection and try again.',
    configMissing:
      'Authentication is not available in this environment yet. You can explore the Landing or come back later.',
    nextStepRetry: 'Try again in a few minutes.',
    rateLimited:
      'Too many requests right now. Wait about an hour and try again — or sign in if you already created an account.',
    sessionExpired: 'Your session expired or was not started. Sign in again to continue.',
    sessionInvalid: 'Invalid session. Sign in again to continue.',
    showPassword: 'Show',
    hidePassword: 'Hide',
  },
  emailOtp: {
    sendFailed: 'We could not send the code.',
    invalidLength: 'Enter the 6-digit code.',
    invalidGeneric: 'Invalid code.',
    expired: 'The code expired. Request a new one.',
    incorrect: 'Incorrect code. Please try again.',
    incorrectOrExpired: 'Incorrect or expired code. Resend the email and try again.',
  },
  actions: {
    updatePasswordFailed: 'We could not update the password.',
    resendEmailFailed: 'We could not resend the email.',
    activateRolesFailed: 'We could not activate the roles.',
    saveNameFailed: 'We could not save the name.',
  },
  register: {
    title: 'Create account',
    subtitle: 'Start in minutes. One account, your roles, your Kuteka space.',
    email: {
      label: 'Email',
      hint: 'We use email to protect and recover your account.',
      placeholder: 'name@email.com',
    },
    password: {
      label: 'Password',
      placeholder: 'Create a strong password',
      ruleMin: 'At least 8 characters',
      ruleUpper: 'One uppercase letter',
      ruleNumber: 'One number',
    },
    confirm: {
      label: 'Confirm password',
      placeholder: 'Repeat the password',
    },
    terms: {
      label: 'I accept the',
      linkLabel: 'Terms of use',
      connector: 'and the',
      privacyLinkLabel: 'Privacy policy',
    },
    submit: 'Create account',
    submitLoading: 'Creating account…',
    submitSuccess: 'Account created',
    ctaLogin: 'Already have an account? Sign in',
    duplicate: {
      title: 'This email already has a Kuteka account.',
      body: 'Instead of creating another account, sign in or recover access with the same email.',
      login: 'Sign in',
      recover: 'Recover access',
    },
  },
  verify: {
    title: 'Verify your email',
    subtitle:
      'Confirm with the 6-digit code or open the link in the Kuteka email. Both methods are valid.',
    sentTo: 'Sent to',
    dualHint:
      'Prefer entering the OTP code below if the link does not open on your device or mail client.',
    otpLabel: '6-digit code',
    otpPlaceholder: '000000',
    otpSubmit: 'Confirm with code',
    orLink: 'or',
    linkHint: 'You can also open the confirmation link in the email (Method A).',
    sandboxHint: 'Test environment: code {code}',
    resend: 'Resend email and code',
    resendLoading: 'Resending…',
    resendSuccess: 'Email and code resent. Check Spam as well.',
    cooldown: 'You can resend in {seconds}s.',
    confirming: 'We are confirming your account…',
    already: {
      title: 'Your account is already confirmed.',
      cta: 'Enter Kuteka',
    },
  },
  login: {
    title: 'Sign in',
    subtitle: 'Welcome back to your Kuteka space.',
    email: {
      label: 'Email',
      placeholder: 'name@email.com',
    },
    password: {
      label: 'Password',
      show: 'Show',
      placeholder: 'Your password',
    },
    submit: 'Sign in',
    submitLoading: 'Signing in…',
    submitSuccess: 'Signed in',
    ctaRegister: 'Create account',
    ctaRecover: 'Forgot your password?',
    errorGeneric:
      'Could not sign in. Check your email and password. If needed, use Recover access.',
  },
  logout: {
    title: 'Signing out',
    pending: 'Ending your session securely…',
    done: 'You signed out successfully. You can sign in again whenever you want.',
    expired: 'Your session expired. Sign in again to continue.',
    action: 'Sign out',
  },
  recover: {
    request: {
      title: 'Recover access',
      subtitle: 'Do not worry. We will help you recover access securely.',
      channelLabel: 'How do you prefer to recover?',
      channelEmail: 'By email',
      channelPhone: 'By phone (SMS)',
      channelBoth: 'Email and phone',
      email: {
        label: 'Email',
      },
      phone: {
        label: 'Phone',
        placeholder: '+2449XXXXXXXX',
      },
      otpLabel: '6-digit code',
      otpSubmit: 'Validate code',
      sendOtp: 'Send SMS code',
      phoneSuccess:
        'SMS code validated (sandbox). Set a new password when you have a session, or also use email.',
      phonePrepared:
        'SMS recovery is prepared (sandbox). In production it will use Kuteka’s SMS provider.',
      submit: 'Send instructions',
      submitLoading: 'Sending…',
      back: 'Back to Sign in',
      noemail: 'No access to email? Contact',
      success: 'If an account exists with this email, we sent instructions.',
    },
    confirm: {
      title: 'New password',
      subtitle: 'Set a strong password to recover access to your account.',
      password: {
        label: 'Password',
      },
      confirm: {
        label: 'Confirm password',
      },
      submit: 'Save',
      submitLoading: 'Saving…',
      submitSuccess: 'Password updated',
    },
  },
  onboarding: {
    welcomeTitle: 'Welcome to Kuteka',
    welcomeSubtitle: 'Your account is almost ready. Let’s finish a quick setup.',
    roles: {
      title: 'How do you want to use Kuteka?',
      hint: 'Choose the role to activate. Exploring as a Client does not grant Partner, Agent or Admin powers. Partner is only assigned if you select it. Agent and Admin are never self-assigned.',
      client: 'Client',
      clientDesc: 'Search, book or manage your housing journey.',
      partner: 'Patrimonial Partner',
      partnerDesc: 'List and manage properties.',
      multiRole: 'You can select one or both. The same account can hold several roles as needed.',
      selectAtLeastOne: 'Choose at least one role to continue.',
      agentNote: 'Agent and Administrator are assigned by Kuteka.',
      submit: 'Continue',
      submitLoading: 'Activating…',
      success: 'Your account is ready. Welcome to Kuteka.',
    },
    profile: {
      title: 'What should we call you?',
      subtitle: 'This name appears in your Kuteka space. You can change it later.',
      displayName: {
        label: 'Display name',
      },
      submit: 'Continue',
      submitLoading: 'Saving…',
      skip: 'Continue without a name',
    },
  },
  app: {
    title: 'Kuteka dashboard',
    welcome: 'Welcome',
    welcomeAnonymous: 'Welcome to the platform',
    emailLabel: 'Email',
    userFallback: 'Kuteka user',
    active: 'Active account',
    accountStatusTitle: 'Account status',
    accountStatusHint: 'Account ready to use the available modules.',
    accountSummaryAria: 'Account summary',
    dashboardHint: 'The platform is ready — choose an action or open a module.',
    todayTitle: 'What would you like to do today?',
    todayHint: 'Shortcuts to the most used actions in active modules.',
    quickActivateProperty: 'Activate property',
    quickExploreHousing: 'Explore housing',
    quickAgent: 'Agent area',
    quickAdmin: 'Administration',
    quickContracts: 'Contracts',
    quickTrust: 'Verify account',
    quickRoles: 'Manage roles',
    experienceHint: 'Cockpit and flows for this experience — switch role in the account menu.',
    feedPreparing: 'Preparing the continuous environment…',
    rolesLabel: 'Active roles',
    rolesHint: 'The same account can hold several roles.',
    noRoles: 'No active roles yet',
    modulesTitle: 'Platform modules',
    modulesHint: 'Direct access to core platform modules.',
    upcomingTitle: 'Modules',
    moduleAvailable: 'Active',
    moduleUnavailable: 'Soon',
    loadError: 'We are having trouble opening your space. Try again in a moment.',
    stub: 'Use the active modules with the same account and your roles.',
    ctaLanding: 'Back to Landing',
    ctaProfile: 'Profile',
    ctaRoles: 'Manage roles',
    adminTitle: 'Administration',
    adminStub: 'Admin area (admin.panel permission): operations summary, users and Trust review.',
    adminForbidden:
      'You do not have permission for this area (admin.panel). If you think this is an error, contact Kuteka.',
    configMissing:
      'The authenticated area requires Supabase configuration. Set the environment variables and try again.',
    loginRequired: 'You need to sign in to access this area.',
    continuing: 'Continuing…',
  },
};
