import type { ContratosCopy } from './pt';

export const contratosCopyEn: ContratosCopy = {
  title: 'Contracts',
  subtitle:
    'Formalise an approved intent into a contract, with parties, amount, terms and clear statuses.',
  create: 'Prepare contract',
  createTitle: 'Prepare new contract',
  createHint:
    'Choose an active property, identify the Client and register the draft before payment.',
  creating: 'Preparing…',
  created: 'Contract prepared for acceptance.',
  detailTitle: 'Contract detail',
  demoNote: 'Demo data: contracts linked to the KTK-DEMO inventory to show the process in use.',
  emptyTitle: 'No contracts yet',
  empty:
    'Once Trust and Administration validate the parties, prepare the first contract to proceed to Payments.',
  emptyDemo: 'If the database is empty, run the PRD-008 migration to load KTK-CTR demo contracts.',
  loadError: 'We are having trouble showing the contracts. Please try again.',
  saveError: 'We could not prepare the contract. Check the details and try again.',
  transitionError: 'We could not update the contract. Please try again.',
  forbidden:
    'The Contracts area becomes available once your account has the right role (Client, Partner, Agent or Admin).',
  kycRequired:
    'Verified identity is required (KYC level 2+): complete the Client and Partner Profile and Trust before formalising real contracts.',
  kycBanner:
    'Real contracts require Real Identity (validated document). Complete your Profile if you have not done so yet.',
  kycBannerCta: 'Open KYC Profile',
  accept: 'Accept contract',
  accepting: 'Accepting…',
  accepted: 'Contract active. The next step is to prepare payment.',
  cancel: 'Cancel contract',
  cancelling: 'Cancelling…',
  cancelled: 'Contract cancelled.',
  complete: 'Mark as completed',
  completing: 'Completing…',
  completed: 'Contract completed.',
  openDetail: 'Open contract',
  preparePayment: 'Prepare payment',
  paymentsSoon: 'Payments is expanding — for now, follow up from the dashboard.',
  fields: {
    code: 'Code',
    property: 'Property',
    propertyId: 'Property ID',
    clientId: 'Client ID',
    agentId: 'Agent ID (optional)',
    interestId: 'Interest ID (optional)',
    purpose: 'Purpose',
    amount: 'Amount (AOA)',
    title: 'Title',
    titlePlaceholder: 'e.g. Rental agreement — T3 apartment in Kilamba',
    terms: 'Terms and notes',
    termsPlaceholder: 'Include essential conditions, deadlines and responsibilities.',
    status: 'Status',
    createdAt: 'Created',
    updatedAt: 'Updated',
    parties: 'Parties',
    partner: 'Partner',
    client: 'Client',
    agent: 'Agent',
    payment: 'Payment',
  },
  purposes: {
    rent: 'Rent',
    sale: 'Sale',
  },
  statuses: {
    draft: 'Draft',
    pending_acceptance: 'Pending acceptance',
    active: 'Active',
    completed: 'Completed',
    cancelled: 'Cancelled',
  },
};
