import type { ListingsCopy } from './pt';

export const listingsCopyEn: ListingsCopy = {
  reviews: {
    starsAriaTemplate: '{n} out of 5 stars',
    title: 'Reputation & reviews',
    subtitle: 'Stars, comments, replies and history — after a completed contract.',
    averageTemplate: 'Overall average {avg} · {count} review(s)',
    writeTitle: 'Write a review',
    unavailable: 'Available after a completed contract on this property.',
    contractLabel: 'Contract',
    subjectLabel: 'Subject',
    ratingLabel: 'Rating',
    commentLabel: 'Comment',
    commentPlaceholder: 'Describe the experience…',
    submitting: 'Saving…',
    submit: 'Publish review',
    loading: 'Loading reviews…',
    empty:
      'No public reviews yet. They appear once a contract is completed and parties share feedback.',
    ownerReply: 'Owner reply',
    agentReply: 'Agent reply',
    replyPlaceholder: 'Write a public reply…',
    replyAsOwner: 'Reply as owner',
    replyAsAgent: 'Reply as agent',
    needContractError: 'You can only review after a completed contract linked to this property.',
    invalidSessionError: 'Invalid session.',
    duplicateError: 'You have already reviewed this subject for this contract.',
    saveError: 'We could not save the review. Please try again.',
    saveSuccess: 'Review registered.',
    reviewerVerifiedLabel: 'Verified client',
    contractConfirmedBadge: 'Confirmed contract',
    emptyEncourage: 'Be the first to share your experience and help build trust in this community.',
  },
  subjects: {
    property: 'Property',
    owner: 'Owner',
    agent: 'Agent',
    client: 'Client',
    experience: 'Experience',
  },
  dimensions: {
    estado: 'Condition',
    limpeza: 'Cleanliness',
    localizacao: 'Location',
    honestidade: 'Honesty',
    negociacao: 'Negotiation',
    rapidez: 'Speed',
    acompanhamento: 'Follow-up',
    experiencia_geral: 'Overall experience',
    seriedade: 'Reliability',
    comunicacao: 'Communication',
    desempenho: 'Performance',
    quality: 'Quality',
    cleanliness: 'Cleanliness',
    location: 'Location',
    communication: 'Communication',
    value: 'Value for money',
    accuracy: 'Listing accuracy',
  },
  health: {
    eyebrow: 'Property cockpit',
    title: 'Property Health Panel',
    subtitle: 'Track the Kuteka Index, alerts, trends and automatic recommendations.',
    riskUnrated: 'Not yet rated',
    riskLow: 'Low risk',
    riskModerate: 'Moderate risk',
    riskHigh: 'High risk',
    renovationAlert: 'Alert: renovation recommended',
    noUrgentRenovation: 'No urgent renovation',
    upcomingMaintenance: 'Maintenance due soon',
    tipRenovation:
      'Small facade improvements and professional photography can raise market value by up to about 8%.',
    tipExcellent:
      'Property in excellent condition — keep half-yearly inspections and update the PDK after any works.',
    tipDefault:
      'Schedule the next preventive maintenance and confirm documentation in the Digital Passport.',
    tipLabel: 'Kuteka tip',
    overallState: 'Overall status',
    preparing: 'In preparation',
    conservation: 'Conservation',
    estimatedValue: 'Estimated value',
    lastMaintenance: 'Last maintenance',
    lastInspection: 'Last inspection',
    nextMaintenance: 'Next maintenance',
    nextInspection: 'Next inspection',
    toDefine: 'To be defined',
    views30d: 'Views (30d)',
    visits30d: 'Visits (30d)',
    proposals30d: 'Proposals (30d)',
    estimatedYield: 'Estimated yield',
    valueEvolution: 'Property / value trend',
    indexLabel: 'Index {score}',
    technicalHistory: 'Technical history',
    inspections: 'Inspections',
    valuations: 'Valuations',
    noRecords: 'No records yet.',
  },
  opsLabels: {
    service: {
      announce: 'Only list the property',
      find_buyer: 'Only find a buyer',
      find_tenant: 'Only find a tenant',
      rental_management: 'Hand rental management to Kuteka',
      full_management: 'Hand full property management to Kuteka',
      evaluation: 'Request a professional evaluation',
      photography: 'Request a professional photo session',
      technical_visit: 'Request a technical visit',
      renovation: 'Request renovation',
      renewal: 'Request renewal',
      construction_finish: 'Request construction completion',
      home_staging: 'Request decoration / Home Staging',
      cleaning: 'Request professional cleaning',
      maintenance: 'Request maintenance',
      works_supervision: 'Request works supervision',
      condo_admin: 'Request condo administration',
    },
    management: {
      announce_only: 'List only',
      find_buyer: 'Sell only (find a buyer)',
      find_tenant: 'Rent only (find a tenant)',
      rental_management: 'Rental management by Kuteka',
      full_management: 'Full property management by Kuteka',
    },
    renovation: {
      full_renovation: 'Full renovation',
      partial_renovation: 'Partial renovation',
      painting: 'Painting',
      electricity: 'Electricity',
      plumbing: 'Plumbing',
      roof: 'Roofing',
      kitchen: 'Kitchen',
      bathrooms: 'Bathrooms',
      facade: 'Facade',
      gardening: 'Gardening',
      landscaping: 'Landscaping',
      decoration: 'Decoration',
      home_staging: 'Home Staging',
    },
    unfinished: {
      none: 'Not applicable',
      kuteka_finish: 'I want Kuteka to complete the construction',
      budget_only: 'I want a budget to finish the works',
      technical_supervision: 'I only want technical follow-up',
      works_evaluation: 'I only want an evaluation of the works',
    },
    construction: {
      complete: 'Construction complete',
      partial: 'Partially built',
      not_started: 'Works not started',
      needs_finish: 'Needs completion',
    },
    conservation: {
      excellent: 'Excellent',
      good: 'Good',
      fair: 'Fair',
      needs_work: 'Needs work',
      ruin: 'In ruins',
      under_construction: 'Under construction',
    },
    lifecycle: {
      em_preparacao: 'In preparation',
      em_analise_documental: 'In document review',
      em_inspecao_tecnica: 'In technical inspection',
      em_avaliacao: 'In evaluation',
      aprovado: 'Approved',
      publicado: 'Published',
      em_negociacao: 'In negotiation',
      reservado: 'Reserved',
      vendido: 'Sold',
      arrendado: 'Rented',
      em_manutencao: 'In maintenance',
      temporariamente_indisponivel: 'Temporarily unavailable',
      arquivado: 'Archived',
    },
    partnerCategory: {
      A: 'A · Private Owner',
      B: 'B · Investor Owner',
      C: 'C · Owner Companies',
      D: 'D · Real Estate Developers',
      E: 'E · Resident Abroad',
      F: 'F · Full Kuteka Management',
      G: 'G · Value-appreciation Properties',
    },
    partnerLifecycleStage: {
      descoberta: 'Discovery',
      registo: 'Registration',
      verificacao: 'Verification',
      registo_patrimonio: 'Property registration',
      verificacao_tecnica: 'Technical verification',
      avaliacao: 'Evaluation',
      contrato_servicos: 'Service contract',
      publicacao: 'Publication',
      gestao_comercial: 'Commercial management',
      negociacao: 'Negotiation',
      formalizacao: 'Formalization',
      pos_contrato: 'Post-contract',
      avaliacao_experiencia: 'Experience evaluation',
      fidelizacao: 'Loyalty',
      reativacao: 'Reactivation',
    },
    amenities: {
      internet: 'Internet',
      energia: 'Power',
      agua: 'Water',
      seguranca: 'Security',
      estacionamento: 'Parking',
      piscina: 'Pool',
      jardim: 'Garden',
      acessibilidade: 'Accessibility',
    },
  },
};
