import type { ListingsCopy } from './pt';

export const listingsCopyEn: ListingsCopy = {
  reviews: {
    starsAriaTemplate: '{n} out of 5 stars',
    title: 'Reputation & reviews',
    subtitle: 'Stars, comments, replies and history — after a completed contract.',
    averageTemplate: 'Overall average {avg} · {count} review(s)',
    writeTitle: 'Write a review',
    unavailable: 'Available after a completed contract on this property.',
    contractLabel: 'Contract',
    subjectLabel: 'Subject',
    ratingLabel: 'Rating',
    commentLabel: 'Comment',
    commentPlaceholder: 'Describe the experience…',
    submitting: 'Saving…',
    submit: 'Publish review',
    loading: 'Loading reviews…',
    empty:
      'No public reviews yet. They appear once a contract is completed and parties share feedback.',
    ownerReply: 'Owner reply',
    agentReply: 'Agent reply',
    replyPlaceholder: 'Write a public reply…',
    replyAsOwner: 'Reply as owner',
    replyAsAgent: 'Reply as agent',
    needContractError: 'You can only review after a completed contract linked to this property.',
    invalidSessionError: 'Invalid session.',
    duplicateError: 'You have already reviewed this subject for this contract.',
    saveError: 'We could not save the review. Please try again.',
    saveSuccess: 'Review registered.',
    reviewerVerifiedLabel: 'Verified client',
    contractConfirmedBadge: 'Confirmed contract',
    emptyEncourage: 'Be the first to share your experience and help build trust in this community.',
  },
  social: {
    title: 'Property interaction',
    subtitle: 'Quick actions right under the photos.',
    toolbarAria: 'Property social actions',
    likes: 'Likes',
    favorites: 'Favorites',
    comments: 'Comments',
    questions: 'Questions',
    ask: 'Ask',
    evaluate: 'Rate',
    tapHint: 'Tap a button above to comment, ask or share.',
    like: 'Like',
    unlike: 'Unlike',
    favorite: 'Favorite',
    unfavorite: 'Unfavorite',
    share: 'Share',
    copyLink: 'Copy link',
    shareNative: 'Share via device',
    shareTitle: 'Kuteka property',
    shareNativeText: 'See this property on Kuteka',
    shareWhatsAppPrefix: 'See this property on Kuteka:',
    shareCopied: 'Link copied.',
    shareOk: 'Share started.',
    shareError: 'Could not share. Try copying the link.',
    commentTab: 'Comment',
    questionTab: 'Ask',
    commentPlaceholder: 'Write a comment…',
    questionPlaceholder: 'Ask the partner or Kuteka…',
    answerPlaceholder: 'Answer the question…',
    submitComment: 'Publish comment',
    submitQuestion: 'Send question',
    submitAnswer: 'Reply',
    report: 'Report',
    reportSpam: 'Spam',
    reportOffensive: 'Offensive',
    officialPartner: 'Official reply · Partner',
    officialAgent: 'Official reply · Agent',
    officialKuteka: 'Official reply · Kuteka',
    loading: 'Loading…',
    empty: 'No comments or questions yet. Be the first.',
    emptyComments: 'No comments yet. Be the first.',
    emptyQuestions: 'No questions yet. Be the first.',
    signInHint: 'Sign in to like, favorite or take part.',
    saveError: 'Could not save. Please try again.',
    reportOk: 'Report submitted.',
    postOk: 'Published.',
  },
  subjects: {
    property: 'Property',
    owner: 'Owner',
    agent: 'Agent',
    client: 'Client',
    experience: 'Experience',
  },
  dimensions: {
    estado: 'Condition',
    limpeza: 'Cleanliness',
    localizacao: 'Location',
    honestidade: 'Honesty',
    negociacao: 'Negotiation',
    rapidez: 'Speed',
    acompanhamento: 'Follow-up',
    experiencia_geral: 'Overall experience',
    seriedade: 'Reliability',
    comunicacao: 'Communication',
    desempenho: 'Performance',
    quality: 'Quality',
    cleanliness: 'Cleanliness',
    location: 'Location',
    communication: 'Communication',
    value: 'Value for money',
    accuracy: 'Listing accuracy',
  },
  health: {
    eyebrow: 'Property cockpit',
    title: 'Property Health Panel',
    subtitle: 'Track the Kuteka Index, alerts, trends and automatic recommendations.',
    riskUnrated: 'Not yet rated',
    riskLow: 'Low risk',
    riskModerate: 'Moderate risk',
    riskHigh: 'High risk',
    renovationAlert: 'Alert: renovation recommended',
    noUrgentRenovation: 'No urgent renovation',
    upcomingMaintenance: 'Maintenance due soon',
    tipRenovation:
      'Small facade improvements and professional photography can raise market value by up to about 8%.',
    tipExcellent:
      'Property in excellent condition — keep half-yearly inspections and update the PDK after any works.',
    tipDefault:
      'Schedule the next preventive maintenance and confirm documentation in the Digital Passport.',
    tipLabel: 'Kuteka tip',
    overallState: 'Overall status',
    preparing: 'In preparation',
    conservation: 'Conservation',
    estimatedValue: 'Estimated value',
    lastMaintenance: 'Last maintenance',
    lastInspection: 'Last inspection',
    nextMaintenance: 'Next maintenance',
    nextInspection: 'Next inspection',
    toDefine: 'To be defined',
    views30d: 'Views (30d)',
    visits30d: 'Visits (30d)',
    proposals30d: 'Proposals (30d)',
    estimatedYield: 'Estimated yield',
    valueEvolution: 'Property / value trend',
    indexLabel: 'Index {score}',
    technicalHistory: 'Technical history',
    inspections: 'Inspections',
    valuations: 'Valuations',
    noRecords: 'No records yet.',
  },
  showcase: {
    navAria: 'Property sections',
    navPdk: 'Digital Passport',
    navHealth: 'Health Panel',
    navEvaluation: 'Technical Evaluation',
    navContract: 'Kuteka Contract',
    navHistory: 'History',
    navReviews: 'Reviews',
  },
  gallery: {
    ariaTemplate: 'Gallery of {title}',
    empty: 'No photo or video',
    video: 'Video',
    photo: 'Photo',
    thumbAriaTemplate: '{kind} {n} of {title}',
  },
  facts: {
    yes: 'Yes',
    no: 'No',
    eyebrow: 'Property sheet',
    title: 'Essential information',
    description: 'Description',
    typology: 'Typology',
    commercialPurpose: 'Commercial purpose',
    managementLevel: 'Management level',
    province: 'Province',
    municipality: 'Municipality',
    commune: 'Commune',
    city: 'City',
    neighborhood: 'Neighborhood',
    street: 'Street',
    streetNumber: 'Number',
    gps: 'GPS coordinates',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    usefulArea: 'Useful area',
    totalArea: 'Total area',
    floors: 'Floors',
    parking: 'Parking',
    yearBuilt: 'Year built',
    conservation: 'Conservation state',
    construction: 'Construction status',
    renovation: 'Renovation',
    monthlyCondo: 'Monthly condo fees',
    pipedWater: 'Piped water',
    electricity: 'Electricity',
    generator: 'Generator',
    internet: 'Internet',
    security: 'Security',
    pavedStreet: 'Paved street',
    nearSchools: 'Nearby schools',
    nearHospitals: 'Nearby hospitals',
    nearMarkets: 'Nearby markets',
    nearTransport: 'Nearby transport',
    amenitiesTitle: 'Amenities & services',
    condoRulesTitle: 'Condo rules',
    video: 'Home video',
    videoSoon: 'Video · coming soon',
    tour: '360° tour',
    tourSoon: '360° tour · coming soon',
    floorPlan: 'Floor plan',
    floorPlanSoon: 'Floor plan · coming soon',
    documents: 'Documents',
    documentsOnRequest: 'Documents · on request',
    parkingTemplate: '{n} space(s)',
    areaM2Template: '{n} m²',
  },
  passport: {
    eyebrow: 'KTK Digital Passport',
    title: 'Permanent property identity',
    printButton: 'View / print document',
    propertyCode: 'Property code',
    yearBuilt: 'Year built',
    constructionStatus: 'Construction status',
    conservation: 'Conservation',
    contractedManagement: 'Contracted management',
    unfinishedWorks: 'Unfinished works',
    owners: 'Owners',
    contracts: 'Contracts',
    reviews: 'Reviews',
    maintenances: 'Maintenance',
    photos: 'Photos',
    kutekaServices: 'Kuteka services',
    renovations: 'Renovations / value-up',
    ownerHistory: 'Owner history',
    ownerHistoryEmpty: 'Current title holder on Kuteka',
    commercialHistory: 'Commercial / valuation history',
    maintenanceHistory: 'Maintenance history',
    inspectionHistory: 'Inspection history',
    historyEmpty: 'No records yet — they will be added across the lifecycle.',
    indexLabel: 'Index {score}',
    legalDocs: 'Documentation / legal',
    commercialNotes: 'Commercial notes',
    openDocuments: 'Open validated documents',
  },
  map: {
    title: 'Location',
    titleWithSurroundings: 'Location & surroundings',
    noCoords: 'Map available once the property has GPS coordinates on record.',
    exactLocation: 'Exact location (authorized)',
    approximateLocation: 'Approximate area (owner privacy)',
    openStreetMap: 'OpenStreetMap',
    streetView: 'Street View',
    googleMaps: 'Google Maps',
    iframeTitle: 'Property map',
    poisTitle: 'Nearby points of interest',
    etaDisclaimer: 'Estimated times in normal traffic — confirm on Street View / full map.',
    poiSchools: 'Schools / colleges',
    poiSchoolsEta: '5–12 min',
    poiSchoolsKind: 'education',
    poiHospitals: 'Hospitals / clinics',
    poiHospitalsEta: '10–20 min',
    poiHospitalsKind: 'health',
    poiMarkets: 'Markets / supermarkets',
    poiMarketsEta: '5–15 min',
    poiMarketsKind: 'commerce',
    poiTransport: 'Public transport',
    poiTransportEta: '5–10 min',
    poiTransportKind: 'mobility',
    poiBanks: 'Banks / ATM',
    poiBanksEta: '8–18 min',
    poiBanksKind: 'services',
  },
  timeline: {
    title: 'Property history',
    loading: 'Loading timeline…',
    empty:
      'The timeline records registration, documentation, inspection, evaluation, publication, visits, proposals, contracts and renewals.',
    subtitle: 'Full timeline — each event with date, responsible party and description.',
    responsibleTemplate: 'Responsible: {name}',
    actorUser: 'Kuteka user',
    actorTeam: 'Kuteka team',
    actorSystem: 'Kuteka system',
    types: {
      registered: 'Registration',
      documents: 'Documentation',
      inspection: 'Inspection',
      evaluation: 'Evaluation',
      renovation: 'Renovation',
      service_contract: 'Kuteka contract',
      published: 'Publication',
      interest: 'Interest',
      visit: 'Visit',
      proposal: 'Proposal',
      negotiation: 'Negotiation',
      contract: 'Contract',
      payment: 'Payment',
      review: 'Review',
      completed: 'Completion',
      renewal: 'Renewal',
    },
  },
  evaluation: {
    loading: 'Loading technical evaluation…',
    title: 'Technical evaluation',
    titleFull: 'Technical & commercial evaluation',
    empty:
      'No report yet. Management, renovation or construction-completion services require a Cap.6 evaluation before full publication.',
    eyebrow: 'Manual Cap.6',
    printReport: 'PDF report / print',
    calculatedIndex: 'Calculated index',
    suggestedPrice: 'Suggested price',
    reportDate: 'Report date',
    dimsTitle: 'Score by dimension',
    checklistTitle: 'Technical checklist',
    inspectionPhotos: 'Inspection photos',
    photosPending: 'Inspection photos will be attached by the Agent after the technical visit.',
    reportNotes: 'Notes / report',
    recommendations: 'Recommendations & value-up plan',
    counterProposal: 'Price counter-proposal',
    status: {
      draft: 'In preparation',
      submitted: 'Submitted',
      approved: 'Approved',
      rejected: 'Rejected',
    },
    risk: {
      low: 'Low risk',
      medium: 'Moderate risk',
      high: 'High risk',
    },
    dims: {
      structure: 'Structure',
      location: 'Location',
      documentation: 'Documentation',
      finishes: 'Finishes',
      profitability: 'Profitability',
      security: 'Security',
    },
  },
  serviceContract: {
    eyebrow: 'Manual Cap.7',
    title: 'Kuteka ↔ Partner service contract',
    subtitle:
      'Status, validity, signature and history — distinct from the Client–Partner contract.',
    loading: 'Loading contracts…',
    empty:
      'No service contract yet. When activating a property with Kuteka services, the system automatically drafts a contract.',
    versionExclusivityTemplate: 'Version {version} · Exclusivity: {exclusivity}',
    created: 'Created',
    validFrom: 'Valid from',
    validUntil: 'Valid until',
    signature: 'Signature',
    awaitingAcceptance: 'Awaiting acceptance',
    pending: 'Pending',
    cancelledOnTemplate: 'Cancelled on {date}',
    downloadPdf: 'Download / print PDF',
    openDocument: 'Open document',
    renewalContact: 'Renewal: contact Kuteka',
    types: {
      intermediation_sale: 'Sale intermediation',
      intermediation_rent: 'Rental intermediation',
      full_management: 'Full management',
      patrimonial_valuation: 'Property valuation',
      legal_admin: 'Legal and administrative services',
      photography: 'Photo session',
      technical_visit: 'Technical visit',
      renovation: 'Renovation',
      construction_finish: 'Construction completion',
      home_staging: 'Home Staging',
      cleaning: 'Cleaning',
      maintenance: 'Maintenance',
      works_supervision: 'Works supervision',
      condo_admin: 'Condo administration',
      evaluation: 'Professional evaluation',
    },
    status: {
      draft: 'Draft',
      pending_acceptance: 'Pending acceptance',
      active: 'Active',
      completed: 'Completed',
      cancelled: 'Cancelled',
    },
  },
  gauge: {
    label: 'Kuteka Index',
    statusGood: 'Good overall condition',
    statusFair: 'Fair condition',
    statusAttention: 'Needs attention',
  },
  cockpit: {
    title: 'Listing cockpit',
    subtitle: 'Last 30 days performance and suggested reading from Kuteka intelligence.',
    views: 'Views',
    favorites: 'Favorites',
    visits: 'Visits',
    proposals: 'Proposals',
    listingScore: 'Listing score',
    unrated: 'Not yet rated',
    recommendedPrice: 'Recommended price (KAI)',
    saleProbability: 'Sale probability',
    rentProbability: 'Rental probability',
    probabilityHigh: 'High',
    probabilityMedium: 'Medium',
    probabilityImprove: 'Needs improvement',
    estimatedYieldTemplate: 'Estimated yield: {pct}%',
  },
  opsLabels: {
    service: {
      announce: 'Only list the property',
      find_buyer: 'Only find a buyer',
      find_tenant: 'Only find a tenant',
      rental_management: 'Hand rental management to Kuteka',
      full_management: 'Hand full property management to Kuteka',
      evaluation: 'Request a professional evaluation',
      photography: 'Request a professional photo session',
      technical_visit: 'Request a technical visit',
      renovation: 'Request renovation',
      renewal: 'Request renewal',
      construction_finish: 'Request construction completion',
      home_staging: 'Request decoration / Home Staging',
      cleaning: 'Request professional cleaning',
      maintenance: 'Request maintenance',
      works_supervision: 'Request works supervision',
      condo_admin: 'Request condo administration',
    },
    management: {
      announce_only: 'List only',
      find_buyer: 'Sell only (find a buyer)',
      find_tenant: 'Rent only (find a tenant)',
      rental_management: 'Rental management by Kuteka',
      full_management: 'Full property management by Kuteka',
    },
    renovation: {
      full_renovation: 'Full renovation',
      partial_renovation: 'Partial renovation',
      painting: 'Painting',
      electricity: 'Electricity',
      plumbing: 'Plumbing',
      roof: 'Roofing',
      kitchen: 'Kitchen',
      bathrooms: 'Bathrooms',
      facade: 'Facade',
      gardening: 'Gardening',
      landscaping: 'Landscaping',
      decoration: 'Decoration',
      home_staging: 'Home Staging',
    },
    unfinished: {
      none: 'Not applicable',
      kuteka_finish: 'I want Kuteka to complete the construction',
      budget_only: 'I want a budget to finish the works',
      technical_supervision: 'I only want technical follow-up',
      works_evaluation: 'I only want an evaluation of the works',
    },
    construction: {
      complete: 'Construction complete',
      partial: 'Partially built',
      not_started: 'Works not started',
      needs_finish: 'Needs completion',
    },
    conservation: {
      excellent: 'Excellent',
      good: 'Good',
      fair: 'Fair',
      needs_work: 'Needs work',
      ruin: 'In ruins',
      under_construction: 'Under construction',
    },
    lifecycle: {
      rascunho: 'Draft',
      submetido: 'Submitted',
      em_analise_kai: 'KAI review',
      em_analise_admin: 'Admin review',
      pendente: 'Pending',
      correcoes: 'Corrections requested',
      em_preparacao: 'In preparation',
      em_analise_documental: 'In document review',
      em_inspecao_tecnica: 'In technical inspection',
      em_avaliacao: 'In evaluation',
      aprovado: 'Approved',
      janela_premium: 'Premium window',
      publicado: 'Published',
      em_negociacao: 'In negotiation',
      reservado: 'Reserved',
      contrato: 'Contract',
      vendido: 'Sold',
      arrendado: 'Rented',
      em_utilizacao: 'In use',
      libertacao_prevista: 'Release scheduled',
      disponivel_novamente: 'Available again',
      em_manutencao: 'In maintenance',
      temporariamente_indisponivel: 'Temporarily unavailable',
      arquivado: 'Archived',
    },
    partnerCategory: {
      A: 'A · Private Owner',
      B: 'B · Investor Owner',
      C: 'C · Owner Companies',
      D: 'D · Real Estate Developers',
      E: 'E · Resident Abroad',
      F: 'F · Full Kuteka Management',
      G: 'G · Value-appreciation Properties',
    },
    partnerLifecycleStage: {
      descoberta: 'Discovery',
      registo: 'Registration',
      verificacao: 'Verification',
      registo_patrimonio: 'Property registration',
      verificacao_tecnica: 'Technical verification',
      avaliacao: 'Evaluation',
      contrato_servicos: 'Service contract',
      publicacao: 'Publication',
      gestao_comercial: 'Commercial management',
      negociacao: 'Negotiation',
      formalizacao: 'Formalization',
      pos_contrato: 'Post-contract',
      avaliacao_experiencia: 'Experience evaluation',
      fidelizacao: 'Loyalty',
      reativacao: 'Reactivation',
    },
    amenities: {
      internet: 'Internet',
      energia: 'Power',
      agua: 'Water',
      seguranca: 'Security',
      estacionamento: 'Parking',
      piscina: 'Pool',
      jardim: 'Garden',
      acessibilidade: 'Accessibility',
    },
  },
};
