import type { ListingsCopy } from './pt';

export const listingsCopyEs: ListingsCopy = {
  reviews: {
    starsAriaTemplate: '{n} de 5 estrellas',
    title: 'Reputación y reseñas',
    subtitle: 'Estrellas, comentarios, respuestas e historial — después de un contrato concluido.',
    averageTemplate: 'Media general {avg} · {count} reseña(s)',
    writeTitle: 'Escribir una reseña',
    unavailable: 'Disponible después de un contrato concluido en este patrimonio.',
    contractLabel: 'Contrato',
    subjectLabel: 'Asunto',
    ratingLabel: 'Calificación',
    commentLabel: 'Comentario',
    commentPlaceholder: 'Describa la experiencia…',
    submitting: 'Guardando…',
    submit: 'Publicar reseña',
    loading: 'Cargando reseñas…',
    empty:
      'Aún no hay reseñas públicas. Aparecen cuando se concluye un contrato y las partes comparten su opinión.',
    ownerReply: 'Respuesta del propietario',
    agentReply: 'Respuesta del agente',
    replyPlaceholder: 'Escribir una respuesta pública…',
    replyAsOwner: 'Responder como propietario',
    replyAsAgent: 'Responder como agente',
    needContractError:
      'Solo puede valorar después de un contrato concluido asociado a este inmueble.',
    invalidSessionError: 'Sesión inválida.',
    duplicateError: 'Ya valoró este asunto en este contrato.',
    saveError: 'No pudimos guardar la valoración. Inténtelo de nuevo.',
    saveSuccess: 'Valoración registrada.',
    reviewerVerifiedLabel: 'Cliente verificado',
    contractConfirmedBadge: 'Contrato confirmado',
    emptyEncourage:
      'Sea el primero en compartir su experiencia y ayude a construir confianza en esta comunidad.',
  },
  social: {
    title: 'Comunidad del inmueble',
    subtitle: 'Me gusta, favoritos, comentarios y preguntas oficiales.',
    likes: 'Me gusta',
    favorites: 'Favoritos',
    comments: 'Comentarios',
    questions: 'Preguntas',
    like: 'Me gusta',
    unlike: 'Quitar me gusta',
    favorite: 'Favorito',
    unfavorite: 'Quitar favorito',
    commentTab: 'Comentar',
    questionTab: 'Preguntar',
    commentPlaceholder: 'Escriba un comentario…',
    questionPlaceholder: 'Haga una pregunta al socio o a Kuteka…',
    answerPlaceholder: 'Responder a la pregunta…',
    submitComment: 'Publicar comentario',
    submitQuestion: 'Enviar pregunta',
    submitAnswer: 'Responder',
    report: 'Denunciar',
    reportSpam: 'Spam',
    reportOffensive: 'Ofensivo',
    officialPartner: 'Respuesta oficial · Socio',
    officialAgent: 'Respuesta oficial · Agente',
    officialKuteka: 'Respuesta oficial · Kuteka',
    loading: 'Cargando…',
    empty: 'Aún no hay comentarios ni preguntas. Sea el primero.',
    signInHint: 'Inicie sesión para dar me gusta, favoritar o participar.',
    saveError: 'No se pudo guardar. Inténtelo de nuevo.',
    reportOk: 'Denuncia registrada.',
    postOk: 'Publicado.',
  },
  subjects: {
    property: 'Inmueble',
    owner: 'Propietario',
    agent: 'Agente',
    client: 'Cliente',
    experience: 'Experiencia',
  },
  dimensions: {
    estado: 'Estado',
    limpeza: 'Limpieza',
    localizacao: 'Ubicación',
    honestidade: 'Honestidad',
    negociacao: 'Negociación',
    rapidez: 'Rapidez',
    acompanhamento: 'Seguimiento',
    experiencia_geral: 'Experiencia general',
    seriedade: 'Seriedad',
    comunicacao: 'Comunicación',
    desempenho: 'Desempeño',
    quality: 'Calidad',
    cleanliness: 'Limpieza',
    location: 'Ubicación',
    communication: 'Comunicación',
    value: 'Relación calidad/precio',
    accuracy: 'Precisión del anuncio',
  },
  health: {
    eyebrow: 'Cockpit patrimonial',
    title: 'Panel de Salud del Patrimonio',
    subtitle: 'Siga el Índice Kuteka, alertas, evolución y recomendaciones automáticas.',
    riskUnrated: 'Por evaluar',
    riskLow: 'Riesgo bajo',
    riskModerate: 'Riesgo moderado',
    riskHigh: 'Riesgo alto',
    renovationAlert: 'Alerta: remodelación recomendada',
    noUrgentRenovation: 'Sin remodelación urgente',
    upcomingMaintenance: 'Mantenimiento previsto próximamente',
    tipRenovation:
      'Pequeñas mejoras en la fachada y fotografía profesional pueden aumentar el valor de mercado hasta un 8% aproximadamente.',
    tipExcellent:
      'Patrimonio en excelente estado — mantenga inspecciones semestrales y actualice el PDK tras cualquier obra.',
    tipDefault:
      'Programe el próximo mantenimiento preventivo y confirme la documentación en el Pasaporte Digital.',
    tipLabel: 'Consejo Kuteka',
    overallState: 'Estado general',
    preparing: 'En preparación',
    conservation: 'Conservación',
    estimatedValue: 'Valor estimado',
    lastMaintenance: 'Último mantenimiento',
    lastInspection: 'Última inspección',
    nextMaintenance: 'Próximo mantenimiento',
    nextInspection: 'Próxima inspección',
    toDefine: 'Por definir',
    views30d: 'Visualizaciones (30d)',
    visits30d: 'Visitas (30d)',
    proposals30d: 'Propuestas (30d)',
    estimatedYield: 'Rentabilidad estimada',
    valueEvolution: 'Evolución del inmueble / valor',
    indexLabel: 'Índice {score}',
    technicalHistory: 'Historial técnico',
    inspections: 'Inspecciones',
    valuations: 'Valoraciones',
    noRecords: 'Aún sin registros.',
  },
  showcase: {
    navAria: 'Secciones de la ficha',
    navPdk: 'Pasaporte Digital',
    navHealth: 'Panel de Salud',
    navEvaluation: 'Evaluación Técnica',
    navContract: 'Contrato Kuteka',
    navHistory: 'Historial',
    navReviews: 'Valoraciones',
  },
  gallery: {
    ariaTemplate: 'Galería de {title}',
    empty: 'Sin fotografía ni vídeo',
    video: 'Vídeo',
    photo: 'Fotografía',
    thumbAriaTemplate: '{kind} {n} de {title}',
  },
  facts: {
    yes: 'Sí',
    no: 'No',
    eyebrow: 'Ficha del patrimonio',
    title: 'Información esencial',
    description: 'Descripción',
    typology: 'Tipología',
    commercialPurpose: 'Finalidad comercial',
    managementLevel: 'Nivel de gestión',
    province: 'Provincia',
    municipality: 'Municipio',
    commune: 'Comuna',
    city: 'Ciudad',
    neighborhood: 'Barrio',
    street: 'Calle',
    streetNumber: 'Número',
    gps: 'Coordenadas GPS',
    bedrooms: 'Dormitorios',
    bathrooms: 'Baños',
    usefulArea: 'Área útil',
    totalArea: 'Área total',
    floors: 'Pisos',
    parking: 'Estacionamiento',
    yearBuilt: 'Año de construcción',
    conservation: 'Estado de conservación',
    construction: 'Estado de la construcción',
    renovation: 'Remodelación',
    monthlyCondo: 'Costes mensuales (condominio)',
    pipedWater: 'Agua canalizada',
    electricity: 'Energía eléctrica',
    generator: 'Generador',
    internet: 'Internet',
    security: 'Seguridad',
    pavedStreet: 'Calle pavimentada',
    nearSchools: 'Escuelas cercanas',
    nearHospitals: 'Hospitales cercanos',
    nearMarkets: 'Mercados cercanos',
    nearTransport: 'Transportes cercanos',
    amenitiesTitle: 'Comodidades y servicios',
    condoRulesTitle: 'Normas del condominio',
    video: 'Vídeo de la casa',
    videoSoon: 'Vídeo · próximamente',
    tour: 'Visita 360°',
    tourSoon: 'Visita 360° · próximamente',
    floorPlan: 'Plano',
    floorPlanSoon: 'Plano · próximamente',
    documents: 'Documentos',
    documentsOnRequest: 'Documentos · bajo petición',
    parkingTemplate: '{n} plaza(s)',
    areaM2Template: '{n} m²',
  },
  passport: {
    eyebrow: 'Pasaporte Digital KTK',
    title: 'Identidad permanente del inmueble',
    printButton: 'Ver / imprimir documento',
    propertyCode: 'Código patrimonial',
    yearBuilt: 'Año de construcción',
    constructionStatus: 'Estado de la construcción',
    conservation: 'Conservación',
    contractedManagement: 'Gestión contratada',
    unfinishedWorks: 'Obra inacabada',
    owners: 'Propietarios',
    contracts: 'Contratos',
    reviews: 'Valoraciones',
    maintenances: 'Mantenimientos',
    photos: 'Fotografías',
    kutekaServices: 'Servicios Kuteka',
    renovations: 'Remodelaciones / valorización',
    ownerHistory: 'Historial de propietarios',
    ownerHistoryEmpty: 'Titular actual en Kuteka',
    commercialHistory: 'Historial comercial / valorizaciones',
    maintenanceHistory: 'Historial de mantenimiento',
    inspectionHistory: 'Historial de inspecciones',
    historyEmpty: 'Aún sin registros — se añadirán a lo largo del ciclo de vida.',
    indexLabel: 'Índice {score}',
    legalDocs: 'Documentación / jurídico',
    commercialNotes: 'Notas comerciales',
    openDocuments: 'Abrir documentos validados',
  },
  map: {
    title: 'Ubicación',
    titleWithSurroundings: 'Ubicación y entorno',
    noCoords: 'Mapa disponible cuando el patrimonio tenga coordenadas GPS registradas.',
    exactLocation: 'Ubicación exacta (autorizada)',
    approximateLocation: 'Zona aproximada (privacidad del propietario)',
    openStreetMap: 'OpenStreetMap',
    streetView: 'Street View',
    googleMaps: 'Google Maps',
    iframeTitle: 'Mapa del patrimonio',
    poisTitle: 'Puntos de interés cercanos',
    etaDisclaimer:
      'Tiempos estimados en condiciones normales de tráfico — confirme en Street View / mapa completo.',
    poiSchools: 'Escuelas / colegios',
    poiSchoolsEta: '5–12 min',
    poiSchoolsKind: 'educación',
    poiHospitals: 'Hospitales / clínicas',
    poiHospitalsEta: '10–20 min',
    poiHospitalsKind: 'salud',
    poiMarkets: 'Mercados / supermercados',
    poiMarketsEta: '5–15 min',
    poiMarketsKind: 'comercio',
    poiTransport: 'Transportes públicos',
    poiTransportEta: '5–10 min',
    poiTransportKind: 'movilidad',
    poiBanks: 'Bancos / ATM',
    poiBanksEta: '8–18 min',
    poiBanksKind: 'servicios',
  },
  timeline: {
    title: 'Historial del inmueble',
    loading: 'Cargando línea temporal…',
    empty:
      'La línea temporal registra el registro, documentación, inspección, evaluación, publicación, visitas, propuestas, contratos y renovaciones.',
    subtitle: 'Línea temporal completa — cada evento con fecha, responsable y descripción.',
    responsibleTemplate: 'Responsable: {name}',
    actorUser: 'Usuario Kuteka',
    actorTeam: 'Equipo Kuteka',
    actorSystem: 'Sistema Kuteka',
    types: {
      registered: 'Registro',
      documents: 'Documentación',
      inspection: 'Inspección',
      evaluation: 'Evaluación',
      renovation: 'Remodelación',
      service_contract: 'Contrato Kuteka',
      published: 'Publicación',
      interest: 'Interés',
      visit: 'Visita',
      proposal: 'Propuesta',
      negotiation: 'Negociación',
      contract: 'Contrato',
      payment: 'Pago',
      review: 'Valoración',
      completed: 'Conclusión',
      renewal: 'Renovación',
    },
  },
  evaluation: {
    loading: 'Cargando evaluación técnica…',
    title: 'Evaluación técnica',
    titleFull: 'Evaluación técnica y comercial',
    empty:
      'Aún no hay informe. Los servicios de gestión, remodelación o finalización de obra exigen evaluación Cap.6 antes de la publicación plena.',
    eyebrow: 'Manual Cap.6',
    printReport: 'Informe PDF / imprimir',
    calculatedIndex: 'Índice calculado',
    suggestedPrice: 'Precio sugerido',
    reportDate: 'Fecha del informe',
    dimsTitle: 'Clasificación por dimensión',
    checklistTitle: 'Checklist técnica',
    inspectionPhotos: 'Fotografías de la inspección',
    photosPending:
      'Las fotografías de inspección serán adjuntadas por el Agente tras la visita técnica.',
    reportNotes: 'Observaciones / informe',
    recommendations: 'Recomendaciones y plan de valorización',
    counterProposal: 'Contrapropuesta de precio',
    status: {
      draft: 'En preparación',
      submitted: 'Enviada',
      approved: 'Aprobada',
      rejected: 'Rechazada',
    },
    risk: {
      low: 'Riesgo bajo',
      medium: 'Riesgo moderado',
      high: 'Riesgo alto',
    },
    dims: {
      structure: 'Estructura',
      location: 'Ubicación',
      documentation: 'Documentación',
      finishes: 'Acabados',
      profitability: 'Rentabilidad',
      security: 'Seguridad',
    },
  },
  serviceContract: {
    eyebrow: 'Manual Cap.7',
    title: 'Contrato de servicios Kuteka ↔ Socio',
    subtitle: 'Estado, validez, firma e historial — distinto del contrato Cliente–Socio.',
    loading: 'Cargando contratos…',
    empty:
      'Aún no existe contrato de servicios. Al activar patrimonio con servicios Kuteka, el sistema genera automáticamente un borrador contractual.',
    versionExclusivityTemplate: 'Versión {version} · Exclusividad: {exclusivity}',
    created: 'Creado',
    validFrom: 'Válido desde',
    validUntil: 'Válido hasta',
    signature: 'Firma',
    awaitingAcceptance: 'Espera aceptación',
    pending: 'Pendiente',
    cancelledOnTemplate: 'Cancelado el {date}',
    downloadPdf: 'Descargar / imprimir PDF',
    openDocument: 'Abrir documento',
    renewalContact: 'Renovación: contacte a Kuteka',
    types: {
      intermediation_sale: 'Intermediación de venta',
      intermediation_rent: 'Intermediación de arrendamiento',
      full_management: 'Gestión total',
      patrimonial_valuation: 'Valorización patrimonial',
      legal_admin: 'Servicios jurídicos y administrativos',
      photography: 'Sesión fotográfica',
      technical_visit: 'Visita técnica',
      renovation: 'Remodelación',
      construction_finish: 'Finalización de construcción',
      home_staging: 'Home Staging',
      cleaning: 'Limpieza',
      maintenance: 'Mantenimiento',
      works_supervision: 'Supervisión de obra',
      condo_admin: 'Administración de condominio',
      evaluation: 'Evaluación profesional',
    },
    status: {
      draft: 'Borrador',
      pending_acceptance: 'Pendiente de aceptación',
      active: 'Activo',
      completed: 'Completado',
      cancelled: 'Cancelado',
    },
  },
  gauge: {
    label: 'Índice Kuteka',
    statusGood: 'Buen estado general',
    statusFair: 'Estado razonable',
    statusAttention: 'Requiere atención',
  },
  cockpit: {
    title: 'Cockpit del anuncio',
    subtitle: 'Rendimiento de los últimos 30 días y lectura sugerida por la inteligencia Kuteka.',
    views: 'Visualizaciones',
    favorites: 'Favoritos',
    visits: 'Visitas',
    proposals: 'Propuestas',
    listingScore: 'Score del anuncio',
    unrated: 'Por evaluar',
    recommendedPrice: 'Precio recomendado (KAI)',
    saleProbability: 'Probabilidad de venta',
    rentProbability: 'Probabilidad de arrendamiento',
    probabilityHigh: 'Alta',
    probabilityMedium: 'Media',
    probabilityImprove: 'A mejorar',
    estimatedYieldTemplate: 'Rendimiento estimado: {pct}%',
  },
  opsLabels: {
    service: {
      announce: 'Solo anunciar el inmueble',
      find_buyer: 'Solo encontrar comprador',
      find_tenant: 'Solo encontrar arrendatario',
      rental_management: 'Entregar la gestión del arrendamiento a Kuteka',
      full_management: 'Entregar la gestión completa del patrimonio a Kuteka',
      evaluation: 'Solicitar evaluación profesional',
      photography: 'Solicitar sesión fotográfica profesional',
      technical_visit: 'Solicitar visita técnica',
      renovation: 'Solicitar remodelación',
      renewal: 'Solicitar renovación',
      construction_finish: 'Solicitar finalización de la construcción',
      home_staging: 'Solicitar decoración / Home Staging',
      cleaning: 'Solicitar limpieza profesional',
      maintenance: 'Solicitar mantenimiento',
      works_supervision: 'Solicitar supervisión de obra',
      condo_admin: 'Solicitar administración del condominio',
    },
    management: {
      announce_only: 'Solo anunciar',
      find_buyer: 'Solo vender (encontrar comprador)',
      find_tenant: 'Solo arrendar (encontrar arrendatario)',
      rental_management: 'Gestión del arrendamiento por Kuteka',
      full_management: 'Gestión completa del patrimonio por Kuteka',
    },
    renovation: {
      full_renovation: 'Remodelación completa',
      partial_renovation: 'Remodelación parcial',
      painting: 'Pintura',
      electricity: 'Electricidad',
      plumbing: 'Fontanería',
      roof: 'Cubierta',
      kitchen: 'Cocina',
      bathrooms: 'Baños',
      facade: 'Fachada',
      gardening: 'Jardinería',
      landscaping: 'Paisajismo',
      decoration: 'Decoración',
      home_staging: 'Home Staging',
    },
    unfinished: {
      none: 'No aplicable',
      kuteka_finish: 'Quiero que Kuteka termine la construcción',
      budget_only: 'Quiero un presupuesto para terminar la obra',
      technical_supervision: 'Solo quiero seguimiento técnico',
      works_evaluation: 'Solo quiero evaluación de la obra',
    },
    construction: {
      complete: 'Construcción terminada',
      partial: 'Parcialmente construido',
      not_started: 'Obra no iniciada',
      needs_finish: 'Necesita finalización',
    },
    conservation: {
      excellent: 'Excelente',
      good: 'Bueno',
      fair: 'Razonable',
      needs_work: 'Necesita intervención',
      ruin: 'En ruina',
      under_construction: 'En construcción',
    },
    lifecycle: {
      rascunho: 'Borrador',
      submetido: 'Enviado',
      em_analise_kai: 'En análisis KAI',
      em_analise_admin: 'En análisis admin',
      pendente: 'Pendiente',
      correcoes: 'Correcciones pedidas',
      em_preparacao: 'En preparación',
      em_analise_documental: 'En análisis documental',
      em_inspecao_tecnica: 'En inspección técnica',
      em_avaliacao: 'En evaluación',
      aprovado: 'Aprobado',
      janela_premium: 'Ventana premium',
      publicado: 'Publicado',
      em_negociacao: 'En negociación',
      reservado: 'Reservado',
      contrato: 'Contrato',
      vendido: 'Vendido',
      arrendado: 'Arrendado',
      em_utilizacao: 'En utilización',
      libertacao_prevista: 'Liberación prevista',
      disponivel_novamente: 'Disponible de nuevo',
      em_manutencao: 'En mantenimiento',
      temporariamente_indisponivel: 'Temporalmente no disponible',
      arquivado: 'Archivado',
    },
    partnerCategory: {
      A: 'A · Propietario particular',
      B: 'B · Propietario inversor',
      C: 'C · Empresas propietarias',
      D: 'D · Promotores inmobiliarios',
      E: 'E · Residente en el extranjero',
      F: 'F · Gestión total Kuteka',
      G: 'G · Inmuebles en valorización',
    },
    partnerLifecycleStage: {
      descoberta: 'Descubrimiento',
      registo: 'Registro',
      verificacao: 'Verificación',
      registo_patrimonio: 'Registro del patrimonio',
      verificacao_tecnica: 'Verificación técnica',
      avaliacao: 'Evaluación',
      contrato_servicos: 'Contrato de servicios',
      publicacao: 'Publicación',
      gestao_comercial: 'Gestión comercial',
      negociacao: 'Negociación',
      formalizacao: 'Formalización',
      pos_contrato: 'Posventa',
      avaliacao_experiencia: 'Evaluación de la experiencia',
      fidelizacao: 'Fidelización',
      reativacao: 'Reactivación',
    },
    amenities: {
      internet: 'Internet',
      energia: 'Energía',
      agua: 'Agua',
      seguranca: 'Seguridad',
      estacionamento: 'Estacionamiento',
      piscina: 'Piscina',
      jardim: 'Jardín',
      acessibilidade: 'Accesibilidad',
    },
  },
};
