import type { ListingsCopy } from './pt';

export const listingsCopyEs: ListingsCopy = {
  reviews: {
    starsAriaTemplate: '{n} de 5 estrellas',
    title: 'Reputación y reseñas',
    subtitle: 'Estrellas, comentarios, respuestas e historial — después de un contrato concluido.',
    averageTemplate: 'Media general {avg} · {count} reseña(s)',
    writeTitle: 'Escribir una reseña',
    unavailable: 'Disponible después de un contrato concluido en este patrimonio.',
    contractLabel: 'Contrato',
    subjectLabel: 'Asunto',
    ratingLabel: 'Calificación',
    commentLabel: 'Comentario',
    commentPlaceholder: 'Describa la experiencia…',
    submitting: 'Guardando…',
    submit: 'Publicar reseña',
    loading: 'Cargando reseñas…',
    empty:
      'Aún no hay reseñas públicas. Aparecen cuando se concluye un contrato y las partes comparten su opinión.',
    ownerReply: 'Respuesta del propietario',
    agentReply: 'Respuesta del agente',
    replyPlaceholder: 'Escribir una respuesta pública…',
    replyAsOwner: 'Responder como propietario',
    replyAsAgent: 'Responder como agente',
    needContractError:
      'Solo puede valorar después de un contrato concluido asociado a este inmueble.',
    invalidSessionError: 'Sesión inválida.',
    duplicateError: 'Ya valoró este asunto en este contrato.',
    saveError: 'No pudimos guardar la valoración. Inténtelo de nuevo.',
    saveSuccess: 'Valoración registrada.',
    reviewerVerifiedLabel: 'Cliente verificado',
    contractConfirmedBadge: 'Contrato confirmado',
    emptyEncourage:
      'Sea el primero en compartir su experiencia y ayude a construir confianza en esta comunidad.',
  },
  subjects: {
    property: 'Inmueble',
    owner: 'Propietario',
    agent: 'Agente',
    client: 'Cliente',
    experience: 'Experiencia',
  },
  dimensions: {
    estado: 'Estado',
    limpeza: 'Limpieza',
    localizacao: 'Ubicación',
    honestidade: 'Honestidad',
    negociacao: 'Negociación',
    rapidez: 'Rapidez',
    acompanhamento: 'Seguimiento',
    experiencia_geral: 'Experiencia general',
    seriedade: 'Seriedad',
    comunicacao: 'Comunicación',
    desempenho: 'Desempeño',
    quality: 'Calidad',
    cleanliness: 'Limpieza',
    location: 'Ubicación',
    communication: 'Comunicación',
    value: 'Relación calidad/precio',
    accuracy: 'Precisión del anuncio',
  },
  health: {
    eyebrow: 'Cockpit patrimonial',
    title: 'Panel de Salud del Patrimonio',
    subtitle: 'Siga el Índice Kuteka, alertas, evolución y recomendaciones automáticas.',
    riskUnrated: 'Por evaluar',
    riskLow: 'Riesgo bajo',
    riskModerate: 'Riesgo moderado',
    riskHigh: 'Riesgo alto',
    renovationAlert: 'Alerta: remodelación recomendada',
    noUrgentRenovation: 'Sin remodelación urgente',
    upcomingMaintenance: 'Mantenimiento previsto próximamente',
    tipRenovation:
      'Pequeñas mejoras en la fachada y fotografía profesional pueden aumentar el valor de mercado hasta un 8% aproximadamente.',
    tipExcellent:
      'Patrimonio en excelente estado — mantenga inspecciones semestrales y actualice el PDK tras cualquier obra.',
    tipDefault:
      'Programe el próximo mantenimiento preventivo y confirme la documentación en el Pasaporte Digital.',
    tipLabel: 'Consejo Kuteka',
    overallState: 'Estado general',
    preparing: 'En preparación',
    conservation: 'Conservación',
    estimatedValue: 'Valor estimado',
    lastMaintenance: 'Último mantenimiento',
    lastInspection: 'Última inspección',
    nextMaintenance: 'Próximo mantenimiento',
    nextInspection: 'Próxima inspección',
    toDefine: 'Por definir',
    views30d: 'Visualizaciones (30d)',
    visits30d: 'Visitas (30d)',
    proposals30d: 'Propuestas (30d)',
    estimatedYield: 'Rentabilidad estimada',
    valueEvolution: 'Evolución del inmueble / valor',
    indexLabel: 'Índice {score}',
    technicalHistory: 'Historial técnico',
    inspections: 'Inspecciones',
    valuations: 'Valoraciones',
    noRecords: 'Aún sin registros.',
  },
  opsLabels: {
    service: {
      announce: 'Solo anunciar el inmueble',
      find_buyer: 'Solo encontrar comprador',
      find_tenant: 'Solo encontrar arrendatario',
      rental_management: 'Entregar la gestión del arrendamiento a Kuteka',
      full_management: 'Entregar la gestión completa del patrimonio a Kuteka',
      evaluation: 'Solicitar evaluación profesional',
      photography: 'Solicitar sesión fotográfica profesional',
      technical_visit: 'Solicitar visita técnica',
      renovation: 'Solicitar remodelación',
      renewal: 'Solicitar renovación',
      construction_finish: 'Solicitar finalización de la construcción',
      home_staging: 'Solicitar decoración / Home Staging',
      cleaning: 'Solicitar limpieza profesional',
      maintenance: 'Solicitar mantenimiento',
      works_supervision: 'Solicitar supervisión de obra',
      condo_admin: 'Solicitar administración del condominio',
    },
    management: {
      announce_only: 'Solo anunciar',
      find_buyer: 'Solo vender (encontrar comprador)',
      find_tenant: 'Solo arrendar (encontrar arrendatario)',
      rental_management: 'Gestión del arrendamiento por Kuteka',
      full_management: 'Gestión completa del patrimonio por Kuteka',
    },
    renovation: {
      full_renovation: 'Remodelación completa',
      partial_renovation: 'Remodelación parcial',
      painting: 'Pintura',
      electricity: 'Electricidad',
      plumbing: 'Fontanería',
      roof: 'Cubierta',
      kitchen: 'Cocina',
      bathrooms: 'Baños',
      facade: 'Fachada',
      gardening: 'Jardinería',
      landscaping: 'Paisajismo',
      decoration: 'Decoración',
      home_staging: 'Home Staging',
    },
    unfinished: {
      none: 'No aplicable',
      kuteka_finish: 'Quiero que Kuteka termine la construcción',
      budget_only: 'Quiero un presupuesto para terminar la obra',
      technical_supervision: 'Solo quiero seguimiento técnico',
      works_evaluation: 'Solo quiero evaluación de la obra',
    },
    construction: {
      complete: 'Construcción terminada',
      partial: 'Parcialmente construido',
      not_started: 'Obra no iniciada',
      needs_finish: 'Necesita finalización',
    },
    conservation: {
      excellent: 'Excelente',
      good: 'Bueno',
      fair: 'Razonable',
      needs_work: 'Necesita intervención',
      ruin: 'En ruina',
      under_construction: 'En construcción',
    },
    lifecycle: {
      em_preparacao: 'En preparación',
      em_analise_documental: 'En análisis documental',
      em_inspecao_tecnica: 'En inspección técnica',
      em_avaliacao: 'En evaluación',
      aprovado: 'Aprobado',
      publicado: 'Publicado',
      em_negociacao: 'En negociación',
      reservado: 'Reservado',
      vendido: 'Vendido',
      arrendado: 'Arrendado',
      em_manutencao: 'En mantenimiento',
      temporariamente_indisponivel: 'Temporalmente no disponible',
      arquivado: 'Archivado',
    },
    partnerCategory: {
      A: 'A · Propietario particular',
      B: 'B · Propietario inversor',
      C: 'C · Empresas propietarias',
      D: 'D · Promotores inmobiliarios',
      E: 'E · Residente en el extranjero',
      F: 'F · Gestión total Kuteka',
      G: 'G · Inmuebles en valorización',
    },
    partnerLifecycleStage: {
      descoberta: 'Descubrimiento',
      registo: 'Registro',
      verificacao: 'Verificación',
      registo_patrimonio: 'Registro del patrimonio',
      verificacao_tecnica: 'Verificación técnica',
      avaliacao: 'Evaluación',
      contrato_servicos: 'Contrato de servicios',
      publicacao: 'Publicación',
      gestao_comercial: 'Gestión comercial',
      negociacao: 'Negociación',
      formalizacao: 'Formalización',
      pos_contrato: 'Posventa',
      avaliacao_experiencia: 'Evaluación de la experiencia',
      fidelizacao: 'Fidelización',
      reativacao: 'Reactivación',
    },
    amenities: {
      internet: 'Internet',
      energia: 'Energía',
      agua: 'Agua',
      seguranca: 'Seguridad',
      estacionamento: 'Estacionamiento',
      piscina: 'Piscina',
      jardim: 'Jardín',
      acessibilidade: 'Accesibilidad',
    },
  },
};
