import type { ListingsCopy } from './pt';

export const listingsCopyFr: ListingsCopy = {
  reviews: {
    starsAriaTemplate: '{n} sur 5 étoiles',
    title: 'Réputation & avis',
    subtitle: 'Étoiles, commentaires, réponses et historique — après un contrat conclu.',
    averageTemplate: 'Moyenne générale {avg} · {count} avis',
    writeTitle: 'Écrire un avis',
    unavailable: 'Disponible après un contrat conclu sur ce patrimoine.',
    contractLabel: 'Contrat',
    subjectLabel: 'Sujet',
    ratingLabel: 'Note',
    commentLabel: 'Commentaire',
    commentPlaceholder: 'Décrivez l’expérience…',
    submitting: 'Enregistrement…',
    submit: 'Publier l’avis',
    loading: 'Chargement des avis…',
    empty:
      'Aucun avis public pour le moment. Ils apparaissent une fois un contrat conclu et les parties partagent leur retour.',
    ownerReply: 'Réponse du propriétaire',
    agentReply: 'Réponse de l’agent',
    replyPlaceholder: 'Écrire une réponse publique…',
    replyAsOwner: 'Répondre en tant que propriétaire',
    replyAsAgent: 'Répondre en tant qu’agent',
    needContractError: 'Vous ne pouvez évaluer qu’après un contrat conclu lié à ce bien.',
    invalidSessionError: 'Session invalide.',
    duplicateError: 'Vous avez déjà évalué ce sujet pour ce contrat.',
    saveError: 'Nous n’avons pas pu enregistrer l’avis. Veuillez réessayer.',
    saveSuccess: 'Avis enregistré.',
    reviewerVerifiedLabel: 'Client vérifié',
    contractConfirmedBadge: 'Contrat confirmé',
    emptyEncourage:
      'Soyez le premier à partager votre expérience et aidez à construire la confiance dans cette communauté.',
  },
  subjects: {
    property: 'Bien',
    owner: 'Propriétaire',
    agent: 'Agent',
    client: 'Client',
    experience: 'Expérience',
  },
  dimensions: {
    estado: 'État',
    limpeza: 'Propreté',
    localizacao: 'Emplacement',
    honestidade: 'Honnêteté',
    negociacao: 'Négociation',
    rapidez: 'Rapidité',
    acompanhamento: 'Suivi',
    experiencia_geral: 'Expérience globale',
    seriedade: 'Sérieux',
    comunicacao: 'Communication',
    desempenho: 'Performance',
    quality: 'Qualité',
    cleanliness: 'Propreté',
    location: 'Emplacement',
    communication: 'Communication',
    value: 'Rapport qualité/prix',
    accuracy: 'Exactitude de l’annonce',
  },
  health: {
    eyebrow: 'Cockpit du patrimoine',
    title: 'Panneau de santé du patrimoine',
    subtitle:
      'Suivez l’Indice Kuteka, les alertes, l’évolution et les recommandations automatiques.',
    riskUnrated: 'À évaluer',
    riskLow: 'Risque faible',
    riskModerate: 'Risque modéré',
    riskHigh: 'Risque élevé',
    renovationAlert: 'Alerte : rénovation recommandée',
    noUrgentRenovation: 'Pas de rénovation urgente',
    upcomingMaintenance: 'Maintenance prévue prochainement',
    tipRenovation:
      'De petites améliorations de façade et une photographie professionnelle peuvent augmenter la valeur marchande d’environ 8 %.',
    tipExcellent:
      'Patrimoine en excellent état — maintenez des inspections semestrielles et mettez à jour le PDK après toute rénovation.',
    tipDefault:
      'Planifiez la prochaine maintenance préventive et confirmez la documentation dans le Passeport Numérique.',
    tipLabel: 'Astuce Kuteka',
    overallState: 'État général',
    preparing: 'En préparation',
    conservation: 'Conservation',
    estimatedValue: 'Valeur estimée',
    lastMaintenance: 'Dernière maintenance',
    lastInspection: 'Dernière inspection',
    nextMaintenance: 'Prochaine maintenance',
    nextInspection: 'Prochaine inspection',
    toDefine: 'À définir',
    views30d: 'Vues (30j)',
    visits30d: 'Visites (30j)',
    proposals30d: 'Propositions (30j)',
    estimatedYield: 'Rendement estimé',
    valueEvolution: 'Évolution du bien / de la valeur',
    indexLabel: 'Indice {score}',
    technicalHistory: 'Historique technique',
    inspections: 'Inspections',
    valuations: 'Valorisations',
    noRecords: 'Aucun enregistrement pour le moment.',
  },
  showcase: {
    navAria: 'Sections de la fiche',
    navPdk: 'Passeport numérique',
    navHealth: 'Panneau de santé',
    navEvaluation: 'Évaluation technique',
    navContract: 'Contrat Kuteka',
    navHistory: 'Historique',
    navReviews: 'Avis',
  },
  gallery: {
    ariaTemplate: 'Galerie de {title}',
    empty: 'Pas de photo ni de vidéo',
    video: 'Vidéo',
    photo: 'Photographie',
    thumbAriaTemplate: '{kind} {n} de {title}',
  },
  facts: {
    yes: 'Oui',
    no: 'Non',
    eyebrow: 'Fiche du patrimoine',
    title: 'Informations essentielles',
    description: 'Description',
    typology: 'Typologie',
    commercialPurpose: 'Finalité commerciale',
    managementLevel: 'Niveau de gestion',
    province: 'Province',
    municipality: 'Municipalité',
    commune: 'Commune',
    city: 'Ville',
    neighborhood: 'Quartier',
    street: 'Rue',
    streetNumber: 'Numéro',
    gps: 'Coordonnées GPS',
    bedrooms: 'Chambres',
    bathrooms: 'Salles de bain',
    usefulArea: 'Surface utile',
    totalArea: 'Surface totale',
    floors: 'Étages',
    parking: 'Stationnement',
    yearBuilt: 'Année de construction',
    conservation: 'État de conservation',
    construction: 'État de la construction',
    renovation: 'Rénovation',
    monthlyCondo: 'Charges mensuelles (copropriété)',
    pipedWater: 'Eau courante',
    electricity: 'Électricité',
    generator: 'Générateur',
    internet: 'Internet',
    security: 'Sécurité',
    pavedStreet: 'Rue pavée',
    nearSchools: 'Écoles à proximité',
    nearHospitals: 'Hôpitaux à proximité',
    nearMarkets: 'Marchés à proximité',
    nearTransport: 'Transports à proximité',
    amenitiesTitle: 'Commodités & services',
    condoRulesTitle: 'Règlement de copropriété',
    video: 'Vidéo du bien',
    videoSoon: 'Vidéo · bientôt',
    tour: 'Visite 360°',
    tourSoon: 'Visite 360° · bientôt',
    floorPlan: 'Plan',
    floorPlanSoon: 'Plan · bientôt',
    documents: 'Documents',
    documentsOnRequest: 'Documents · sur demande',
    parkingTemplate: '{n} place(s)',
    areaM2Template: '{n} m²',
  },
  passport: {
    eyebrow: 'Passeport numérique KTK',
    title: 'Identité permanente du bien',
    printButton: 'Voir / imprimer le document',
    propertyCode: 'Code patrimonial',
    yearBuilt: 'Année de construction',
    constructionStatus: 'État de la construction',
    conservation: 'Conservation',
    contractedManagement: 'Gestion contractée',
    unfinishedWorks: 'Travaux inachevés',
    owners: 'Propriétaires',
    contracts: 'Contrats',
    reviews: 'Avis',
    maintenances: 'Maintenances',
    photos: 'Photographies',
    kutekaServices: 'Services Kuteka',
    renovations: 'Rénovations / valorisation',
    ownerHistory: 'Historique des propriétaires',
    ownerHistoryEmpty: 'Titulaire actuel sur Kuteka',
    commercialHistory: 'Historique commercial / valorisations',
    maintenanceHistory: 'Historique de maintenance',
    inspectionHistory: 'Historique des inspections',
    historyEmpty:
      'Aucun enregistrement pour le moment — ils seront ajoutés au fil du cycle de vie.',
    indexLabel: 'Indice {score}',
    legalDocs: 'Documentation / juridique',
    commercialNotes: 'Notes commerciales',
    openDocuments: 'Ouvrir les documents validés',
  },
  map: {
    title: 'Localisation',
    titleWithSurroundings: 'Localisation & environs',
    noCoords: 'Carte disponible lorsque le patrimoine a des coordonnées GPS enregistrées.',
    exactLocation: 'Localisation exacte (autorisée)',
    approximateLocation: 'Zone approximative (confidentialité du propriétaire)',
    openStreetMap: 'OpenStreetMap',
    streetView: 'Street View',
    googleMaps: 'Google Maps',
    iframeTitle: 'Carte du patrimoine',
    poisTitle: 'Points d’intérêt à proximité',
    etaDisclaimer:
      'Temps estimés en conditions normales de trafic — confirmez sur Street View / carte complète.',
    poiSchools: 'Écoles / collèges',
    poiSchoolsEta: '5–12 min',
    poiSchoolsKind: 'éducation',
    poiHospitals: 'Hôpitaux / cliniques',
    poiHospitalsEta: '10–20 min',
    poiHospitalsKind: 'santé',
    poiMarkets: 'Marchés / supermarchés',
    poiMarketsEta: '5–15 min',
    poiMarketsKind: 'commerce',
    poiTransport: 'Transports publics',
    poiTransportEta: '5–10 min',
    poiTransportKind: 'mobilité',
    poiBanks: 'Banques / ATM',
    poiBanksEta: '8–18 min',
    poiBanksKind: 'services',
  },
  timeline: {
    title: 'Historique du bien',
    loading: 'Chargement de la chronologie…',
    empty:
      'La chronologie enregistre l’inscription, la documentation, l’inspection, l’évaluation, la publication, les visites, les propositions, les contrats et les renouvellements.',
    subtitle: 'Chronologie complète — chaque événement avec date, responsable et description.',
    responsibleTemplate: 'Responsable : {name}',
    actorUser: 'Utilisateur Kuteka',
    actorTeam: 'Équipe Kuteka',
    actorSystem: 'Système Kuteka',
    types: {
      registered: 'Inscription',
      documents: 'Documentation',
      inspection: 'Inspection',
      evaluation: 'Évaluation',
      renovation: 'Rénovation',
      service_contract: 'Contrat Kuteka',
      published: 'Publication',
      interest: 'Intérêt',
      visit: 'Visite',
      proposal: 'Proposition',
      negotiation: 'Négociation',
      contract: 'Contrat',
      payment: 'Paiement',
      review: 'Avis',
      completed: 'Conclusion',
      renewal: 'Renouvellement',
    },
  },
  evaluation: {
    loading: 'Chargement de l’évaluation technique…',
    title: 'Évaluation technique',
    titleFull: 'Évaluation technique & commerciale',
    empty:
      'Aucun rapport pour le moment. Les services de gestion, rénovation ou finition de construction exigent une évaluation Cap.6 avant publication complète.',
    eyebrow: 'Manuel Cap.6',
    printReport: 'Rapport PDF / imprimer',
    calculatedIndex: 'Indice calculé',
    suggestedPrice: 'Prix suggéré',
    reportDate: 'Date du rapport',
    dimsTitle: 'Classification par dimension',
    checklistTitle: 'Checklist technique',
    inspectionPhotos: 'Photos d’inspection',
    photosPending: 'Les photos d’inspection seront jointes par l’Agent après la visite technique.',
    reportNotes: 'Observations / rapport',
    recommendations: 'Recommandations & plan de valorisation',
    counterProposal: 'Contre-proposition de prix',
    status: {
      draft: 'En préparation',
      submitted: 'Soumise',
      approved: 'Approuvée',
      rejected: 'Rejetée',
    },
    risk: {
      low: 'Risque faible',
      medium: 'Risque modéré',
      high: 'Risque élevé',
    },
    dims: {
      structure: 'Structure',
      location: 'Emplacement',
      documentation: 'Documentation',
      finishes: 'Finitions',
      profitability: 'Rentabilité',
      security: 'Sécurité',
    },
  },
  serviceContract: {
    eyebrow: 'Manuel Cap.7',
    title: 'Contrat de services Kuteka ↔ Partenaire',
    subtitle: 'État, validité, signature et historique — distinct du contrat Client–Partenaire.',
    loading: 'Chargement des contrats…',
    empty:
      'Aucun contrat de services pour le moment. Lors de l’activation d’un patrimoine avec services Kuteka, le système génère automatiquement un brouillon contractuel.',
    versionExclusivityTemplate: 'Version {version} · Exclusivité : {exclusivity}',
    created: 'Créé',
    validFrom: 'Valide du',
    validUntil: 'Valide jusqu’au',
    signature: 'Signature',
    awaitingAcceptance: 'En attente d’acceptation',
    pending: 'En attente',
    cancelledOnTemplate: 'Annulé le {date}',
    downloadPdf: 'Télécharger / imprimer PDF',
    openDocument: 'Ouvrir le document',
    renewalContact: 'Renouvellement : contactez Kuteka',
    types: {
      intermediation_sale: 'Intermédiation de vente',
      intermediation_rent: 'Intermédiation de location',
      full_management: 'Gestion totale',
      patrimonial_valuation: 'Valorisation patrimoniale',
      legal_admin: 'Services juridiques et administratifs',
      photography: 'Séance photo',
      technical_visit: 'Visite technique',
      renovation: 'Rénovation',
      construction_finish: 'Finition de construction',
      home_staging: 'Home Staging',
      cleaning: 'Nettoyage',
      maintenance: 'Maintenance',
      works_supervision: 'Supervision de travaux',
      condo_admin: 'Administration de copropriété',
      evaluation: 'Évaluation professionnelle',
    },
    status: {
      draft: 'Brouillon',
      pending_acceptance: 'En attente d’acceptation',
      active: 'Actif',
      completed: 'Terminé',
      cancelled: 'Annulé',
    },
  },
  gauge: {
    label: 'Indice Kuteka',
    statusGood: 'Bon état général',
    statusFair: 'État correct',
    statusAttention: 'Nécessite attention',
  },
  cockpit: {
    title: 'Cockpit de l’annonce',
    subtitle: 'Performance des 30 derniers jours et lecture suggérée par l’intelligence Kuteka.',
    views: 'Vues',
    favorites: 'Favoris',
    visits: 'Visites',
    proposals: 'Propositions',
    listingScore: 'Score de l’annonce',
    unrated: 'À évaluer',
    recommendedPrice: 'Prix recommandé (KAI)',
    saleProbability: 'Probabilité de vente',
    rentProbability: 'Probabilité de location',
    probabilityHigh: 'Élevée',
    probabilityMedium: 'Moyenne',
    probabilityImprove: 'À améliorer',
    estimatedYieldTemplate: 'Rendement estimé : {pct}%',
  },
  opsLabels: {
    service: {
      announce: 'Uniquement annoncer le bien',
      find_buyer: 'Uniquement trouver un acheteur',
      find_tenant: 'Uniquement trouver un locataire',
      rental_management: 'Confier la gestion locative à Kuteka',
      full_management: 'Confier la gestion complète du patrimoine à Kuteka',
      evaluation: 'Demander une évaluation professionnelle',
      photography: 'Demander une séance photo professionnelle',
      technical_visit: 'Demander une visite technique',
      renovation: 'Demander une rénovation',
      renewal: 'Demander un renouvellement',
      construction_finish: 'Demander la finition de la construction',
      home_staging: 'Demander une décoration / Home Staging',
      cleaning: 'Demander un nettoyage professionnel',
      maintenance: 'Demander une maintenance',
      works_supervision: 'Demander une supervision de travaux',
      condo_admin: 'Demander l’administration de la copropriété',
    },
    management: {
      announce_only: 'Annoncer uniquement',
      find_buyer: 'Vendre uniquement (trouver un acheteur)',
      find_tenant: 'Louer uniquement (trouver un locataire)',
      rental_management: 'Gestion locative par Kuteka',
      full_management: 'Gestion complète du patrimoine par Kuteka',
    },
    renovation: {
      full_renovation: 'Rénovation complète',
      partial_renovation: 'Rénovation partielle',
      painting: 'Peinture',
      electricity: 'Électricité',
      plumbing: 'Plomberie',
      roof: 'Toiture',
      kitchen: 'Cuisine',
      bathrooms: 'Salles de bain',
      facade: 'Façade',
      gardening: 'Jardinage',
      landscaping: 'Paysagisme',
      decoration: 'Décoration',
      home_staging: 'Home Staging',
    },
    unfinished: {
      none: 'Non applicable',
      kuteka_finish: 'Je souhaite que Kuteka termine la construction',
      budget_only: 'Je souhaite un devis pour terminer les travaux',
      technical_supervision: 'Je souhaite uniquement un suivi technique',
      works_evaluation: 'Je souhaite uniquement une évaluation des travaux',
    },
    construction: {
      complete: 'Construction terminée',
      partial: 'Partiellement construit',
      not_started: 'Travaux non commencés',
      needs_finish: 'Nécessite une finition',
    },
    conservation: {
      excellent: 'Excellent',
      good: 'Bon',
      fair: 'Correct',
      needs_work: 'Nécessite des travaux',
      ruin: 'En ruine',
      under_construction: 'En construction',
    },
    lifecycle: {
      em_preparacao: 'En préparation',
      em_analise_documental: 'En analyse documentaire',
      em_inspecao_tecnica: 'En inspection technique',
      em_avaliacao: 'En évaluation',
      aprovado: 'Approuvé',
      publicado: 'Publié',
      em_negociacao: 'En négociation',
      reservado: 'Réservé',
      vendido: 'Vendu',
      arrendado: 'Loué',
      em_manutencao: 'En maintenance',
      temporariamente_indisponivel: 'Temporairement indisponible',
      arquivado: 'Archivé',
    },
    partnerCategory: {
      A: 'A · Propriétaire particulier',
      B: 'B · Propriétaire investisseur',
      C: 'C · Sociétés propriétaires',
      D: 'D · Promoteurs immobiliers',
      E: 'E · Résident à l’étranger',
      F: 'F · Gestion totale Kuteka',
      G: 'G · Biens en valorisation',
    },
    partnerLifecycleStage: {
      descoberta: 'Découverte',
      registo: 'Inscription',
      verificacao: 'Vérification',
      registo_patrimonio: 'Enregistrement du patrimoine',
      verificacao_tecnica: 'Vérification technique',
      avaliacao: 'Évaluation',
      contrato_servicos: 'Contrat de services',
      publicacao: 'Publication',
      gestao_comercial: 'Gestion commerciale',
      negociacao: 'Négociation',
      formalizacao: 'Formalisation',
      pos_contrato: 'Post-contrat',
      avaliacao_experiencia: 'Évaluation de l’expérience',
      fidelizacao: 'Fidélisation',
      reativacao: 'Réactivation',
    },
    amenities: {
      internet: 'Internet',
      energia: 'Électricité',
      agua: 'Eau',
      seguranca: 'Sécurité',
      estacionamento: 'Parking',
      piscina: 'Piscine',
      jardim: 'Jardin',
      acessibilidade: 'Accessibilité',
    },
  },
};
