import type { ListingsCopy } from './pt';

export const listingsCopyFr: ListingsCopy = {
  reviews: {
    starsAriaTemplate: '{n} sur 5 étoiles',
    title: 'Réputation & avis',
    subtitle: 'Étoiles, commentaires, réponses et historique — après un contrat conclu.',
    averageTemplate: 'Moyenne générale {avg} · {count} avis',
    writeTitle: 'Écrire un avis',
    unavailable: 'Disponible après un contrat conclu sur ce patrimoine.',
    contractLabel: 'Contrat',
    subjectLabel: 'Sujet',
    ratingLabel: 'Note',
    commentLabel: 'Commentaire',
    commentPlaceholder: 'Décrivez l’expérience…',
    submitting: 'Enregistrement…',
    submit: 'Publier l’avis',
    loading: 'Chargement des avis…',
    empty:
      'Aucun avis public pour le moment. Ils apparaissent une fois un contrat conclu et les parties partagent leur retour.',
    ownerReply: 'Réponse du propriétaire',
    agentReply: 'Réponse de l’agent',
    replyPlaceholder: 'Écrire une réponse publique…',
    replyAsOwner: 'Répondre en tant que propriétaire',
    replyAsAgent: 'Répondre en tant qu’agent',
    needContractError: 'Vous ne pouvez évaluer qu’après un contrat conclu lié à ce bien.',
    invalidSessionError: 'Session invalide.',
    duplicateError: 'Vous avez déjà évalué ce sujet pour ce contrat.',
    saveError: 'Nous n’avons pas pu enregistrer l’avis. Veuillez réessayer.',
    saveSuccess: 'Avis enregistré.',
    reviewerVerifiedLabel: 'Client vérifié',
    contractConfirmedBadge: 'Contrat confirmé',
    emptyEncourage:
      'Soyez le premier à partager votre expérience et aidez à construire la confiance dans cette communauté.',
  },
  subjects: {
    property: 'Bien',
    owner: 'Propriétaire',
    agent: 'Agent',
    client: 'Client',
    experience: 'Expérience',
  },
  dimensions: {
    estado: 'État',
    limpeza: 'Propreté',
    localizacao: 'Emplacement',
    honestidade: 'Honnêteté',
    negociacao: 'Négociation',
    rapidez: 'Rapidité',
    acompanhamento: 'Suivi',
    experiencia_geral: 'Expérience globale',
    seriedade: 'Sérieux',
    comunicacao: 'Communication',
    desempenho: 'Performance',
    quality: 'Qualité',
    cleanliness: 'Propreté',
    location: 'Emplacement',
    communication: 'Communication',
    value: 'Rapport qualité/prix',
    accuracy: 'Exactitude de l’annonce',
  },
  health: {
    eyebrow: 'Cockpit du patrimoine',
    title: 'Panneau de santé du patrimoine',
    subtitle:
      'Suivez l’Indice Kuteka, les alertes, l’évolution et les recommandations automatiques.',
    riskUnrated: 'À évaluer',
    riskLow: 'Risque faible',
    riskModerate: 'Risque modéré',
    riskHigh: 'Risque élevé',
    renovationAlert: 'Alerte : rénovation recommandée',
    noUrgentRenovation: 'Pas de rénovation urgente',
    upcomingMaintenance: 'Maintenance prévue prochainement',
    tipRenovation:
      'De petites améliorations de façade et une photographie professionnelle peuvent augmenter la valeur marchande d’environ 8 %.',
    tipExcellent:
      'Patrimoine en excellent état — maintenez des inspections semestrielles et mettez à jour le PDK après toute rénovation.',
    tipDefault:
      'Planifiez la prochaine maintenance préventive et confirmez la documentation dans le Passeport Numérique.',
    tipLabel: 'Astuce Kuteka',
    overallState: 'État général',
    preparing: 'En préparation',
    conservation: 'Conservation',
    estimatedValue: 'Valeur estimée',
    lastMaintenance: 'Dernière maintenance',
    lastInspection: 'Dernière inspection',
    nextMaintenance: 'Prochaine maintenance',
    nextInspection: 'Prochaine inspection',
    toDefine: 'À définir',
    views30d: 'Vues (30j)',
    visits30d: 'Visites (30j)',
    proposals30d: 'Propositions (30j)',
    estimatedYield: 'Rendement estimé',
    valueEvolution: 'Évolution du bien / de la valeur',
    indexLabel: 'Indice {score}',
    technicalHistory: 'Historique technique',
    inspections: 'Inspections',
    valuations: 'Valorisations',
    noRecords: 'Aucun enregistrement pour le moment.',
  },
  opsLabels: {
    service: {
      announce: 'Uniquement annoncer le bien',
      find_buyer: 'Uniquement trouver un acheteur',
      find_tenant: 'Uniquement trouver un locataire',
      rental_management: 'Confier la gestion locative à Kuteka',
      full_management: 'Confier la gestion complète du patrimoine à Kuteka',
      evaluation: 'Demander une évaluation professionnelle',
      photography: 'Demander une séance photo professionnelle',
      technical_visit: 'Demander une visite technique',
      renovation: 'Demander une rénovation',
      renewal: 'Demander un renouvellement',
      construction_finish: 'Demander la finition de la construction',
      home_staging: 'Demander une décoration / Home Staging',
      cleaning: 'Demander un nettoyage professionnel',
      maintenance: 'Demander une maintenance',
      works_supervision: 'Demander une supervision de travaux',
      condo_admin: 'Demander l’administration de la copropriété',
    },
    management: {
      announce_only: 'Annoncer uniquement',
      find_buyer: 'Vendre uniquement (trouver un acheteur)',
      find_tenant: 'Louer uniquement (trouver un locataire)',
      rental_management: 'Gestion locative par Kuteka',
      full_management: 'Gestion complète du patrimoine par Kuteka',
    },
    renovation: {
      full_renovation: 'Rénovation complète',
      partial_renovation: 'Rénovation partielle',
      painting: 'Peinture',
      electricity: 'Électricité',
      plumbing: 'Plomberie',
      roof: 'Toiture',
      kitchen: 'Cuisine',
      bathrooms: 'Salles de bain',
      facade: 'Façade',
      gardening: 'Jardinage',
      landscaping: 'Paysagisme',
      decoration: 'Décoration',
      home_staging: 'Home Staging',
    },
    unfinished: {
      none: 'Non applicable',
      kuteka_finish: 'Je souhaite que Kuteka termine la construction',
      budget_only: 'Je souhaite un devis pour terminer les travaux',
      technical_supervision: 'Je souhaite uniquement un suivi technique',
      works_evaluation: 'Je souhaite uniquement une évaluation des travaux',
    },
    construction: {
      complete: 'Construction terminée',
      partial: 'Partiellement construit',
      not_started: 'Travaux non commencés',
      needs_finish: 'Nécessite une finition',
    },
    conservation: {
      excellent: 'Excellent',
      good: 'Bon',
      fair: 'Correct',
      needs_work: 'Nécessite des travaux',
      ruin: 'En ruine',
      under_construction: 'En construction',
    },
    lifecycle: {
      em_preparacao: 'En préparation',
      em_analise_documental: 'En analyse documentaire',
      em_inspecao_tecnica: 'En inspection technique',
      em_avaliacao: 'En évaluation',
      aprovado: 'Approuvé',
      publicado: 'Publié',
      em_negociacao: 'En négociation',
      reservado: 'Réservé',
      vendido: 'Vendu',
      arrendado: 'Loué',
      em_manutencao: 'En maintenance',
      temporariamente_indisponivel: 'Temporairement indisponible',
      arquivado: 'Archivé',
    },
    partnerCategory: {
      A: 'A · Propriétaire particulier',
      B: 'B · Propriétaire investisseur',
      C: 'C · Sociétés propriétaires',
      D: 'D · Promoteurs immobiliers',
      E: 'E · Résident à l’étranger',
      F: 'F · Gestion totale Kuteka',
      G: 'G · Biens en valorisation',
    },
    partnerLifecycleStage: {
      descoberta: 'Découverte',
      registo: 'Inscription',
      verificacao: 'Vérification',
      registo_patrimonio: 'Enregistrement du patrimoine',
      verificacao_tecnica: 'Vérification technique',
      avaliacao: 'Évaluation',
      contrato_servicos: 'Contrat de services',
      publicacao: 'Publication',
      gestao_comercial: 'Gestion commerciale',
      negociacao: 'Négociation',
      formalizacao: 'Formalisation',
      pos_contrato: 'Post-contrat',
      avaliacao_experiencia: 'Évaluation de l’expérience',
      fidelizacao: 'Fidélisation',
      reativacao: 'Réactivation',
    },
    amenities: {
      internet: 'Internet',
      energia: 'Électricité',
      agua: 'Eau',
      seguranca: 'Sécurité',
      estacionamento: 'Parking',
      piscina: 'Piscine',
      jardim: 'Jardin',
      acessibilidade: 'Accessibilité',
    },
  },
};
