/** Listings (patrimónios / habitação shared panels) copy — pt-AO. */
export const listingsCopyPt = {
  reviews: {
    starsAriaTemplate: '{n} de 5 estrelas',
    title: 'Reputação & avaliações',
    subtitle: 'Estrelas, comentários, respostas e histórico — após contrato concluído.',
    averageTemplate: 'Média geral {avg} · {count} avaliação(ões)',
    writeTitle: 'Escrever avaliação',
    unavailable: 'Disponível após um contrato concluído neste património.',
    contractLabel: 'Contrato',
    subjectLabel: 'Assunto',
    ratingLabel: 'Classificação',
    commentLabel: 'Comentário',
    commentPlaceholder: 'Descreva a experiência…',
    submitting: 'A guardar…',
    submit: 'Publicar avaliação',
    loading: 'A carregar avaliações…',
    empty:
      'Ainda não há avaliações públicas. Aparecem quando um contrato é concluído e as partes partilham feedback.',
    ownerReply: 'Resposta do proprietário',
    agentReply: 'Resposta do agente',
    replyPlaceholder: 'Escrever resposta pública…',
    replyAsOwner: 'Responder como proprietário',
    replyAsAgent: 'Responder como agente',
    needContractError: 'Só pode avaliar após um contrato concluído associado a este imóvel.',
    invalidSessionError: 'Sessão inválida.',
    duplicateError: 'Já avaliou este assunto neste contrato.',
    saveError: 'Não conseguimos guardar a avaliação. Tente novamente.',
    saveSuccess: 'Avaliação registada.',
    reviewerVerifiedLabel: 'Cliente verificado',
    contractConfirmedBadge: 'Contrato confirmado',
    emptyEncourage:
      'Seja o primeiro a partilhar a sua experiência e ajude a construir confiança nesta comunidade.',
  },
  social: {
    title: 'Comunidade do imóvel',
    subtitle: 'Gostos, favoritos, comentários e perguntas oficiais.',
    likes: 'Gostos',
    favorites: 'Favoritos',
    comments: 'Comentários',
    questions: 'Perguntas',
    like: 'Gostar',
    unlike: 'Remover gosto',
    favorite: 'Favorito',
    unfavorite: 'Remover favorito',
    commentTab: 'Comentar',
    questionTab: 'Perguntar',
    commentPlaceholder: 'Escreva um comentário…',
    questionPlaceholder: 'Faça uma pergunta ao parceiro ou à Kuteka…',
    answerPlaceholder: 'Responder à pergunta…',
    submitComment: 'Publicar comentário',
    submitQuestion: 'Enviar pergunta',
    submitAnswer: 'Responder',
    report: 'Denunciar',
    reportSpam: 'Spam',
    reportOffensive: 'Ofensivo',
    officialPartner: 'Resposta oficial · Parceiro',
    officialAgent: 'Resposta oficial · Agente',
    officialKuteka: 'Resposta oficial · Kuteka',
    loading: 'A carregar…',
    empty: 'Ainda sem comentários ou perguntas. Seja o primeiro.',
    signInHint: 'Inicie sessão para gostar, favoritar ou participar.',
    saveError: 'Não foi possível guardar. Tente novamente.',
    reportOk: 'Denúncia registada.',
    postOk: 'Publicado.',
  },
  subjects: {
    property: 'Imóvel',
    owner: 'Proprietário',
    agent: 'Agente',
    client: 'Cliente',
    experience: 'Experiência',
  },
  dimensions: {
    estado: 'Estado',
    limpeza: 'Limpeza',
    localizacao: 'Localização',
    honestidade: 'Honestidade',
    negociacao: 'Negociação',
    rapidez: 'Rapidez',
    acompanhamento: 'Acompanhamento',
    experiencia_geral: 'Experiência geral',
    seriedade: 'Seriedade',
    comunicacao: 'Comunicação',
    desempenho: 'Desempenho',
    quality: 'Qualidade',
    cleanliness: 'Limpeza',
    location: 'Localização',
    communication: 'Comunicação',
    value: 'Relação qualidade/preço',
    accuracy: 'Rigor do anúncio',
  },
  health: {
    eyebrow: 'Cockpit patrimonial',
    title: 'Painel de Saúde do Património',
    subtitle: 'Acompanhe o Índice Kuteka, alertas, evolução e recomendações automáticas.',
    riskUnrated: 'Por avaliar',
    riskLow: 'Risco baixo',
    riskModerate: 'Risco moderado',
    riskHigh: 'Risco elevado',
    renovationAlert: 'Alerta: remodelação recomendada',
    noUrgentRenovation: 'Sem remodelação urgente',
    upcomingMaintenance: 'Manutenção prevista em breve',
    tipRenovation:
      'Pequenas melhorias na fachada e fotografia profissional podem aumentar o valor de mercado até cerca de 8%.',
    tipExcellent:
      'Património em excelente condição — mantenha inspeções semestrais e actualize o PDK após qualquer obra.',
    tipDefault:
      'Agende a próxima manutenção preventiva e confirme a documentação no Passaporte Digital.',
    tipLabel: 'Dica Kuteka',
    overallState: 'Estado geral',
    preparing: 'Em preparação',
    conservation: 'Conservação',
    estimatedValue: 'Valor estimado',
    lastMaintenance: 'Última manutenção',
    lastInspection: 'Última inspecção',
    nextMaintenance: 'Próxima manutenção',
    nextInspection: 'Próxima inspecção',
    toDefine: 'A definir',
    views30d: 'Visualizações (30d)',
    visits30d: 'Visitas (30d)',
    proposals30d: 'Propostas (30d)',
    estimatedYield: 'Rentabilidade estimada',
    valueEvolution: 'Evolução do imóvel / valor',
    indexLabel: 'Índice {score}',
    technicalHistory: 'Histórico técnico',
    inspections: 'Inspecções',
    valuations: 'Valorizações',
    noRecords: 'Sem registos ainda.',
  },
  showcase: {
    navAria: 'Secções da ficha',
    navPdk: 'Passaporte Digital',
    navHealth: 'Painel de Saúde',
    navEvaluation: 'Avaliação Técnica',
    navContract: 'Contrato Kuteka',
    navHistory: 'Histórico',
    navReviews: 'Avaliações',
  },
  gallery: {
    ariaTemplate: 'Galeria de {title}',
    empty: 'Sem fotografia ou vídeo',
    video: 'Vídeo',
    photo: 'Fotografia',
    thumbAriaTemplate: '{kind} {n} de {title}',
  },
  facts: {
    yes: 'Sim',
    no: 'Não',
    eyebrow: 'Ficha do património',
    title: 'Informações essenciais',
    description: 'Descrição',
    typology: 'Tipologia',
    commercialPurpose: 'Finalidade comercial',
    managementLevel: 'Nível de gestão',
    province: 'Província',
    municipality: 'Município',
    commune: 'Comuna',
    city: 'Cidade',
    neighborhood: 'Bairro',
    street: 'Rua',
    streetNumber: 'Número',
    gps: 'Coordenadas GPS',
    bedrooms: 'Quartos',
    bathrooms: 'Casas de banho',
    usefulArea: 'Área útil',
    totalArea: 'Área total',
    floors: 'Pisos',
    parking: 'Estacionamento',
    yearBuilt: 'Ano de construção',
    conservation: 'Estado de conservação',
    construction: 'Estado da construção',
    renovation: 'Remodelação',
    monthlyCondo: 'Custos mensais (condomínio)',
    pipedWater: 'Água canalizada',
    electricity: 'Energia eléctrica',
    generator: 'Gerador',
    internet: 'Internet',
    security: 'Segurança',
    pavedStreet: 'Pavimentação',
    nearSchools: 'Escolas próximas',
    nearHospitals: 'Hospitais próximos',
    nearMarkets: 'Mercados próximos',
    nearTransport: 'Transportes próximos',
    amenitiesTitle: 'Comodidades & serviços',
    condoRulesTitle: 'Regras do condomínio',
    video: 'Vídeo da casa',
    videoSoon: 'Vídeo · em breve',
    tour: 'Visita 360°',
    tourSoon: 'Visita 360° · em breve',
    floorPlan: 'Planta',
    floorPlanSoon: 'Planta · em breve',
    documents: 'Documentos',
    documentsOnRequest: 'Documentos · sob pedido',
    parkingTemplate: '{n} lugar(es)',
    areaM2Template: '{n} m²',
  },
  passport: {
    eyebrow: 'Passaporte Digital KTK',
    title: 'Identidade permanente do imóvel',
    printButton: 'Ver / imprimir documento',
    propertyCode: 'Código patrimonial',
    yearBuilt: 'Ano de construção',
    constructionStatus: 'Estado da construção',
    conservation: 'Conservação',
    contractedManagement: 'Gestão contratada',
    unfinishedWorks: 'Obra inacabada',
    owners: 'Proprietários',
    contracts: 'Contratos',
    reviews: 'Avaliações',
    maintenances: 'Manutenções',
    photos: 'Fotografias',
    kutekaServices: 'Serviços Kuteka',
    renovations: 'Remodelações / valorização',
    ownerHistory: 'Histórico de proprietários',
    ownerHistoryEmpty: 'Titular actual na Kuteka',
    commercialHistory: 'Histórico comercial / valorizações',
    maintenanceHistory: 'Histórico de manutenção',
    inspectionHistory: 'Histórico de inspeções',
    historyEmpty: 'Sem registos ainda — serão adicionados ao longo do ciclo de vida.',
    indexLabel: 'Índice {score}',
    legalDocs: 'Documentação / jurídico',
    commercialNotes: 'Notas comerciais',
    openDocuments: 'Abrir documentos validados',
  },
  map: {
    title: 'Localização',
    titleWithSurroundings: 'Localização & envolvente',
    noCoords: 'Mapa disponível quando o património tiver coordenadas GPS no registo.',
    exactLocation: 'Localização exacta (autorizada)',
    approximateLocation: 'Zona aproximada (privacidade do proprietário)',
    openStreetMap: 'OpenStreetMap',
    streetView: 'Street View',
    googleMaps: 'Google Maps',
    iframeTitle: 'Mapa do património',
    poisTitle: 'Pontos de interesse próximos',
    etaDisclaimer:
      'Tempos estimados em condições normais de trânsito — confirme no Street View / mapa completo.',
    poiSchools: 'Escolas / colégios',
    poiSchoolsEta: '5–12 min',
    poiSchoolsKind: 'educação',
    poiHospitals: 'Hospitais / clínicas',
    poiHospitalsEta: '10–20 min',
    poiHospitalsKind: 'saúde',
    poiMarkets: 'Mercados / supermercados',
    poiMarketsEta: '5–15 min',
    poiMarketsKind: 'comércio',
    poiTransport: 'Transportes públicos',
    poiTransportEta: '5–10 min',
    poiTransportKind: 'mobilidade',
    poiBanks: 'Bancos / ATM',
    poiBanksEta: '8–18 min',
    poiBanksKind: 'serviços',
  },
  timeline: {
    title: 'Histórico do imóvel',
    loading: 'A carregar linha temporal…',
    empty:
      'A linha temporal regista registo, documentação, inspeção, avaliação, publicação, visitas, propostas, contratos e renovações.',
    subtitle: 'Linha temporal completa — cada evento com data, responsável e descrição.',
    responsibleTemplate: 'Responsável: {name}',
    actorUser: 'Utilizador Kuteka',
    actorTeam: 'Equipa Kuteka',
    actorSystem: 'Sistema Kuteka',
    types: {
      registered: 'Registo',
      documents: 'Documentação',
      inspection: 'Inspeção',
      evaluation: 'Avaliação',
      renovation: 'Remodelação',
      service_contract: 'Contrato Kuteka',
      published: 'Publicação',
      interest: 'Interesse',
      visit: 'Visita',
      proposal: 'Proposta',
      negotiation: 'Negociação',
      contract: 'Contrato',
      payment: 'Pagamento',
      review: 'Avaliação',
      completed: 'Conclusão',
      renewal: 'Renovação',
    },
  },
  evaluation: {
    loading: 'A carregar avaliação técnica…',
    title: 'Avaliação técnica',
    titleFull: 'Avaliação técnica & comercial',
    empty:
      'Ainda não existe relatório. Serviços de gestão, remodelação ou conclusão de obra exigem avaliação Cap.6 antes da publicação plena.',
    eyebrow: 'Manual Cap.6',
    printReport: 'Relatório PDF / imprimir',
    calculatedIndex: 'Índice calculado',
    suggestedPrice: 'Preço sugerido',
    reportDate: 'Data do relatório',
    dimsTitle: 'Classificação por dimensão',
    checklistTitle: 'Checklist técnica',
    inspectionPhotos: 'Fotografias da inspeção',
    photosPending: 'Fotografias de inspeção serão anexadas pelo Agente após a visita técnica.',
    reportNotes: 'Observações / relatório',
    recommendations: 'Recomendações & plano de valorização',
    counterProposal: 'Contraproposta de preço',
    status: {
      draft: 'Em preparação',
      submitted: 'Submetida',
      approved: 'Aprovada',
      rejected: 'Rejeitada',
    },
    risk: {
      low: 'Risco baixo',
      medium: 'Risco moderado',
      high: 'Risco elevado',
    },
    dims: {
      structure: 'Estrutura',
      location: 'Localização',
      documentation: 'Documentação',
      finishes: 'Acabamentos',
      profitability: 'Rentabilidade',
      security: 'Segurança',
    },
  },
  serviceContract: {
    eyebrow: 'Manual Cap.7',
    title: 'Contrato de serviços Kuteka ↔ Parceiro',
    subtitle: 'Estado, validade, assinatura e histórico — distinto do contrato Cliente–Parceiro.',
    loading: 'A carregar contratos…',
    empty:
      'Ainda não existe contrato de serviços. Ao activar património com serviços Kuteka, o sistema gera automaticamente um rascunho contratual.',
    versionExclusivityTemplate: 'Versão {version} · Exclusividade: {exclusivity}',
    created: 'Criado',
    validFrom: 'Válido de',
    validUntil: 'Válido até',
    signature: 'Assinatura',
    awaitingAcceptance: 'Aguarda aceitação',
    pending: 'Pendente',
    cancelledOnTemplate: 'Cancelado em {date}',
    downloadPdf: 'Download / imprimir PDF',
    openDocument: 'Abrir documento',
    renewalContact: 'Renovação: contacte a Kuteka',
    types: {
      intermediation_sale: 'Intermediação de venda',
      intermediation_rent: 'Intermediação de arrendamento',
      full_management: 'Gestão total',
      patrimonial_valuation: 'Valorização patrimonial',
      legal_admin: 'Serviços jurídicos e administrativos',
      photography: 'Sessão fotográfica',
      technical_visit: 'Visita técnica',
      renovation: 'Remodelação',
      construction_finish: 'Conclusão de construção',
      home_staging: 'Home Staging',
      cleaning: 'Limpeza',
      maintenance: 'Manutenção',
      works_supervision: 'Fiscalização de obra',
      condo_admin: 'Administração de condomínio',
      evaluation: 'Avaliação profissional',
    },
    status: {
      draft: 'Rascunho',
      pending_acceptance: 'Pendente de aceitação',
      active: 'Activo',
      completed: 'Concluído',
      cancelled: 'Cancelado',
    },
  },
  gauge: {
    label: 'Índice Kuteka',
    statusGood: 'Bom estado geral',
    statusFair: 'Estado razoável',
    statusAttention: 'Requer atenção',
  },
  cockpit: {
    title: 'Cockpit do anúncio',
    subtitle: 'Desempenho dos últimos 30 dias e leitura sugerida pela inteligência Kuteka.',
    views: 'Visualizações',
    favorites: 'Favoritos',
    visits: 'Visitas',
    proposals: 'Propostas',
    listingScore: 'Score do anúncio',
    unrated: 'Por avaliar',
    recommendedPrice: 'Preço recomendado (KAI)',
    saleProbability: 'Probabilidade de venda',
    rentProbability: 'Probabilidade de arrendamento',
    probabilityHigh: 'Alta',
    probabilityMedium: 'Média',
    probabilityImprove: 'A melhorar',
    estimatedYieldTemplate: 'Rendimento estimado: {pct}%',
  },
  opsLabels: {
    service: {
      announce: 'Apenas anunciar o imóvel',
      find_buyer: 'Apenas encontrar comprador',
      find_tenant: 'Apenas encontrar arrendatário',
      rental_management: 'Entregar a gestão do arrendamento à Kuteka',
      full_management: 'Entregar a gestão completa do património à Kuteka',
      evaluation: 'Solicitar avaliação profissional',
      photography: 'Solicitar sessão fotográfica profissional',
      technical_visit: 'Solicitar visita técnica',
      renovation: 'Solicitar remodelação',
      renewal: 'Solicitar renovação',
      construction_finish: 'Solicitar conclusão da construção',
      home_staging: 'Solicitar decoração / Home Staging',
      cleaning: 'Solicitar limpeza profissional',
      maintenance: 'Solicitar manutenção',
      works_supervision: 'Solicitar fiscalização de obra',
      condo_admin: 'Solicitar administração do condomínio',
    },
    management: {
      announce_only: 'Apenas anunciar',
      find_buyer: 'Apenas vender (encontrar comprador)',
      find_tenant: 'Apenas arrendar (encontrar arrendatário)',
      rental_management: 'Gestão do arrendamento pela Kuteka',
      full_management: 'Gestão completa do património pela Kuteka',
    },
    renovation: {
      full_renovation: 'Remodelação completa',
      partial_renovation: 'Remodelação parcial',
      painting: 'Pintura',
      electricity: 'Electricidade',
      plumbing: 'Canalização',
      roof: 'Cobertura',
      kitchen: 'Cozinha',
      bathrooms: 'Casas de banho',
      facade: 'Fachada',
      gardening: 'Jardinagem',
      landscaping: 'Paisagismo',
      decoration: 'Decoração',
      home_staging: 'Home Staging',
    },
    unfinished: {
      none: 'Não aplicável',
      kuteka_finish: 'Pretendo que a Kuteka conclua a construção',
      budget_only: 'Pretendo orçamento para terminar a obra',
      technical_supervision: 'Pretendo apenas acompanhamento técnico',
      works_evaluation: 'Pretendo apenas avaliação da obra',
    },
    construction: {
      complete: 'Construção concluída',
      partial: 'Parcialmente construído',
      not_started: 'Obra não iniciada',
      needs_finish: 'Necessita conclusão',
    },
    conservation: {
      excellent: 'Excelente',
      good: 'Bom',
      fair: 'Razoável',
      needs_work: 'Necessita intervenção',
      ruin: 'Em ruína',
      under_construction: 'Em construção',
    },
    lifecycle: {
      rascunho: 'Rascunho',
      submetido: 'Submetido',
      em_analise_kai: 'Em análise KAI',
      em_analise_admin: 'Em análise admin',
      pendente: 'Pendente',
      correcoes: 'Correcções pedidas',
      em_preparacao: 'Em preparação',
      em_analise_documental: 'Em análise documental',
      em_inspecao_tecnica: 'Em inspeção técnica',
      em_avaliacao: 'Em avaliação',
      aprovado: 'Aprovado',
      janela_premium: 'Janela premium',
      publicado: 'Publicado',
      em_negociacao: 'Em negociação',
      reservado: 'Reservado',
      contrato: 'Contrato',
      vendido: 'Vendido',
      arrendado: 'Arrendado',
      em_utilizacao: 'Em utilização',
      libertacao_prevista: 'Libertação prevista',
      disponivel_novamente: 'Disponível novamente',
      em_manutencao: 'Em manutenção',
      temporariamente_indisponivel: 'Temporariamente indisponível',
      arquivado: 'Arquivado',
    },
    partnerCategory: {
      A: 'A · Proprietário Particular',
      B: 'B · Proprietário Investidor',
      C: 'C · Empresas Proprietárias',
      D: 'D · Promotores Imobiliários',
      E: 'E · Residente no Estrangeiro',
      F: 'F · Gestão Total Kuteka',
      G: 'G · Imóveis em Valorização',
    },
    partnerLifecycleStage: {
      descoberta: 'Descoberta',
      registo: 'Registo',
      verificacao: 'Verificação',
      registo_patrimonio: 'Registo do património',
      verificacao_tecnica: 'Verificação técnica',
      avaliacao: 'Avaliação',
      contrato_servicos: 'Contrato de serviços',
      publicacao: 'Publicação',
      gestao_comercial: 'Gestão comercial',
      negociacao: 'Negociação',
      formalizacao: 'Formalização',
      pos_contrato: 'Pós-contrato',
      avaliacao_experiencia: 'Avaliação da experiência',
      fidelizacao: 'Fidelização',
      reativacao: 'Reativação',
    },
    amenities: {
      internet: 'Internet',
      energia: 'Energia',
      agua: 'Água',
      seguranca: 'Segurança',
      estacionamento: 'Estacionamento',
      piscina: 'Piscina',
      jardim: 'Jardim',
      acessibilidade: 'Acessibilidade',
    },
  },
} as const;

type DeepStringify<T> = {
  [K in keyof T]: T[K] extends string ? string : DeepStringify<T[K]>;
};

export type ListingsCopy = DeepStringify<typeof listingsCopyPt>;
