/** Listings (patrimónios / habitação shared panels) copy — pt-AO. */
export const listingsCopyPt = {
  reviews: {
    starsAriaTemplate: '{n} de 5 estrelas',
    title: 'Reputação & avaliações',
    subtitle: 'Estrelas, comentários, respostas e histórico — após contrato concluído.',
    averageTemplate: 'Média geral {avg} · {count} avaliação(ões)',
    writeTitle: 'Escrever avaliação',
    unavailable: 'Disponível após um contrato concluído neste património.',
    contractLabel: 'Contrato',
    subjectLabel: 'Assunto',
    ratingLabel: 'Classificação',
    commentLabel: 'Comentário',
    commentPlaceholder: 'Descreva a experiência…',
    submitting: 'A guardar…',
    submit: 'Publicar avaliação',
    loading: 'A carregar avaliações…',
    empty:
      'Ainda não há avaliações públicas. Aparecem quando um contrato é concluído e as partes partilham feedback.',
    ownerReply: 'Resposta do proprietário',
    agentReply: 'Resposta do agente',
    replyPlaceholder: 'Escrever resposta pública…',
    replyAsOwner: 'Responder como proprietário',
    replyAsAgent: 'Responder como agente',
    needContractError: 'Só pode avaliar após um contrato concluído associado a este imóvel.',
    invalidSessionError: 'Sessão inválida.',
    duplicateError: 'Já avaliou este assunto neste contrato.',
    saveError: 'Não conseguimos guardar a avaliação. Tente novamente.',
    saveSuccess: 'Avaliação registada.',
  },
  subjects: {
    property: 'Imóvel',
    owner: 'Proprietário',
    agent: 'Agente',
    client: 'Cliente',
    experience: 'Experiência',
  },
  health: {
    eyebrow: 'Cockpit patrimonial',
    title: 'Painel de Saúde do Património',
    subtitle: 'Acompanhe o Índice Kuteka, alertas, evolução e recomendações automáticas.',
    riskUnrated: 'Por avaliar',
    riskLow: 'Risco baixo',
    riskModerate: 'Risco moderado',
    riskHigh: 'Risco elevado',
    renovationAlert: 'Alerta: remodelação recomendada',
    noUrgentRenovation: 'Sem remodelação urgente',
    upcomingMaintenance: 'Manutenção prevista em breve',
    tipRenovation:
      'Pequenas melhorias na fachada e fotografia profissional podem aumentar o valor de mercado até cerca de 8%.',
    tipExcellent:
      'Património em excelente condição — mantenha inspeções semestrais e actualize o PDK após qualquer obra.',
    tipDefault:
      'Agende a próxima manutenção preventiva e confirme a documentação no Passaporte Digital.',
    tipLabel: 'Dica Kuteka',
    overallState: 'Estado geral',
    preparing: 'Em preparação',
    conservation: 'Conservação',
    estimatedValue: 'Valor estimado',
    lastMaintenance: 'Última manutenção',
    lastInspection: 'Última inspecção',
    nextMaintenance: 'Próxima manutenção',
    nextInspection: 'Próxima inspecção',
    toDefine: 'A definir',
    views30d: 'Visualizações (30d)',
    visits30d: 'Visitas (30d)',
    proposals30d: 'Propostas (30d)',
    estimatedYield: 'Rentabilidade estimada',
    valueEvolution: 'Evolução do imóvel / valor',
    indexLabel: 'Índice {score}',
    technicalHistory: 'Histórico técnico',
    inspections: 'Inspecções',
    valuations: 'Valorizações',
    noRecords: 'Sem registos ainda.',
  },
  opsLabels: {
    service: {
      announce: 'Apenas anunciar o imóvel',
      find_buyer: 'Apenas encontrar comprador',
      find_tenant: 'Apenas encontrar arrendatário',
      rental_management: 'Entregar a gestão do arrendamento à Kuteka',
      full_management: 'Entregar a gestão completa do património à Kuteka',
      evaluation: 'Solicitar avaliação profissional',
      photography: 'Solicitar sessão fotográfica profissional',
      technical_visit: 'Solicitar visita técnica',
      renovation: 'Solicitar remodelação',
      renewal: 'Solicitar renovação',
      construction_finish: 'Solicitar conclusão da construção',
      home_staging: 'Solicitar decoração / Home Staging',
      cleaning: 'Solicitar limpeza profissional',
      maintenance: 'Solicitar manutenção',
      works_supervision: 'Solicitar fiscalização de obra',
      condo_admin: 'Solicitar administração do condomínio',
    },
    management: {
      announce_only: 'Apenas anunciar',
      find_buyer: 'Apenas vender (encontrar comprador)',
      find_tenant: 'Apenas arrendar (encontrar arrendatário)',
      rental_management: 'Gestão do arrendamento pela Kuteka',
      full_management: 'Gestão completa do património pela Kuteka',
    },
    renovation: {
      full_renovation: 'Remodelação completa',
      partial_renovation: 'Remodelação parcial',
      painting: 'Pintura',
      electricity: 'Electricidade',
      plumbing: 'Canalização',
      roof: 'Cobertura',
      kitchen: 'Cozinha',
      bathrooms: 'Casas de banho',
      facade: 'Fachada',
      gardening: 'Jardinagem',
      landscaping: 'Paisagismo',
      decoration: 'Decoração',
      home_staging: 'Home Staging',
    },
    unfinished: {
      none: 'Não aplicável',
      kuteka_finish: 'Pretendo que a Kuteka conclua a construção',
      budget_only: 'Pretendo orçamento para terminar a obra',
      technical_supervision: 'Pretendo apenas acompanhamento técnico',
      works_evaluation: 'Pretendo apenas avaliação da obra',
    },
    construction: {
      complete: 'Construção concluída',
      partial: 'Parcialmente construído',
      not_started: 'Obra não iniciada',
      needs_finish: 'Necessita conclusão',
    },
    conservation: {
      excellent: 'Excelente',
      good: 'Bom',
      fair: 'Razoável',
      needs_work: 'Necessita intervenção',
      ruin: 'Em ruína',
      under_construction: 'Em construção',
    },
    lifecycle: {
      em_preparacao: 'Em preparação',
      em_analise_documental: 'Em análise documental',
      em_inspecao_tecnica: 'Em inspeção técnica',
      em_avaliacao: 'Em avaliação',
      aprovado: 'Aprovado',
      publicado: 'Publicado',
      em_negociacao: 'Em negociação',
      reservado: 'Reservado',
      vendido: 'Vendido',
      arrendado: 'Arrendado',
      em_manutencao: 'Em manutenção',
      temporariamente_indisponivel: 'Temporariamente indisponível',
      arquivado: 'Arquivado',
    },
    partnerCategory: {
      A: 'A · Proprietário Particular',
      B: 'B · Proprietário Investidor',
      C: 'C · Empresas Proprietárias',
      D: 'D · Promotores Imobiliários',
      E: 'E · Residente no Estrangeiro',
      F: 'F · Gestão Total Kuteka',
      G: 'G · Imóveis em Valorização',
    },
    partnerLifecycleStage: {
      descoberta: 'Descoberta',
      registo: 'Registo',
      verificacao: 'Verificação',
      registo_patrimonio: 'Registo do património',
      verificacao_tecnica: 'Verificação técnica',
      avaliacao: 'Avaliação',
      contrato_servicos: 'Contrato de serviços',
      publicacao: 'Publicação',
      gestao_comercial: 'Gestão comercial',
      negociacao: 'Negociação',
      formalizacao: 'Formalização',
      pos_contrato: 'Pós-contrato',
      avaliacao_experiencia: 'Avaliação da experiência',
      fidelizacao: 'Fidelização',
      reativacao: 'Reativação',
    },
    amenities: {
      internet: 'Internet',
      energia: 'Energia',
      agua: 'Água',
      seguranca: 'Segurança',
      estacionamento: 'Estacionamento',
      piscina: 'Piscina',
      jardim: 'Jardim',
      acessibilidade: 'Acessibilidade',
    },
  },
} as const;

type DeepStringify<T> = {
  [K in keyof T]: T[K] extends string ? string : DeepStringify<T[K]>;
};

export type ListingsCopy = DeepStringify<typeof listingsCopyPt>;
