import type { ExperienceMode } from './role-experience';
import type { AppLocale } from '@/modules/i18n/types';

export type ShellNotification = {
  id: string;
  title: string;
  body: string;
  href: string;
  unread?: boolean;
};

type Catalog = Record<ExperienceMode, ShellNotification[]>;

const CATALOG: Record<AppLocale, Catalog> = {
  pt: {
    client: [
      {
        id: 'c1',
        title: 'Encontrámos 4 imóveis para o seu pedido',
        body: 'Novos resultados alinhados com as suas preferências.',
        href: '/app/habitacao/explorar',
        unread: true,
      },
      {
        id: 'c2',
        title: 'Visita marcada para amanhã',
        body: 'Confirme a hora e o local no seu calendário Kuteka.',
        href: '/app/habitacao?vista=visitas',
        unread: true,
      },
      {
        id: 'c3',
        title: 'Proprietário respondeu',
        body: 'Há uma nova mensagem sobre um imóvel do seu interesse.',
        href: '/app/habitacao?vista=interesses',
        unread: true,
      },
      {
        id: 'c4',
        title: 'Nova proposta disponível',
        body: 'Reveja condições e prossiga se fizer sentido.',
        href: '/app/contratos',
        unread: true,
      },
      {
        id: 'c5',
        title: 'Contrato pronto',
        body: 'A minuta está disponível para leitura e assinatura.',
        href: '/app/contratos',
        unread: true,
      },
      {
        id: 'c6',
        title: 'Mensagem Kuteka',
        body: 'Actualização sobre o seu processo habitacional.',
        href: '/contacto',
        unread: true,
      },
      {
        id: 'c7',
        title: 'Agendamento de visita',
        body: 'Pedido de visita aguarda a sua confirmação.',
        href: '/app/habitacao?vista=visitas',
        unread: true,
      },
    ],
    patrimonial_partner: [
      {
        id: 'p1',
        title: 'Pedidos de visita',
        body: 'Novos pedidos para patrimónios activos.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'p2',
        title: 'Novos interessados',
        body: 'Clientes demonstraram interesse nos seus anúncios.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'p3',
        title: 'Propostas recebidas',
        body: 'Há propostas a aguardar a sua análise.',
        href: '/app/contratos',
        unread: true,
      },
      {
        id: 'p4',
        title: 'Documentos pendentes',
        body: 'Complete a confiança para acelerar activação.',
        href: '/app/confianca',
        unread: true,
      },
      {
        id: 'p5',
        title: 'Avaliação concluída',
        body: 'Uma avaliação de reputação foi registada.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'p6',
        title: 'Contratos',
        body: 'Actualização no estado de um contrato activo.',
        href: '/app/contratos',
        unread: true,
      },
    ],
    client_partner: [
      {
        id: 'cp1',
        title: 'Actualização Cliente',
        body: 'Novos imóveis e visitas na sua jornada habitacional.',
        href: '/app/habitacao/explorar',
        unread: true,
      },
      {
        id: 'cp2',
        title: 'Actualização Parceiro',
        body: 'Interessados e propostas nos seus patrimónios.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'cp3',
        title: 'Contratos',
        body: 'Movimentos em contratos como cliente e como parceiro.',
        href: '/app/contratos',
        unread: true,
      },
    ],
    certified_agent: [
      {
        id: 'a1',
        title: 'Novas visitas',
        body: 'Visitas atribuídas ao seu pipeline.',
        href: '/app/agente',
        unread: true,
      },
      {
        id: 'a2',
        title: 'Novos clientes',
        body: 'Clientes à espera de acompanhamento.',
        href: '/app/agente',
        unread: true,
      },
      {
        id: 'a3',
        title: 'Avaliações pendentes',
        body: 'Avaliações técnicas por concluir.',
        href: '/app/agente',
        unread: true,
      },
      {
        id: 'a4',
        title: 'Tarefas',
        body: 'Checklist do dia no terreno.',
        href: '/app/agente',
        unread: true,
      },
    ],
    administrator: [
      {
        id: 'ad1',
        title: 'Novos utilizadores',
        body: 'Contas recentes para revisão operacional.',
        href: '/app/admin/utilizadores',
        unread: true,
      },
      {
        id: 'ad2',
        title: 'Aprovações',
        body: 'Pedidos de confiança e conteúdos pendentes.',
        href: '/app/confianca/revisao',
        unread: true,
      },
      {
        id: 'ad3',
        title: 'Imóveis pendentes',
        body: 'Anúncios à espera de validação.',
        href: '/app/admin',
        unread: true,
      },
      {
        id: 'ad4',
        title: 'Alertas',
        body: 'Sinais operacionais da plataforma.',
        href: '/app/admin',
        unread: true,
      },
    ],
    super_administrator: [
      {
        id: 's1',
        title: 'Métricas executivas',
        body: 'Resumo operacional da plataforma.',
        href: '/app/admin',
        unread: true,
      },
      {
        id: 's2',
        title: 'Aprovações críticas',
        body: 'Itens que exigem supervisão.',
        href: '/app/confianca/revisao',
        unread: true,
      },
      {
        id: 's3',
        title: 'Novos utilizadores',
        body: 'Crescimento de contas na rede Kuteka.',
        href: '/app/admin/utilizadores',
        unread: true,
      },
    ],
  },
  en: {
    client: [
      {
        id: 'c1',
        title: 'We found 4 homes for your request',
        body: 'New results matching your preferences.',
        href: '/app/habitacao/explorar',
        unread: true,
      },
      {
        id: 'c2',
        title: 'Visit booked for tomorrow',
        body: 'Confirm time and place in your Kuteka calendar.',
        href: '/app/habitacao?vista=visitas',
        unread: true,
      },
      {
        id: 'c3',
        title: 'Owner replied',
        body: 'There is a new message about a property you like.',
        href: '/app/habitacao?vista=interesses',
        unread: true,
      },
      {
        id: 'c4',
        title: 'New proposal available',
        body: 'Review terms and continue if it fits.',
        href: '/app/contratos',
        unread: true,
      },
      {
        id: 'c5',
        title: 'Contract ready',
        body: 'The draft is ready to review and sign.',
        href: '/app/contratos',
        unread: true,
      },
      {
        id: 'c6',
        title: 'Kuteka message',
        body: 'An update on your housing journey.',
        href: '/contacto',
        unread: true,
      },
      {
        id: 'c7',
        title: 'Visit scheduling',
        body: 'A visit request awaits your confirmation.',
        href: '/app/habitacao?vista=visitas',
        unread: true,
      },
    ],
    patrimonial_partner: [
      {
        id: 'p1',
        title: 'Visit requests',
        body: 'New requests for your active listings.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'p2',
        title: 'New interested clients',
        body: 'Clients showed interest in your properties.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'p3',
        title: 'Proposals received',
        body: 'Proposals are waiting for your review.',
        href: '/app/contratos',
        unread: true,
      },
      {
        id: 'p4',
        title: 'Pending documents',
        body: 'Complete trust checks to speed activation.',
        href: '/app/confianca',
        unread: true,
      },
      {
        id: 'p5',
        title: 'Review completed',
        body: 'A reputation review was recorded.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'p6',
        title: 'Contracts',
        body: 'An active contract status changed.',
        href: '/app/contratos',
        unread: true,
      },
    ],
    client_partner: [
      {
        id: 'cp1',
        title: 'Client update',
        body: 'New homes and visits in your housing journey.',
        href: '/app/habitacao/explorar',
        unread: true,
      },
      {
        id: 'cp2',
        title: 'Partner update',
        body: 'Interest and proposals on your properties.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'cp3',
        title: 'Contracts',
        body: 'Movement on contracts as client and partner.',
        href: '/app/contratos',
        unread: true,
      },
    ],
    certified_agent: [
      {
        id: 'a1',
        title: 'New visits',
        body: 'Visits assigned to your pipeline.',
        href: '/app/agente',
        unread: true,
      },
      {
        id: 'a2',
        title: 'New clients',
        body: 'Clients waiting for follow-up.',
        href: '/app/agente',
        unread: true,
      },
      {
        id: 'a3',
        title: 'Pending evaluations',
        body: 'Technical evaluations to complete.',
        href: '/app/agente',
        unread: true,
      },
      {
        id: 'a4',
        title: 'Tasks',
        body: 'Today’s field checklist.',
        href: '/app/agente',
        unread: true,
      },
    ],
    administrator: [
      {
        id: 'ad1',
        title: 'New users',
        body: 'Recent accounts for operational review.',
        href: '/app/admin/utilizadores',
        unread: true,
      },
      {
        id: 'ad2',
        title: 'Approvals',
        body: 'Trust requests and pending content.',
        href: '/app/confianca/revisao',
        unread: true,
      },
      {
        id: 'ad3',
        title: 'Pending listings',
        body: 'Listings awaiting validation.',
        href: '/app/admin',
        unread: true,
      },
      {
        id: 'ad4',
        title: 'Alerts',
        body: 'Operational signals from the platform.',
        href: '/app/admin',
        unread: true,
      },
    ],
    super_administrator: [
      {
        id: 's1',
        title: 'Executive metrics',
        body: 'Operational summary of the platform.',
        href: '/app/admin',
        unread: true,
      },
      {
        id: 's2',
        title: 'Critical approvals',
        body: 'Items that need supervision.',
        href: '/app/confianca/revisao',
        unread: true,
      },
      {
        id: 's3',
        title: 'New users',
        body: 'Account growth across Kuteka.',
        href: '/app/admin/utilizadores',
        unread: true,
      },
    ],
  },
  fr: {
    client: [
      {
        id: 'c1',
        title: 'Nous avons trouvé 4 biens pour votre demande',
        body: 'Nouveaux résultats alignés avec vos préférences.',
        href: '/app/habitacao/explorar',
        unread: true,
      },
      {
        id: 'c2',
        title: 'Visite prévue demain',
        body: 'Confirmez l’heure et le lieu dans votre calendrier Kuteka.',
        href: '/app/habitacao?vista=visitas',
        unread: true,
      },
      {
        id: 'c3',
        title: 'Le propriétaire a répondu',
        body: 'Nouveau message sur un bien qui vous intéresse.',
        href: '/app/habitacao?vista=interesses',
        unread: true,
      },
      {
        id: 'c4',
        title: 'Nouvelle proposition',
        body: 'Examinez les conditions et poursuivez si cela convient.',
        href: '/app/contratos',
        unread: true,
      },
      {
        id: 'c5',
        title: 'Contrat prêt',
        body: 'Le projet est disponible pour lecture et signature.',
        href: '/app/contratos',
        unread: true,
      },
      {
        id: 'c6',
        title: 'Message Kuteka',
        body: 'Mise à jour de votre parcours logement.',
        href: '/contacto',
        unread: true,
      },
      {
        id: 'c7',
        title: 'Planification de visite',
        body: 'Une demande de visite attend votre confirmation.',
        href: '/app/habitacao?vista=visitas',
        unread: true,
      },
    ],
    patrimonial_partner: [
      {
        id: 'p1',
        title: 'Demandes de visite',
        body: 'Nouvelles demandes pour vos patrimoines actifs.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'p2',
        title: 'Nouveaux intéressés',
        body: 'Des clients ont manifesté leur intérêt.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'p3',
        title: 'Propositions reçues',
        body: 'Des propositions attendent votre analyse.',
        href: '/app/contratos',
        unread: true,
      },
      {
        id: 'p4',
        title: 'Documents en attente',
        body: 'Complétez la confiance pour accélérer l’activation.',
        href: '/app/confianca',
        unread: true,
      },
      {
        id: 'p5',
        title: 'Évaluation terminée',
        body: 'Une évaluation de réputation a été enregistrée.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'p6',
        title: 'Contrats',
        body: 'Mise à jour sur un contrat actif.',
        href: '/app/contratos',
        unread: true,
      },
    ],
    client_partner: [
      {
        id: 'cp1',
        title: 'Mise à jour Client',
        body: 'Nouveaux biens et visites dans votre parcours.',
        href: '/app/habitacao/explorar',
        unread: true,
      },
      {
        id: 'cp2',
        title: 'Mise à jour Partenaire',
        body: 'Intérêts et propositions sur vos patrimoines.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'cp3',
        title: 'Contrats',
        body: 'Mouvements côté client et partenaire.',
        href: '/app/contratos',
        unread: true,
      },
    ],
    certified_agent: [
      {
        id: 'a1',
        title: 'Nouvelles visites',
        body: 'Visites assignées à votre pipeline.',
        href: '/app/agente',
        unread: true,
      },
      {
        id: 'a2',
        title: 'Nouveaux clients',
        body: 'Clients en attente d’accompagnement.',
        href: '/app/agente',
        unread: true,
      },
      {
        id: 'a3',
        title: 'Évaluations en attente',
        body: 'Évaluations techniques à terminer.',
        href: '/app/agente',
        unread: true,
      },
      {
        id: 'a4',
        title: 'Tâches',
        body: 'Checklist du jour sur le terrain.',
        href: '/app/agente',
        unread: true,
      },
    ],
    administrator: [
      {
        id: 'ad1',
        title: 'Nouveaux utilisateurs',
        body: 'Comptes récents à examiner.',
        href: '/app/admin/utilizadores',
        unread: true,
      },
      {
        id: 'ad2',
        title: 'Approbations',
        body: 'Demandes de confiance et contenus en attente.',
        href: '/app/confianca/revisao',
        unread: true,
      },
      {
        id: 'ad3',
        title: 'Biens en attente',
        body: 'Annonces à valider.',
        href: '/app/admin',
        unread: true,
      },
      {
        id: 'ad4',
        title: 'Alertes',
        body: 'Signaux opérationnels de la plateforme.',
        href: '/app/admin',
        unread: true,
      },
    ],
    super_administrator: [
      {
        id: 's1',
        title: 'Métriques exécutives',
        body: 'Résumé opérationnel de la plateforme.',
        href: '/app/admin',
        unread: true,
      },
      {
        id: 's2',
        title: 'Approbations critiques',
        body: 'Éléments nécessitant une supervision.',
        href: '/app/confianca/revisao',
        unread: true,
      },
      {
        id: 's3',
        title: 'Nouveaux utilisateurs',
        body: 'Croissance des comptes Kuteka.',
        href: '/app/admin/utilizadores',
        unread: true,
      },
    ],
  },
  es: {
    client: [
      {
        id: 'c1',
        title: 'Encontramos 4 inmuebles para su solicitud',
        body: 'Nuevos resultados alineados con sus preferencias.',
        href: '/app/habitacao/explorar',
        unread: true,
      },
      {
        id: 'c2',
        title: 'Visita programada para mañana',
        body: 'Confirme la hora y el lugar en su calendario Kuteka.',
        href: '/app/habitacao?vista=visitas',
        unread: true,
      },
      {
        id: 'c3',
        title: 'El propietario respondió',
        body: 'Hay un nuevo mensaje sobre un inmueble de su interés.',
        href: '/app/habitacao?vista=interesses',
        unread: true,
      },
      {
        id: 'c4',
        title: 'Nueva propuesta disponible',
        body: 'Revise las condiciones y continúe si encaja.',
        href: '/app/contratos',
        unread: true,
      },
      {
        id: 'c5',
        title: 'Contrato listo',
        body: 'La minuta está disponible para lectura y firma.',
        href: '/app/contratos',
        unread: true,
      },
      {
        id: 'c6',
        title: 'Mensaje Kuteka',
        body: 'Actualización sobre su proceso habitacional.',
        href: '/contacto',
        unread: true,
      },
      {
        id: 'c7',
        title: 'Agendamiento de visita',
        body: 'Una solicitud de visita espera su confirmación.',
        href: '/app/habitacao?vista=visitas',
        unread: true,
      },
    ],
    patrimonial_partner: [
      {
        id: 'p1',
        title: 'Solicitudes de visita',
        body: 'Nuevas solicitudes para patrimonios activos.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'p2',
        title: 'Nuevos interesados',
        body: 'Clientes mostraron interés en sus anuncios.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'p3',
        title: 'Propuestas recibidas',
        body: 'Hay propuestas pendientes de análisis.',
        href: '/app/contratos',
        unread: true,
      },
      {
        id: 'p4',
        title: 'Documentos pendientes',
        body: 'Complete la confianza para acelerar la activación.',
        href: '/app/confianca',
        unread: true,
      },
      {
        id: 'p5',
        title: 'Evaluación concluida',
        body: 'Se registró una evaluación de reputación.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'p6',
        title: 'Contratos',
        body: 'Actualización en el estado de un contrato activo.',
        href: '/app/contratos',
        unread: true,
      },
    ],
    client_partner: [
      {
        id: 'cp1',
        title: 'Actualización Cliente',
        body: 'Nuevos inmuebles y visitas en su recorrido.',
        href: '/app/habitacao/explorar',
        unread: true,
      },
      {
        id: 'cp2',
        title: 'Actualización Socio',
        body: 'Interesados y propuestas en sus patrimonios.',
        href: '/app/patrimonios',
        unread: true,
      },
      {
        id: 'cp3',
        title: 'Contratos',
        body: 'Movimientos como cliente y como socio.',
        href: '/app/contratos',
        unread: true,
      },
    ],
    certified_agent: [
      {
        id: 'a1',
        title: 'Nuevas visitas',
        body: 'Visitas asignadas a su pipeline.',
        href: '/app/agente',
        unread: true,
      },
      {
        id: 'a2',
        title: 'Nuevos clientes',
        body: 'Clientes en espera de acompañamiento.',
        href: '/app/agente',
        unread: true,
      },
      {
        id: 'a3',
        title: 'Evaluaciones pendientes',
        body: 'Evaluaciones técnicas por concluir.',
        href: '/app/agente',
        unread: true,
      },
      {
        id: 'a4',
        title: 'Tareas',
        body: 'Checklist del día en terreno.',
        href: '/app/agente',
        unread: true,
      },
    ],
    administrator: [
      {
        id: 'ad1',
        title: 'Nuevos usuarios',
        body: 'Cuentas recientes para revisión operativa.',
        href: '/app/admin/utilizadores',
        unread: true,
      },
      {
        id: 'ad2',
        title: 'Aprobaciones',
        body: 'Solicitudes de confianza y contenidos pendientes.',
        href: '/app/confianca/revisao',
        unread: true,
      },
      {
        id: 'ad3',
        title: 'Inmuebles pendientes',
        body: 'Anuncios en espera de validación.',
        href: '/app/admin',
        unread: true,
      },
      {
        id: 'ad4',
        title: 'Alertas',
        body: 'Señales operativas de la plataforma.',
        href: '/app/admin',
        unread: true,
      },
    ],
    super_administrator: [
      {
        id: 's1',
        title: 'Métricas ejecutivas',
        body: 'Resumen operativo de la plataforma.',
        href: '/app/admin',
        unread: true,
      },
      {
        id: 's2',
        title: 'Aprobaciones críticas',
        body: 'Elementos que exigen supervisión.',
        href: '/app/confianca/revisao',
        unread: true,
      },
      {
        id: 's3',
        title: 'Nuevos usuarios',
        body: 'Crecimiento de cuentas en Kuteka.',
        href: '/app/admin/utilizadores',
        unread: true,
      },
    ],
  },
};

export function notificationsForMode(
  mode: ExperienceMode,
  locale: AppLocale = 'pt',
): ShellNotification[] {
  return CATALOG[locale][mode] ?? CATALOG.pt[mode] ?? [];
}

export function unreadCount(items: readonly ShellNotification[]): number {
  return items.filter((item) => item.unread !== false).length;
}
