/* Generated by scripts/write-kuteka-config.mjs — do not commit secrets in git if real. */
window.__KUTEKA_CONFIG__ = {
  supabaseUrl: "https://vhqwitbrpqaiutjbundo.supabase.co",
  supabaseAnonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZocXdpdGJycHFhaXV0amJ1bmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1MjYyNzQsImV4cCI6MjEwMTEwMjI3NH0.jZNo-FtKDsuPy6VMQyUDvQoZ0B72O3m2TcXsU9pwP58",
};
