import type { OpsCopy } from './pt';

export const opsCopyEn: OpsCopy = {
  kai: {
    aria: 'KAI — Kuteka Intelligence',
    eyebrow: 'KAI · Kuteka Intelligence',
    title: 'Operational foresight',
    subtitle: 'Proactive insights for decisions — availability, payments, renewal and pipeline.',
  },
  client: {
    eyebrow: 'Client · Residence',
    title: 'Housing management centre',
    subtitle: 'Contract, payments, calendar, communications and exit intent.',
    daysRemaining: 'Days remaining',
    nextRent: 'Next rent',
    paymentsPaid: 'Payments made',
    late: 'Overdue',
    maintenanceOpen: 'Open maintenance',
    interests: 'Interests',
    deposit: 'Deposit',
    contractStatus: 'Contract status',
    noActiveContract: 'no active contract',
    linkResidence: 'Residence cockpit',
    linkContracts: 'Contracts',
    linkFuture: 'Future availability',
    linkExplore: 'Explore',
    currentProperty: 'Current property',
    exitLabel: 'Exit',
    calendarHint: 'Calendar: next payment {due} · renewal / inspections in the residence hub.',
    empty: 'No active contract yet — explore housing or follow proposals.',
  },
  partner: {
    eyebrow: 'Property Partner',
    title: 'Smart property management',
    subtitle: 'Revenue, occupancy, contracts, release forecast and commercial pipeline.',
    monthlyRevenue: 'Monthly revenue',
    annualRevenue: 'Annual revenue',
    occupancy: 'Occupancy',
    occupied: 'Occupied',
    available: 'Available',
    soonFree: 'Soon free',
    activeContracts: 'Active contracts',
    expiring: 'Expiring (60d)',
    interested: 'Interested',
    visits30: 'Visits 30d',
    proposals30: 'Proposals 30d',
    rating: 'Rating',
    linkProperties: 'Properties',
    linkContracts: 'Contracts',
    linkReleases: 'Upcoming releases',
    linkTrust: 'Trust',
    pipelineTitle: 'Commercial pipeline',
    pipelineFlow:
      'Interest → Visits → Proposals → Negotiation → Contract → Move → Occupancy → Renewal',
    kaiForecast: 'KAI forecast: {title} should become available in ~{days} days',
  },
  agent: {
    eyebrow: 'Agent · CRM',
    title: 'Field pipeline',
    subtitle: 'Clients, visits, urgent listings, ratings and commissions.',
    assigned: 'Assigned properties',
    contracts: 'Contracts',
    futureReleases: 'Upcoming releases',
    networkInterests: 'Network interests',
    visits30: 'Visits 30d',
    proposals30: 'Proposals 30d',
    linkCrm: 'Agent CRM',
    linkInventory: 'Inventory',
    linkSignatures: 'Signatures',
    linkUrgent: 'Urgent / upcoming',
  },
  admin: {
    eyebrow: 'Administrator · Operations',
    eyebrowExec: 'Super Administrator · Executive',
    title: 'Operations cockpit',
    titleExec: 'Executive cockpit',
    subtitle: 'Listings, contracts, releases, payments and new stakeholders.',
    subtitleExec: 'Assets under management, revenue, growth, occupancy and satisfaction.',
    users: 'Users',
    contractsActive: 'Active contracts',
    contractsCompleted: 'Completed contracts',
    soonFree: 'Soon free',
    newClients: 'New clients',
    partners: 'Partners',
    agents: 'Agents',
    trustPending: 'Pending trust',
    avgOccupancy: 'Average occupancy',
    avgRelease: 'Avg. days to free',
    monthlyRevenue: 'Monthly revenue (demo)',
    annualRevenue: 'Annual revenue (demo)',
    linkAdmin: 'Administration',
    linkUsers: 'Users',
    linkFinance: 'Finance',
    linkLegal: 'Legal',
    linkProviders: 'Providers',
    linkApprovals: 'Approvals',
  },
  future: {
    aria: 'Future availability',
    eyebrow: 'Marketplace · Future',
    title: 'Future availability',
    subtitle: 'Homes Kuteka expects to free up — enable alerts and prepare campaigns.',
    propertyFallback: 'Property',
    freeIn: 'free in ~{days} days',
    viewNotify: 'View / notify',
  },
};
