import type { OpsCopy } from './pt';

export const opsCopyEn: OpsCopy = {
  kai: {
    aria: 'KAI — Kuteka Intelligence',
    eyebrow: 'KAI · Kuteka Intelligence',
    title: 'Operational foresight',
    subtitle: 'Proactive insights for decisions — availability, payments, renewal and pipeline.',
  },
  client: {
    eyebrow: 'Client · Residence',
    title: 'Housing management centre',
    subtitle: 'Contract, payments, calendar, communications and exit intent.',
    daysRemaining: 'Days remaining',
    nextRent: 'Next rent',
    paymentsPaid: 'Payments made',
    late: 'Overdue',
    maintenanceOpen: 'Open maintenance',
    interests: 'Interests',
    deposit: 'Deposit',
    contractStatus: 'Contract status',
    noActiveContract: 'no active contract',
    linkResidence: 'Residence cockpit',
    linkContracts: 'Contracts',
    linkFuture: 'Future availability',
    linkExplore: 'Explore',
    currentProperty: 'Current property',
    exitLabel: 'Exit',
    calendarHint: 'Calendar: next payment {due} · renewal / inspections in the residence hub.',
    empty: 'No active contract yet — explore housing or follow proposals.',
  },
  partner: {
    eyebrow: 'Property Partner',
    title: 'Smart property management',
    subtitle: 'Revenue, occupancy, contracts, release forecast and commercial pipeline.',
    monthlyRevenue: 'Monthly revenue',
    annualRevenue: 'Annual revenue',
    occupancy: 'Occupancy',
    occupied: 'Occupied',
    available: 'Available',
    soonFree: 'Soon free',
    activeContracts: 'Active contracts',
    expiring: 'Expiring (60d)',
    interested: 'Interested',
    visits30: 'Visits 30d',
    proposals30: 'Proposals 30d',
    rating: 'Rating',
    linkProperties: 'Properties',
    linkContracts: 'Contracts',
    linkReleases: 'Upcoming releases',
    linkTrust: 'Trust',
    pipelineTitle: 'Commercial pipeline',
    pipelineFlow:
      'Interest → Visits → Proposals → Negotiation → Contract → Move → Occupancy → Renewal',
    kaiForecast: 'KAI forecast: {title} should become available in ~{days} days',
  },
  agent: {
    eyebrow: 'Agent · CRM',
    title: 'Field pipeline',
    subtitle: 'Clients, visits, urgent listings, ratings and commissions.',
    assigned: 'Assigned properties',
    contracts: 'Contracts',
    futureReleases: 'Upcoming releases',
    networkInterests: 'Network interests',
    visits30: 'Visits 30d',
    proposals30: 'Proposals 30d',
    linkCrm: 'Agent CRM',
    linkInventory: 'Inventory',
    linkSignatures: 'Signatures',
    linkUrgent: 'Urgent / upcoming',
  },
  admin: {
    eyebrow: 'Administrator · Operations',
    eyebrowExec: 'Super Administrator · Executive',
    title: 'Operations cockpit',
    titleExec: 'Executive cockpit',
    subtitle: 'Listings, contracts, releases, payments and new stakeholders.',
    subtitleExec: 'Assets under management, revenue, growth, occupancy and satisfaction.',
    users: 'Users',
    contractsActive: 'Active contracts',
    contractsCompleted: 'Completed contracts',
    soonFree: 'Soon free',
    newClients: 'New clients',
    partners: 'Partners',
    agents: 'Agents',
    trustPending: 'Pending trust',
    avgOccupancy: 'Average occupancy',
    avgRelease: 'Avg. days to free',
    monthlyRevenue: 'Monthly revenue (Beta)',
    annualRevenue: 'Annual revenue (Beta)',
    linkAdmin: 'Administration',
    linkUsers: 'Users',
    linkFinance: 'Finance',
    linkLegal: 'Legal',
    linkProviders: 'Providers',
    linkApprovals: 'Approvals',
  },
  future: {
    aria: 'Future availability',
    eyebrow: 'Marketplace · Future',
    title: 'Future availability',
    subtitle: 'Homes Kuteka expects to free up — enable alerts and prepare campaigns.',
    propertyFallback: 'Property',
    freeIn: 'free in ~{days} days',
    viewNotify: 'View / notify',
  },
  resident: {
    eyebrow: 'Client · Residence',
    title: 'Housing management',
    subtitle: 'Current contract, payments, calendar, communications and exit intent.',
    loading: 'Loading cockpit…',
    noContractBody: 'You do not have an active contract yet. Explore housing or follow proposals.',
    exploreHousing: 'Explore Housing',
    contractTitle: 'Current contract',
    statusLabel: 'Status',
    startLabel: 'Start',
    endLabel: 'End',
    daysRemainingLabel: 'Days remaining',
    rentLabel: 'Rent / amount',
    depositLabel: 'Deposit',
    nextPaymentLabel: 'Next payment',
    daysUntilPaymentLabel: 'Days until payment',
    paymentsLabel: 'Payments',
    paymentsPaidLabel: 'paid',
    paymentsPendingLabel: 'pending',
    paymentsLateLabel: 'overdue',
    serviceTitle: 'Request a service',
    serviceSubtitle: 'Maintenance, cleaning, renovation, painting, electricity or plumbing.',
    servicePlaceholder: 'Describe the request',
    send: 'Send',
    maintenanceNoteDefault: 'Request created from the client cockpit.',
    maintenanceSuccess: 'Service request sent to the partner / Kuteka network.',
    maintenanceError: 'We could not create the request. Check your account or try again later.',
    exitTitle: 'Exit intent',
    exitSubtitle:
      'Let us know in advance so Kuteka can find new interested parties, organise visits and ease the deposit return.',
    exit30: 'I plan to leave in 30 days',
    exit60: 'I plan to leave in 60 days',
    exit90: 'I plan to leave in 90 days',
    exitCustom: 'Custom date (~45 days)',
    registerExit: 'Register intent',
    exitNoteTemplate: 'Exit intent in {days} days.',
    exitSuccess: 'Exit intent registered. Kuteka can start looking for new interested parties.',
    exitError: 'We could not save the exit intent. Please try again.',
    currentStateLabel: 'Current status',
    activateSmartMove: 'Activate Smart Move',
    providersTitle: 'Provider network',
    providersSubtitle: 'Cleaning, moving and works requests with Kuteka commission (marketplace).',
    openMarketplace: 'Open marketplace',
  },
  notify: {
    activateLabel: 'Notify me when available',
    activatedLabel: 'Notification enabled',
    error: 'We could not enable the notification. Please try again.',
  },
  exitReasons: {
    mudanca_cidade: 'Moving to another city',
    compra_casa: 'Buying a home',
    renda_elevada: 'Rent too high',
    mudanca_emprego: 'Job change',
    outro: 'Other',
  },
  maintenanceCategories: {
    maintenance: 'Maintenance',
    cleaning: 'Cleaning',
    renovation: 'Renovation',
    painting: 'Painting',
    electricity: 'Electricity',
    plumbing: 'Plumbing',
    gardening: 'Gardening',
    security: 'Security',
    other: 'Other',
  },
  dates: {
    today: 'Today',
    lateSuffix: 'd overdue',
    daysSuffix: 'days',
  },
};
