import type { OpsCopy } from './pt';

export const opsCopyEs: OpsCopy = {
  kai: {
    aria: 'KAI — Inteligencia Kuteka',
    eyebrow: 'KAI · Inteligencia Kuteka',
    title: 'Anticipación operativa',
    subtitle: 'Insights proactivos para decidir — disponibilidad, pagos, renovación y pipeline.',
  },
  client: {
    eyebrow: 'Cliente · Residencia',
    title: 'Centro de gestión de la vivienda',
    subtitle: 'Contrato, pagos, calendario, comunicaciones e intención de salida.',
    daysRemaining: 'Días restantes',
    nextRent: 'Próxima renta',
    paymentsPaid: 'Pagos realizados',
    late: 'Atrasados',
    maintenanceOpen: 'Mantenimientos abiertos',
    interests: 'Intereses',
    deposit: 'Fianza',
    contractStatus: 'Estado del contrato',
    noActiveContract: 'sin contrato activo',
    linkResidence: 'Cockpit residencia',
    linkContracts: 'Contratos',
    linkFuture: 'Disponibilidad futura',
    linkExplore: 'Explorar',
    currentProperty: 'Inmueble actual',
    exitLabel: 'Salida',
    calendarHint:
      'Calendario: próximo pago {due} · renovación / inspecciones en el hub de residencia.',
    empty: 'Aún sin contrato activo — explore vivienda o siga propuestas.',
  },
  partner: {
    eyebrow: 'Socio patrimonial',
    title: 'Gestión inteligente del patrimonio',
    subtitle: 'Ingresos, ocupación, contratos, previsión de liberación y pipeline comercial.',
    monthlyRevenue: 'Ingreso mensual',
    annualRevenue: 'Ingreso anual',
    occupancy: 'Ocupación',
    occupied: 'Ocupados',
    available: 'Disponibles',
    soonFree: 'Próximos a liberar',
    activeContracts: 'Contratos activos',
    expiring: 'Por vencer (60d)',
    interested: 'Interesados',
    visits30: 'Visitas 30d',
    proposals30: 'Propuestas 30d',
    rating: 'Valoración',
    linkProperties: 'Patrimonios',
    linkContracts: 'Contratos',
    linkReleases: 'Liberaciones futuras',
    linkTrust: 'Confianza',
    pipelineTitle: 'Pipeline comercial',
    pipelineFlow:
      'Interés → Visitas → Propuestas → Negociación → Contrato → Mudanza → Ocupación → Renovación',
    kaiForecast: 'Previsión KAI: {title} debería estar disponible en ~{days} días',
  },
  agent: {
    eyebrow: 'Agente · CRM',
    title: 'Pipeline en el terreno',
    subtitle: 'Clientes, visitas, inmuebles urgentes, valoraciones y comisiones.',
    assigned: 'Inmuebles asignados',
    contracts: 'Contratos',
    futureReleases: 'Liberaciones futuras',
    networkInterests: 'Intereses (red)',
    visits30: 'Visitas 30d',
    proposals30: 'Propuestas 30d',
    linkCrm: 'CRM Agente',
    linkInventory: 'Inventario',
    linkSignatures: 'Firmas',
    linkUrgent: 'Urgentes / futuros',
  },
  admin: {
    eyebrow: 'Administrador · Operaciones',
    eyebrowExec: 'SuperAdministrador · Ejecutivo',
    title: 'Cockpit operativo',
    titleExec: 'Cockpit ejecutivo',
    subtitle: 'Inmuebles, contratos, liberaciones, pagos y nuevos actores.',
    subtitleExec: 'Patrimonio bajo gestión, ingresos, crecimiento, ocupación y satisfacción.',
    users: 'Usuarios',
    contractsActive: 'Contratos activos',
    contractsCompleted: 'Contratos terminados',
    soonFree: 'Próximos a liberar',
    newClients: 'Nuevos clientes',
    partners: 'Socios',
    agents: 'Agentes',
    trustPending: 'Confianza pendiente',
    avgOccupancy: 'Ocupación media',
    avgRelease: 'Tiempo medio de liberación',
    monthlyRevenue: 'Ingreso mensual (demo)',
    annualRevenue: 'Ingreso anual (demo)',
    linkAdmin: 'Administración',
    linkUsers: 'Usuarios',
    linkFinance: 'Financiero',
    linkLegal: 'Jurídico',
    linkProviders: 'Proveedores',
    linkApprovals: 'Aprobaciones',
  },
  future: {
    aria: 'Disponibilidad futura',
    eyebrow: 'Marketplace · Futuro',
    title: 'Disponibilidad futura',
    subtitle: 'Inmuebles que Kuteka prevé liberar — active notificaciones y prepare campañas.',
    propertyFallback: 'Patrimonio',
    freeIn: 'libre en ~{days} días',
    viewNotify: 'Ver / notificar',
  },
};
