import type { OpsCopy } from './pt';

export const opsCopyEs: OpsCopy = {
  kai: {
    aria: 'KAI — Inteligencia Kuteka',
    eyebrow: 'KAI · Inteligencia Kuteka',
    title: 'Anticipación operativa',
    subtitle: 'Insights proactivos para decidir — disponibilidad, pagos, renovación y pipeline.',
  },
  client: {
    eyebrow: 'Cliente · Residencia',
    title: 'Centro de gestión de la vivienda',
    subtitle: 'Contrato, pagos, calendario, comunicaciones e intención de salida.',
    daysRemaining: 'Días restantes',
    nextRent: 'Próxima renta',
    paymentsPaid: 'Pagos realizados',
    late: 'Atrasados',
    maintenanceOpen: 'Mantenimientos abiertos',
    interests: 'Intereses',
    deposit: 'Fianza',
    contractStatus: 'Estado del contrato',
    noActiveContract: 'sin contrato activo',
    linkResidence: 'Cockpit residencia',
    linkContracts: 'Contratos',
    linkFuture: 'Disponibilidad futura',
    linkExplore: 'Explorar',
    currentProperty: 'Inmueble actual',
    exitLabel: 'Salida',
    calendarHint:
      'Calendario: próximo pago {due} · renovación / inspecciones en el hub de residencia.',
    empty: 'Aún sin contrato activo — explore vivienda o siga propuestas.',
  },
  partner: {
    eyebrow: 'Socio patrimonial',
    title: 'Gestión inteligente del patrimonio',
    subtitle: 'Ingresos, ocupación, contratos, previsión de liberación y pipeline comercial.',
    monthlyRevenue: 'Ingreso mensual',
    annualRevenue: 'Ingreso anual',
    occupancy: 'Ocupación',
    occupied: 'Ocupados',
    available: 'Disponibles',
    soonFree: 'Próximos a liberar',
    activeContracts: 'Contratos activos',
    expiring: 'Por vencer (60d)',
    interested: 'Interesados',
    visits30: 'Visitas 30d',
    proposals30: 'Propuestas 30d',
    rating: 'Valoración',
    linkProperties: 'Patrimonios',
    linkContracts: 'Contratos',
    linkReleases: 'Liberaciones futuras',
    linkTrust: 'Confianza',
    pipelineTitle: 'Pipeline comercial',
    pipelineFlow:
      'Interés → Visitas → Propuestas → Negociación → Contrato → Mudanza → Ocupación → Renovación',
    kaiForecast: 'Previsión KAI: {title} debería estar disponible en ~{days} días',
  },
  agent: {
    eyebrow: 'Agente · CRM',
    title: 'Pipeline en el terreno',
    subtitle: 'Clientes, visitas, inmuebles urgentes, valoraciones y comisiones.',
    assigned: 'Inmuebles asignados',
    contracts: 'Contratos',
    futureReleases: 'Liberaciones futuras',
    networkInterests: 'Intereses (red)',
    visits30: 'Visitas 30d',
    proposals30: 'Propuestas 30d',
    linkCrm: 'CRM Agente',
    linkInventory: 'Inventario',
    linkSignatures: 'Firmas',
    linkUrgent: 'Urgentes / futuros',
  },
  admin: {
    eyebrow: 'Administrador · Operaciones',
    eyebrowExec: 'SuperAdministrador · Ejecutivo',
    title: 'Cockpit operativo',
    titleExec: 'Cockpit ejecutivo',
    subtitle: 'Inmuebles, contratos, liberaciones, pagos y nuevos actores.',
    subtitleExec: 'Patrimonio bajo gestión, ingresos, crecimiento, ocupación y satisfacción.',
    users: 'Usuarios',
    contractsActive: 'Contratos activos',
    contractsCompleted: 'Contratos terminados',
    soonFree: 'Próximos a liberar',
    newClients: 'Nuevos clientes',
    partners: 'Socios',
    agents: 'Agentes',
    trustPending: 'Confianza pendiente',
    avgOccupancy: 'Ocupación media',
    avgRelease: 'Tiempo medio de liberación',
    monthlyRevenue: 'Ingreso mensual (Beta)',
    annualRevenue: 'Ingreso anual (Beta)',
    linkAdmin: 'Administración',
    linkUsers: 'Usuarios',
    linkFinance: 'Financiero',
    linkLegal: 'Jurídico',
    linkProviders: 'Proveedores',
    linkApprovals: 'Aprobaciones',
  },
  future: {
    aria: 'Disponibilidad futura',
    eyebrow: 'Marketplace · Futuro',
    title: 'Disponibilidad futura',
    subtitle: 'Inmuebles que Kuteka prevé liberar — active notificaciones y prepare campañas.',
    propertyFallback: 'Patrimonio',
    freeIn: 'libre en ~{days} días',
    viewNotify: 'Ver / notificar',
  },
  resident: {
    eyebrow: 'Cliente · Residencia',
    title: 'Gestión de la vivienda',
    subtitle: 'Contrato actual, pagos, calendario, comunicaciones e intención de salida.',
    loading: 'Cargando cockpit…',
    noContractBody: 'Aún no tiene un contrato activo. Explore vivienda o siga propuestas.',
    exploreHousing: 'Explorar Vivienda',
    contractTitle: 'Contrato actual',
    statusLabel: 'Estado',
    startLabel: 'Inicio',
    endLabel: 'Término',
    daysRemainingLabel: 'Días restantes',
    rentLabel: 'Renta / valor',
    depositLabel: 'Fianza',
    nextPaymentLabel: 'Próximo pago',
    daysUntilPaymentLabel: 'Días hasta el pago',
    paymentsLabel: 'Pagos',
    paymentsPaidLabel: 'pagados',
    paymentsPendingLabel: 'pendientes',
    paymentsLateLabel: 'atrasados',
    serviceTitle: 'Solicitar servicio',
    serviceSubtitle: 'Mantenimiento, limpieza, remodelación, pintura, electricidad o fontanería.',
    servicePlaceholder: 'Describa la solicitud',
    send: 'Enviar',
    maintenanceNoteDefault: 'Solicitud creada desde el cockpit del cliente.',
    maintenanceSuccess: 'Solicitud de servicio enviada al socio / red Kuteka.',
    maintenanceError: 'No pudimos crear la solicitud. Verifique su cuenta o inténtelo más tarde.',
    exitTitle: 'Intención de salida',
    exitSubtitle:
      'Avise con antelación para que Kuteka busque nuevos interesados, organice visitas y facilite la devolución de la fianza.',
    exit30: 'Planeo salir en 30 días',
    exit60: 'Planeo salir en 60 días',
    exit90: 'Planeo salir en 90 días',
    exitCustom: 'Fecha personalizada (~45 días)',
    registerExit: 'Registrar intención',
    exitNoteTemplate: 'Intención de salida en {days} días.',
    exitSuccess:
      'Intención de salida registrada. Kuteka puede iniciar la búsqueda de nuevos interesados.',
    exitError: 'No pudimos guardar la intención de salida. Inténtelo de nuevo.',
    currentStateLabel: 'Estado actual',
    activateSmartMove: 'Activar Mudanza Inteligente',
    providersTitle: 'Red de proveedores',
    providersSubtitle:
      'Solicitudes de limpieza, mudanzas y obras con comisión Kuteka (marketplace).',
    openMarketplace: 'Abrir marketplace',
  },
  notify: {
    activateLabel: 'Notificarme cuando esté disponible',
    activatedLabel: 'Notificación activada',
    error: 'No pudimos activar la notificación. Inténtelo de nuevo.',
  },
  exitReasons: {
    mudanca_cidade: 'Mudanza a otra ciudad',
    compra_casa: 'Compra de vivienda',
    renda_elevada: 'Renta demasiado alta',
    mudanca_emprego: 'Cambio de empleo',
    outro: 'Otro',
  },
  maintenanceCategories: {
    maintenance: 'Mantenimiento',
    cleaning: 'Limpieza',
    renovation: 'Remodelación',
    painting: 'Pintura',
    electricity: 'Electricidad',
    plumbing: 'Fontanería',
    gardening: 'Jardinería',
    security: 'Seguridad',
    other: 'Otro',
  },
  dates: {
    today: 'Hoy',
    lateSuffix: 'd de atraso',
    daysSuffix: 'días',
  },
};
