import type { OpsCopy } from './pt';

export const opsCopyFr: OpsCopy = {
  kai: {
    aria: 'KAI — Intelligence Kuteka',
    eyebrow: 'KAI · Intelligence Kuteka',
    title: 'Anticipation opérationnelle',
    subtitle:
      'Insights proactifs pour décider — disponibilité, paiements, renouvellement et pipeline.',
  },
  client: {
    eyebrow: 'Client · Résidence',
    title: 'Centre de gestion du logement',
    subtitle: 'Contrat, paiements, calendrier, communications et intention de départ.',
    daysRemaining: 'Jours restants',
    nextRent: 'Prochain loyer',
    paymentsPaid: 'Paiements effectués',
    late: 'En retard',
    maintenanceOpen: 'Maintenances ouvertes',
    interests: 'Intérêts',
    deposit: 'Caution',
    contractStatus: 'État du contrat',
    noActiveContract: 'aucun contrat actif',
    linkResidence: 'Cockpit résidence',
    linkContracts: 'Contrats',
    linkFuture: 'Disponibilité future',
    linkExplore: 'Explorer',
    currentProperty: 'Bien actuel',
    exitLabel: 'Départ',
    calendarHint:
      'Calendrier : prochain paiement {due} · renouvellement / inspections dans le hub résidence.',
    empty: 'Pas encore de contrat actif — explorez le logement ou suivez les propositions.',
  },
  partner: {
    eyebrow: 'Partenaire patrimonial',
    title: 'Gestion intelligente du patrimoine',
    subtitle: 'Revenus, occupation, contrats, prévision de libération et pipeline commercial.',
    monthlyRevenue: 'Revenu mensuel',
    annualRevenue: 'Revenu annuel',
    occupancy: 'Occupation',
    occupied: 'Occupés',
    available: 'Disponibles',
    soonFree: 'Bientôt libres',
    activeContracts: 'Contrats actifs',
    expiring: 'À échéance (60j)',
    interested: 'Intéressés',
    visits30: 'Visites 30j',
    proposals30: 'Propositions 30j',
    rating: 'Évaluation',
    linkProperties: 'Patrimoines',
    linkContracts: 'Contrats',
    linkReleases: 'Libérations futures',
    linkTrust: 'Confiance',
    pipelineTitle: 'Pipeline commercial',
    pipelineFlow:
      'Intérêt → Visites → Propositions → Négociation → Contrat → Déménagement → Occupation → Renouvellement',
    kaiForecast: 'Prévision KAI : {title} devrait être disponible dans ~{days} jours',
  },
  agent: {
    eyebrow: 'Agent · CRM',
    title: 'Pipeline sur le terrain',
    subtitle: 'Clients, visites, biens urgents, évaluations et commissions.',
    assigned: 'Biens attribués',
    contracts: 'Contrats',
    futureReleases: 'Libérations futures',
    networkInterests: 'Intérêts (réseau)',
    visits30: 'Visites 30j',
    proposals30: 'Propositions 30j',
    linkCrm: 'CRM Agent',
    linkInventory: 'Inventaire',
    linkSignatures: 'Signatures',
    linkUrgent: 'Urgents / futurs',
  },
  admin: {
    eyebrow: 'Administrateur · Opérations',
    eyebrowExec: 'SuperAdministrateur · Exécutif',
    title: 'Cockpit opérationnel',
    titleExec: 'Cockpit exécutif',
    subtitle: 'Biens, contrats, libérations, paiements et nouveaux acteurs.',
    subtitleExec: 'Patrimoine géré, revenus, croissance, occupation et satisfaction.',
    users: 'Utilisateurs',
    contractsActive: 'Contrats actifs',
    contractsCompleted: 'Contrats terminés',
    soonFree: 'Bientôt libres',
    newClients: 'Nouveaux clients',
    partners: 'Partenaires',
    agents: 'Agents',
    trustPending: 'Confiance en attente',
    avgOccupancy: 'Occupation moyenne',
    avgRelease: 'Délai moyen de libération',
    monthlyRevenue: 'Revenu mensuel (démo)',
    annualRevenue: 'Revenu annuel (démo)',
    linkAdmin: 'Administration',
    linkUsers: 'Utilisateurs',
    linkFinance: 'Finance',
    linkLegal: 'Juridique',
    linkProviders: 'Prestataires',
    linkApprovals: 'Approbations',
  },
  future: {
    aria: 'Disponibilité future',
    eyebrow: 'Marketplace · Futur',
    title: 'Disponibilité future',
    subtitle:
      'Biens que Kuteka prévoit de libérer — activez les alertes et préparez les campagnes.',
    propertyFallback: 'Patrimoine',
    freeIn: 'libre dans ~{days} jours',
    viewNotify: 'Voir / notifier',
  },
};
