import type { OpsCopy } from './pt';

export const opsCopyFr: OpsCopy = {
  kai: {
    aria: 'KAI — Intelligence Kuteka',
    eyebrow: 'KAI · Intelligence Kuteka',
    title: 'Anticipation opérationnelle',
    subtitle:
      'Insights proactifs pour décider — disponibilité, paiements, renouvellement et pipeline.',
  },
  client: {
    eyebrow: 'Client · Résidence',
    title: 'Centre de gestion du logement',
    subtitle: 'Contrat, paiements, calendrier, communications et intention de départ.',
    daysRemaining: 'Jours restants',
    nextRent: 'Prochain loyer',
    paymentsPaid: 'Paiements effectués',
    late: 'En retard',
    maintenanceOpen: 'Maintenances ouvertes',
    interests: 'Intérêts',
    deposit: 'Caution',
    contractStatus: 'État du contrat',
    noActiveContract: 'aucun contrat actif',
    linkResidence: 'Cockpit résidence',
    linkContracts: 'Contrats',
    linkFuture: 'Disponibilité future',
    linkExplore: 'Explorer',
    currentProperty: 'Bien actuel',
    exitLabel: 'Départ',
    calendarHint:
      'Calendrier : prochain paiement {due} · renouvellement / inspections dans le hub résidence.',
    empty: 'Pas encore de contrat actif — explorez le logement ou suivez les propositions.',
  },
  partner: {
    eyebrow: 'Partenaire patrimonial',
    title: 'Gestion intelligente du patrimoine',
    subtitle: 'Revenus, occupation, contrats, prévision de libération et pipeline commercial.',
    monthlyRevenue: 'Revenu mensuel',
    annualRevenue: 'Revenu annuel',
    occupancy: 'Occupation',
    occupied: 'Occupés',
    available: 'Disponibles',
    soonFree: 'Bientôt libres',
    activeContracts: 'Contrats actifs',
    expiring: 'À échéance (60j)',
    interested: 'Intéressés',
    visits30: 'Visites 30j',
    proposals30: 'Propositions 30j',
    rating: 'Évaluation',
    linkProperties: 'Patrimoines',
    linkContracts: 'Contrats',
    linkReleases: 'Libérations futures',
    linkTrust: 'Confiance',
    pipelineTitle: 'Pipeline commercial',
    pipelineFlow:
      'Intérêt → Visites → Propositions → Négociation → Contrat → Déménagement → Occupation → Renouvellement',
    kaiForecast: 'Prévision KAI : {title} devrait être disponible dans ~{days} jours',
  },
  agent: {
    eyebrow: 'Agent · CRM',
    title: 'Pipeline sur le terrain',
    subtitle: 'Clients, visites, biens urgents, évaluations et commissions.',
    assigned: 'Biens attribués',
    contracts: 'Contrats',
    futureReleases: 'Libérations futures',
    networkInterests: 'Intérêts (réseau)',
    visits30: 'Visites 30j',
    proposals30: 'Propositions 30j',
    linkCrm: 'CRM Agent',
    linkInventory: 'Inventaire',
    linkSignatures: 'Signatures',
    linkUrgent: 'Urgents / futurs',
  },
  admin: {
    eyebrow: 'Administrateur · Opérations',
    eyebrowExec: 'SuperAdministrateur · Exécutif',
    title: 'Cockpit opérationnel',
    titleExec: 'Cockpit exécutif',
    subtitle: 'Biens, contrats, libérations, paiements et nouveaux acteurs.',
    subtitleExec: 'Patrimoine géré, revenus, croissance, occupation et satisfaction.',
    users: 'Utilisateurs',
    contractsActive: 'Contrats actifs',
    contractsCompleted: 'Contrats terminés',
    soonFree: 'Bientôt libres',
    newClients: 'Nouveaux clients',
    partners: 'Partenaires',
    agents: 'Agents',
    trustPending: 'Confiance en attente',
    avgOccupancy: 'Occupation moyenne',
    avgRelease: 'Délai moyen de libération',
    monthlyRevenue: 'Revenu mensuel (Bêta)',
    annualRevenue: 'Revenu annuel (Bêta)',
    linkAdmin: 'Administration',
    linkUsers: 'Utilisateurs',
    linkFinance: 'Finance',
    linkLegal: 'Juridique',
    linkProviders: 'Prestataires',
    linkApprovals: 'Approbations',
  },
  future: {
    aria: 'Disponibilité future',
    eyebrow: 'Marketplace · Futur',
    title: 'Disponibilité future',
    subtitle:
      'Biens que Kuteka prévoit de libérer — activez les alertes et préparez les campagnes.',
    propertyFallback: 'Patrimoine',
    freeIn: 'libre dans ~{days} jours',
    viewNotify: 'Voir / notifier',
  },
  resident: {
    eyebrow: 'Client · Résidence',
    title: 'Gestion du logement',
    subtitle: 'Contrat actuel, paiements, calendrier, communications et intention de départ.',
    loading: 'Chargement du cockpit…',
    noContractBody:
      'Vous n’avez pas encore de contrat actif. Explorez le logement ou suivez les propositions.',
    exploreHousing: 'Explorer l’habitat',
    contractTitle: 'Contrat actuel',
    statusLabel: 'État',
    startLabel: 'Début',
    endLabel: 'Fin',
    daysRemainingLabel: 'Jours restants',
    rentLabel: 'Loyer / montant',
    depositLabel: 'Caution',
    nextPaymentLabel: 'Prochain paiement',
    daysUntilPaymentLabel: 'Jours avant paiement',
    paymentsLabel: 'Paiements',
    paymentsPaidLabel: 'effectués',
    paymentsPendingLabel: 'en attente',
    paymentsLateLabel: 'en retard',
    serviceTitle: 'Demander un service',
    serviceSubtitle: 'Maintenance, nettoyage, rénovation, peinture, électricité ou plomberie.',
    servicePlaceholder: 'Décrivez la demande',
    send: 'Envoyer',
    maintenanceNoteDefault: 'Demande créée depuis le cockpit du client.',
    maintenanceSuccess: 'Demande de service envoyée au partenaire / réseau Kuteka.',
    maintenanceError:
      'Nous n’avons pas pu créer la demande. Vérifiez votre compte ou réessayez plus tard.',
    exitTitle: 'Intention de départ',
    exitSubtitle:
      'Prévenez à l’avance pour que Kuteka recherche de nouveaux intéressés, organise les visites et facilite la restitution de la caution.',
    exit30: 'Je prévois de partir dans 30 jours',
    exit60: 'Je prévois de partir dans 60 jours',
    exit90: 'Je prévois de partir dans 90 jours',
    exitCustom: 'Date personnalisée (~45 jours)',
    registerExit: 'Enregistrer l’intention',
    exitNoteTemplate: 'Intention de départ dans {days} jours.',
    exitSuccess:
      'Intention de départ enregistrée. Kuteka peut commencer à chercher de nouveaux intéressés.',
    exitError: 'Nous n’avons pas pu enregistrer l’intention de départ. Veuillez réessayer.',
    currentStateLabel: 'État actuel',
    activateSmartMove: 'Activer Déménagement Intelligent',
    providersTitle: 'Réseau de prestataires',
    providersSubtitle:
      'Demandes de nettoyage, déménagement et travaux avec commission Kuteka (marketplace).',
    openMarketplace: 'Ouvrir le marketplace',
  },
  notify: {
    activateLabel: 'Me notifier dès que disponible',
    activatedLabel: 'Notification activée',
    error: 'Nous n’avons pas pu activer la notification. Veuillez réessayer.',
  },
  exitReasons: {
    mudanca_cidade: 'Déménagement vers une autre ville',
    compra_casa: 'Achat d’un logement',
    renda_elevada: 'Loyer trop élevé',
    mudanca_emprego: 'Changement d’emploi',
    outro: 'Autre',
  },
  maintenanceCategories: {
    maintenance: 'Maintenance',
    cleaning: 'Nettoyage',
    renovation: 'Rénovation',
    painting: 'Peinture',
    electricity: 'Électricité',
    plumbing: 'Plomberie',
    gardening: 'Jardinage',
    security: 'Sécurité',
    other: 'Autre',
  },
  dates: {
    today: 'Aujourd’hui',
    lateSuffix: 'j de retard',
    daysSuffix: 'jours',
  },
};
