/** Ops / cockpit copy — pt-AO. */
export const opsCopyPt = {
  kai: {
    aria: 'KAI — Inteligência Kuteka',
    eyebrow: 'KAI · Inteligência Kuteka',
    title: 'Antecipação operacional',
    subtitle:
      'Insights proactivos para decisões — disponibilidade, pagamentos, renovação e pipeline.',
  },
  client: {
    eyebrow: 'Cliente · Residência',
    title: 'Centro de gestão da habitação',
    subtitle: 'Contrato, pagamentos, calendário, comunicações e intenção de saída.',
    daysRemaining: 'Dias restantes',
    nextRent: 'Próxima renda',
    paymentsPaid: 'Pagamentos feitos',
    late: 'Em atraso',
    maintenanceOpen: 'Manutenções abertas',
    interests: 'Interesses',
    deposit: 'Caução',
    contractStatus: 'Estado contrato',
    noActiveContract: 'sem contrato activo',
    linkResidence: 'Cockpit residência',
    linkContracts: 'Contratos',
    linkFuture: 'Disponibilidade futura',
    linkExplore: 'Explorar',
    currentProperty: 'Imóvel actual',
    exitLabel: 'Saída',
    calendarHint:
      'Calendário: próximo pagamento {due} · renovação / inspeções no hub de residência.',
    empty: 'Ainda sem contrato activo — explore habitação ou acompanhe propostas.',
  },
  partner: {
    eyebrow: 'Parceiro Patrimonial',
    title: 'Gestão inteligente do património',
    subtitle: 'Receitas, ocupação, contratos, previsão de libertação e pipeline comercial.',
    monthlyRevenue: 'Receita mensal',
    annualRevenue: 'Receita anual',
    occupancy: 'Ocupação',
    occupied: 'Ocupados',
    available: 'Disponíveis',
    soonFree: 'Prestes a libertar',
    activeContracts: 'Contratos activos',
    expiring: 'A vencer (60d)',
    interested: 'Interessados',
    visits30: 'Visitas 30d',
    proposals30: 'Propostas 30d',
    rating: 'Avaliação',
    linkProperties: 'Patrimónios',
    linkContracts: 'Contratos',
    linkReleases: 'Libertações futuras',
    linkTrust: 'Confiança',
    pipelineTitle: 'Pipeline comercial',
    pipelineFlow:
      'Interessados → Visitas → Propostas → Negociação → Contrato → Mudança → Ocupação → Renovação',
    kaiForecast: 'Previsão KAI: {title} deverá ficar disponível em ~{days} dias',
  },
  agent: {
    eyebrow: 'Agente · CRM',
    title: 'Pipeline no terreno',
    subtitle: 'Clientes, visitas, imóveis urgentes, avaliações e comissões.',
    assigned: 'Imóveis atribuídos',
    contracts: 'Contratos',
    futureReleases: 'Libertações futuras',
    networkInterests: 'Interessados (rede)',
    visits30: 'Visitas 30d',
    proposals30: 'Propostas 30d',
    linkCrm: 'CRM Agente',
    linkInventory: 'Inventário',
    linkSignatures: 'Assinaturas',
    linkUrgent: 'Urgentes / futuros',
  },
  admin: {
    eyebrow: 'Administrador · Operações',
    eyebrowExec: 'SuperAdministrador · Executivo',
    title: 'Cockpit operacional',
    titleExec: 'Cockpit executivo',
    subtitle: 'Imóveis, contratos, libertações, pagamentos e novos stakeholders.',
    subtitleExec: 'Património sob gestão, receitas, crescimento, ocupação e satisfação.',
    users: 'Utilizadores',
    contractsActive: 'Contratos activos',
    contractsCompleted: 'Contratos terminados',
    soonFree: 'Prestes a libertar',
    newClients: 'Novos clientes',
    partners: 'Parceiros',
    agents: 'Agentes',
    trustPending: 'Confiança pendente',
    avgOccupancy: 'Ocupação média',
    avgRelease: 'Tempo médio libertação',
    monthlyRevenue: 'Receita mensal (demo)',
    annualRevenue: 'Receita anual (demo)',
    linkAdmin: 'Administração',
    linkUsers: 'Utilizadores',
    linkFinance: 'Financeiro',
    linkLegal: 'Jurídico',
    linkProviders: 'Prestadores',
    linkApprovals: 'Aprovações',
  },
  future: {
    aria: 'Disponibilidade futura',
    eyebrow: 'Marketplace · Futuro',
    title: 'Disponibilidade futura',
    subtitle: 'Imóveis que a Kuteka prevê libertar — active notificações e prepare campanhas.',
    propertyFallback: 'Património',
    freeIn: 'livre em ~{days} dias',
    viewNotify: 'Ver / notificar',
  },
} as const satisfies Record<string, Record<string, string>>;

type DeepStringify<T> = {
  [K in keyof T]: T[K] extends string ? string : DeepStringify<T[K]>;
};

export type OpsCopy = DeepStringify<typeof opsCopyPt>;
